### ISSUE TITLE
Pool logs stack trace on HSM remove errors using script driver

### ISSUE THREAD

**Issue by gbehrmann** [dCache/dcache#1534]
When using the HSM script driver, if the HSM script returns a non-zero error code on remove callouts, the pool logs a stack trace, e.g.

    23 maj 2015 12:57:37 (pool_sm) [cleaner PoolRemoveFilesFromHSM 460d212a-b6c2-4ed1-93c4-0c85519f21aa] Remove of hsm://osm/?store=test&group=tape&bfid=0000DC03F5FD35BA4D9FAF7CDBFF18823B73 failed with {}.
    diskCacheV111.util.CacheException: HSM script failed (script reported: 2: Need 'hsmBase' ... 
        at diskCacheV111.util.HsmRunSystem.execute(HsmRunSystem.java:49) ~[dcache-core-2.13.0-SNAPSHOT.jar:2.13.0-SNAPSHOT]
        at org.dcache.pool.nearline.script.ScriptNearlineStorage.remove(ScriptNearlineStorage.java:152) ~[dcache-core-2.13.0-SNAPSHOT.jar:2.13.0-SNAPSHOT]
        at org.dcache.pool.nearline.AbstractBlockingNearlineStorage$3.call(AbstractBlockingNearlineStorage.java:131) ~[dcache-core-2.13.0-SNAPSHOT.jar:2.13.0-SNAPSHOT]
        at org.dcache.pool.nearline.AbstractBlockingNearlineStorage$3.call(AbstractBlockingNearlineStorage.java:125) ~[dcache-core-2.13.0-SNAPSHOT.jar:2.13.0-SNAPSHOT]
        at org.dcache.pool.nearline.AbstractBlockingNearlineStorage$Task.processRequest(AbstractBlockingNearlineStorage.java:251) [dcache-core-2.13.0-SNAPSHOT.jar:2.13.0-SNAPSHOT]
        at org.dcache.pool.nearline.AbstractBlockingNearlineStorage$Task.run(AbstractBlockingNearlineStorage.java:235) [dcache-core-2.13.0-SNAPSHOT.jar:2.13.0-SNAPSHOT]
        at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:153) [dcache-core-2.13.0-SNAPSHOT.jar:2.13.0-SNAPSHOT]
        at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:217) [dcache-core-2.13.0-SNAPSHOT.jar:2.13.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]

**Comment by gbehrmann** [comment]
Turns out that this is a bug in Logback 1.1.*, see http://jira.qos.ch/browse/LOGBACK-1083 for details. In dCache we reverted back to logback 1.0.12 due to other issues and thus we do not currently suffer from this problem.
