### ISSUE TITLE
storage group names with '/'-sign break statistics service

### ISSUE THREAD

**Issue by ahaupt** [dCache/dcache#1635]
Dear dCache support,

we created some storage groups with a pattern like this (from poolmanager.conf):

```
psu create unit -store  ifh:magic15/testosm:testgroup@osm
```

This seems to break the statistics service (dCache 2.10.31) as it does not seem to properly mask the '/'. Excerpt from httpDomain (runs inside that domain here):

```
 [puck] /var/log/dcache % tail -n 12 httpdDomain.log
 09 Jun 2015 14:05:52 (PoolStatistics) [] Can't prepare Html directory: /var/lib/dcache/statistics/2015/06/09
 java.io.FileNotFoundException: /var/lib/dcache/statistics/2015/06/09/class-ifh:magic15/testosm:testgroup@osm.html (No such file or directory)
    at java.io.FileOutputStream.open(Native Method) ~[na:1.7.0_79]
    at java.io.FileOutputStream.<init>(FileOutputStream.java:221) ~[na:1.7.0_79]
    at java.io.FileOutputStream.<init>(FileOutputStream.java:171) ~[na:1.7.0_79]
    at java.io.FileWriter.<init>(FileWriter.java:90) ~[na:1.7.0_79]
    at diskCacheV111.services.PoolStatisticsV0.prepareDailyHtml(PoolStatisticsV0.java:1266) [dcache-core-2.10.31.jar:2.10.31]
    at diskCacheV111.services.PoolStatisticsV0.prepareDailyHtmlFiles(PoolStatisticsV0.java:1126) [dcache-core-2.10.31.jar:2.10.31]
    at diskCacheV111.services.PoolStatisticsV0.access$1100(PoolStatisticsV0.java:119) [dcache-core-2.10.31.jar:2.10.31]
    at diskCacheV111.services.PoolStatisticsV0$HourlyRunner.run(PoolStatisticsV0.java:511) [dcache-core-2.10.31.jar:2.10.31]
    at dmg.cells.nucleus.CellNucleus$5.run(CellNucleus.java:742) [cells-2.10.31.jar:2.10.31]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
```

Cheers,
Andreas

**Comment by gbehrmann** [comment]
There are likely many other places in which this would break. The easy solution would be to disallow `/` in storage classes. Opinions?

**Comment by paulmillar** [comment]
To me the problem is that the statistics service takes a somewhat arbitrary string identifier and assumes it is OK to use this as a filename.

By coincidence, the code mostly runs on POSIX filesystems (so only '/', and NUL are invalid characters) and, by coincidence, storage classes tend not to include '/' in them, so this generally works, but I don't think it should be a requirement of a storage-class name that it is also a valid filename.

An alternative would be to build the statistics filename by escaping any awkward characters in the storage class -- percent-encoding, for example.

**Comment by gbehrmann** [comment]
@paul, congratulations - you just won a bug.

**Comment by paulmillar** [comment]
https://rb.dcache.org/r/8315/

**Comment by paulmillar** [comment]
Fix is now in all supported versions of dCache
