### ISSUE TITLE
httpd gets somehow in a bad state and doesn't update the transfers.txt

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#1783]
Hi.

Somehow the httpd got in a bad state with error messages like these:
2015-07-22 17:57:08 Launching /usr/bin/java -server -Xmx2048M -XX:MaxDirectMemorySize=512m -Dsun.net.inetaddr.ttl=1800 -Dorg.globus.tcp.port.range=60000,64999 -Dorg.dcache.dcap.port=0 -Dorg.
2015-07-22 17:57:11+02:00 (httpdPoolCollector) [] Failed to update topology map: Failed to deliver String message <1437580631914:121> to [>PoolManager@local]: Route for >PoolManager@local< n
2015-07-24 12:08:09+02:00 (httpd) [] Uncaught exception in thread Active Transfers Collector
java.lang.IllegalArgumentException: Multiple entries with same key: dcap.plain_lcg-lrz-dc61-<unknown>-AAUbhtA9W7g@dcap_lcg-lrz-dc61#35=150994948;dcap.plain_lcg-lrz-dc61-<unknown>-AAUbhtA9W7g
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150) ~[guava-18.0.jar:na]
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104) ~[guava-18.0.jar:na]
        at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70) ~[guava-18.0.jar:na]
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254) ~[guava-18.0.jar:na]
        at com.google.common.collect.Maps.uniqueIndex(Maps.java:1166) ~[guava-18.0.jar:na]
        at com.google.common.collect.Maps.uniqueIndex(Maps.java:1140) ~[guava-18.0.jar:na]
        at org.dcache.util.TransferCollector.getTransfers(TransferCollector.java:147) ~[dcache-core-2.13.4.jar:2.13.4]
        at org.dcache.util.TransferCollector.lambda$null$54(TransferCollector.java:119) ~[dcache-core-2.13.4.jar:2.13.4]
        at org.dcache.util.TransferCollector$$Lambda$51/1140826663.apply(Unknown Source) ~[na:na]
        at com.google.common.util.concurrent.Futures$2.apply(Futures.java:760) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture$1.run(Futures.java:918) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.Futures$ImmediateFuture.addListener(Futures.java:106) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:914) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.Futures$CombinedFuture.setOneValue(Futures.java:1764) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.Futures$CombinedFuture.access$400(Futures.java:1608) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.Futures$CombinedFuture$2.run(Futures.java:1686) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.Futures$FallbackFuture$1.onSuccess(Futures.java:462) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) ~[guava-18.0.jar:na]
        at org.dcache.cells.CellStub$CallbackFuture.set(CellStub.java:651) ~[dcache-core-2.13.4.jar:2.13.4]
        at org.dcache.cells.CellStub$CallbackFuture.answerArrived(CellStub.java:673) ~[dcache-core-2.13.4.jar:2.13.4]
        at dmg.cells.nucleus.CellNucleus$CallbackTask.run(CellNucleus.java:1053) ~[cells-2.13.4.jar:2.13.4]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299) ~[guava-18.0.jar:na]
        at dmg.cells.nucleus.CellNucleus.addToEventQueue(CellNucleus.java:836) ~[cells-2.13.4.jar:2.13.4]
        at dmg.cells.nucleus.CellGlue.deliverLocally(CellGlue.java:624) ~[cells-2.13.4.jar:2.13.4]
        at dmg.cells.nucleus.CellGlue.sendMessage(CellGlue.java:539) ~[cells-2.13.4.jar:2.13.4]
        at dmg.cells.nucleus.CellGlue.sendMessage(CellGlue.java:504) ~[cells-2.13.4.jar:2.13.4]
        at dmg.cells.nucleus.CellNucleus.sendMessage(CellNucleus.java:363) ~[cells-2.13.4.jar:2.13.4]
        at dmg.cells.nucleus.CellAdapter.sendMessage(CellAdapter.java:434) ~[cells-2.13.4.jar:2.13.4]
        at dmg.cells.network.LocationMgrTunnel.receive(LocationMgrTunnel.java:147) ~[cells-2.13.4.jar:2.13.4]
        at dmg.cells.network.LocationMgrTunnel.run(LocationMgrTunnel.java:165) ~[cells-2.13.4.jar:2.13.4]
        at dmg.cells.nucleus.CellNucleus$5.run(CellNucleus.java:744) ~[cells-2.13.4.jar:2.13.4]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_51]
2015-07-24 12:08:19+02:00 (httpdTransferObserver) [] java.lang.IllegalArgumentException: Multiple entries with same key: dcap.plain_lcg-lrz-dc61-<unknown>-AAUbhtA9W7g@dcap_lcg-lrz-dc61#35=15
java.lang.IllegalArgumentException: Multiple entries with same key: dcap.plain_lcg-lrz-dc61-<unknown>-AAUbhtA9W7g@dcap_lcg-lrz-dc61#35=150994948;dcap.plain_lcg-lrz-dc61-<unknown>-AAUbhtA9W7g
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150) ~[guava-18.0.jar:na]
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104) ~[guava-18.0.jar:na]
        at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70) ~[guava-18.0.jar:na]
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254) ~[guava-18.0.jar:na]
        at com.google.common.collect.Maps.uniqueIndex(Maps.java:1166) ~[guava-18.0.jar:na]
        at com.google.common.collect.Maps.uniqueIndex(Maps.java:1140) ~[guava-18.0.jar:na]
        at org.dcache.util.TransferCollector.getTransfers(TransferCollector.java:147) ~[dcache-core-2.13.4.jar:2.13.4]
        at diskCacheV111.cells.TransferObserverV1.collectDataSequentially(TransferObserverV1.java:420) ~[dcache-core-2.13.4.jar:2.13.4]
        at diskCacheV111.cells.TransferObserverV1.run(TransferObserverV1.java:385) ~[dcache-core-2.13.4.jar:2.13.4]
        at dmg.cells.nucleus.CellNucleus$5.run(CellNucleus.java:744) [cells-2.13.4.jar:2.13.4]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
2015-07-24 12:09:52+02:00 (httpdTransferObserver) [] java.lang.IllegalArgumentException: Multiple entries with same key: dcap.plain_lcg-lrz-dc55-<unknown>-AAUbijs0tOE@dcap_lcg-lrz-dc55#1=150
java.lang.IllegalArgumentException: Multiple entries with same key: dcap.plain_lcg-lrz-dc55-<unknown>-AAUbijs0tOE@dcap_lcg-lrz-dc55#1=150994982;dcap.plain_lcg-lrz-dc55-<unknown>-AAUbijs0tOE@
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150) ~[guava-18.0.jar:na]
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104) ~[guava-18.0.jar:na]
        at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70) ~[guava-18.0.jar:na]
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254) ~[guava-18.0.jar:na]
        at com.google.common.collect.Maps.uniqueIndex(Maps.java:1166) ~[guava-18.0.jar:na]
        at com.google.common.collect.Maps.uniqueIndex(Maps.java:1140) ~[guava-18.0.jar:na]
        at org.dcache.util.TransferCollector.getTransfers(TransferCollector.java:147) ~[dcache-core-2.13.4.jar:2.13.4]
        at diskCacheV111.cells.TransferObserverV1.collectDataSequentially(TransferObserverV1.java:420) ~[dcache-core-2.13.4.jar:2.13.4]
        at diskCacheV111.cells.TransferObserverV1.run(TransferObserverV1.java:385) ~[dcache-core-2.13.4.jar:2.13.4]
        at dmg.cells.nucleus.CellNucleus$5.run(CellNucleus.java:744) [cells-2.13.4.jar:2.13.4]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

A consequence is that the transfers.txt file is no longer update but kept at the same state.

Immediately after restarting http, the above errors occur again:
2015-07-27 16:27:27 Launching /usr/bin/java -server -Xmx2048M -XX:MaxDirectMemorySize=512m -Dsun.net.inetaddr.ttl=1800 -Dorg.globus.tcp.port.range=60000,64999 -Dorg.dcache.dcap.port=0 -Dorg.
2015-07-27 16:27:32+02:00 (httpd) [] Uncaught exception in thread Active Transfers Collector
java.lang.IllegalArgumentException: Multiple entries with same key: dcap.plain_lcg-lrz-dc55-<unknown>-AAUbyC3vPYA@dcap_lcg-lrz-dc55#19=150994996;dcap.plain_lcg-lrz-dc55-<unknown>-AAUbyC3vPYA
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150) ~[guava-18.0.jar:na]
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104) ~[guava-18.0.jar:na]
        at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70) ~[guava-18.0.jar:na]
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254) ~[guava-18.0.jar:na]
        at com.google.common.collect.Maps.uniqueIndex(Maps.java:1166) ~[guava-18.0.jar:na]
        at com.google.common.collect.Maps.uniqueIndex(Maps.java:1140) ~[guava-18.0.jar:na]
        at org.dcache.util.TransferCollector.getTransfers(TransferCollector.java:147) ~[dcache-core-2.13.4.jar:2.13.4]
        at org.dcache.util.TransferCollector.lambda$null$54(TransferCollector.java:119) ~[dcache-core-2.13.4.jar:2.13.4]
        at org.dcache.util.TransferCollector$$Lambda$64/1164875777.apply(Unknown Source) ~[na:na]
        at com.google.common.util.concurrent.Futures$2.apply(Futures.java:760) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture$1.run(Futures.java:918) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.Futures$ImmediateFuture.addListener(Futures.java:106) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:914) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.Futures$CombinedFuture.setOneValue(Futures.java:1764) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.Futures$CombinedFuture.access$400(Futures.java:1608) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.Futures$CombinedFuture$2.run(Futures.java:1686) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.Futures$FallbackFuture$1.onSuccess(Futures.java:462) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) ~[guava-18.0.jar:na]
        at org.dcache.cells.CellStub$CallbackFuture.set(CellStub.java:651) ~[dcache-core-2.13.4.jar:2.13.4]
        at org.dcache.cells.CellStub$CallbackFuture.answerArrived(CellStub.java:673) ~[dcache-core-2.13.4.jar:2.13.4]
        at dmg.cells.nucleus.CellNucleus$CallbackTask.run(CellNucleus.java:1053) ~[cells-2.13.4.jar:2.13.4]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299) ~[guava-18.0.jar:na]
        at dmg.cells.nucleus.CellNucleus.addToEventQueue(CellNucleus.java:836) ~[cells-2.13.4.jar:2.13.4]
        at dmg.cells.nucleus.CellGlue.deliverLocally(CellGlue.java:624) ~[cells-2.13.4.jar:2.13.4]
        at dmg.cells.nucleus.CellGlue.sendMessage(CellGlue.java:539) ~[cells-2.13.4.jar:2.13.4]
        at dmg.cells.nucleus.CellGlue.sendMessage(CellGlue.java:504) ~[cells-2.13.4.jar:2.13.4]
        at dmg.cells.nucleus.CellNucleus.sendMessage(CellNucleus.java:363) ~[cells-2.13.4.jar:2.13.4]
        at dmg.cells.nucleus.CellAdapter.sendMessage(CellAdapter.java:434) ~[cells-2.13.4.jar:2.13.4]
        at dmg.cells.network.LocationMgrTunnel.receive(LocationMgrTunnel.java:147) ~[cells-2.13.4.jar:2.13.4]
        at dmg.cells.network.LocationMgrTunnel.run(LocationMgrTunnel.java:165) ~[cells-2.13.4.jar:2.13.4]
        at dmg.cells.nucleus.CellNucleus$5.run(CellNucleus.java:744) ~[cells-2.13.4.jar:2.13.4]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_51]

Any ideas?

Cheers,
Chris

(dcache 2.13.4)

**Comment by gbehrmann** [comment]
https://rb.dcache.org/r/8435/

**Comment by calestyo** [comment]
Is there a tricky workaround that can be used in current 2.13.4? Like restarting domains foo and bar?

**Comment by calestyo** [comment]
+ thx for the fast fix :-)

**Comment by gbehrmann** [comment]
Restart all pools. Not much of a workaround. It is triggered by DCAP doors retrying transfers.
