### ISSUE TITLE
Stacktrace from JdbcFs#createFile throwing IllegalArgumentException

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#1825]
I see the following error with current tip of master

    02 Sep 2015 11:22:04 (NFS-sisyphus) [] Unhandled exception: java.lang.IllegalArgumentException: null
            at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108) ~[guava-18.0.jar:na]
            at org.dcache.chimera.JdbcFs.createFile(JdbcFs.java:353) ~[chimera-2.14.0-SNAPSHOT.jar:2.14.0-SNAPSHOT]
            at org.dcache.chimera.nfsv41.door.ChimeraVfs.create(ChimeraVfs.java:103) ~[dcache-nfs-2.14.0-SNAPSHOT.jar:2.14.0-SNAPSHOT]
            at org.dcache.nfs.vfs.VfsCache.create(VfsCache.java:155) ~[nfs4j-core-0.11.0.jar:0.11.0]
            at org.dcache.nfs.vfs.PseudoFs.create(PseudoFs.java:151) ~[nfs4j-core-0.11.0.jar:0.11.0]
            at org.dcache.nfs.v4.OperationCREATE.process(OperationCREATE.java:106) ~[nfs4j-core-0.11.0.jar:0.11.0]
            at org.dcache.nfs.v4.NFSServerV41.NFSPROC4_COMPOUND_4(NFSServerV41.java:152) ~[nfs4j-core-0.11.0.jar:0.11.0]
            at org.dcache.nfs.v4.xdr.nfs4_prot_NFS4_PROGRAM_ServerStub.dispatchOncRpcCall(nfs4_prot_NFS4_PROGRAM_ServerStub.java:48) [nfs4j-core-0.11.0.jar:0.11.0]
            at org.dcache.xdr.RpcDispatcher$1.run(RpcDispatcher.java:82) [oncrpc4j-core-2.4.1.jar:na]
            at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591) [grizzly-framework-2.3.21.jar:2.3.21]
            at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571) [grizzly-framework-2.3.21.jar:2.3.21]
            at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

**Comment by kofemann** [comment]
since commit 2228bb8 we assume that file can be only REG, nevertheless we support BLOCK , CHAR, FIFO  and SOCKET types as well.

**Comment by kofemann** [comment]
fixed in 3a94450

**Comment by gbehrmann** [comment]
Thanks.
