### ISSUE TITLE
NFS door LOOKUPP failing with NPE

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#1827]
I see the following error with current tip of master

    02 Sep 2015 11:14:02 (NFS-sisyphus) [] Unhandled exception: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
            at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[guava-18.0.jar:na]
            at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:na]
            at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava-18.0.jar:na]
            at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[guava-18.0.jar:na]
            at org.dcache.nfs.vfs.VfsCache.parentFromCacheOrLoad(VfsCache.java:249) ~[nfs4j-core-0.11.0.jar:0.11.0]
            at org.dcache.nfs.vfs.VfsCache.parentOf(VfsCache.java:110) ~[nfs4j-core-0.11.0.jar:0.11.0]
            at org.dcache.nfs.vfs.PseudoFs.parentOf(PseudoFs.java:228) ~[nfs4j-core-0.11.0.jar:0.11.0]
            at org.dcache.nfs.v4.OperationLOOKUPP.process(OperationLOOKUPP.java:58) ~[nfs4j-core-0.11.0.jar:0.11.0]
            at org.dcache.nfs.v4.NFSServerV41.NFSPROC4_COMPOUND_4(NFSServerV41.java:152) ~[nfs4j-core-0.11.0.jar:0.11.0]
            at org.dcache.nfs.v4.xdr.nfs4_prot_NFS4_PROGRAM_ServerStub.dispatchOncRpcCall(nfs4_prot_NFS4_PROGRAM_ServerStub.java:48) [nfs4j-core-0.11.0.jar:0.11.0]
            at org.dcache.xdr.RpcDispatcher$1.run(RpcDispatcher.java:82) [oncrpc4j-core-2.4.1.jar:na]
            at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591) [grizzly-framework-2.3.21.jar:2.3.21]
            at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571) [grizzly-framework-2.3.21.jar:2.3.21]
            at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
    Caused by: java.lang.NullPointerException: null
            at org.dcache.chimera.JdbcFs.inodeToBytes(JdbcFs.java:1521) ~[chimera-2.14.0-SNAPSHOT.jar:2.14.0-SNAPSHOT]
            at org.dcache.chimera.nfsv41.door.ChimeraVfs.toInode(ChimeraVfs.java:241) ~[dcache-nfs-2.14.0-SNAPSHOT.jar:2.14.0-SNAPSHOT]
            at org.dcache.chimera.nfsv41.door.ChimeraVfs.parentOf(ChimeraVfs.java:220) ~[dcache-nfs-2.14.0-SNAPSHOT.jar:2.14.0-SNAPSHOT]
            at org.dcache.nfs.vfs.VfsCache$ParentLoader.load(VfsCache.java:243) ~[nfs4j-core-0.11.0.jar:0.11.0]
            at org.dcache.nfs.vfs.VfsCache$ParentLoader.load(VfsCache.java:239) ~[nfs4j-core-0.11.0.jar:0.11.0]
            at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[guava-18.0.jar:na]
            at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) ~[guava-18.0.jar:na]
            at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) ~[guava-18.0.jar:na]
            at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) ~[guava-18.0.jar:na]
            ... 13 common frames omitted

**Comment by kofemann** [comment]
fixed in 718212c

**Comment by gbehrmann** [comment]
As far as I can see, this was the behaviour before my Chimera changes too. Is this an old bug, or is there something I am missing?

**Comment by paulmillar** [comment]
From sisyphus' dCacheDomain.log files, I see it was introduced by commit 87254c412 ("nfs: fix lookup of '..' after 2677f7ac")

**Comment by gbehrmann** [comment]
I see.

**Comment by kofemann** [comment]
the removal of '..'  had an effect that getParent on any inode was returning  not exist. The fix end up with NPE ojn petParent on the root of file system.
