### ISSUE TITLE
srmcp failure with IPv6

### ISSUE THREAD

**Issue by gbehrmann** [dCache/dcache#1838]
Our FTP client gets confused when the local host resolves to an IPv6 address while the control channel is IPv4:

    Gerds-MacBook-Pro:dcache-git behrmann$ srmcp  srm://localhost:8443/disk/test-1443503833-1/a file:////tmp/test
    Exception in thread "Thread-4" java.lang.NumberFormatException: For input string: "fe80:0:0:0:af64:477a:fb3e:dcfe%10"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.globus.ftp.HostPort.<init>(HostPort.java:72)
	at org.globus.ftp.vanilla.FTPServerFacade.setPassive(FTPServerFacade.java:202)
	at org.globus.ftp.extended.GridFTPServerFacade.setPassive(GridFTPServerFacade.java:235)
	at org.globus.ftp.vanilla.FTPServerFacade.setPassive(FTPServerFacade.java:173)
	at org.globus.ftp.FTPClient.setLocalPassive(FTPClient.java:1106)
	at org.globus.ftp.FTPClient.get2(FTPClient.java:1745)
	at org.dcache.srm.util.GridftpClient$TransferThread.run(GridftpClient.java:925)
	at java.lang.Thread.run(Thread.java:745)
    2015-09-29 08:08:25,576 [Thread-0] ERROR org.dcache.srm.util.GridftpClient - we wrote less then file size!!!

The same applies to the remote gsiftp mover.

**Comment by gbehrmann** [comment]
Karsten, can you have a look at this?

**Comment by kofemann** [comment]
SRM is not used anymore. Closing.
