### ISSUE TITLE
NPE during LocationManager initialization

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#1965]
I have rebased to master @bc9c55737d5b5c8a691fc5bb78a70317491c3b14 and I am seeing the following:
​
08:27
SLF4J: Failed toString() invocation on an object of type [dmg.cells.services.login.LoginManager]
java.lang.NullPointerException
       at dmg.cells.services.login.LoginManager.toString(LoginManager.java:456)
       at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:305)
       at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:277)
       at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:231)
       at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:115)
       at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:439)
       at ch.qos.logback.classic.Logger.filterAndLog_1(Logger.java:413)
       at ch.qos.logback.classic.Logger.info(Logger.java:603)
       at dmg.cells.services.LocationManager$Client.startListener(LocationManager.java:1025)
       at dmg.cells.services.LocationManager$Client.executeToDoList(LocationManager.java:1167)
       at dmg.cells.services.LocationManager$Client.runWhatToDo(LocationManager.java:1093)
       at dmg.cells.services.LocationManager$Client.run(LocationManager.java:1055)
       at dmg.cells.nucleus.CellNucleus$4.run(CellNucleus.java:712)
       at java.lang.Thread.run(Thread.java:745)

It appears that the logging info statement which calls toString() on the LoginManager is ahead of startUp() having been called for that cell.  I would recommend removing that final logging statement.

**Comment by gbehrmann** [comment]
Thanks - there is a bigger bug in this than the logging error though. I will submit a patch.

**Comment by gbehrmann** [comment]
See https://rb.dcache.org/r/8792/
