### ISSUE TITLE
index out of bount in the httpd

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#1971]
Hey.

dcache 2.13.10...

Every now and then there are exceptions like these in httpd

```
2015-10-26 11:25:50+01:00 (httpdPoolCollector) [] Failed to query lcg-lrz-dc58_1@pool_lcg-lrz-dc58_1: Failed to deliver String message <1445855150237:55816035> to [>lcg-lrz-dc58_1@pool_lcg-lrz-dc58_1]: Route for >lcg-lrz-dc58_1@pool_lcg-lrz-dc58_1< not found at >core<
2015-11-11 11:37:14+01:00 (httpd) [] Unexpected error occurred
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
    at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[na:1.8.0_66-internal]
    at java.util.ArrayList.get(ArrayList.java:429) ~[na:1.8.0_66-internal]
    at org.apache.wicket.core.request.mapper.CryptoMapper.decryptEntireUrl(CryptoMapper.java:528) ~[wicket-core-6.19.0.jar:6.19.0]
    at org.apache.wicket.core.request.mapper.CryptoMapper.decryptUrl(CryptoMapper.java:378) ~[wicket-core-6.19.0.jar:6.19.0]
    at org.apache.wicket.core.request.mapper.CryptoMapper.getCompatibilityScore(CryptoMapper.java:189) ~[wicket-core-6.19.0.jar:6.19.0]
    at org.apache.wicket.request.mapper.CompoundRequestMapper.mapRequest(CompoundRequestMapper.java:138) ~[wicket-request-6.19.0.jar:6.19.0]
    at org.apache.wicket.protocol.https.HttpsMapper.mapRequest(HttpsMapper.java:102) ~[wicket-core-6.19.0.jar:6.19.0]
    at org.apache.wicket.request.cycle.RequestCycle.resolveRequestHandler(RequestCycle.java:190) [wicket-core-6.19.0.jar:6.19.0]
    at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:215) [wicket-core-6.19.0.jar:6.19.0]
    at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289) [wicket-core-6.19.0.jar:6.19.0]
    at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259) [wicket-core-6.19.0.jar:6.19.0]
    at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201) [wicket-core-6.19.0.jar:6.19.0]
    at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:282) [wicket-core-6.19.0.jar:6.19.0]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.dcache.services.httpd.handlers.HandlerDelegator.handle(HandlerDelegator.java:135) [dcache-core-2.13.10.jar:2.13.10]
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.Server.handle(Server.java:497) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.10.v20150310.jar:9.2.10.v20150310]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66-internal]
2015-11-11 11:37:30+01:00 (httpd) [] Unexpected error occurred
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
    at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[na:1.8.0_66-internal]
    at java.util.ArrayList.get(ArrayList.java:429) ~[na:1.8.0_66-internal]
    at org.apache.wicket.core.request.mapper.CryptoMapper.decryptEntireUrl(CryptoMapper.java:528) ~[wicket-core-6.19.0.jar:6.19.0]
    at org.apache.wicket.core.request.mapper.CryptoMapper.decryptUrl(CryptoMapper.java:378) ~[wicket-core-6.19.0.jar:6.19.0]
    at org.apache.wicket.core.request.mapper.CryptoMapper.getCompatibilityScore(CryptoMapper.java:189) ~[wicket-core-6.19.0.jar:6.19.0]
    at org.apache.wicket.request.mapper.CompoundRequestMapper.mapRequest(CompoundRequestMapper.java:138) ~[wicket-request-6.19.0.jar:6.19.0]
    at org.apache.wicket.protocol.https.HttpsMapper.mapRequest(HttpsMapper.java:102) ~[wicket-core-6.19.0.jar:6.19.0]
    at org.apache.wicket.request.cycle.RequestCycle.resolveRequestHandler(RequestCycle.java:190) [wicket-core-6.19.0.jar:6.19.0]
    at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:215) [wicket-core-6.19.0.jar:6.19.0]
    at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289) [wicket-core-6.19.0.jar:6.19.0]
    at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259) [wicket-core-6.19.0.jar:6.19.0]
    at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201) [wicket-core-6.19.0.jar:6.19.0]
    at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:282) [wicket-core-6.19.0.jar:6.19.0]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.dcache.services.httpd.handlers.HandlerDelegator.handle(HandlerDelegator.java:135) [dcache-core-2.13.10.jar:2.13.10]
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.Server.handle(Server.java:497) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.10.v20150310.jar:9.2.10.v20150310]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.10.v20150310.jar:9.2.10.v20150310]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66-internal]
2015-11-12 10:24:18+01:00 (httpdPoolCollector) [] Failed to query lcg-lrz-dc58_7@pool_lcg-lrz-dc58_7: Failed to deliver String message <1447320258633:218947526> to [>lcg-lrz-dc58_7@pool_lcg-lrz-dc58_7]: Route for >lcg-lrz-dc58_7@pool_lcg-lrz-dc58_7< not found at >core<
2015-11-12 18:25:14+01:00 (httpdPoolCollector) [] Failed to query lcg-lrz-dc58_1@pool_lcg-lrz-dc58_1: Failed to deliver String message <1447349114206:222155102> to [>lcg-lrz-dc58_1@pool_lcg-lrz-dc58_1]: Route for >lcg-lrz-dc58_1@pool_lcg-lrz-dc58_1< not found at >core<
2015-11-15 00:01:10+01:00 (httpdPoolCollector) [] Failed to query lcg-lrz-dc58_5@pool_lcg-lrz-dc58_5: Failed to deliver String message <1447542070792:243984005> to [>lcg-lrz-dc58_5@pool_lcg-lrz-dc58_5]: Route for >lcg-lrz-dc58_5@pool_lcg-lrz-dc58_5< not found at >core<
```

Not sure whether this is actually a problem (the only what really doesn't seem to work properly in the httpd right now seems to be, that creating the pool mover queues page takes ages (i.e. 3 mins or so).

Just in case you that log helps you... if not simply close the issue.

Cheers,
Chris.

**Comment by paulmillar** [comment]
Prima facie, this looks like a problem within the Wicket library itself, rather than dCache.

However, I'm unable to reproduce this on the test system, and it doesn't seem to be a problem already reported against Wicket.

Could you try to discover more details about what is triggering these stack-traces.

Is it navigating to certain pages that causes the problem? Perhaps some activity on a particular page?

**Comment by alrossi** [comment]
I think Paul might be on the right track here.   Looks like a URL issue.  Might not like a pool name with an @ in it?

P.S., it looks like this is triggered internally by the collector, not from browser navigation ...

**Comment by alrossi** [comment]
sorry not "pool" with @ ... that's just a dCache address.
Not sure what the array issue is at this point ...

**Comment by paulmillar** [comment]
I think we need to understand how to reproduce the problem.  Until then, we cannot say for sure whether this is a dCache problem or a Wicket problem.  If it is a Wicket problem then we need to know how to reproduce it in order to write a reasonable bug-report.

**Comment by calestyo** [comment]
I already tried to trigger it (originally I expected it was related to the slow pool mover queue page)... but no sucess so far. It's at least nothing obvious, like clicking on any of the top pages...

@al ... we don't have pool names that contain "@"

**Comment by calestyo** [comment]
Haven't seen this in quite a while... guess we can close it.
