### ISSUE TITLE
canceling migration job in INITIALIZING state should produce a stacktrace

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#2006]
04 Dec 2015 15:19:10 (dcache-photon41-01) [admin] Command failed due to a bug, please contact support@dcache.org.
dmg.util.CommandPanicException: (1) Command failed: java.lang.IllegalStateException: The job cannot be cancelled in its present state
        at org.dcache.util.cli.AnnotatedCommandExecutor.execute(AnnotatedCommandExecutor.java:141) ~[common-cli-2.13.10sf.jar:2.13.10sf]
        at org.dcache.util.cli.CommandInterpreter$CommandEntry.execute(CommandInterpreter.java:260) ~[common-cli-2.13.10sf.jar:2.13.10sf]
        at org.dcache.util.cli.CommandInterpreter.doExecute(CommandInterpreter.java:169) ~[common-cli-2.13.10sf.jar:2.13.10sf]
        at dmg.cells.nucleus.CellAdapter$1.doExecute(CellAdapter.java:99) ~[cells-2.13.10sf.jar:2.13.10sf]
        at org.dcache.util.cli.CommandInterpreter.command(CommandInterpreter.java:155) ~[common-cli-2.13.10sf.jar:2.13.10sf]
        at dmg.cells.nucleus.CellAdapter$1.command(CellAdapter.java:116) ~[cells-2.13.10sf.jar:2.13.10sf]
        at dmg.cells.nucleus.CellAdapter.command(CellAdapter.java:218) ~[cells-2.13.10sf.jar:2.13.10sf]
        at dmg.cells.nucleus.CellAdapter.executeLocalCommand(CellAdapter.java:876) ~[cells-2.13.10sf.jar:2.13.10sf]
        at dmg.cells.nucleus.CellAdapter.messageArrived(CellAdapter.java:813) ~[cells-2.13.10sf.jar:2.13.10sf]
        at dmg.cells.nucleus.CellNucleus$DeliverMessageTask.run(CellNucleus.java:1105) [cells-2.13.10sf.jar:2.13.10sf]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: java.lang.IllegalStateException: The job cannot be cancelled in its present state
        at org.dcache.pool.migration.Job.cancel(Job.java:283) ~[dcache-core-2.13.10sf.jar:2.13.10sf]
        at org.dcache.pool.migration.MigrationModule$MigrationCancelCommand.call(MigrationModule.java:948) ~[dcache-core-2.13.10sf.jar:2.13.10sf]
        at org.dcache.pool.migration.MigrationModule$MigrationCancelCommand.call(MigrationModule.java:934) ~[dcache-core-2.13.10sf.jar:2.13.10sf]
        at org.dcache.util.cli.AnnotatedCommandExecutor.execute(AnnotatedCommandExecutor.java:130) ~[common-cli-2.13.10sf.jar:2.13.10sf]
        ... 12 common frames omitted

**Comment by gbehrmann** [comment]
Thanks
