### ISSUE TITLE
bad SQL grammar exceptions in PnfsManager

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#2407]
found in your log files

14 May 2016 00:43:11 (PnfsManager) [dcache-photon17-08 PnfsFlag 0000A46614130D18483ABAF9FA374DD59B07] Exception in setFileAttributes: {}
org.dcache.chimera.IOHimeraFsException: PreparedStatementCallback; bad SQL grammar [UPDATE t_level_2 SET ifiledata=?,isize=? WHERE ino=?]; nested excepti
on is org.postgresql.util.PSQLException: ERROR: column "ino" does not exist
  Position: 50
        at org.dcache.chimera.JdbcFs.inTransaction(JdbcFs.java:210) ~[chimera-2.15.5.jar:2.15.5]
        at org.dcache.chimera.JdbcFs.write(JdbcFs.java:1012) ~[chimera-2.15.5.jar:2.15.5]
        at sun.reflect.GeneratedMethodAccessor290.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
        at org.dcache.commons.stats.MonitoringProxy.invoke(MonitoringProxy.java:54) ~[dcache-common-2.15.5.jar:2.15.5]
        at com.sun.proxy.$Proxy18.write(Unknown Source) ~[na:na]
        at org.dcache.chimera.FsInode.write(FsInode.java:202) ~[chimera-2.15.5.jar:2.15.5]
        at org.dcache.chimera.namespace.ChimeraCacheInfo.writeCacheInfo(ChimeraCacheInfo.java:161) ~[dcache-chimera-2.15.5.jar:2.15.5]
        at org.dcache.chimera.namespace.ChimeraNameSpaceProvider.setFileAttributes(ChimeraNameSpaceProvider.java:997) ~[dcache-chimera-2.15.5.jar:2.15.5]
        at diskCacheV111.namespace.PnfsManagerV3.updateFlag(PnfsManagerV3.java:1011) [dcache-core-2.15.5.jar:2.15.5]
        at diskCacheV111.namespace.PnfsManagerV3.updateFlag(PnfsManagerV3.java:986) [dcache-core-2.15.5.jar:2.15.5]
        at diskCacheV111.namespace.PnfsManagerV3.processMessageTransactionally_aroundBody16(PnfsManagerV3.java:1696) [dcache-core-2.15.5.jar:2.15.5]
        at diskCacheV111.namespace.PnfsManagerV3$AjcClosure17.run(PnfsManagerV3.java:1) [dcache-core-2.15.5.jar:2.15.5]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect
$1$2a73e96cproceed(AbstractTransactionAspect.aj:66) [spring-aspects-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.
aj:72) [spring-aspects-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) [spring-tx-4.2
.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect
$1$2a73e96c(AbstractTransactionAspect.aj:70) [spring-aspects-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at diskCacheV111.namespace.PnfsManagerV3.processMessageTransactionally(PnfsManagerV3.java:1671) [dcache-core-2.15.5.jar:2.15.5]
        at diskCacheV111.namespace.PnfsManagerV3.processPnfsMessage(PnfsManagerV3.java:1639) [dcache-core-2.15.5.jar:2.15.5]
        at diskCacheV111.namespace.PnfsManagerV3$ProcessThread.run(PnfsManagerV3.java:1562) [dcache-core-2.15.5.jar:2.15.5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]

**Comment by gbehrmann** [comment]
Good catch - do you write a patch or should I?

**Comment by kofemann** [comment]
I can do that, as we have to update out system
