### ISSUE TITLE
IllegalArgumentException in PnfsManager when told to create directory //upload

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#2430]
The arc FTP client attempts to create a directory for each path element.  For a dCache SRM-generated TURL, it tries to create paths before attempting the upload; for example, issuing the commands `MKD /`, `MKD //upload`, `MKD //upload/4` and finally `MKD //upload/4/a8d6de30-85ac-47d3-b814-259cdccd82ed`.

The first command (`MKD /`) fails with `550 directory already exists`, the next one (`MKD //upload`) fails with `550 Cannot create directory, reason: CacheException(rc=10011;msg=java.lang.IllegalArgumentException)`, subsequent `MKD` commands fail with `550 Permission denied`.

The `MKD //upload` triggers a bug in PnfsManager, which is logged as:

```
19 May 2016 08:27:40 (PnfsManager) [door:GFTP-prometheus-AAUzLBIqbEg@dCacheDomain GFTP-prometheus-AAUzLBIqbEg PnfsCreateDirectory] Failed to create directory
java.lang.IllegalArgumentException: null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108) ~[guava-19.0.jar:na]
        at diskCacheV111.util.FsPath.create(FsPath.java:37) ~[dcache-common-2.16.0-SNAPSHOT.jar:2.16.0-SNAPSHOT]
        at org.dcache.chimera.namespace.ExtendedInode.getPath(ExtendedInode.java:243) ~[dcache-chimera-2.16.0-SNAPSHOT.jar:2.16.0-SNAPSHOT]
        at org.dcache.chimera.namespace.ChimeraNameSpaceProvider.mkdir(ChimeraNameSpaceProvider.java:1079) ~[dcache-chimera-2.16.0-SNAPSHOT.jar:2.16.0-SNAPSHOT]
        at org.dcache.chimera.namespace.ChimeraNameSpaceProvider.createDirectory(ChimeraNameSpaceProvider.java:292) ~[dcache-chimera-2.16.0-SNAPSHOT.jar:2.16.0-SNAPSHOT]
        at diskCacheV111.namespace.PnfsManagerV3.createDirectory(PnfsManagerV3.java:1190) [dcache-core-2.16.0-SNAPSHOT.jar:2.16.0-SNAPSHOT]
        at diskCacheV111.namespace.PnfsManagerV3.processMessageTransactionally_aroundBody8(PnfsManagerV3.java:1711) [dcache-core-2.16.0-SNAPSHOT.jar:2.16.0-SNAPSHOT]
        at diskCacheV111.namespace.PnfsManagerV3$AjcClosure9.run(PnfsManagerV3.java:1) [dcache-core-2.16.0-SNAPSHOT.jar:2.16.0-SNAPSHOT]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:66) [spring-aspects-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:72) [spring-aspects-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) [spring-tx-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:70) [spring-aspects-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at diskCacheV111.namespace.PnfsManagerV3.processMessageTransactionally(PnfsManagerV3.java:1702) [dcache-core-2.16.0-SNAPSHOT.jar:2.16.0-SNAPSHOT]
        at diskCacheV111.namespace.PnfsManagerV3.processPnfsMessage(PnfsManagerV3.java:1670) [dcache-core-2.16.0-SNAPSHOT.jar:2.16.0-SNAPSHOT]
        at diskCacheV111.namespace.PnfsManagerV3$ProcessThread.run(PnfsManagerV3.java:1593) [dcache-core-2.16.0-SNAPSHOT.jar:2.16.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
```

**Comment by paulmillar** [comment]
I noticed this on prometheus, and can reproduce this using UberFTP directly:

```
paul@celebrimbor:~$ ~/git/UberFTP/uberftp prometheus
220 GSI FTP door ready
200 User :globus-mapping: logged in
UberFTP (2.8)> quote MKD //upload
550 Cannot create directory, reason:CacheException(rc=10011;msg=java.lang.IllegalArgumentException)
UberFTP (2.8)> 
```
However, I have been unable to reproduce this using system-test or with sisyphus.
System-test gives the expected response:
```
paul@celebrimbor:~$ ~/git/UberFTP/uberftp localhost
220 GSI FTP door ready
200 User :globus-mapping: logged in
UberFTP (2.8)> quote MKD //upload
550 Permission denied
UberFTP (2.8)>
```

Whereas sisyphus gives a different response:
```
220 GSI FTP door ready                                                     
200 User :globus-mapping: logged in                                  
UberFTP (2.8)> quote MKD //upload                                              
550 "/upload" directory already exists                                     
UberFTP (2.8)>
```

Permissions of the root inode are different: on prometheus:
```
[root@prometheus ~]# chimera ls
total 6
drwxr-xr-x  7 0    0 512 May 19 06:04 .
d-w-rwxr--  2 0    0 512 May 19 06:00 lost+found
drwxr-xr-x 13 0 1000 512 May 19 06:00 VOs
drwxr-xr-x  8 0 2000 512 May 19 06:00 Users
drwxr-xr-x  4 0 2000 512 May 19 06:02 Video
drwx--x--x 10 0    0 512 May 19 09:36 upload
[root@prometheus ~]# 
```

for system-test:
```
paul@celebrimbor:~/git/dCache (fix/pnfsmanager-npe-path)$ packages/system-test/target/dcache/bin/chimera ls
total 10
dr-xr-xr-x 11    0    0 512 May 19 09:39 .
drwxr-xr-x  2 1000 1000 512 May 19 09:30 disk
d-w-rwxr--  2    0    0 512 May 19 09:30 lost+found
drwx------  2 1000 1000 512 May 19 09:30 private
drwxrwxrwx  3 1000 1000 512 May 19 09:39 public
drwxr-xr-x  2 1000 1000 512 May 19 09:30 replica
drwxr-xr-x  2 1000 1000 512 May 19 09:30 reserved
drwxr-xr-x  2 1000 1000 512 May 19 09:30 resilient
drwxr-xr-x  4 1000 1000 512 May 19 09:38 tape
drwx--x--x  3    0    0 512 May 19 09:39 upload
paul@celebrimbor:~/git/dCache (fix/pnfsmanager-npe-path)$ 
```

and for sisyphus:
```
[root@sisyphus ~]# chimera ls
total 4
drwxrwxrwx  5 0 0 512 May 18 18:00 .
d-w-rwxr--  2 0 0 512 May 18 17:51 lost+found
drwxr-xr-x  5 0 0 512 May 18 17:52 data
drwx--x--x 14 0 0 512 May 18 18:00 upload
[root@sisyphus ~]# 
```

**Comment by gbehrmann** [comment]
The issue is postgresql specific and is a regression in master. The cause is #2389 (which is an old bug), but combined with the refactoring of the FsPath class (which contains stronger preconditions), this is now triggering a precondition failure.
