### ISSUE TITLE
webdav: Invalid response when downloading a file for which user lacks authorization

### ISSUE THREAD

**Issue by gbehrmann** [dCache/dcache#2461]
Using `system-test`, do the following:

    $ globus-url-copy file:/bin/bash gsiftp://localhost/private/test-1464468242-1
    $ curl -v http://localhost:2880/private/test-1464468242-1

This should result in an access denied error page, but it results in a 200 OK response with a truncated body:

```
*   Trying ::1...
* connect to ::1 port 2880 failed: Connection refused
*   Trying fe80::1...
* connect to fe80::1 port 2880 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 2880 (#0)
> GET /private/test-1464468242-1 HTTP/1.1
> Host: localhost:2880
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Sat, 28 May 2016 20:44:12 GMT
< Server: dCache/2.17.0-SNAPSHOT
< Transfer-Encoding: chunked
< 
* transfer closed with outstanding read data remaining
* Closing connection 0
curl: (18) transfer closed with outstanding read data remaining
```

The log file contains the following error:

```
28 maj 2016 22:44:12 (PnfsManager) [door:WebDAV-Gerds-MacBook-Pro@dCacheDomain:AAUz7RX4OMA WebDAV-Gerds-MacBook-Pro PnfsGetFileAttributes] Error while retrieving file attributes: Access denied: /private/test-1464468242-1
28 maj 2016 22:44:12 (WebDAV-Gerds-MacBook-Pro) [] //localhost:2880/private/test-1464468242-1
java.lang.RuntimeException: Can't generate challenge because resource is null, so can't get realm
        at io.milton.http.http11.auth.BasicAuthHandler.appendChallenges(BasicAuthHandler.java:75) ~[milton-server-ce-2.7.1.5.jar:na]
        at io.milton.http.AuthenticationService.getChallenges(AuthenticationService.java:146) ~[milton-server-ce-2.7.1.5.jar:na]
        at org.dcache.webdav.DcacheResponseHandler.respondUnauthorised(DcacheResponseHandler.java:134) ~[dcache-webdav-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
        at io.milton.http.AbstractWrappingResponseHandler.respondUnauthorised(AbstractWrappingResponseHandler.java:124) ~[milton-server-ce-2.7.1.5.jar:na]
        at org.dcache.webdav.DcacheStandardFilter.process(DcacheStandardFilter.java:74) ~[dcache-webdav-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
        at io.milton.http.FilterChain.process(FilterChain.java:40) ~[milton-server-ce-2.7.1.5.jar:na]
        at org.dcache.webdav.transfer.CopyFilter.process(CopyFilter.java:187) ~[dcache-webdav-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
        at io.milton.http.FilterChain.process(FilterChain.java:40) ~[milton-server-ce-2.7.1.5.jar:na]
        at io.milton.http.HttpManager.process(HttpManager.java:158) ~[milton-server-ce-2.7.1.5.jar:na]
        at org.dcache.webdav.MiltonHandler.handle(MiltonHandler.java:74) ~[dcache-webdav-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) ~[jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) ~[jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
        at org.dcache.webdav.AuthenticationHandler.access$001(AuthenticationHandler.java:50) ~[dcache-webdav-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
        at org.dcache.webdav.AuthenticationHandler.lambda$handle$0(AuthenticationHandler.java:93) ~[dcache-webdav-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_60]
        at javax.security.auth.Subject.doAs(Subject.java:360) ~[na:1.8.0_60]
        at org.dcache.webdav.AuthenticationHandler.handle(AuthenticationHandler.java:91) ~[dcache-webdav-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) ~[jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
        at org.dcache.webdav.LoggingHandler.handle(LoggingHandler.java:38) ~[dcache-webdav-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) ~[jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) ~[jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:318) ~[jetty-rewrite-9.3.8.v20160314.jar:9.3.8.v20160314]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) ~[jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
        at org.eclipse.jetty.server.Server.handle(Server.java:518) ~[jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308) ~[jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244) [jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.8.v20160314.jar:9.3.8.v20160314]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.8.v20160314.jar:9.3.8.v20160314]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.8.v20160314.jar:9.3.8.v20160314]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246) [jetty-util-9.3.8.v20160314.jar:9.3.8.v20160314]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156) [jetty-util-9.3.8.v20160314.jar:9.3.8.v20160314]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [jetty-util-9.3.8.v20160314.jar:9.3.8.v20160314]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [jetty-util-9.3.8.v20160314.jar:9.3.8.v20160314]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```

This bug is already present in 2.10, so this is not a recent regression.

**Comment by anupash** [comment]
This happens because 

`DcacheResourceFactory.java:569    public DcacheResource getResource(FsPath path)`

throws an UnauthorizedException and sets the resource field in the UnauthorizedException constructor to be null.

**Comment by gbehrmann** [comment]
Yes, I know. There is a patch for it on review board.
