### ISSUE TITLE
Subjects.isNobody still throws NPE

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#2502]
Looks like I still haven't covered all the bases.

```
01 Jun 2016 14:22:48 (httpd) [] Uncaught exception in thread Active Transfers Collector
java.lang.NullPointerException: null
        at org.dcache.auth.Subjects.isNobody(Subjects.java:74) ~[dcache-common-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
        at diskCacheV111.util.UserInfo.<init>(UserInfo.java:99) ~[dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
        at diskCacheV111.util.TransferInfo.setSubject(TransferInfo.java:269) ~[dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
        at org.dcache.webadmin.controller.util.BeanDataMapper.moverModelToView(BeanDataMapper.java:129) ~[classes/:na]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_91]
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[na:1.8.0_91]
        at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294) ~[na:1.8.0_91]
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206) ~[na:1.8.0_91]
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169) ~[na:1.8.0_91]
        at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300) ~[na:1.8.0_91]
        at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681) ~[na:1.8.0_91]
        at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:409) ~[guava-19.0.jar:na]
        at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:692) ~[guava-19.0.jar:na]
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:256) ~[guava-19.0.jar:na]
        at org.dcache.webadmin.model.dataaccess.communication.collectors.ActiveTransfersCollector.call(ActiveTransfersCollector.java:40) ~[classes/:na]
        at org.dcache.webadmin.model.dataaccess.communication.collectors.ActiveTransfersCollector.call(ActiveTransfersCollector.java:18) ~[classes/:na]
        at org.dcache.util.backoff.BackoffController.call(BackoffController.java:94) ~[dcache-common-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
        at org.dcache.webadmin.model.dataaccess.communication.collectors.Collector.run(Collector.java:65) ~[classes/:na]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]
```

**Comment by gbehrmann** [comment]
So you have a transfer that is reported without a Subject at all. Any idea where that comes from?

**Comment by alrossi** [comment]
All I know is that under the conditions we have on our testbed it can occur.  I am using anonymous dccp, I don't think this is related to another issue we have been seeing involving p2p?  We are getting interference from our security people monitoring the http connections (they think they are renegade web services).   When the connection remains open for a bit longer they seem to be able to intercept it.  I've noticed that we occasionally get "faulty URL" exceptions.  But would that show up here? I don't think so, as this path in the code has to do with Active Transfers from the doors, if I understand correctly.

**Comment by jstarek** [comment]
Is this issue still open?

**Comment by alrossi** [comment]
If I recall, the code was fixed to catch the NPE, but the origin of it has never been resolved.
