### ISSUE TITLE
dcache nfs41: Internal failure during space management

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#2550]
Hi.

dCache 2.15.3-1

I noted the following by accident (haven't tried to reproduce it yet).
We must upload these rucio chimera dumps for ATLAS, in some dir.
Apparently the dump dir (on which I've had set WriteToken) got empty and deleted, and subsequently auto-recreated by my script (but without WriteToken set).

So first any uploads failed because of this (which is of course expected), but then I set it, and then some error condition came up that only resolved by unmounting pnfs and restarting the nfs door:

Uploads failed with:
```
/pnfs/lrz-muenchen.de/data/atlas/dq2/atlascalibdisk/dumps# echo "foo" > bar
-bash: echo: write error: Remote I/O error

```

The nfs door's log said:
```
2016-06-10 15:02:03+02:00 (nfs_lcg-lrz-dcache) [/0:0:0:0:0:0:0:1:849 0000080000000000D2C8BD0130 door:nfs_lcg-lrz-dcache:AAU07CUoUlg 0000268136173D044507B39BEA8436BA3DAB /0:0:0:0:0:0:0:1:849] No write pools configured outside of a linkgroup.
2016-06-10 15:02:03+02:00 (nfs_lcg-lrz-dcache) [/0:0:0:0:0:0:0:1:849 0000080000000000D2C8BD0130] failed to create IO adapter: NFS4ERR_NOSPC : No write pools configured outside of a linkgroup.
2016-06-10 15:02:03+02:00 (nfs_lcg-lrz-dcache) [/0:0:0:0:0:0:0:1:849 0000080000000000D2C8BD0130 door:nfs_lcg-lrz-dcache:AAU07CUocZg 0000268136173D044507B39BEA8436BA3DAB /0:0:0:0:0:0:0:1:849] No write pools configured outside of a linkgroup.
2016-06-10 15:02:03+02:00 (nfs_lcg-lrz-dcache) [/0:0:0:0:0:0:0:1:849 0000080000000000D2C8BD0130] failed to create IO adapter: NFS4ERR_NOSPC : No write pools configured outside of a linkgroup.
2016-06-10 15:02:03+02:00 (nfs_lcg-lrz-dcache) [/0:0:0:0:0:0:0:1:849 0000080000000000D2C8BD0130 door:nfs_lcg-lrz-dcache:AAU07CUoiQg 0000268136173D044507B39BEA8436BA3DAB /0:0:0:0:0:0:0:1:849] No write pools configured outside of a linkgroup.
2016-06-10 15:02:03+02:00 (nfs_lcg-lrz-dcache) [/0:0:0:0:0:0:0:1:849 0000080000000000D2C8BD0130] failed to create IO adapter: NFS4ERR_NOSPC : No write pools configured outside of a linkgroup.
2016-06-10 15:08:01+02:00 (nfs_lcg-lrz-dcache) [] Unhandled exception:
org.dcache.chimera.InvalidArgumentChimeraException: Not a file.
	at org.dcache.chimera.FsSqlDriver.remove(FsSqlDriver.java:280) ~[chimera-2.15.3.jar:2.15.3]
	at org.dcache.chimera.JdbcFs.lambda$remove$12(JdbcFs.java:498) ~[chimera-2.15.3.jar:2.15.3]
	at org.dcache.chimera.JdbcFs.inTransaction(JdbcFs.java:200) ~[chimera-2.15.3.jar:2.15.3]
	at org.dcache.chimera.JdbcFs.remove(JdbcFs.java:497) ~[chimera-2.15.3.jar:2.15.3]
	at org.dcache.chimera.DCacheAwareJdbcFs.remove(DCacheAwareJdbcFs.java:181) ~[dcache-chimera-2.15.3.jar:2.15.3]
	at org.dcache.chimera.nfsv41.door.ChimeraVfs.remove(ChimeraVfs.java:203) ~[dcache-nfs-2.15.3.jar:2.15.3]
	at org.dcache.nfs.vfs.VfsCache.remove(VfsCache.java:102) ~[nfs4j-core-0.11.2.jar:0.11.2]
	at org.dcache.nfs.vfs.PseudoFs.remove(PseudoFs.java:264) ~[nfs4j-core-0.11.2.jar:0.11.2]
	at org.dcache.nfs.v4.OperationREMOVE.process(OperationREMOVE.java:62) ~[nfs4j-core-0.11.2.jar:0.11.2]
	at org.dcache.chimera.nfsv41.door.proxy.ProxyIoMdsOpFactory$1.lambda$process$17(ProxyIoMdsOpFactory.java:53) ~[dcache-nfs-2.15.3.jar:2.15.3]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_72-internal]
	at javax.security.auth.Subject.doAs(Subject.java:360) ~[na:1.8.0_72-internal]
	at org.dcache.chimera.nfsv41.door.proxy.ProxyIoMdsOpFactory$1.process(ProxyIoMdsOpFactory.java:50) ~[dcache-nfs-2.15.3.jar:2.15.3]
	at org.dcache.nfs.v4.NFSServerV41.NFSPROC4_COMPOUND_4(NFSServerV41.java:152) ~[nfs4j-core-0.11.2.jar:0.11.2]
	at org.dcache.nfs.v4.xdr.nfs4_prot_NFS4_PROGRAM_ServerStub.dispatchOncRpcCall(nfs4_prot_NFS4_PROGRAM_ServerStub.java:48) [nfs4j-core-0.11.2.jar:0.11.2]
	at org.dcache.xdr.RpcDispatcher$1.run(RpcDispatcher.java:82) [oncrpc4j-core-2.4.2.jar:na]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591) [grizzly-framework-2.3.23.jar:2.3.23]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571) [grizzly-framework-2.3.23.jar:2.3.23]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72-internal]
2016-06-10 15:12:24+02:00 (nfs_lcg-lrz-dcache) [/0:0:0:0:0:0:0:1:849 0000080000000000D2CF7C0130] failed to create IO adapter: NFS4ERR_LAYOUTTRYLATER : Internal failure during space management
2016-06-10 15:14:37+02:00 (nfs_lcg-lrz-dcache) [/0:0:0:0:0:0:0:1:849 0000080000000000D2D0640130] failed to create IO adapter: NFS4ERR_LAYOUTTRYLATER : Internal failure during space management
2016-06-10 21:31:44+02:00 (nfs_lcg-lrz-dcache) [/0:0:0:0:0:0:0:1:849 0000080000000000D38B880130] failed to create IO adapter: NFS4ERR_LAYOUTTRYLATER : Internal failure during space management
2016-06-10 21:33:30+02:00 (nfs_lcg-lrz-dcache) [] Bad client: op: ILLEGAL<57> : NFS4ERR_STALE_CLIENTID : bad client id.
2016-06-10 21:33:53+02:00 (RoutingMgr) [] Unable to notify [>RoutingMgr@nfs] about delivery failure of message sent to [>RoutingMgr@local]: No route for RoutingMgr@nfs in nfs.
2016-06-10 21:33:53+02:00 (c-core-AAUvm9S8bKA) [] Sleeping 29 seconds
2016-06-10 21:33:54 Process terminated

2016-06-10 21:33:54 Launching /usr/bin/java -server -Xmx4096M -XX:MaxDirectMemorySize=512m -Dsun.net.inetaddr.ttl=1800 -Dorg.globus.tcp.port.range=60000,64999 -Dorg.dcache.dcap.port=0 -Dorg.dcache.net.tcp.portrange=65000:65499 -Dorg.globus.jglobus.delegation.cache.lifetime=30000 -Dorg.globus.jglobus.crl.cache.lifetime=60000 -Djava.security.krb5.realm= -Djava.security.krb5.kdc= -Djavax.security.auth.useSubjectCredsOnly=false -Djava.security.auth.login.config=/etc/dcache/jgss.conf -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/dcache/nfs-oom.hprof -XX:+UseCompressedOops -javaagent:/usr/share/dcache/classes/aspectjweaver-1.8.8.jar -Djava.awt.headless=true -DwantLog4jSetup=n -Ddcache.home=/usr/share/dcache -Ddcache.paths.defaults=/usr/share/dcache/defaults org.dcache.boot.BootLoader start nfs

```

This is from the beginning where no WriteToken was set over the error, until restart.
After restart it worked again. Nothing else was changed in between.

Cheers,
Chris.

**Comment by calestyo** [comment]
okay the issue seems reproducible... I managed to upload one file,... then I start getting:
```
2016-06-10 21:42:08+02:00 (nfs_lcg-lrz-dcache) [] Bad client: op: ILLEGAL<57> : NFS4ERR_STALE_CLIENTID : bad client id.
2016-06-10 21:43:38+02:00 (nfs_lcg-lrz-dcache) [/0:0:0:0:0:0:0:1:840 0000080000000000D390D70130] failed to create IO adapter: NFS4ERR_LAYOUTTRYLATER : Internal failure during space management
2016-06-10 21:44:54+02:00 (nfs_lcg-lrz-dcache) [/0:0:0:0:0:0:0:1:840 0000080000000000D391670130] failed to create IO adapter: NFS4ERR_LAYOUTTRYLATER : Internal failure during space management

```

The bad client thingy seems to appear on unmounting /pnfs

**Comment by calestyo** [comment]
Also,... while it's e.g. trying to cp to /pnfs/lrz-muenchen.de/data/atlas/dq2/atlasdatadisk/dumps/.placeholder, directory listings on that dir basically hang... and also the copy(try) hangs quite long, till it fails... a minute or so.

**Comment by paulmillar** [comment]
Hi Chris,

Thanks for reporting this.

Tigran is currently away at an NFS conference, so may be delayed in replying.

In the mean time, could you run these queries and copy back the output:

    SELECT * FROM t_inodes WHERE ipnfsid='0000080000000000D2C8BD0130';

and

    SELECT * FROM t_dirs WHERE iparent=(SELECT inumber FROM t_inodes WHERE ipnfsid='0000080000000000D2C8BD0130') OR ichild=(SELECT inumber FROM t_inodes WHERE ipnfsid='0000080000000000D2C8BD0130');

**Comment by calestyo** [comment]
Will look up what you wanted in a minute... but for now:
When I try to upload to nfs41, then I get these in the logs:

```
2016-06-13 16:57:25+02:00 (SpaceManager) [door:nfs_lcg-lrz-dcache:AAU1KhtELmg nfs_lcg-lrz-dcache PoolAcceptFile 0000A0C73B0D108D450EB323136688C4C80A] Message processing failed: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL []; ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(0000A0C73B0D108D450EB323136688C4C80A) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(0000A0C73B0D108D450EB323136688C4C80A) already exists.
2016-06-13 16:57:41+02:00 (SpaceManager) [door:nfs_lcg-lrz-dcache:AAU1KhwsHWg nfs_lcg-lrz-dcache PoolAcceptFile 0000A0C73B0D108D450EB323136688C4C80A] Message processing failed: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL []; ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(0000A0C73B0D108D450EB323136688C4C80A) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(0000A0C73B0D108D450EB323136688C4C80A) already exists.
2016-06-13 16:58:10+02:00 (SpaceManager) [door:nfs_lcg-lrz-dcache:AAU1Kh3yN2g nfs_lcg-lrz-dcache PoolAcceptFile 0000A0C73B0D108D450EB323136688C4C80A] Message processing failed: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL []; ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(0000A0C73B0D108D450EB323136688C4C80A) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(0000A0C73B0D108D450EB323136688C4C80A) already exists.
2016-06-13 16:58:10+02:00 (SpaceManager) [door:nfs_lcg-lrz-dcache:AAU1Kh3yUsA nfs_lcg-lrz-dcache PoolAcceptFile 0000A0C73B0D108D450EB323136688C4C80A] Message processing failed: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL []; ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(0000A0C73B0D108D450EB323136688C4C80A) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(0000A0C73B0D108D450EB323136688C4C80A) already exists.
2016-06-13 16:58:42+02:00 (SpaceManager) [door:nfs_lcg-lrz-dcache:AAU1Kh/Ox2g nfs_lcg-lrz-dcache PoolAcceptFile 000092E0BD0896C142A490F0243F58D9C77D] Message processing failed: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL []; ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(000092E0BD0896C142A490F0243F58D9C77D) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(000092E0BD0896C142A490F0243F58D9C77D) already exists.
2016-06-13 16:58:57+02:00 (SpaceManager) [door:nfs_lcg-lrz-dcache:AAU1KiC2OWg nfs_lcg-lrz-dcache PoolAcceptFile 000092E0BD0896C142A490F0243F58D9C77D] Message processing failed: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL []; ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(000092E0BD0896C142A490F0243F58D9C77D) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(000092E0BD0896C142A490F0243F58D9C77D) already exists.
2016-06-13 16:59:27+02:00 (SpaceManager) [door:nfs_lcg-lrz-dcache:AAU1KiJ8U2g nfs_lcg-lrz-dcache PoolAcceptFile 000092E0BD0896C142A490F0243F58D9C77D] Message processing failed: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL []; ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(000092E0BD0896C142A490F0243F58D9C77D) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(000092E0BD0896C142A490F0243F58D9C77D) already exists.
2016-06-13 16:59:27+02:00 (SpaceManager) [door:nfs_lcg-lrz-dcache:AAU1KiJ8atg nfs_lcg-lrz-dcache PoolAcceptFile 000092E0BD0896C142A490F0243F58D9C77D] Message processing failed: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL []; ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(000092E0BD0896C142A490F0243F58D9C77D) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(000092E0BD0896C142A490F0243F58D9C77D) already exists.
2016-06-13 16:59:42+02:00 (SpaceManager) [door:nfs_lcg-lrz-dcache:AAU1KiNop2g nfs_lcg-lrz-dcache PoolAcceptFile 00006C15336F65AB4450852EA921357E449D] Message processing failed: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL []; ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(00006C15336F65AB4450852EA921357E449D) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(00006C15336F65AB4450852EA921357E449D) already exists.
2016-06-13 16:59:57+02:00 (SpaceManager) [door:nfs_lcg-lrz-dcache:AAU1KiRQGWg nfs_lcg-lrz-dcache PoolAcceptFile 00006C15336F65AB4450852EA921357E449D] Message processing failed: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL []; ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(00006C15336F65AB4450852EA921357E449D) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(00006C15336F65AB4450852EA921357E449D) already exists.
2016-06-13 17:00:27+02:00 (SpaceManager) [door:nfs_lcg-lrz-dcache:AAU1KiYWM2g nfs_lcg-lrz-dcache PoolAcceptFile 00006C15336F65AB4450852EA921357E449D] Message processing failed: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL []; ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(00006C15336F65AB4450852EA921357E449D) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(00006C15336F65AB4450852EA921357E449D) already exists.
2016-06-13 17:00:27+02:00 (SpaceManager) [door:nfs_lcg-lrz-dcache:AAU1KiYWStg nfs_lcg-lrz-dcache PoolAcceptFile 00006C15336F65AB4450852EA921357E449D] Message processing failed: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL []; ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(00006C15336F65AB4450852EA921357E449D) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(00006C15336F65AB4450852EA921357E449D) already exists.
2016-06-13 17:00:42+02:00 (SpaceManager) [door:nfs_lcg-lrz-dcache:AAU1Kib+Img nfs_lcg-lrz-dcache PoolAcceptFile 0000FD617D1D233E401BBFEA25E440D6394E] Message processing failed: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL []; ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(0000FD617D1D233E401BBFEA25E440D6394E) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(0000FD617D1D233E401BBFEA25E440D6394E) already exists.
2016-06-13 17:00:57+02:00 (SpaceManager) [door:nfs_lcg-lrz-dcache:AAU1KifmEWg nfs_lcg-lrz-dcache PoolAcceptFile 0000FD617D1D233E401BBFEA25E440D6394E] Message processing failed: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL []; ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(0000FD617D1D233E401BBFEA25E440D6394E) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(0000FD617D1D233E401BBFEA25E440D6394E) already exists.
2016-06-13 17:01:27+02:00 (SpaceManager) [door:nfs_lcg-lrz-dcache:AAU1KimsK2g nfs_lcg-lrz-dcache PoolAcceptFile 0000FD617D1D233E401BBFEA25E440D6394E] Message processing failed: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL []; ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(0000FD617D1D233E401BBFEA25E440D6394E) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(0000FD617D1D233E401BBFEA25E440D6394E) already exists.
2016-06-13 17:01:27+02:00 (SpaceManager) [door:nfs_lcg-lrz-dcache:AAU1KimsQtg nfs_lcg-lrz-dcache PoolAcceptFile 0000FD617D1D233E401BBFEA25E440D6394E] Message processing failed: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL []; ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(0000FD617D1D233E401BBFEA25E440D6394E) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "srmspacefile_pnfsid_unique"
  Detail: Key (pnfsid)=(0000FD617D1D233E401BBFEA25E440D6394E) already exists.

```


You already know these:
```
2016-06-13 16:58:10+02:00 (nfs_lcg-lrz-dcache) [/0:0:0:0:0:0:0:1:699 0000080000000000D73B640130] failed to create IO adapter: NFS4ERR_LAYOUTTRYLATER : Internal failure during space management
2016-06-13 16:59:27+02:00 (nfs_lcg-lrz-dcache) [/0:0:0:0:0:0:0:1:699 0000080000000000D73B9D0130] failed to create IO adapter: NFS4ERR_LAYOUTTRYLATER : Internal failure during space management
2016-06-13 17:00:27+02:00 (nfs_lcg-lrz-dcache) [/0:0:0:0:0:0:0:1:699 0000080000000000D73BBE0130] failed to create IO adapter: NFS4ERR_LAYOUTTRYLATER : Internal failure during space management
2016-06-13 17:01:27+02:00 (nfs_lcg-lrz-dcache) [/0:0:0:0:0:0:0:1:699 0000080000000000D73BEE0130] failed to create IO adapter: NFS4ERR_LAYOUTTRYLATER : Internal failure during space management
```


That happened during doing this:
```
# for dir in /pnfs/lrz-muenchen.de/data/atlas/dq2/atlascalibdisk /pnfs/lrz-muenchen.de/data/atlas/dq2/atlasdatadisk /pnfs/lrz-muenchen.de/data/atlas/dq2/atlasgroupdisk/phys-sm /pnfs/lrz-muenchen.de/data/atlas/dq2/atlasgroupdisk/phys-susy /pnfs/lrz-muenchen.de/data/atlas/dq2/atlaslocalgroupdisk /pnfs/lrz-muenchen.de/data/atlas/dq2/atlasscratchdisk ; do cp ~/.placeholder $dir/dumps/ -n ; done
cp: error writing ‘/pnfs/lrz-muenchen.de/data/atlas/dq2/atlasdatadisk/dumps/.placeholder’: Remote I/O error
cp: failed to extend ‘/pnfs/lrz-muenchen.de/data/atlas/dq2/atlasdatadisk/dumps/.placeholder’: Remote I/O error
cp: error writing ‘/pnfs/lrz-muenchen.de/data/atlas/dq2/atlasgroupdisk/phys-susy/dumps/.placeholder’: Remote I/O error
cp: failed to extend ‘/pnfs/lrz-muenchen.de/data/atlas/dq2/atlasgroupdisk/phys-susy/dumps/.placeholder’: Remote I/O error
cp: error writing ‘/pnfs/lrz-muenchen.de/data/atlas/dq2/atlaslocalgroupdisk/dumps/.placeholder’: Remote I/O error
cp: failed to extend ‘/pnfs/lrz-muenchen.de/data/atlas/dq2/atlaslocalgroupdisk/dumps/.placeholder’: Remote I/O error
cp: error writing ‘/pnfs/lrz-muenchen.de/data/atlas/dq2/atlasscratchdisk/dumps/.placeholder’: Remote I/O error
cp: failed to extend ‘/pnfs/lrz-muenchen.de/data/atlas/dq2/atlasscratchdisk/dumps/.placeholder’: Remote I/O error
```

If you wonder, in /pnfs/lrz-muenchen.de/data/atlas/dq2/atlascalibdisk/dumps, the file was already present (it worked once before I've reported this issue).

**Comment by calestyo** [comment]
```
chimera=> SELECT * FROM t_inodes WHERE ipnfsid='0000080000000000D2C8BD0130';
 ipnfsid | itype | imode | inlink | iuid | igid | isize | iio | ictime | iatime | imtime | icrtime | igeneration | iaccess_latency | iretention_policy | inumber 
---------+-------+-------+--------+------+------+-------+-----+--------+--------+--------+---------+-------------+-----------------+-------------------+---------
(0 rows)


chimera=> SELECT * FROM t_dirs WHERE iparent=(SELECT inumber FROM t_inodes WHERE ipnfsid='0000080000000000D2C8BD0130') OR ichild=(SELECT inumber FROM t_inodes WHERE ipnfsid='0000080000000000D2C8BD0130');
 iparent | ichild | iname 
---------+--------+-------
(0 rows)

```

**Comment by calestyo** [comment]
Both your queries return always 0 rows, for the new PNFSIDs, I've mentioned just above:
0000080000000000D73B640130
0000080000000000D73B9D0130
0000080000000000D73BBE0130
0000080000000000D73BEE0130

(btw, strangely, it tries the same pnfsid there twice..)

**Comment by calestyo** [comment]
anything new here?

**Comment by paulmillar** [comment]
Not yet: Tigran is only just back from his trip to USA to talk with the other NFS implementers

**Comment by kofemann** [comment]
we had an issue in way how nfs and space manager handle retries. While NFS simply sends client retries to PoolManager, as it will squash multiple requests into a single one, space manager, acting as pool manager, keeps the state in db and fails to add yet another record for existing entry.

**Comment by gbehrmann** [comment]
Which space manager does deliberately, of course, as the previous mover had not reported completion and having two write movers running would lead to inconsistent results (both regarding file content and regarding how much space is used) - a problem I recall NFS suffered from in the past,

**Comment by kofemann** [comment]
Space manager doesn't start the mover, it only selects a pool and if it already did so can return it second time instead of "Internal failure during space management".

**Comment by gbehrmann** [comment]
The internal failure is clearly a bug.

However it doesn't know if the request goes to the same pool or a different pool. If you create two movers on two different pools, then space management would break.

**Comment by gbehrmann** [comment]
Anyway, as I said when we discussed this during the weekly a couple of weeks ago, I will look into this. Just haven't had the time yet.

**Comment by calestyo** [comment]
Do you have any rough estimate on how long this will take to fix? And especially which services this would require to be updated (just NFS door)?

Since there will be another downtime necessary due to the security hole in the non-NFS doors we obviously want to avoid having to many of them.

But right now this bug here, prevents the monthly uploading of chimera dumps for ATLAS :-(
So I wonder, whether it's worth to do a intermediate solution for this =)

**Comment by gbehrmann** [comment]
Space manager doesn't select pools. It only accounts for the space being consumed by files being uploaded.

**Comment by gbehrmann** [comment]
@calestyo, I will write a fix for this tomorrow. I only expect that space manager will need to be updated, but we will know more when the patch is finished.

**Comment by calestyo** [comment]
Nice :) you think it'll be possible to push out a 2.15.11 soon afterwards (which has this fix + the security fix)?

**Comment by paulmillar** [comment]
No, we're in an embargo period due to the security vulnerability.  The next release (2.15.11) won't happen until after that embargo ends.  That's currently slated at 2016-07-07.

**Comment by calestyo** [comment]
AFAICS these haven't made it into the 2.15.11, right?
When are they scheduled for?

**Comment by gbehrmann** [comment]
The changes are in 2.15.11.
