### ISSUE TITLE
Deleting a file with tags causes ForeignKeyViolationException

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#2648]
Dear dCache developers,

When a file has tags, I can't delete it with the NFS door (Remote I/O error). After I remove the tags with `chimera rmtag`, I can delete the file without any problem.

Here is a relevant piece of logging:

13 Jul 2016 09:44:12 (NFS-db1) [] Executing prepared SQL statement [DELETE FROM t_inodes WHERE inumber=? AND inlink = 0]
13 Jul 2016 09:44:12 (NFS-db1) [] Initiating transaction rollback on application exception
org.dcache.chimera.ForeignKeyViolationException: PreparedStatementCallback; SQL [DELETE FROM t_inodes WHERE inumber=? AND inlink = 0]; ERROR: update or delete on table "t_inodes" violates foreign key constraint "t_tags_inumber_fkey" on table "t_tags"
  Detail: Key (inumber)=(79915) is still referenced from table "t_tags".; nested exception is org.postgresql.util.PSQLException: ERROR: update or delete on table "t_inodes" violates foreign key constraint "t_tags_inumber_fkey" on table "t_tags"
  Detail: Key (inumber)=(79915) is still referenced from table "t_tags".
        at org.dcache.chimera.FsSqlDriver$1.customTranslate(FsSqlDriver.java:114) ~[chimera-2.15.9.jar:2.15.9]
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:179) ~[spring-jdbc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73) ~[spring-jdbc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:645) ~[spring-jdbc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:866) ~[spring-jdbc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:927) ~[spring-jdbc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:937) ~[spring-jdbc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.dcache.chimera.PgSQLFsSqlDriver.removeInodeIfUnlinked(PgSQLFsSqlDriver.java:106) ~[chimera-2.15.9.jar:2.15.9]
        at org.dcache.chimera.FsSqlDriver.removeFile(FsSqlDriver.java:319) ~[chimera-2.15.9.jar:2.15.9]
        at org.dcache.chimera.FsSqlDriver.remove(FsSqlDriver.java:285) ~[chimera-2.15.9.jar:2.15.9]
        at org.dcache.chimera.JdbcFs.lambda$remove$12(JdbcFs.java:498) [chimera-2.15.9.jar:2.15.9]
        at org.dcache.chimera.JdbcFs.inTransaction(JdbcFs.java:200) [chimera-2.15.9.jar:2.15.9]
        at org.dcache.chimera.JdbcFs.remove(JdbcFs.java:497) [chimera-2.15.9.jar:2.15.9]
        at org.dcache.chimera.DCacheAwareJdbcFs.remove(DCacheAwareJdbcFs.java:181) [dcache-chimera-2.15.9.jar:2.15.9]
        at org.dcache.chimera.nfsv41.door.ChimeraVfs.remove(ChimeraVfs.java:203) [dcache-nfs-2.15.9.jar:2.15.9]
        at org.dcache.nfs.vfs.VfsCache.remove(VfsCache.java:102) [nfs4j-core-0.11.2.jar:0.11.2]
        at org.dcache.nfs.vfs.PseudoFs.remove(PseudoFs.java:264) [nfs4j-core-0.11.2.jar:0.11.2]
        at org.dcache.nfs.v4.OperationREMOVE.process(OperationREMOVE.java:62) [nfs4j-core-0.11.2.jar:0.11.2]
        at org.dcache.chimera.nfsv41.door.proxy.ProxyIoMdsOpFactory$1.lambda$process$0(ProxyIoMdsOpFactory.java:53) [dcache-nfs-2.15.9.jar:2.15.9]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_91]
        at javax.security.auth.Subject.doAs(Subject.java:360) ~[na:1.8.0_91]
        at org.dcache.chimera.nfsv41.door.proxy.ProxyIoMdsOpFactory$1.process(ProxyIoMdsOpFactory.java:50) [dcache-nfs-2.15.9.jar:2.15.9]
        at org.dcache.nfs.v4.NFSServerV41.NFSPROC4_COMPOUND_4(NFSServerV41.java:152) ~[nfs4j-core-0.11.2.jar:0.11.2]
        at org.dcache.nfs.v4.xdr.nfs4_prot_NFS4_PROGRAM_ServerStub.dispatchOncRpcCall(nfs4_prot_NFS4_PROGRAM_ServerStub.java:48) ~[nfs4j-core-0.11.2.jar:0.11.2]
        at org.dcache.xdr.RpcDispatcher$1.run(RpcDispatcher.java:82) ~[oncrpc4j-core-2.4.2.jar:na]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591) ~[grizzly-framework-2.3.23.jar:2.3.23]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571) ~[grizzly-framework-2.3.23.jar:2.3.23]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "t_inodes" violates foreign key constraint "t_tags_inumber_fkey" on table "t_tags"
  Detail: Key (inumber)=(79915) is still referenced from table "t_tags".
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182) ~[postgresql-9.4.1207.jre7.jar:9.4.1207.jre7]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911) ~[postgresql-9.4.1207.jre7.jar:9.4.1207.jre7]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173) ~[postgresql-9.4.1207.jre7.jar:9.4.1207.jre7]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:622) ~[postgresql-9.4.1207.jre7.jar:9.4.1207.jre7]
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:472) ~[postgresql-9.4.1207.jre7.jar:9.4.1207.jre7]
        at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:429) ~[postgresql-9.4.1207.jre7.jar:9.4.1207.jre7]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-2.4.3.jar:na]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-2.4.3.jar:na]
        at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:873) ~[spring-jdbc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:866) ~[spring-jdbc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:629) ~[spring-jdbc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        ... 24 common frames omitted
13 Jul 2016 09:44:12 (NFS-db1) [] Initiating transaction rollback

**Comment by onnozweers** [comment]
We haven't seen this issue again. Assuming it was a single incident.
