### ISSUE TITLE
pool reports incorrect error condition when request to pnfs manager timed out

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#2929]
**Failed to instantiate mover due to unsupported checksum type: Request to [>PnfsManager@local] timed out.**

```
09 Nov 2016 06:31:42 (dcache-photon15-08) [door:DCap-dcache-door-photon02-<unknown>-AAVAxwea-mA DCap-dcache-door-photon02-<unknown>-AAVAxwea-mA PoolAcceptFile 00009F9DC4B46F3E498FB6F8BFAF3F695B84] Failed to instantiate mover due to unsupported checksum type: Request to [>PnfsManager@local] timed out.
diskCacheV111.util.TimeoutCacheException: Request to [>PnfsManager@local] timed out.
        at org.dcache.cells.CellStub$CallbackFuture.answerTimedOut(CellStub.java:685) ~[dcache-core-2.15.5.jar:2.15.5]
        at dmg.cells.nucleus.CellNucleus$2.run(CellNucleus.java:434) ~[cells-2.15.5.jar:2.15.5]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456) ~[guava-19.0.jar:na]
        at dmg.cells.nucleus.CellNucleus.executeMaintenanceTasks(CellNucleus.java:427) ~[cells-2.15.5.jar:2.15.5]
        at dmg.cells.nucleus.CellNucleus.access$200(CellNucleus.java:56) ~[cells-2.15.5.jar:2.15.5]
        at dmg.cells.nucleus.CellNucleus$7.run(CellNucleus.java:913) ~[cells-2.15.5.jar:2.15.5]
        at java.util.TimerThread.mainLoop(Timer.java:555) ~[na:1.8.0_92]
        at java.util.TimerThread.run(Timer.java:505) ~[na:1.8.0_92]
```

**Comment by paulmillar** [comment]
Which of these are failures here?
  1. That the message "due to unsupported checksum type" appears to be wrong?
  2. that we log a stack-trace?
  3. there was a timeout?

**Comment by kofemann** [comment]
Well, obviously **due to unsupported checksum type** must not be reported in case of timeouts to pnfs manager

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/10241/
