### ISSUE TITLE
Stack-trace found by Jenkins

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#3008]
See [Jenkins 3.0 build 173](https://ci.dcache.org/view/dCache%203.0/job/3.0%20post%20testing/173/)

From the console:

```
Found stack traces in /var/log/dcache/dCacheDomain.log

java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:159) ~[guava-19.0.jar:na]
	at dmg.cells.nucleus.CellNucleus.sendMessage(CellNucleus.java:519) ~[cells-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at dmg.cells.nucleus.CellAdapter.sendMessage(CellAdapter.java:468) ~[cells-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.dcache.services.info.gathers.MessageHandlerChain.sendMessage(MessageHandlerChain.java:129) ~[dcache-info-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.dcache.services.info.gathers.MessageHandlerChain.sendMessage(MessageHandlerChain.java:99) ~[dcache-info-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.dcache.services.info.gathers.SingleMessageDga.trigger(SingleMessageDga.java:83) ~[dcache-info-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.dcache.services.info.gathers.DataGatheringScheduler$RegisteredActivity.checkAndTrigger(DataGatheringScheduler.java:131) ~[dcache-info-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.dcache.services.info.gathers.DataGatheringScheduler.run(DataGatheringScheduler.java:281) ~[dcache-info-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
```

**Comment by paulmillar** [comment]
Duplicate of #3219
