### ISSUE TITLE
Jenkins found stacktrace at Zookeeper's NIOServerCnxn.doIO

### ISSUE THREAD

**Issue by jstarek** [dCache/dcache#3009]
Jenkins logs indicate a stack trace in the latest 3.0 (at 77d105280b6345df658ed98220334fec974e2e18), see [run 182](https://ci.dcache.org/view/dCache%203.0/job/3.0%20post%20testing/182/console):

```
Found stack traces in /var/log/dcache/dCacheDomain.log

	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208) [zookeeper-3.4.6.jar:3.4.6-1569965]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
```

**Comment by jstarek** [comment]
This stack trace seems to have re-occured in [run #413 of 2.16 post testing](https://ci.dcache.org/view/dCache%202.16/job/2.16%20post%20testing/lastFailedBuild/console):

Found stack traces in /var/log/dcache/dCacheDomain.log

	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208) [zookeeper-3.4.6.jar:3.4.6-1569965]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
+ return 1

**Comment by paulmillar** [comment]
Problem found (again) in [run #1798 of master post testing](https://ci.dcache.org/job/master%20post%20testing/1798/).  Full stack-trace is:
```
22 Mar 2017 13:29:05 (zookeeper) [] caught end of stream exception
org.apache.zookeeper.server.ServerCnxn$EndOfStreamException: Unable to read additional data from client sessionid 0x15af5e9b88e0001, likely client has closed socket
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208) [zookeeper-3.4.6.jar:3.4.6-1569965]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```

**Comment by jstarek** [comment]
Problem keeps re-occuring. Any insights?

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/10244/

**Comment by paulmillar** [comment]
Reported upstream as: [ZOOKEEPER-2809](https://issues.apache.org/jira/browse/ZOOKEEPER-2809)
Patch: https://rb.dcache.org/r/10252/
Committed: master@a7b3d077
