### ISSUE TITLE
pynfs-tests are failing on Jenkins 

### ISSUE THREAD

**Issue by mksahakyan** [dCache/dcache#3102]
See [dCache-master builds 5295 and 5301 ](https://ci.dcache.org/view/Test%20Suite/job/pynfs-test-suite/5301/testReport/junit/(root)/st_open/testCloseWithZeroSeqid/)

**Error Message**
OP_CLOSE should return NFS4_OK, instead got NFS4ERR_OLD_STATEID

**Stacktrace**

Traceback (most recent call last):
  File "/scratch/jenkins/pnfs-python/nfs4.1/testmod.py", line 222, in run
    self.runtest(self, environment)
  File "/scratch/jenkins/pnfs-python/nfs4.1/server41tests/st_open.py", line 172, in testCloseWithZeroSeqid
    check(res)
  File "/scratch/jenkins/pnfs-python/nfs4.1/server41tests/environment.py", line 297, in check
    raise testmod.FailureException(msg)
FailureException: OP_CLOSE should return NFS4_OK, instead got NFS4ERR_OLD_STATEID

**Comment by kofemann** [comment]
There were no updates on this issue for quite some time. Closing.
