### ISSUE TITLE
nfs door logs a stacktrace if client send bad malformed file handle

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#3131]
if file handle format does not match, nfs door will log stacktrace:

```
org.dcache.chimera.FileNotFoundHimeraFsException: path [Bad Opaque len]
does not exist
        at org.dcache.chimera.JdbcFs.inodeFromBytes(JdbcFs.java:1381)
~[chimera-2.16.28.jar:2.16.28]
        at
org.dcache.chimera.nfsv41.door.ChimeraVfs.toFsInode(ChimeraVfs.java:249)
~[dcache-nfs-2.16.28.jar:2.16.28]
        at
org.dcache.chimera.nfsv41.door.ChimeraVfs.getattr(ChimeraVfs.java:262)
~[dcache-nfs-2.16.28.jar:2.16.28]
        at org.dcache.nfs.vfs.VfsCache$1.call(VfsCache.java:230)
~[nfs4j-core-0.12.2.jar:0.12.2]
        at org.dcache.nfs.vfs.VfsCache$1.call(VfsCache.java:226)
~[nfs4j-core-0.12.2.jar:0.12.2]
        at
com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4793)
~[guava-19.0.jar:na]
        at
com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
~[guava-19.0.jar:na]
        at
com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
~[guava-19.0.jar:na]
        at
com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
~[guava-19.0.jar:na]
        at
com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
~[guava-19.0.jar:na]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
~[guava-19.0.jar:na]
        at
com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4790)
~[guava-19.0.jar:na]
        at
```

A correct behaviour must be log entry at warn level and corresponding error code to the client.

**Comment by kofemann** [comment]
fixed by  4682fd3b77e122815f6eb4a208f24f8dc99b7a5e
