### ISSUE TITLE
Frontend: IllegalState Exception on namespace operation (listing) contents of a directory using REST

### ISSUE THREAD

**Issue by anupash** [dCache/dcache#3179]
In order to reproduce this with system-test

**1. Create a file without redirect-on upload (-L)**

$ curl  -s -u user:password -T /bin/bash http://localhost:2880/private/test-`date +%s`.img

```
* Server auth using Basic with user 'user'
> PUT /private/test-1494336636.img HTTP/1.1
> Authorization: Basic <>
> User-Agent: curl/7.35.0
> Host: localhost:2880
> Accept: */*
> Content-Length: 1021112
> Expect: 100-continue
>
< HTTP/1.1 307 Temporary Redirect
< Date: Tue, 09 May 2017 13:30:36 GMT
* Server dCache/3.2.0-SNAPSHOT is not blacklisted
< Server: dCache/3.2.0-SNAPSHOT
< Location: http://[0:0:0:0:0:0:0:1]:20181/private/test-1494336636.img?dcache-http-uuid=eaf9df33-ba73-419f-8d30-215b13d946c0
< Connection: close
<
* Closing connection 0

```
**2. List files on the directory**

$ curl -u user:password -X GET 'http://localhost:3880/api/v1/namespace/private?children=true'

`{"errors":[{"message":"Internal error: java.lang.IllegalStateException: Attribute is not defined: SIZE","status":"500"}]}`

Following is the stack trace from dCache logs

```
09 May 2017 15:35:13 (Frontend-zitpcx19949) [] Thread Thread[jetty-61605,5,Frontend-zitpcx19949-threads] died
java.lang.IllegalStateException: Attribute is not defined: SIZE
	at org.dcache.vehicles.FileAttributes.guard(FileAttributes.java:181) ~[dcache-vehicles-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.dcache.vehicles.FileAttributes.getSize(FileAttributes.java:352) ~[dcache-vehicles-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.dcache.restful.resources.namespace.FileResources.chimeraToJsonAttributes(FileResources.java:374) ~[dcache-restful-api-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.dcache.restful.resources.namespace.FileResources.getFileAttributes(FileResources.java:161) ~[dcache-restful-api-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.24.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[jersey-server-2.24.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[jersey-server-2.24.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[jersey-server-2.24.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[jersey-server-2.24.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[jersey-server-2.24.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[jersey-server-2.24.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[jersey-server-2.24.jar:na]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) ~[jersey-server-2.24.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.24.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.24.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.24.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.24.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.24.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.24.jar:na]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [jersey-server-2.24.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [jersey-server-2.24.jar:na]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473) [jersey-container-servlet-core-2.24.jar:na]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) [jersey-container-servlet-core-2.24.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) [jersey-container-servlet-core-2.24.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) [jersey-container-servlet-core-2.24.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) [jersey-container-servlet-core-2.24.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) [jetty-servlet-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584) [jetty-servlet-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.dcache.http.AuthenticationHandler.access$101(AuthenticationHandler.java:58) [dcache-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.dcache.http.AuthenticationHandler.lambda$handle$0(AuthenticationHandler.java:120) [dcache-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_131]
	at javax.security.auth.Subject.doAs(Subject.java:360) ~[na:1.8.0_131]
	at org.dcache.http.AuthenticationHandler.handle(AuthenticationHandler.java:118) [dcache-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) ~[jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) ~[jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335) ~[jetty-rewrite-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.server.Server.handle(Server.java:534) ~[jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) ~[jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) ~[jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) ~[jetty-io-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) ~[jetty-io-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) ~[jetty-io-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) ~[jetty-util-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) ~[jetty-util-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) ~[jetty-util-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) ~[jetty-util-9.3.14.v20161028.jar:9.3.14.v20161028]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) ~[jetty-util-9.3.14.v20161028.jar:9.3.14.v20161028]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
```

**Comment by alrossi** [comment]
I noticed that SIZE can be undefined as well.
If you look at https://rb.dcache.org/r/10166 you will see that, in addition to pulling common functionality out into a utilities file, I have added GUARD checks for the definition of each attribute.
It would be great if we could get this patch in in some form because namespace continues to be modified and the merge will become more complicated :-)

**Comment by paulmillar** [comment]
See: https://rb.dcache.org/r/10240/
