### ISSUE TITLE
space-manager attempt to release EXPIRED space

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#3197]
Jenkins [recently found](https://ci.dcache.org/job/3.1%20post%20testing/40/) the following stack-trace in [dCacheDomain.log](https://ci.dcache.org/job/3.1%20post%20testing/40/artifact/Logs/dCacheDomain.log/*view*/) file:

```
java.lang.IllegalStateException: Change from EXPIRED to RELEASED is not allowed.
	at diskCacheV111.services.space.Space.setState(Space.java:102) ~[dcache-vehicles-3.1.5-SNAPSHOT.jar:3.1.5-SNAPSHOT]
	at diskCacheV111.services.space.SpaceManagerService.releaseSpace(SpaceManagerService.java:699) [dcache-spacemanager-3.1.5-SNAPSHOT.jar:3.1.5-SNAPSHOT]
[...]
	at diskCacheV111.services.space.SpaceManagerService.processMessageTransactionally_aroundBody0(SpaceManagerService.java:639) [dcache-spacemanager-3.1.5-SNAPSHOT.jar:3.1.5-SNAPSHOT]
	at diskCacheV111.services.space.SpaceManagerService$AjcClosure1.run(SpaceManagerService.java:1) ~[dcache-spacemanager-3.1.5-SNAPSHOT.jar:3.1.5-SNAPSHOT]
	at diskCacheV111.services.space.SpaceManagerService.processMessageTransactionally(SpaceManagerService.java:619) [dcache-spacemanager-3.1.5-SNAPSHOT.jar:3.1.5-SNAPSHOT]
	at diskCacheV111.services.space.SpaceManagerService.processMessage(SpaceManagerService.java:568) [dcache-spacemanager-3.1.5-SNAPSHOT.jar:3.1.5-SNAPSHOT]
	at diskCacheV111.services.space.SpaceManagerService.access$200(SpaceManagerService.java:128) [dcache-spacemanager-3.1.5-SNAPSHOT.jar:3.1.5-SNAPSHOT]
	at diskCacheV111.services.space.SpaceManagerService$1.process(SpaceManagerService.java:481) [dcache-spacemanager-3.1.5-SNAPSHOT.jar:3.1.5-SNAPSHOT]
	at diskCacheV111.services.space.SpaceManagerService$FibonacciBackoffMessageProcessor.run(SpaceManagerService.java:1284) [dcache-spacemanager-3.1.5-SNAPSHOT.jar:3.1.5-SNAPSHOT]
[...]
```

**Comment by paulmillar** [comment]
See patch: https://rb.dcache.org/r/10238/
