### ISSUE TITLE
IllegalStateException in cell communication 

### ISSUE THREAD

**Issue by jstarek** [dCache/dcache#3219]
During regular Jenkins testing, the following occured in a 3.0 instance:

```
Found stack traces in /var/log/dcache/dCacheDomain.log

java.lang.IllegalStateException: Cannot send message with callback in state {} [PRE_STARTUP]
	at com.google.common.base.Preconditions.checkState(Preconditions.java:199) ~[guava-19.0.jar:na]
	at dmg.cells.nucleus.CellNucleus.sendMessage(CellNucleus.java:519) ~[cells-3.0.19-SNAPSHOT.jar:3.0.19-SNAPSHOT]
	at dmg.cells.nucleus.CellAdapter.sendMessage(CellAdapter.java:468) ~[cells-3.0.19-SNAPSHOT.jar:3.0.19-SNAPSHOT]
	at org.dcache.services.info.gathers.MessageHandlerChain.sendMessage(MessageHandlerChain.java:129) ~[dcache-info-3.0.19-SNAPSHOT.jar:3.0.19-SNAPSHOT]
	at org.dcache.services.info.gathers.MessageHandlerChain.sendMessage(MessageHandlerChain.java:99) ~[dcache-info-3.0.19-SNAPSHOT.jar:3.0.19-SNAPSHOT]
	at org.dcache.services.info.gathers.SingleMessageDga.trigger(SingleMessageDga.java:83) ~[dcache-info-3.0.19-SNAPSHOT.jar:3.0.19-SNAPSHOT]
	at org.dcache.services.info.gathers.DataGatheringScheduler$RegisteredActivity.checkAndTrigger(DataGatheringScheduler.java:131) ~[dcache-info-3.0.19-SNAPSHOT.jar:3.0.19-SNAPSHOT]
	at org.dcache.services.info.gathers.DataGatheringScheduler.run(DataGatheringScheduler.java:281) ~[dcache-info-3.0.19-SNAPSHOT.jar:3.0.19-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
```

Full logs and details at https://ci.dcache.org/job/3.0%20post%20testing/334/ .

**Comment by paulmillar** [comment]
See https://rb.dcache.org/r/10234/
