### ISSUE TITLE
zookeeper accepter in NPE tight-loop

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#3248]
Jenkins [found](https://ci.dcache.org/view/dCache%20master/job/master%20post%20testing/1873/) a bug in zookeeper during startup that can result in the zookeeper service getting caught in a tight loop.

This results in a stack-trace like:

```
13 Jun 2017 15:31:39 (zookeeper) [] Ignoring unexpected runtime exception
java.lang.NullPointerException: null
	at org.apache.zookeeper.server.ZooKeeperServer.processConnectRequest(ZooKeeperServer.java:864) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.server.NIOServerCnxn.readConnectRequest(NIOServerCnxn.java:418) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.server.NIOServerCnxn.readPayload(NIOServerCnxn.java:198) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:244) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
13 Jun 2017 15:31:39 (zookeeper) [] Ignoring unexpected runtime exception
java.lang.NullPointerException: null
	at org.apache.zookeeper.server.ZooKeeperServer.createSession(ZooKeeperServer.java:569) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.server.ZooKeeperServer.processConnectRequest(ZooKeeperServer.java:902) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.server.NIOServerCnxn.readConnectRequest(NIOServerCnxn.java:418) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.server.NIOServerCnxn.readPayload(NIOServerCnxn.java:198) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:244) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
13 Jun 2017 15:31:40 (zookeeper) [] Ignoring unexpected runtime exception
java.lang.NullPointerException: null
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:185) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
13 Jun 2017 15:31:40 (zookeeper) [] Ignoring unexpected runtime exception
java.lang.NullPointerException: null
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:185) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
13 Jun 2017 15:31:40 (zookeeper) [] Ignoring unexpected runtime exception
java.lang.NullPointerException: null
```

The problem seems to be triggered by some existing zookeeper error (e.g., [ZOOKEEPER-2810](https://issues.apache.org/jira/browse/ZOOKEEPER-2810) or [ZOOKEEPER-2812](https://issues.apache.org/jira/browse/ZOOKEEPER-2812)), with the resulting exception being badly handled within NIOServerCnxnFactory.

The NPE triggered by NIOServerCnxnFactory.java:185 triggers a subsequent NPE failure, as the accepter is never cleared.  This means the error never ends.

This has been reported upstream as [ZOOKEEPER-2813](https://issues.apache.org/jira/browse/ZOOKEEPER-2813), along with one suggested (albeit non-perfect) way of addressing this issue.

There doesn't seem to be any easy work-around for this issue: it would require copying the NIOServerCnxnFactory#run method into some subclass, making some minor changes.  This would make maintaining the patch problematic.

The problem appears to be fixed with ZooKeeper 3.5, with a patch that effectively rewrites this class.

Therefore, I think our best bet is to try to avoid the errors that trigger this problem.

**Comment by kofemann** [comment]
There were no updates on this issue for quite some time. Closing.
