### ISSUE TITLE
ConcurrentModificationException in 2.16

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#3276]
Spotted with system-test on 2.16 branch, during start-up.

java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[na:1.8.0_131]
        at java.util.HashMap$ValueIterator.next(HashMap.java:1466) ~[na:1.8.0_131]
        at javax.imageio.spi.PartialOrderIterator.<init>(PartiallyOrderedSet.java:177) ~[na:1.8.0_131]
        at javax.imageio.spi.PartiallyOrderedSet.iterator(PartiallyOrderedSet.java:85) ~[na:1.8.0_131]
        at javax.imageio.spi.SubRegistry.getServiceProviders(ServiceRegistry.java:770) ~[na:1.8.0_131]
        at javax.imageio.spi.ServiceRegistry.getServiceProviders(ServiceRegistry.java:458) ~[na:1.8.0_131]
        at javax.imageio.spi.ServiceRegistry.getServiceProviders(ServiceRegistry.java:515) ~[na:1.8.0_131]
        at javax.imageio.ImageIO.getImageWritersByFormatName(ImageIO.java:891) ~[na:1.8.0_131]
        at org.rrd4j.graph.ImageWorker.saveImage(ImageWorker.java:181) ~[rrd4j-2.2.1.jar:na]
        at org.rrd4j.graph.ImageWorker.getImageBytes(ImageWorker.java:246) ~[rrd4j-2.2.1.jar:na]
        at org.rrd4j.graph.ImageWorker.saveImage(ImageWorker.java:231) ~[rrd4j-2.2.1.jar:na]
        at org.rrd4j.graph.RrdGraph.saveImage(RrdGraph.java:114) ~[rrd4j-2.2.1.jar:na]
        at org.rrd4j.graph.RrdGraph.createGraph(RrdGraph.java:89) ~[rrd4j-2.2.1.jar:na]
        at org.rrd4j.graph.RrdGraph.<init>(RrdGraph.java:46) ~[rrd4j-2.2.1.jar:na]
        at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.createPlot(RrdPoolInfoAgent.java:204) ~[classes/:na]
        at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.run(RrdPoolInfoAgent.java:176) ~[classes/:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]

**Comment by paulmillar** [comment]
This looks like a bug in the JRE library -- RRD4j is using the standard ImageIO.  While that doesn't claim to be thread-safe, it's unclear from where the list of providers is being modified.

**Comment by kofemann** [comment]
There were no updates on this issue for quite some time. Closing.
