### ISSUE TITLE
Jenkins found race-condition in zookeeper shutdown "Failed to fetch acls for 1"

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#3290]
Jenkins found a stack-trace in the "3.1 post testing" Job, in [build 97](https://ci.dcache.org/view/dCache%203.1/job/3.1%20post%20testing/97) (see [dCacheDomain.log](https://ci.dcache.org/view/dCache%203.1/job/3.1%20post%20testing/97/artifact/Logs/dCacheDomain.log/*view*/)):
```
java.lang.RuntimeException: Failed to fetch acls for 1
	at org.apache.zookeeper.server.DataTree.convertLong(DataTree.java:218) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.server.ZKDatabase.convertLong(ZKDatabase.java:358) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.server.PrepRequestProcessor.getRecordForPath(PrepRequestProcessor.java:167) [zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.server.PrepRequestProcessor.pRequest2Txn(PrepRequestProcessor.java:401) [zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.server.PrepRequestProcessor.pRequest(PrepRequestProcessor.java:538) [zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.server.PrepRequestProcessor.run(PrepRequestProcessor.java:131) [zookeeper-3.4.6.jar:3.4.6-1569965]
```
Note that this is with ZooKeeper v3.4.6.

**Comment by kofemann** [comment]
There were no updates on this issue for quite some time. Closing.
