### ISSUE TITLE
admin: login fails after OS upgrade

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3335]
Hi.

Today I've upgraded the OS (Debian jessie to stretch). dCache stayed the same, Java version as well.

Since then, when I try to log into the admin interface via ssh one gets a sudden:
```
Connection to localhost closed by remote host.
Connection to localhost closed.
```
and the admin log shows:
```
2017-07-13 20:21:32 Launching /usr/bin/java -server -Xmx1024M -XX:MaxDirectMemorySize=512m -Dsun.net.inetaddr.ttl=1800 -Dorg.globus.tcp.port.range=60000,64999 -Dorg.dcache.dcap.port=0 -Dorg.dcache.net.tcp.portrange=65000:65499 -Dorg.globus.jglobus.delegation.cache.lifetime=30000 -Dorg.globus.jglobus.crl.cache.lifetime=60000 -Djava.security.krb5.realm= -Djava.security.krb5.kdc= -Djavax.security.auth.useSubjectCredsOnly=false -Djava.security.auth.login.config=/etc/dcache/jgss.conf -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/dcache/admin-oom.hprof -XX:+UseCompressedOops -javaagent:/usr/share/dcache/classes/aspectjweaver-1.8.8.jar -Djava.awt.headless=true -DwantLog4jSetup=n -Ddcache.home=/usr/share/dcache -Ddcache.paths.defaults=/usr/share/dcache/defaults org.dcache.boot.BootLoader start admin
2017-07-13 20:21:40+02:00 (admin) [] Exception caught
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[na:1.8.0_131]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[na:1.8.0_131]
	at org.apache.sshd.server.channel.ChannelSession.handlePtyReq(ChannelSession.java:292) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.channel.ChannelSession.handleRequest(ChannelSession.java:218) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.channel.ChannelSession.handleRequest(ChannelSession.java:195) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.session.AbstractSession.channelRequest(AbstractSession.java:1057) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.session.ServerSession.running(ServerSession.java:229) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.session.ServerSession.handleMessage(ServerSession.java:205) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.session.AbstractSession.decode(AbstractSession.java:566) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.session.AbstractSession.messageReceived(AbstractSession.java:236) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.AbstractSessionIoHandler.messageReceived(AbstractSessionIoHandler.java:58) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:716) ~[mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:46) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:796) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:119) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:426) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:697) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:651) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:640) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1111) [mina-core-2.0.5.jar:na]
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) [mina-core-2.0.5.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
2017-07-13 20:24:35+02:00 (admin) [] Exception caught
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[na:1.8.0_131]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[na:1.8.0_131]
	at org.apache.sshd.server.channel.ChannelSession.handlePtyReq(ChannelSession.java:292) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.channel.ChannelSession.handleRequest(ChannelSession.java:218) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.channel.ChannelSession.handleRequest(ChannelSession.java:195) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.session.AbstractSession.channelRequest(AbstractSession.java:1057) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.session.ServerSession.running(ServerSession.java:229) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.session.ServerSession.handleMessage(ServerSession.java:205) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.session.AbstractSession.decode(AbstractSession.java:566) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.session.AbstractSession.messageReceived(AbstractSession.java:236) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.AbstractSessionIoHandler.messageReceived(AbstractSessionIoHandler.java:58) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:716) ~[mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:46) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:796) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:119) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:426) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:697) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:651) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:640) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1111) [mina-core-2.0.5.jar:na]
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) [mina-core-2.0.5.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
2017-07-13 20:24:38+02:00 (admin) [] Exception caught
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[na:1.8.0_131]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[na:1.8.0_131]
	at org.apache.sshd.server.channel.ChannelSession.handlePtyReq(ChannelSession.java:292) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.channel.ChannelSession.handleRequest(ChannelSession.java:218) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.channel.ChannelSession.handleRequest(ChannelSession.java:195) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.session.AbstractSession.channelRequest(AbstractSession.java:1057) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.session.ServerSession.running(ServerSession.java:229) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.session.ServerSession.handleMessage(ServerSession.java:205) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.session.AbstractSession.decode(AbstractSession.java:566) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.session.AbstractSession.messageReceived(AbstractSession.java:236) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.AbstractSessionIoHandler.messageReceived(AbstractSessionIoHandler.java:58) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:716) ~[mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:46) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:796) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:119) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:426) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:697) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:651) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:640) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1111) [mina-core-2.0.5.jar:na]
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) [mina-core-2.0.5.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
2017-07-13 20:25:19+02:00 (admin) [] Exception caught
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[na:1.8.0_131]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[na:1.8.0_131]
	at org.apache.sshd.server.channel.ChannelSession.handlePtyReq(ChannelSession.java:292) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.channel.ChannelSession.handleRequest(ChannelSession.java:218) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.channel.ChannelSession.handleRequest(ChannelSession.java:195) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.session.AbstractSession.channelRequest(AbstractSession.java:1057) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.session.ServerSession.running(ServerSession.java:229) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.session.ServerSession.handleMessage(ServerSession.java:205) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.session.AbstractSession.decode(AbstractSession.java:566) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.session.AbstractSession.messageReceived(AbstractSession.java:236) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.AbstractSessionIoHandler.messageReceived(AbstractSessionIoHandler.java:58) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:716) ~[mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:46) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:796) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:119) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:426) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:697) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:651) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:640) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1111) [mina-core-2.0.5.jar:na]
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) [mina-core-2.0.5.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
2017-07-13 20:25:28+02:00 (admin) [] Exception caught
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[na:1.8.0_131]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[na:1.8.0_131]
	at org.apache.sshd.server.channel.ChannelSession.handlePtyReq(ChannelSession.java:292) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.channel.ChannelSession.handleRequest(ChannelSession.java:218) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.channel.ChannelSession.handleRequest(ChannelSession.java:195) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.session.AbstractSession.channelRequest(AbstractSession.java:1057) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.session.ServerSession.running(ServerSession.java:229) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.server.session.ServerSession.handleMessage(ServerSession.java:205) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.session.AbstractSession.decode(AbstractSession.java:566) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.session.AbstractSession.messageReceived(AbstractSession.java:236) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.sshd.common.AbstractSessionIoHandler.messageReceived(AbstractSessionIoHandler.java:58) ~[sshd-core-0.8.0.jar:0.8.0]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:716) ~[mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:46) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:796) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:119) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:426) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:697) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:651) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:640) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67) [mina-core-2.0.5.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1111) [mina-core-2.0.5.jar:na]
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) [mina-core-2.0.5.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```

**Comment by calestyo** [comment]
Seems it's due to some buggy implemented org.apache.sshd not following SSH protocol correctly.

Going back to stone aged OpenSSH_6.7p1 and it works again... OpenSSH_7.4p1 and it doesn't work anymore.

See e.g. https://jira.exoplatform.org/si/jira.issueviews:issue-html/CRASH-252/CRASH-252.html

This is quite problematic, since we cannot access the admin interface anymore =) hotfix would be nice

**Comment by kofemann** [comment]
Hi Chris,

the newer versions of apache-ssh require newer versions of boncycasel. In dCache version you have,
it's impossible to update boncycasel, as jglobus has a strong dependency on older boncycasel.
You need to use older client version of upgrade to dCache >= 2.16.9

**Comment by calestyo** [comment]
Ah thanks :-)

Well I think we can also just close the issue.
2.15 is anyway no longer supported, so it's probably not even worth a release notes entry.
