### ISSUE TITLE
check-config doesn't notice legacy options as R-value

### ISSUE THREAD

**Issue by calestyo** [dCache/dcache#3388]
Hey.

I just stumbled over something when trying something on our test dCache.

It seems that `dache check-config` doesn't notice obsolete/etc. options when these are used as R-value, e.g. in 3.0 (with having the following from 2.16):
`dcache.zookeeper.connection=example.org:${dcache.zookeeper.net.port}`
in which `dcache.zookeeper.net.port` is obsolete.

`dache check-config` succeeds, but afterwards dCache is in a messed up state as the connection to ZK fails with something like:
```
java.lang.NumberFormatException: For input string: "${dcache.zookeeper.net.port}"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_131]
	at java.lang.Integer.parseInt(Integer.java:569) ~[na:1.8.0_131]
	at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_131]
```

Cheers,
Chris.

**Comment by paulmillar** [comment]
What you say is true, check-config current focus is on catching places where people were configuring dCache-provided properties that are annotated deprecated, obsolete or forbidden; using your example: 

    dcache.zookeeper.net.port = 993

There's currently no check for custom configuration properties that make use of some deprecated, obsolete or forbidden property.

**Comment by paulmillar** [comment]
Sorry, that wasn't very clear.

Yes, the properties are official, but in this case, the value come from you.

We might be able to improve the checking, but the initial idea was to catch people who configure using literal values.  In the majority of cases, this is how people write configuration.

Catching invalid references might be doable; we'll have to see.

**Comment by calestyo** [comment]
Okay... I see.
So basically you don't check any variablise *inside* and R-value.

Well I just wanted to tell you. Feel free to check these as well, or close. =)
