### ISSUE TITLE
Stack-trace from IOException in diskCacheV111.services.PoolStatisticsV0

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#3460]
For details see master post testing [build #2083](https://ci.dcache.org/job/master%20post%20testing/2083/), [console](https://ci.dcache.org/job/master%20post%20testing/2083/console)

```
java.io.IOException: Request to [>PoolManager@local] timed out.
	at diskCacheV111.services.PoolStatisticsV0.getPoolRepositoryStatistics(PoolStatisticsV0.java:1332) ~[dcache-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at diskCacheV111.services.PoolStatisticsV0.createStatisticsMap(PoolStatisticsV0.java:873) ~[dcache-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at diskCacheV111.services.PoolStatisticsV0.createHourlyRawFile(PoolStatisticsV0.java:987) ~[dcache-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at diskCacheV111.services.PoolStatisticsV0.access$300(PoolStatisticsV0.java:124) ~[dcache-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at diskCacheV111.services.PoolStatisticsV0$HourlyRunner.run(PoolStatisticsV0.java:453) ~[dcache-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$4(CellNucleus.java:754) [cells-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]
Caused by: diskCacheV111.util.TimeoutCacheException: Request to [>PoolManager@local] timed out.
	at org.dcache.cells.FutureCellMessageAnswerable.answerTimedOut(FutureCellMessageAnswerable.java:60) ~[dcache-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at dmg.cells.nucleus.CellNucleus.lambda$timeOutMessage$11(CellNucleus.java:1086) [cells-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435) ~[guava-20.0.jar:na]
	at dmg.cells.nucleus.CellNucleus.timeOutMessage(CellNucleus.java:1082) [cells-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at dmg.cells.nucleus.CellNucleus.sendMessage(CellNucleus.java:555) [cells-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at dmg.cells.nucleus.CellAdapter.sendMessage(CellAdapter.java:468) ~[cells-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.dcache.cells.CellStub.send(CellStub.java:417) ~[dcache-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.dcache.cells.CellStub.send(CellStub.java:400) ~[dcache-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.dcache.cells.CellStub.send(CellStub.java:394) ~[dcache-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.dcache.cells.CellStub.sendAndWait(CellStub.java:289) ~[dcache-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at diskCacheV111.services.PoolStatisticsV0.getPoolRepositoryStatistics(PoolStatisticsV0.java:1330) ~[dcache-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
```

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/10632/
