### ISSUE TITLE
NFSv3 stacktrace on FileNotFoundHimeraFsException

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#3465]
From http://rt.dcache.org/Ticket/Display.html?id=9248

```
16 Aug 2017 17:55:01 (NFS-storage02) [] ACCESS
org.dcache.chimera.FileNotFoundHimeraFsException: path [Bad Opaque len] does not exist
at org.dcache.chimera.JdbcFs.inodeFromBytes(JdbcFs.java:1381) ~[chimera-2.16.46.jar:2.16.46]
at org.dcache.chimera.nfsv41.door.ChimeraVfs.toFsInode(ChimeraVfs.java:249) ~[dcache-nfs-2.16.46.jar:2.16.46]
at org.dcache.chimera.nfsv41.door.ChimeraVfs.getattr(ChimeraVfs.java:262) ~[dcache-nfs-2.16.46.jar:2.16.46]
at org.dcache.nfs.vfs.VfsCache$1.call(VfsCache.java:230) ~[nfs4j-core-0.12.4.jar:0.12.4]
at org.dcache.nfs.vfs.VfsCache$1.call(VfsCache.java:226) ~[nfs4j-core-0.12.4.jar:0.12.4]
at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4793) ~[guava-19.0.jar:na]
at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542) ~[guava-19.0.jar:na]
at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323) ~[guava-19.0.jar:na]
at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286) ~[guava-19.0.jar:na]
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) ~[guava-19.0.jar:na]
at com.google.common.cache.LocalCache.get(LocalCache.java:3953) ~[guava-19.0.jar:na]
at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4790) ~[guava-19.0.jar:na]
at org.dcache.nfs.vfs.VfsCache.statFromCacheOrLoad(VfsCache.java:226) ~[nfs4j-core-0.12.4.jar:0.12.4]
at org.dcache.nfs.vfs.VfsCache.getattr(VfsCache.java:165) ~[nfs4j-core-0.12.4.jar:0.12.4]
at org.dcache.nfs.vfs.PseudoFs.getattr(PseudoFs.java:295) ~[nfs4j-core-0.12.4.jar:0.12.4]
at org.dcache.nfs.v3.NfsServerV3.NFSPROC3_ACCESS_3(NfsServerV3.java:218) ~[nfs4j-core-0.12.4.jar:0.12.4]
at org.dcache.nfs.v3.xdr.nfs3_protServerStub.dispatchOncRpcCall(nfs3_protServerStub.java:69) [nfs4j-core-0.12.4.jar:0.12.4]
at org.dcache.xdr.RpcDispatcher$1.run(RpcDispatcher.java:109) [oncrpc4j-core-2.6.0.jar:na]
at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591) [grizzly-framework-2.3.24.jar:2.3.24]
at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571) [grizzly-framework-2.3.24.jar:2.3.24]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```

Problem seems to be that ChimeraVfs#list not handling FileNotFoundHimeraFsException correctly by allowing it to propagate, rather than throwing a corresponding NoEntException (see ChimeraVfs#lookup).

**Comment by kofemann** [comment]
The source of the problem that the client accesses nfs server with an old file handle. The proper solution is to return BADHANDLE error, which is implemented with commit 4682fd3b77e122815f6eb4a208f24f8dc99b7a5e. As the client have to re-mount any way, fixing the older versions makes no sense.

**Comment by paulmillar** [comment]
Just to mention a counter-point, there's still a few (ten or so) instances that are yet to upgrade.  Theoretically, they could upgrade to 2.16 and see a similar problem.

**Comment by kofemann** [comment]
That's right. But fix will remove only stack trace from the log file. They have to re-mount anyway.
