### ISSUE TITLE
stack trace from IOException (org.rrd4j.graph.RrdGraphConstants)

### ISSUE THREAD

**Issue by mksahakyan** [dCache/dcache#3490]
java.lang.ExceptionInInitializerError: null
	at org.rrd4j.graph.RrdGraphDef.<init>(RrdGraphDef.java:74) ~[rrd4j-2.2.1.jar:na]
	at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.getGraphDef(RrdPoolInfoAgent.java:267) ~[na:na]
	at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.createPlot(RrdPoolInfoAgent.java:204) ~[na:na]
	at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.run(RrdPoolInfoAgent.java:176) ~[na:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]
Caused by: java.lang.RuntimeException: java.io.IOException: Problem reading font data.
	at org.rrd4j.graph.RrdGraphConstants$FontConstructor.getFont(RrdGraphConstants.java:274) ~[rrd4j-2.2.1.jar:na]
	at org.rrd4j.graph.RrdGraphConstants.<clinit>(RrdGraphConstants.java:291) ~[rrd4j-2.2.1.jar:na]
Caused by: java.io.IOException: Problem reading font data.
	at java.awt.Font.createFont0(Font.java:1000) ~[na:1.8.0_141]
	at java.awt.Font.createFont(Font.java:877) ~[na:1.8.0_141]
	at org.rrd4j.graph.RrdGraphConstants$FontConstructor.getFont(RrdGraphConstants.java:270) ~[rrd4j-2.2.1.jar:na]
java.lang.NoClassDefFoundError: Could not initialize class org.rrd4j.graph.RrdGraphConstants
	at org.rrd4j.graph.RrdGraphDef.<init>(RrdGraphDef.java:74) ~[rrd4j-2.2.1.jar:na]
	at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.getGraphDef(RrdPoolInfoAgent.java:267) ~[na:na]
	at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.createPlot(RrdPoolInfoAgent.java:204) ~[na:na]
	at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.run(RrdPoolInfoAgent.java:176) ~[na:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]
java.lang.NoClassDefFoundError: Could not initialize class org.rrd4j.graph.RrdGraphConstants
	at org.rrd4j.graph.RrdGraphDef.<init>(RrdGraphDef.java:74) ~[rrd4j-2.2.1.jar:na]
	at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.getGraphDef(RrdPoolInfoAgent.java:267) ~[na:na]
	at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.createPlot(RrdPoolInfoAgent.java:204) ~[na:na]
	at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.run(RrdPoolInfoAgent.java:176) ~[na:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]
java.lang.NoClassDefFoundError: Could not initialize class org.rrd4j.graph.RrdGraphConstants
	at org.rrd4j.graph.RrdGraphDef.<init>(RrdGraphDef.java:74) ~[rrd4j-2.2.1.jar:na]
	at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.getGraphDef(RrdPoolInfoAgent.java:267) ~[na:na]
	at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.createPlot(RrdPoolInfoAgent.java:204) ~[na:na]
	at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.run(RrdPoolInfoAgent.java:176) ~[na:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]
java.lang.NoClassDefFoundError: Could not initialize class org.rrd4j.graph.RrdGraphConstants
	at org.rrd4j.graph.RrdGraphDef.<init>(RrdGraphDef.java:74) ~[rrd4j-2.2.1.jar:na]
	at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.getGraphDef(RrdPoolInfoAgent.java:267) ~[na:na]
	at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.createPlot(RrdPoolInfoAgent.java:204) ~[na:na]
	at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.run(RrdPoolInfoAgent.java:176) ~[na:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]
java.lang.ExceptionInInitializerError: null
	at org.rrd4j.graph.RrdGraphDef.<init>(RrdGraphDef.java:74) ~[rrd4j-2.2.1.jar:na]
	at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.getGraphDef(RrdPoolInfoAgent.java:267) ~[na:na]
	at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.createPlot(RrdPoolInfoAgent.java:204) ~[na:na]
	at org.dcache.webadmin.model.dataaccess.util.rrd4j.RrdPoolInfoAgent.run(RrdPoolInfoAgent.java:176) ~[na:na]

**Comment by alrossi** [comment]
This is the same as #3488
