### ISSUE TITLE
Stack-trace probably due to problems in RESTful's Restore collector

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#3526]
For details, see Jenkins "master post testing" job [build 2126](https://ci.dcache.org/job/master%20post%20testing/2126/)'s [console output](https://ci.dcache.org/job/master%20post%20testing/2126/console), or the complete [dCacheDomain.log](https://ci.dcache.org/job/master%20post%20testing/2126/artifact/Logs/dCacheDomain.log/*view*/) file.

```
	at org.dcache.cells.FutureCellMessageAnswerable.answerTimedOut(FutureCellMessageAnswerable.java:60) ~[dcache-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at dmg.cells.nucleus.CellNucleus.lambda$timeOutMessage$11(CellNucleus.java:1086) ~[cells-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435) ~[guava-20.0.jar:na]
	at dmg.cells.nucleus.CellNucleus.timeOutMessage(CellNucleus.java:1082) ~[cells-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at dmg.cells.nucleus.CellNucleus.sendMessage(CellNucleus.java:555) ~[cells-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at dmg.cells.nucleus.CellAdapter.sendMessage(CellAdapter.java:468) ~[cells-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at org.dcache.cells.CellStub.send(CellStub.java:417) ~[dcache-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at org.dcache.cells.CellStub.send(CellStub.java:400) ~[dcache-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at org.dcache.restful.util.restores.RestoreCollector.collectData(RestoreCollector.java:98) ~[dcache-restful-api-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at org.dcache.restful.util.restores.RestoreCollector.collectData(RestoreCollector.java:78) ~[dcache-restful-api-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at org.dcache.services.collector.CellDataCollectingService.run(CellDataCollectingService.java:222) [dcache-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_141]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_141]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_141]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
```

**Comment by alrossi** [comment]
This is simply that a timeout exception is being treated as a bug?

**Comment by paulmillar** [comment]
Yes, it looks like it. I guess it should be simple enough to fix.

**Comment by alrossi** [comment]
Probably in the base class.  I'll have a look now

**Comment by paulmillar** [comment]
Thanks!

**Comment by alrossi** [comment]
There were a couple of places that needed fixing, I think.

https://rb.dcache.org/r/10467/

**Comment by alrossi** [comment]
https://rb.dcache.org/r/10467/ committed.
