### ISSUE TITLE
AccessLogAwareOperationFactory produces stacktrace on OPEN

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#3530]
8:33:23 AM [OncRpcSvc Worker(28)] [] Unhandled exception:java.lang.NullPointerException: null
    at org.dcache.chimera.nfsv41.door.AccessLogAwareOperationFactory$OpOpen.process(AccessLogAwareOperationFactory.java:243) ~[dcache-nfs-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
    at org.dcache.chimera.nfsv41.door.proxy.ProxyIoMdsOpFactory$1.lambda$process$0(ProxyIoMdsOpFactory.java:53) ~[dcache-nfs-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_111]
    at javax.security.auth.Subject.doAs(Subject.java:360) ~[na:1.8.0_111]
    at org.dcache.chimera.nfsv41.door.proxy.ProxyIoMdsOpFactory$1.process(ProxyIoMdsOpFactory.java:47) ~[dcache-nfs-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
    at org.dcache.nfs.v4.NFSServerV41.NFSPROC4_COMPOUND_4(NFSServerV41.java:173) ~[nfs4j-core-0.15.3.jar:0.15.3]
    at org.dcache.nfs.v4.xdr.nfs4_prot_NFS4_PROGRAM_ServerStub.dispatchOncRpcCall(nfs4_prot_NFS4_PROGRAM_ServerStub.java:48) [nfs4j-core-0.15.3.jar:0.15.3]
    at org.dcache.xdr.RpcDispatcher$1.run(RpcDispatcher.java:110) [oncrpc4j-core-2.7.0.jar:na]
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591) [grizzly-framework-2.3.24.jar:2.3.24]
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571) [grizzly-framework-2.3.24.jar:2.3.24]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

**Comment by paulmillar** [comment]
Is this problem still present after commit 36f471d6 ?
