### ISSUE TITLE
psu(x) match command fails with FNAL storage unit syntax

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#3547]
I discovered that neither the old page nor the webadmin page for Pool Selection Setup works when issuing a simulated match request.   

Adding a print stack trace, I discovered:

Caused by: dmg.util.CommandThrowableException: (3) java.lang.IllegalArgumentException: Invalid format: expected<x:y@z> got <enstore> from ac_psux_match_$_5
       at dmg.util.command.AcCommandExecutor.execute(AcCommandExecutor.java:177)
       at dmg.cells.nucleus.CellAdapter.executeCommand(CellAdapter.java:238)
       at org.dcache.cells.UniversalSpringCell.executeCommand(UniversalSpringCell.java:195)
       at dmg.cells.nucleus.CellAdapter$1.doExecute(CellAdapter.java:104)
       at org.dcache.util.cli.CommandInterpreter.command(CommandInterpreter.java:129)
       at dmg.cells.nucleus.CellAdapter$1.command(CellAdapter.java:121)
       at dmg.cells.nucleus.CellAdapter.command(CellAdapter.java:223)
       at dmg.cells.nucleus.CellAdapter.executeLocalCommand(CellAdapter.java:924)
       at dmg.cells.nucleus.CellAdapter.messageArrived(CellAdapter.java:855)
       at dmg.cells.nucleus.CellNucleus$DeliverMessageTask.run(CellNucleus.java:1218)
       at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:251)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$7(CellNucleus.java:754)
       at dmg.cells.nucleus.CellNucleus$$Lambda$27/461591680.run(Unknown Source)
       ... 1 more
Caused by: java.lang.IllegalArgumentException: Invalid format: expected<x:y@z> got <enstore>
       at diskCacheV111.vehicles.GenericStorageInfo.valueOf(GenericStorageInfo.java:397)
       at diskCacheV111.poolManager.PoolSelectionUnitV2.matchLinkGroupsXml(PoolSelectionUnitV2.java:1588)
       at diskCacheV111.poolManager.PoolSelectionUnitV2.ac_psux_match_$_5(PoolSelectionUnitV2.java:3018)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:483)
       at dmg.util.command.AcCommandExecutor.execute(AcCommandExecutor.java:150)

[14:58] 

The translation of the args to FileAttributes is wrong, I think.   This is because we use '.', not ':'.  

This code:

public PoolPreferenceLevel[] matchLinkGroupsXml(String linkGroup,
                   String direction,
                   String storeUnit,
                   String dCacheUnit,
                   String netUnit,
                   String protocolUnit) {
       StorageInfo info = GenericStorageInfo.valueOf(storeUnit, dCacheUnit);
       return match(DirectionType.valueOf(direction.toUpperCase()),
                    netUnit.equals("*") ? null : netUnit,
                    protocolUnit.equals("*") ? null : protocolUnit,
                    FileAttributes.ofStorageInfo(info), linkGroup);
   }

and possibly other places where GenericStorageInfo is used to service the psu commands needs to be changed to use the Storage Info extraction API.

I will work on a patch for this tomorrow.   This looks like it is broken all the way back to 2.13.

Seems no one has been using this feature here :-)

**Comment by alrossi** [comment]
This also manifests itself as STORAGECLASS not defined.

See patch https://rb.dcache.org/r/10511/
