### ISSUE TITLE
NPE in stage with 

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#3578]
10 Oct 2017 12:34:32 (PoolManager) [door:NFS-ani@dCacheDomain:AAVbLtpOCiA NFS-ani PoolMgrSelectReadPool 000031AAD152AB9C4259AFFA2C34D4072319] Unexpected Exception in state loop for 000031AAD152AB9C4259AFFA2C34D4072319
java.lang.NullPointerException: null
	at diskCacheV111.poolManager.RequestContainerV5$PoolRequestHandler.stateEngine(RequestContainerV5.java:1426) [dcache-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at diskCacheV111.poolManager.RequestContainerV5$PoolRequestHandler.stateLoop(RequestContainerV5.java:1178) [dcache-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at diskCacheV111.poolManager.RequestContainerV5$PoolRequestHandler.access$1700(RequestContainerV5.java:737) [dcache-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at diskCacheV111.poolManager.RequestContainerV5$PoolRequestHandler$RunEngine.run(RequestContainerV5.java:1109) [dcache-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:31) [dcache-common-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:149) [dcache-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]

**Comment by paulmillar** [comment]
Do you remember how you triggered this problem?
