### ISSUE TITLE
unexpected error when writing into space token

### ISSUE THREAD

**Issue by thdesy** [dCache/dcache#3655]
when trying to write via SRMv2 into a specific space token ID, we receive an undefined error 451 without defined message but stack.

```
> srmcp -srm_protocol_version=2 -space_token=8 file:///tmp/foo.file srm://dcache-dot6.desy.de:8443/pnfs/desy.de/dot/user/foo_20171108_in-space-token-8
2017-11-08 11:44:56,901 [Thread-5] ERROR org.dcache.srm.util.GridftpClient - org.dcache.ftp.client.exception.ServerException: Server refused performing the request. Custom message: No write links configured for [net=131.169.71.165,protocol=GFtp/2,store=dot:user@osm,cache=,linkgroup=] (error code 1) [Nested exception message:  Custom message: Unexpected reply: 451 No write links configured for [net=131.169.71.165,protocol=GFtp/2,store=dot:user@osm,cache=,linkgroup=]] [Nested exception is org.dcache.ftp.client.exception.UnexpectedReplyCodeException:  Custom message: Unexpected reply: 451 No write links configured for [net=131.169.71.165,protocol=GFtp/2,store=dot:user@osm,cache=,linkgroup=]]
2017-11-08 11:44:56,908 [Thread-2] ERROR org.dcache.srm.util.GridftpClient -  transfer exception
org.dcache.ftp.client.exception.ServerException: Server refused performing the request. Custom message: No write links configured for [net=131.169.71.165,protocol=GFtp/2,store=dot:user@osm,cache=,linkgroup=] (error code 1) [Nested exception message:  Custom message: Unexpected reply: 451 No write links configured for [net=131.169.71.165,protocol=GFtp/2,store=dot:user@osm,cache=,linkgroup=]]
	at org.dcache.ftp.client.exception.ServerException.embedUnexpectedReplyCodeException(ServerException.java:111) ~[ftp-client-3.0.9.jar:3.0.9]
	at org.dcache.ftp.client.FTPClient.get127Reply(FTPClient.java:1757) ~[ftp-client-3.0.9.jar:3.0.9]
	at org.dcache.ftp.client.FTPClient.put2(FTPClient.java:1997) ~[ftp-client-3.0.9.jar:3.0.9]
	at org.dcache.srm.util.GridftpClient$TransferThread.run(GridftpClient.java:932) ~[srm-common-3.0.9.jar:3.0.9]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
copy failed with the error
org.dcache.ftp.client.exception.ServerException: Server refused performing the request. Custom message: No write links configured for [net=131.169.71.165,protocol=GFtp/2,store=dot:user@osm,cache=,linkgroup=] (error code 1) [Nested exception message:  Custom message: Unexpected reply: 451 No write links configured for [net=131.169.71.165,protocol=GFtp/2,store=dot:user@osm,cache=,linkgroup=]] [Nested exception is org.dcache.ftp.client.exception.UnexpectedReplyCodeException:  Custom message: Unexpected reply: 451 No write links configured for [net=131.169.71.165,protocol=GFtp/2,store=dot:user@osm,cache=,linkgroup=]]
 try again
sleeping for 10000 before retrying

```

**Comment by calestyo** [comment]
Seems your pool manager config doesn't allow writing:
> Custom message: No write links configured for…

**Comment by thdesy** [comment]
yes, but I was referring mainly to the unexpected error reply. I suppose the error message should have been parsed and not just dumped as stack trace.

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/10626/
