### ISSUE TITLE
NPE on pool startup

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#3752]
If you type 'info' command just after pool started, then NPE is logged:

3:45:36 PM [dcache-lab002-A-1] [admin] Command failed due to a bug, please contact support@dcache.org.dmg.util.CommandPanicException: (1) Command failed: java.lang.NullPointerException
	at org.dcache.util.cli.AnnotatedCommandExecutor.execute(AnnotatedCommandExecutor.java:156) ~[common-cli-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at dmg.cells.nucleus.CellAdapter.executeCommand(CellAdapter.java:238) ~[cells-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at org.dcache.cells.UniversalSpringCell.executeCommand(UniversalSpringCell.java:195) ~[dcache-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at dmg.cells.nucleus.CellAdapter$1.doExecute(CellAdapter.java:104) ~[cells-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at org.dcache.util.cli.CommandInterpreter.command(CommandInterpreter.java:129) ~[common-cli-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at dmg.cells.nucleus.CellAdapter$1.command(CellAdapter.java:121) ~[cells-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at dmg.cells.nucleus.CellAdapter.command(CellAdapter.java:223) ~[cells-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at dmg.cells.nucleus.CellAdapter.executeLocalCommand(CellAdapter.java:915) ~[cells-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at dmg.cells.nucleus.CellAdapter.messageArrived(CellAdapter.java:855) ~[cells-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at dmg.cells.nucleus.CellNucleus$DeliverMessageTask.run(CellNucleus.java:1218) [cells-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:251) [dcache-common-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$4(CellNucleus.java:754) [cells-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
Caused by: java.lang.NullPointerException: null
	at org.dcache.pool.classic.HsmFlushController.getDataObject(HsmFlushController.java:212) ~[dcache-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at org.dcache.pool.classic.HsmFlushController.getInfo(HsmFlushController.java:201) ~[dcache-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at org.dcache.cells.UniversalSpringCell.getInfo(UniversalSpringCell.java:454) ~[dcache-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at dmg.cells.nucleus.CellAdapter.getInfo(CellAdapter.java:824) ~[cells-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at dmg.cells.nucleus.CellAdapter$InfoCommand.call(CellAdapter.java:669) ~[cells-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at dmg.cells.nucleus.CellAdapter$InfoCommand.call(CellAdapter.java:624) ~[cells-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at org.dcache.util.cli.AnnotatedCommandExecutor.execute(AnnotatedCommandExecutor.java:145) ~[common-cli-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	... 14 common frames omitted

**Comment by alrossi** [comment]
Looks like this regression is mine.  I'll investigate.

**Comment by alrossi** [comment]
https://rb.dcache.org/r/10664/

refactoring accidentally left out condition null check
