### ISSUE TITLE
possible addWithInfinity bug?

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#3791]
12:48:35 PM [pool-6-thread-1] [] Uncaught exception in thread pool-6-thread-1java.lang.IllegalArgumentException: timeout value is negative
	at java.lang.Object.wait(Native Method) ~[na:1.8.0_91]
	at org.dcache.poolmanager.RemotePoolMonitor.getPoolMonitor(RemotePoolMonitor.java:178) ~[dcache-core-4.1.0-SNAPSHOT.jar:4.1.0-SNAPSHOT]
	at org.dcache.poolmanager.RemotePoolMonitor.getPoolSelectionUnit(RemotePoolMonitor.java:116) ~[dcache-core-4.1.0-SNAPSHOT.jar:4.1.0-SNAPSHOT]
	at org.dcache.services.history.pools.PoolTimeseriesServiceImpl.listPools(PoolTimeseriesServiceImpl.java:168) ~[dcache-history-4.1.0-SNAPSHOT.jar:4.1.0-SNAPSHOT]
	at org.dcache.util.collector.pools.PoolInfoCollector.collectData(PoolInfoCollector.java:101) ~[dcache-core-4.1.0-SNAPSHOT.jar:4.1.0-SNAPSHOT]
	at org.dcache.util.collector.pools.PoolInfoCollector.collectData(PoolInfoCollector.java:82) ~[dcache-core-4.1.0-SNAPSHOT.jar:4.1.0-SNAPSHOT]
	at org.dcache.services.collector.CellDataCollectingService.run(CellDataCollectingService.java:221) ~[dcache-core-4.1.0-SNAPSHOT.jar:4.1.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_91]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

**Comment by paulmillar** [comment]
That could be, but there's also a race-condition between the wait and while clause that could (occasionally) cause this problem.

How often does this happen?  Can you reproduce it?  Can you watch the value of deadline and the returned value from subWithInfinity when the problem happens?

**Comment by alrossi** [comment]
This is the first time I've seen it.   It stopped the history service (as uncaught exception) from updating.

**Comment by paulmillar** [comment]
OK, in that case, I think it's likely the race-condition.

The crux of the issue is that System.currentTimeMillis is evaluated twice.

When evaluated in the while clause, the code will wait if the deadline == System.currentTimeMillis.  The subsequent `subWithInfinity` call uses a potentially different System.currentTimeMillis value.

If the current time is equal to the deadline and, indeed, is "right before" rolling over to the next millisecond then the two System.currentTimeMilli() calls could yield different values and wait will get a negative value (-1).  This is more likely if there's a context switch at just the right moment (or the system clock is adjusted by ntpd, or ...)

Note that changing the `<=` in the while clause to `<` does not solve this problem, it just makes it less likely.

The correct solution is to have a single System.currentTimeMilli() call (i.e., a single concept of "now") and have the looping and wait behaviour based on that single "now".

**Comment by alrossi** [comment]
Ah, a familiar problem.  Surprised it was coded this way (I did not look at this as closely as you did).  Do you want to fix it, or shall I?

**Comment by paulmillar** [comment]
I'm perfectly happy for you to have the honour (or honor) 😃

**Comment by alrossi** [comment]
OK, I'll take care of it later.

**Comment by alrossi** [comment]
Fixed
