### ISSUE TITLE
Resilience manager deis when a pool is removed from the pool manager configuration

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#4024]
With exception:

```
12 Jun 2018 09:33:36 (Resilience) [] Uncaught exception in thread FileOperationMap
java.util.NoSuchElementException: dcache-cms166-01
        at org.dcache.util.NonReindexableList.indexOf(NonReindexableList.java:192) ~[dcache-core-3.1.16.jar:3.1.16]
        at org.dcache.resilience.data.PoolInfoMap.getPoolIndex(PoolInfoMap.java:424) ~[dcache-resilience-3.1.16.jar:3.1.16]
        at org.dcache.resilience.data.FileFilter.matchesPool(FileFilter.java:94) ~[dcache-resilience-3.1.16.jar:3.1.16]
        at org.dcache.resilience.data.FileFilter.matches(FileFilter.java:163) ~[dcache-resilience-3.1.16.jar:3.1.16]
        at org.dcache.resilience.data.FileOperationMap$TerminalOperationProcessor.cancel(FileOperationMap.java:270) ~[dcache-resilience-3.1.16.jar:3.1.16]
        at org.dcache.resilience.data.FileOperationMap$TerminalOperationProcessor.gatherCanceled(FileOperationMap.java:298) ~[dcache-resilience-3.1.16.jar:3.1.16]
        at org.dcache.resilience.data.FileOperationMap$TerminalOperationProcessor.processTerminated(FileOperationMap.java:229) ~[dcache-resilience-3.1.16.jar:3.1.16]
        at org.dcache.resilience.data.FileOperationMap.scan(FileOperationMap.java:871) ~[dcache-resilience-3.1.16.jar:3.1.16]
        at org.dcache.resilience.data.FileOperationMap.run(FileOperationMap.java:819) ~[dcache-resilience-3.1.16.jar:3.1.16]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_144]
```

**Comment by alrossi** [comment]
I am not sure this is really a bug.  I need to know what precisely was done to cause this.

For instance, was the pool removed from the map while file operations involving the pool were in progress? (sort of looks like it).  That should probably not be done.

On the other hand, if the pool was removed, but the location is still in the namespace, is this a normal situation?   If it is, then the logic in Resilience needs to be adjusted accordingly.   That is, during a scan, if the location is no longer in the psu/pool info map, we need to act as if it doesn't exist.  This would entail decreasing the actual replica count for that file and reprocessing.

**Comment by kofemann** [comment]
According to our admins, replica manager stuck every time when a pool is
decomissioned with 'psu remove pool'.

**Comment by alrossi** [comment]
Well, if one of the two conditions above pertains, it does not surprise me.  But did they drain the pool first or just remove it?  In the latter case, I imagine there are all these orphaned locations in Chimera.  If resilience bumps into them, it will not find them in its internal map.  If this is what is happening, the fix should be clear:  don't throw the exception, handle it.
