### ISSUE TITLE
unclean shutdown of history if interrupted during start-up

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#4083]
The following stack-trace was logged on prometheus

```
28 Jul 2018 08:01:26 (history) [] Uncaught exception in thread pool-5-thread-1
org.springframework.remoting.RemoteProxyFailureException: Failed to fetch pool monitor: null; nested exception is java.lang.InterruptedException
        at org.dcache.poolmanager.RemotePoolMonitor.getPoolMonitor(RemotePoolMonitor.java:210) ~[dcache-core-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at org.dcache.poolmanager.RemotePoolMonitor.getPoolSelectionUnit(RemotePoolMonitor.java:119) ~[dcache-core-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at org.dcache.services.history.pools.PoolTimeseriesServiceImpl.listPools(PoolTimeseriesServiceImpl.java:168) ~[dcache-history-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at org.dcache.util.collector.pools.PoolInfoCollector.collectData(PoolInfoCollector.java:101) ~[dcache-core-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at org.dcache.util.collector.pools.PoolInfoCollector.collectData(PoolInfoCollector.java:82) ~[dcache-core-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at org.dcache.services.collector.CellDataCollectingService.run(CellDataCollectingService.java:221) ~[dcache-core-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_181]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_181]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: java.lang.InterruptedException: null
        at java.lang.Object.wait(Native Method) ~[na:1.8.0_181]
        at org.dcache.poolmanager.RemotePoolMonitor.getPoolMonitor(RemotePoolMonitor.java:198) ~[dcache-core-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        ... 12 common frames omitted
28 Jul 2018 08:01:26 (history) [] Uncaught runtime exception in update; this is most likely a bug.  No further collection has been scheduled.
```

The trigger was a bug in poolmanager startup; however, history should shutdown cleanly (without a stack-trace) even under these circumstances.

**Comment by alrossi** [comment]
Actually, this looks like a problem in the handling of exceptions in the RemotePoolMonitor.  It should not treat an InterruptedException as a Runtime failure.

**Comment by alrossi** [comment]
Inspecting all of dCache, I see the following:

1.   The local InterruptedException in the RemotePoolMonitor is propagated using 

``
org.springframework.remoting.RemoteProxyFailureException
``
This is a subclass of RuntimeException, and should be handled explicitly (checking for the nested InterruptedException).

2.  calls to the RemotePoolMonitor occur in the following instances; noted is whether they properly handle this case:

`diskCacheV111.services.space.LinkGroupLoader`
- explicitly throws and catches RemoteAccessException

`diskCacheV111.services.space.SpaceManagerService`
- findLinkGroupForWrite(), isWriteableInLinkgroup() do not handle

`org.dcache.pinmanager.PinManager`
- run() on UnpinProcessor task does not handle differently from RuntimeException (trace)

`org.dcache.pinmanager.PinRequestProcessor`
- selectReadPool() does not handle

`org.dcache.pinmanager.MovePinRequestProcessor`
- setSticky() does not handle

`org.dcache.restful.services.pool.PoolInfoServiceImpl`
- getSelectionUnit() does not handle

`org.dcache.services.history.pools.PoolTimeseriesServiceImpl`
- getSelectionUnit(), listGroups(), listPools(), validKeys() do not handle

`diskCacheV111.srm.dcache.Storage`
- getFileMetaData(), lookupLocality() do not handle

`org.dcache.webdav.DcacheResourceFactory`
- list(), calculateLocality() do not handle

`org.dcache.xrootd.door.XrootdDoor`
- getFileStatus() does not handle

**Comment by alrossi** [comment]
Proposed solution:

https://rb.dcache.org/r/11072/
