### ISSUE TITLE
xrootd TPC gives stack-trace

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#4259]
On prometheus, I'm seeing the following stack-traces:

```
CacheException(rc=10001;msg=No such file or directory: /VOs/dteam/tpc-test/https/test/e5/6c/file8_3478777a-ce05-4fa1-afc5-92ff31ba3cf3)
        at org.dcache.util.CacheExceptionFactory.exceptionOf(CacheExceptionFactory.java:50)
        at org.dcache.util.CacheExceptionFactory.exceptionOf(CacheExceptionFactory.java:42)
        at org.dcache.util.CacheExceptionFactory.exceptionOf(CacheExceptionFactory.java:107)
        at org.dcache.cells.CellStub.getMessage(CellStub.java:548)
        at diskCacheV111.util.PnfsHandler.request(PnfsHandler.java:250)
        at diskCacheV111.util.PnfsHandler.createPnfsEntry(PnfsHandler.java:365)
        at org.dcache.util.Transfer.createNameSpaceEntry(Transfer.java:740)
        at org.dcache.xrootd.door.XrootdDoor.write(XrootdDoor.java:590)
        at org.dcache.xrootd.door.XrootdRedirectHandler.doOnOpen(XrootdRedirectHandler.java:266)
        at org.dcache.xrootd.door.XrootdRedirectHandler.doOnOpen(XrootdRedirectHandler.java:92)
        at org.dcache.xrootd.core.XrootdRequestHandler.requestReceived(XrootdRequestHandler.java:145)
        at org.dcache.xrootd.door.ConcurrentXrootdRequestHandler.lambda$requestReceived$2(ConcurrentXrootdRequestHandler.java:83)
        at org.dcache.util.CDCListeningExecutorServiceDecorator.lambda$wrap$0(CDCListeningExecutorServiceDecorator.java:130)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:251)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

First report was on 2018-10-07; however, log files appear to be missing from 2018-06-03 until 2018-10-07, so the problem may have been introduced before this.

**Comment by paulmillar** [comment]
The underlying problem here comes from #4178.

However, this is a legitimate failure mode if the client does not specify the `kXR_mkpath` option in the `kXR_open` request.  Therefore, logging a stack-trace here is wrong.

From the code, this stack-trace was recently introduced, and likely to aide debugging.
