### ISSUE TITLE
Cancelled HTTP-TPC causes stack-trace

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#4311]
Observed following stack-trace:

```
19 Oct 2018 15:21:32 (SpaceManager) [door:webdav-secure-grid@dCacheDomain:AAV4k/V67Wg pool2 DoorTransferFinished 0000FAF0DCD89D1E43489CDE9F8A5FA400AC] Message processing failed: Attribute is not defined: SIZE
java.lang.IllegalStateException: Attribute is not defined: SIZE
        at org.dcache.vehicles.FileAttributes.guard(FileAttributes.java:180) ~[dcache-vehicles-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at org.dcache.vehicles.FileAttributes.getSize(FileAttributes.java:351) ~[dcache-vehicles-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at diskCacheV111.services.space.SpaceManagerService.transferFinished(SpaceManagerService.java:809) [dcache-spacemanager-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at diskCacheV111.services.space.SpaceManagerService.processMessageTransactionally_aroundBody0(SpaceManagerService.java:658) [dcache-spacemanager-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at diskCacheV111.services.space.SpaceManagerService$AjcClosure1.run(SpaceManagerService.java:1) ~[dcache-spacemanager-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:66) ~[spring-aspects-5.1.0.RELEASE.jar:5.1.0.RELEASE]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:72) ~[spring-aspects-5.1.0.RELEASE.jar:5.1.0.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.1.0.RELEASE.jar:5.1.0.RELEASE]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:70) ~[spring-aspects-5.1.0.RELEASE.jar:5.1.0.RELEASE]
        at diskCacheV111.services.space.SpaceManagerService.processMessageTransactionally(SpaceManagerService.java:648) [dcache-spacemanager-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at diskCacheV111.services.space.SpaceManagerService.processMessage(SpaceManagerService.java:597) [dcache-spacemanager-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at diskCacheV111.services.space.SpaceManagerService.access$200(SpaceManagerService.java:128) [dcache-spacemanager-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at diskCacheV111.services.space.SpaceManagerService$2.process(SpaceManagerService.java:534) [dcache-spacemanager-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at diskCacheV111.services.space.SpaceManagerService$FibonacciBackoffMessageProcessor.run(SpaceManagerService.java:1372) [dcache-spacemanager-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:149) [dcache-core-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:251) [dcache-common-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
```

Billing has the following information:

```
[root@prometheus ~]# grep 0000FAF0DCD89D1E43489CDE9F8A5FA400AC /scratch/billing/2018/10/billing-2018.10.19 
10.19 14:22:37 [door:RemoteTransferManager@dCacheDomain:request] ["dteam":1001:1001:unknown] [0000FAF0DCD89D1E43489CDE9F8A5FA400AC,0] [/VOs/dteam/tpc-test/https/test/6f/72/file6_7d76f84f-a7c2-4dca-a334-0778160ca842] test:default@osm 2522140 57 {24:"java.io.IOException: transfer cancelled: client went away"}
10.19 15:21:31 [pool:pool2@pools:remove] [0000FAF0DCD89D1E43489CDE9F8A5FA400AC,769217256] [Unknown] test:default@osm {0:""}
10.19 15:21:32 [pool:pool2:transfer] [0000FAF0DCD89D1E43489CDE9F8A5FA400AC,769217256] [/VOs/dteam/tpc-test/https/test/6f/72/file6_7d76f84f-a7c2-4dca-a334-0778160ca842] test:default@osm 769217256 2522116 true {RemoteHttpsDataTransfer-1.1:https://dpmhead-trunk.cern.ch:443//dpm/cern.ch/home/dteam/domatests/https/test/6f/72/file6_7d76f84f-a7c2-4dca-a334-0778160ca842} [door:RemoteTransferManager@dCacheDomain:1539951757564-193] {666:"General problem: null"}
[root@prometheus ~]# 
```

The problem seems to stem from aborted WebDAV uploads (i.e., those cancelled via `PoolMoverKillMessage`) not including the file size in the `FileAttributes`, which is included in the `DoorTransferFinishedMessage`.

**Comment by paulmillar** [comment]
As a further observation --  the size value is set in `WriteHandleImpl#commit` (as a post-processing step), yet this `commit` method is not always called: some failure modes call `ReplicaDescriptor#close` without first calling `ReplicaDescriptor#commit`.

Therefore, either `WriteHandleImpl` is broken for not always specifying a file size, or `SpaceManagerService` is broken for requiring that the file size be known.

**Comment by paulmillar** [comment]
Commit 24de52028527563309728bb9fa56504d7f75bed7 should fix the billing log entry, providing a better explanation on what went wrong.
