### ISSUE TITLE
history:  NPE

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#4313]
21 Oct 2018 17:15:18 (history) [] Uncaught exception in thread pool-6-thread-1
java.lang.NullPointerException: null
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_181]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_181]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_181]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_181]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_181]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_181]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_181]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_181]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_181]
        at org.dcache.util.collector.pools.PoolInfoCollectorUtils.mergeLastAccess(PoolInfoCollectorUtils.java:299) ~[dcache-core-4.2.14-FNAL.jar:4.2.14-FNAL]
        at org.dcache.util.collector.pools.PoolHistoriesAggregator.update(PoolHistoriesAggregator.java:98) ~[dcache-history-4.2.14-FNAL.jar:4.2.14-FNAL]
        at org.dcache.util.collector.pools.PoolInfoAggregator.lambda$aggregateDataForPoolGroups$0(PoolInfoAggregator.java:100) ~[dcache-core-4.2.14-FNAL.jar:4.2.14-FNAL]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_181]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_181]
        at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1625) ~[na:1.8.0_181]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_181]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_181]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_181]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_181]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_181]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_181]
        at org.dcache.util.collector.pools.PoolInfoAggregator.aggregateDataForPoolGroups(PoolInfoAggregator.java:95) ~[dcache-core-4.2.14-FNAL.jar:4.2.14-FNAL]
        at org.dcache.services.history.pools.PoolHistoriesRequestProcessor.postProcess(PoolHistoriesRequestProcessor.java:185) ~[dcache-history-4.2.14-FNAL.jar:4.2.14-FNAL]
        at org.dcache.util.collector.RequestFutureProcessor.waitUntilFinished(RequestFutureProcessor.java:231) ~[dcache-core-4.2.14-FNAL.jar:4.2.14-FNAL]
        at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:251) ~[dcache-common-4.2.14-FNAL.jar:4.2.14-FNAL]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

**Comment by alrossi** [comment]
my analysis so far

this:

at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_181]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_181]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_181]
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_181]

means the error is at the end of the pipeline:

 List<CountingHistogram> allHistograms =
                        pools.stream()
                             .map(PoolInfoWrapper::getInfo)
                             .map(PoolData::getSweeperData)
                             .map(SweeperData::getLastAccessHistogram) <<< 
                             .collect(Collectors.toList());


that is, getLastAccessHistogram is being called on a null SweeperData object.

the SweeperData is set in the PoolInfoRequestHandler on the pool:

request.setSweeperData(sweeper.getDataObject());

in both SpaceSweeper2 and NoCachedFilesSpaceSweeper, getDataObject() is implemented to return a SweeperData object, even if empty.

There is a sweeper data stanza in every json file in the pool-history directory:

[root@fndca3a pool-history]# ls -l *.json | wc -l
628
[root@fndca3a pool-history]# grep sweeper *.json | wc -l
628

I restarted history and got the same exception nearly immediately.

Puzzling.

**Comment by alrossi** [comment]
https://rb.dcache.org/r/11287/

**Comment by alrossi** [comment]
fixed but not automatically closed.
