### ISSUE TITLE
Retry mechanism in Transfer class fails with java.lang.StackOverflowError

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#4392]
The retry mechanism in Transfer class based on chaining ListenableFutures. However, when too many retries chained, then processing thread may die with java.lang.StackOverflowError:

```
java.lang.StackOverflowError: null
       at com.google.common.util.concurrent.AbstractFuture.toString(AbstractFuture.java:950) ~[guava-24.1-jre.jar:na]
       at java.lang.String.valueOf(String.java:2994) ~[na:1.8.0_77]
       at com.google.common.util.concurrent.AbstractFuture.userObjectToString(AbstractFuture.java:1018) ~[guava-24.1-jre.jar:na]
       at com.google.common.util.concurrent.AbstractFuture.pendingToString(AbstractFuture.java:987) ~[guava-24.1-jre.jar:na]
       at com.google.common.util.concurrent.AbstractCatchingFuture.pendingToString(AbstractCatchingFuture.java:124) ~[guava-24.1-jre.jar:na]
       at com.google.common.util.concurrent.AbstractFuture.toString(AbstractFuture.java:958) ~[guava-24.1-jre.jar:na]
       at java.lang.String.valueOf(String.java:2994) ~[na:1.8.0_77]
       at com.google.common.util.concurrent.AbstractFuture.userObjectToString(AbstractFuture.java:1018) ~[guava-24.1-jre.jar:na]
       at com.google.common.util.concurrent.AbstractFuture.pendingToString(AbstractFuture.java:987) ~[guava-24.1-jre.jar:na]
       at com.google.common.util.concurrent.AbstractCatchingFuture.pendingToString(AbstractCatchingFuture.java:124) ~[guava-24.1-jre.jar:na]
       at com.google.common.util.concurrent.AbstractFuture.toString(AbstractFuture.java:958) ~[guava-24.1-jre.jar:na]
       at java.lang.String.valueOf(String.java:2994) ~[na:1.8.0_77]
```

**Comment by kofemann** [comment]
On my laptop I run out-of-memory earlier.

**Comment by kofemann** [comment]
Code to reproduce:
```
import com.google.common.util.concurrent.Futures;
import com.google.common.util.concurrent.ListenableFuture;
import com.google.common.util.concurrent.ListeningExecutorService;
import com.google.common.util.concurrent.MoreExecutors;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicLong;
import java.util.concurrent.atomic.AtomicBoolean;

public class FutureTest {

    public static void main(String[] args) throws InterruptedException, ExecutionException {

        ListeningExecutorService executorService = MoreExecutors.listeningDecorator(Executors.newFixedThreadPool(1));
        AtomicLong n = new AtomicLong();
        AtomicBoolean run = new AtomicBoolean(true);

        ListenableFuture<String> f = executorService.submit(() -> {
            Thread.currentThread().setUncaughtExceptionHandler( (t,e) -> {
               run.set(false);
               System.out.println("Failed with " + e.toString() + " after " + n);
            });
            Thread.sleep(1000);
            return "hello";
        });

        try {
            while (run.get()) {
                n.incrementAndGet();;
                f = Futures.transform(f, s -> s.toUpperCase());
            }
        } finally {
            executorService.shutdown();
        }
    }
}
```

Test run on lab node 
(nice feature of java11 run single file with javac)

```
[root@dcache-lab007 ~]# java -cp /usr/share/dcache/classes/guava-24.1-jre.jar FutureTest.java 
Note: FutureTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Failed with java.lang.StackOverflowError after 5544337
[root@dcache-lab007 ~]# 
```

So the answer is yes, I can reproduce it.
