### ISSUE TITLE
Bad xroot gsi TPC credential yields stack-trace

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#4427]
Observed the following:

```
08 Nov 2018 13:16:42 (pool2) [door:xrootd-gsi@dCacheDomain:AAV6JjUbcNA xrootd-gsi PoolAcceptFile 000002ECEE4FCA354945B4930A357E07EFA1] Transfer failed in post-processing: File size mismatch (expected=1000000000, actual=0)
08 Nov 2018 13:17:04 (pool1) [] Failed to initialize a channel. Closing: [id: 0x0e967a42]
java.lang.RuntimeException: Could not read certificates/key from file-system
        at org.dcache.xrootd.plugins.authn.gsi.GSIClientAuthenticationFactory.createHandler(GSIClientAuthenticationFactory.java:101) ~[xrootd4j-gsi-3.3.3.jar:3.3.3]
        at org.dcache.xrootd.tpc.XrootdTpcClient.injectHandlers(XrootdTpcClient.java:606) ~[xrootd4j-3.3.3.jar:5.0.0-SNAPSHOT]
        at org.dcache.xrootd.tpc.XrootdTpcClient.access$000(XrootdTpcClient.java:68) ~[xrootd4j-3.3.3.jar:5.0.0-SNAPSHOT]
        at org.dcache.xrootd.tpc.XrootdTpcClient$1.initChannel(XrootdTpcClient.java:228) ~[xrootd4j-3.3.3.jar:5.0.0-SNAPSHOT]
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-common-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.10.Final.jar:4.1.10.Final]
        at org.dcache.util.CDCThreadFactory.lambda$newThread$0(CDCThreadFactory.java:50) [dcache-core-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]
Caused by: java.io.FileNotFoundException: /var/lib/dcache/xrootd-tpc.pem (Permission denied)
        at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_191]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_191]
        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_191]
        at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[na:1.8.0_191]
        at eu.emi.security.authn.x509.impl.PEMCredential.<init>(PEMCredential.java:52) ~[canl-2.5.0.jar:2.5.0]
        at org.dcache.xrootd.plugins.authn.gsi.GSIClientAuthenticationFactory.loadClientCredentials(GSIClientAuthenticationFactory.java:134) ~[xrootd4j-gsi-3.3.3.jar:3.3.3]
        at org.dcache.xrootd.plugins.authn.gsi.GSIClientAuthenticationFactory.createHandler(GSIClientAuthenticationFactory.java:89) ~[xrootd4j-gsi-3.3.3.jar:3.3.3]
        ... 19 common frames omitted
```

This is due to wrong permissions in the credential, so is not a bug in dCache and therefore should not result in a stack-trace being logged.

**Comment by alrossi** [comment]
https://rb.dcache.org/r/11336/
