### ISSUE TITLE
RENEW with expired lease should return NFS4ERR_EXPIRED, instead got NFS4ERR_STALE_CLIENTID

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache#4439]
Observed dCache v4.2 yielding the following error:

RENEW with expired lease should return NFS4ERR_EXPIRED, instead got NFS4ERR_STALE_CLIENTID

With stack-trace:

```
Traceback (most recent call last):
  File "/scratch/jenkins/pnfs-python/nfs4.0/lib/testmod.py", line 222, in run
    self.runtest(self, environment)
  File "/scratch/jenkins/pnfs-python/nfs4.0/servertests/st_renew.py", line 42, in testExpired
    check(res, NFS4ERR_EXPIRED, "RENEW with expired lease")
  File "/scratch/jenkins/pnfs-python/nfs4.0/servertests/environment.py", line 264, in check
    raise testmod.FailureException(msg)
FailureException: RENEW with expired lease should return NFS4ERR_EXPIRED, instead got NFS4ERR_STALE_CLIENTID
```

pynfs [build #8498](https://ci.dcache.org/job/pynfs-test-suite/8498/): [details](https://ci.dcache.org/job/pynfs-test-suite/8498/testReport/junit/(root)/st_renew/testExpired/
).

**Comment by paulmillar** [comment]
As a temporary fix, I've added `RENEW3` to the list of excluded NFS v4.0 tests

**Comment by paulmillar** [comment]
Reports of this failure on `master` branch:
pynfs [build #8507](https://ci.dcache.org/job/pynfs-test-suite/8507/): [details](https://ci.dcache.org/job/pynfs-test-suite/8507/testReport/junit/(root)/st_renew/testExpired/).

Disabling `RENEW3` on master, too.

**Comment by kofemann** [comment]
There were no updates on this issue for quite some time. Closing.
