### ISSUE TITLE
NPE from logging in xrootd4j

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#4502]
This is probably also an xrootd4j issue (ErrorResponse), but I have not seen it before applying RB 11439 and 11443.

```
13 Dec 2018 13:52:07 (dmsdca15-2) [door:Xrootd1-fndcatemp1@xrootd1-fndcatemp1Domain:AAV87KZFvqA Xrootd1-fndcatemp1 PoolAcceptFile 00003A6BB35D179D454CA2AF293866A8CCC9] Transfer failed due to a bug
java.lang.NullPointerException: null
        at org.dcache.xrootd.protocol.messages.ErrorResponse.getDataLength(ErrorResponse.java:57) ~[xrootd4j-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at org.dcache.xrootd.protocol.messages.AbstractXrootdResponse.writeTo(AbstractXrootdResponse.java:54) ~[xrootd4j-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at org.dcache.xrootd.core.XrootdEncoder.write(XrootdEncoder.java:39) ~[xrootd4j-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.handler.logging.LoggingHandler.write(LoggingHandler.java:249) [netty-handler-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at org.dcache.xrootd.plugins.AccessLogHandler.write(AccessLogHandler.java:229) [dcache-xrootd-5.0.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:305) [netty-handler-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at org.dcache.xrootd.stream.ChunkedResponseWriteHandler.write(ChunkedResponseWriteHandler.java:89) [xrootd4j-3.4.0-SNAPSHOT.jar:3.4.0-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1089) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1136) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1078) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-common-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.10.Final.jar:4.1.10.Final]
        at org.dcache.util.CDCThreadFactory.lambda$newThread$0(CDCThreadFactory.java:50) [dcache-core-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at org.dcache.util.CDCThreadFactory$$Lambda$232/309023221.run(Unknown Source) [dcache-core-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by paulmillar** [comment]
Could the problem come from xrootd4j?  It looks like you're running with a non-released version (`3.4.0-SNAPSHOT`)

**Comment by alrossi** [comment]
I'm investigating (ran out of time yesterday).  Yes, it could be there are several (unrelated) issues occurring here. But the NPE in the ErrorResponse should not happen in any case.  After posting this, I don't think the problem is directly related to the logging though ...

**Comment by paulmillar** [comment]
When a message is sent through the Netty pipeline, it passes through all the providers.  So you'll see the access log provider there, but that should just pass the message on, without changing it.

("should" being an important word ;-)
