### ISSUE TITLE
TheBook: ban.conf example is broken

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#4738]
Dear dCache developers,

In The Book, there is an example of a ban.conf file. Unfortunately, when I copied and pasted this example and modified our gplazma.conf to use it, EVERYONE was denied access because of a syntax error.

The example from https://github.com/dCache/dcache/blob/master/docs/TheBook/src/main/markdown/config-gplazma.md:

```
# Ban users by principal
alias dn=org.globus.gsi.jaas.GlobusPrincipal
alias kerberos=javax.security.auth.kerberos.KerberosPrincipal
alias fqan=org.dcache.auth.FQANPrincipal
alias name=org.dcache.auth.LoginNamePrincipal

ban name:ernie
ban kerberos:BERT@EXAMPLE.COM
ban com.example.SomePrincipal:Samson
```

I added a line like this:
```
ban dn:/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=....
```

From the log:

```
20 Mar 2019 10:08:33 (gPlazma) [admin ACCOUNT banfile] Bug in plugin: 
java.lang.IllegalArgumentException: No matching class found: org.globus.gsi.jaas.GlobusPrincipal
        at org.dcache.auth.Subjects.principalsFromArgs(Subjects.java:502) ~[dcache-common-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.gplazma.plugins.BanFilePlugin.principalsFromFile(BanFilePlugin.scala:82) ~[gplazma2-banfile-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.gplazma.plugins.BanFilePlugin.$anonfun$bannedPrincipals$1(BanFilePlugin.scala:89) ~[gplazma2-banfile-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.gplazma.plugins.FileCache.getOrFetch(FileCache.scala:13) ~[gplazma2-banfile-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.gplazma.plugins.FileCache.getOrFetch$(FileCache.scala:10) ~[gplazma2-banfile-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.gplazma.plugins.BanFilePlugin.getOrFetch(BanFilePlugin.scala:17) ~[gplazma2-banfile-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.gplazma.plugins.BanFilePlugin.bannedPrincipals(BanFilePlugin.scala:89) ~[gplazma2-banfile-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.gplazma.plugins.BanFilePlugin.account(BanFilePlugin.scala:99) ~[gplazma2-banfile-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.gplazma.strategies.DefaultAccountStrategy.lambda$account$0(DefaultAccountStrategy.java:65) [gplazma2-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.gplazma.strategies.PAMStyleStrategy.callPlugins(PAMStyleStrategy.java:98) ~[gplazma2-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.gplazma.strategies.DefaultAccountStrategy.account(DefaultAccountStrategy.java:57) [gplazma2-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.gplazma.GPlazma$Setup.doAccountPhase(GPlazma.java:589) [gplazma2-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.gplazma.GPlazma.login(GPlazma.java:270) [gplazma2-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.auth.Gplazma2LoginStrategy.ac_explain_login_$_1_99(Gplazma2LoginStrategy.java:198) [dcache-gplazma-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
        at dmg.util.command.AcCommandExecutor.execute(AcCommandExecutor.java:150) [cells-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at dmg.cells.nucleus.CellAdapter.executeCommand(CellAdapter.java:239) [cells-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.cells.UniversalSpringCell.executeCommand(UniversalSpringCell.java:195) [dcache-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at dmg.cells.nucleus.CellAdapter$1.doExecute(CellAdapter.java:105) [cells-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.util.cli.CommandInterpreter.command(CommandInterpreter.java:129) [common-cli-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at dmg.cells.nucleus.CellAdapter$1.command(CellAdapter.java:122) [cells-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at dmg.cells.nucleus.CellAdapter.command(CellAdapter.java:224) [cells-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at dmg.cells.nucleus.CellAdapter.executeLocalCommand(CellAdapter.java:916) [cells-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at dmg.cells.nucleus.CellAdapter.messageArrived(CellAdapter.java:856) [cells-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at dmg.cells.nucleus.CellNucleus$DeliverMessageTask.run(CellNucleus.java:1211) [cells-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:251) [dcache-common-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
        at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$4(CellNucleus.java:747) [cells-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]
```

What's the correct syntax?
How can I find out myself what the correct syntax is (in case I may want to add criteria)?

Thanks!
Onno

**Comment by onnozweers** [comment]
It looks like it should be `org.globus.gsi.gssapi.jaas.GlobusPrincipal`. I've tested that and it seems to work. I'll submit a pull request for a Book update.
