### ISSUE TITLE
resilience erroneous remove of all copies

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#4742]
Depending on factors which may influence the speed at which namespace updates occur, resilience may be susceptible to responding to stale information concerning the number of locations of a file.  If resilience believes there are too many copies, this could lead to the removal of all replicas.

**Comment by alrossi** [comment]
I am opening this issue as a place to keep a record of this work.

Investigating the possibility of correcting what we believe to be behavior triggered by some sort of inconsistency or lag between the pool repository state and chimera, I first tested how much overhead would be involved in a given batch of file operations if each contacted all the pools to verify the information in chimera.

I used what might be called a pathological case, based on a setup for a few of our experiments here at Fermi, where resilience maintains 20 copies of each file.

Beginning with 48 pools:

```
chimera=> select count(*), ilocation from t_locationinfo group by ilocation;
  count  |  ilocation   
---------+--------------
 1057065 | dmsdca21-6.1
 1129573 | dmsdca20-4.1
 1043457 | dmsdca21-2.1
 1002415 | dmsdca15-6.1
 1126520 | dmsdca15-2.1
 1121756 | dmsdca21-4.1
 1141665 | dmsdca19-2
 1183815 | dmsdca20-1
 1117530 | dmsdca15-5.1
 1104280 | dmsdca21-7
 1129112 | dmsdca18-2.1
 1163460 | dmsdca18-1.1
 1010732 | dmsdca15-7.1
 1135162 | dmsdca19-1
 1119615 | dmsdca21-8.1
 1118584 | dmsdca15-1
 1138574 | dmsdca15-7
 1039930 | dmsdca15-4
 1060394 | dmsdca21-2
 1104801 | dmsdca15-4.1
 1121920 | dmsdca15-1.1
 1071291 | dmsdca21-3
 1130673 | dmsdca20-3.1
 1110063 | dmsdca21-5.1
 1133387 | dmsdca19-2.1
 1119081 | dmsdca21-3.1
 1121476 | dmsdca21-7.1
 1121716 | dmsdca15-2
 1106428 | dmsdca21-1
 1121079 | dmsdca15-5
 1113890 | dmsdca20-2
 1108901 | dmsdca15-6
 1170138 | dmsdca18-1
 1113509 | dmsdca21-8
 1123490 | dmsdca20-4
 1110777 | dmsdca15-3.1
 1118144 | dmsdca15-8
 1128566 | dmsdca20-3
 1121831 | dmsdca20-1.1
 1113145 | dmsdca15-3
 1123641 | dmsdca18-2
 1116978 | dmsdca21-4
 1096667 | dmsdca21-6
 1127820 | dmsdca20-2.1
 1114962 | dmsdca15-8.1
 1138109 | dmsdca19-1.1
 1122562 | dmsdca21-5
 1063513 | dmsdca21-1.1
(48 rows)
```

I tested bringing up and down a single pool, with verify turned on and off.   The results are summarized here:

**Comment by alrossi** [comment]
Next, the testbed was prepared for testing the correctness of the new patches in handling out of sync situations.

In order to do so, it was impractical to leave 20 copies of each file on the pools, so a reduction was initiated by resetting the storage unit requirement to 2 and initiating a scan of all pools.  

The scan lasted approximately 48 hours and removed 48,665,967 replicas.

Toward the end of the scan, a number of inaccessible file alarms were reported (these also appeared in the resilience.resilience activity log).

**Comment by alrossi** [comment]
This inadvertent confirmation of the behavior we observed at DESY bears a little more scrutiny.

The first observation is that the peculiarity of the setup (20 copies) and reduction (to 2) caused the system to behave as follows:   The first five pool scans ran for nearly 36 hours.  This is because of the queuing semantics:  each operation (there were approximately 2.6M in memory) for these five pools was dequeued and enqueued 17 times.   That means that nearly all the replicas that needed to be removed were removed during the first five scans.

The second observation is that the billing records for the missing files are all characterized by one or more rapid series of removes (multiple files in less than a second) toward the end of the reduction run, that is, after 4 AM March 25.

[missing-removes.txt](https://github.com/dCache/dcache/files/3003586/missing-removes.txt)

The queues at this time were shorter, which explains why these removes could happen so quickly.

What caused this to happen?  again, there is uncertainty as to the precise nature of the failure, but notice that the resilience log contains the following:

```
23 Mar 2019 17:55:53 (Resilience) [] [131.225.240.89]:5703 [dcache-namespace] [3.11.1] Connection[id=1, /131.225.240.89:5703->/131.225.12.217:38286, endpoint=null, alive=false, type=NONE] closed. Reason: Exception in Connection[id=1, /131.225.240.89:5703->/131.225.12.217:38286, endpoint=null, alive=true, type=NONE], thread=hz._hzInstance_1_dcache-namespace.IO.thread-in-0
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_91]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_91]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_91]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_91]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_91]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:113) ~[hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:368) [hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:353) [hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:279) [hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:234) [hazelcast-3.11.1.jar:3.11.1]
23 Mar 2019 18:01:52 (Resilience) [] [131.225.240.89]:5703 [dcache-namespace] [3.11.1] Connection[id=29, /131.225.240.89:5703->/131.225.12.202:36738, endpoint=null, alive=false, type=NONE] closed. Reason: Exception in Connection[id=29, /131.225.240.89:5703->/131.225.12.202:36738, endpoint=null, alive=true, type=NONE], thread=hz._hzInstance_1_dcache-namespace.IO.thread-in-1
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_91]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_91]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_91]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_91]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_91]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:113) ~[hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:368) [hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:353) [hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:279) [hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:234) [hazelcast-3.11.1.jar:3.11.1]
23 Mar 2019 18:02:54 (Resilience) [] [131.225.240.89]:5703 [dcache-namespace] [3.11.1] Connection[id=30, /131.225.240.89:5703->/131.225.12.202:40726, endpoint=null, alive=false, type=NONE] closed. Reason: Exception in Connection[id=30, /131.225.240.89:5703->/131.225.12.202:40726, endpoint=null, alive=true, type=NONE], thread=hz._hzInstance_1_dcache-namespace.IO.thread-in-2
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_91]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_91]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_91]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_91]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_91]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:113) ~[hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:368) [hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:353) [hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:279) [hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:234) [hazelcast-3.11.1.jar:3.11.1]
23 Mar 2019 18:05:40 (Resilience) [] [131.225.240.89]:5703 [dcache-namespace] [3.11.1] Connection[id=32, /131.225.240.89:5703->/131.225.12.202:48872, endpoint=null, alive=false, type=NONE] closed. Reason: Exception in Connection[id=32, /131.225.240.89:5703->/131.225.12.202:48872, endpoint=null, alive=true, type=NONE], thread=hz._hzInstance_1_dcache-namespace.IO.thread-in-1
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_91]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_91]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_91]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_91]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_91]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:113) ~[hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:368) [hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:353) [hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:279) [hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:234) [hazelcast-3.11.1.jar:3.11.1]
23 Mar 2019 18:09:19 (Resilience) [] [131.225.240.89]:5703 [dcache-namespace] [3.11.1] Connection[id=34, /131.225.240.89:5703->/131.225.12.202:34924, endpoint=null, alive=false, type=NONE] closed. Reason: Exception in Connection[id=34, /131.225.240.89:5703->/131.225.12.202:34924, endpoint=null, alive=true, type=NONE], thread=hz._hzInstance_1_dcache-namespace.IO.thread-in-0
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_91]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_91]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_91]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_91]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_91]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:113) ~[hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:368) [hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:353) [hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:279) [hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:234) [hazelcast-3.11.1.jar:3.11.1]
```

This happened on March 23, so I am uncertain that it is connected to the failure.   

If it happened this early and was the cause, one would think more files would have been lost.

My suspicion is that the loss is just provoked by timing.  When the removes take place so quickly (short queues), resilience outraces the clear cache location message.   

We will now seek additional confirmation through the testing.

**Comment by alrossi** [comment]
One other thing:

I noticed that my testbed system has been running with the default postgresql max connections:

```
[root@fndcatemp1 pgsql-9.6]# grep onnections postgresql*.conf 
postgresql.conf:# "postgres -c log_connections=on".  Some parameters can be changed at run time
postgresql.conf:max_connections = 100			# (change requires restart)
postgresql.conf:#superuser_reserved_connections = 3	# (change requires restart)
postgresql.conf:#log_connections = off
postgresql.conf:#log_disconnections = off
```

This is probably because we updated the postgres version on fndcatemp1 after the heavy resilience testing we did several years ago, and forgot to retune the connections.

As the properties file states, this should be at least 210 if we are running the default 200 concurrent operations:

```
# ---- Configuration for database connection pool
#
#      The database connection pool reuses connections between successive
#      database operations.  By reusing connections dCache doesn't suffer
#      the overhead of establishing new database connections for each
#      operation.
#
#      The options here determine how resilience behaves as the
#      number of concurrent requests fluctuates.
# ------------------------------------------------------------------------

# ---- The maximum number of concurrent database connections.
#
#      The recommended minimum setting is:
#
#                  resilience.limits.file.submit-threads
#                  + resilience.limits.file.operation-threads
#                  + (2 * resilience.limits.pool.scan-threads)
#                  + a few extra for admin calls
#
#      Submit and operation threads require 1 database connection, and scan
#      threads need 2.
#
#      Since this service shares the chimera database with pnfsmanager,
#      be sure to adjust the postgresql.conf max connections upwards
#      to accommodate both.  Pnfsmanager runs well with about 100
#      connections.  Adding a separate resilience service means the
#      connections should be increased by at least the amount below.
#
resilience.db.connections.max = 120
```

**Comment by alrossi** [comment]
The first run of correctness tests using a 30 second delay of clear cache updates

1)
```
\s dmsdca15-6.1 pool disable -strict

TOTALS                            101179          101179               6     98.81 KB                 0               0            0

chimera=> SELECT inumber2pnfsid(inumber),isize,inumber2path(inumber) FROM t_inodes WHERE inumber IN (SELECT inumber FROM t_inodes WHERE itype=32768 AND isize>0 EXCEPT SELECT inumber FROM t_locationinfo);
 inumber2pnfsid | isize | inumber2path 
----------------+-------+--------------
(0 rows)

\s dmsdca15-6.1 pool enable

TOTALS                            101179          101179               6     98.81 KB            101179               0     98.81 KB

chimera=> SELECT inumber2pnfsid(inumber),isize,inumber2path(inumber) FROM t_inodes WHERE inumber IN (SELECT inumber FROM t_inodes WHERE itype=32768 AND isize>0 EXCEPT SELECT inumber FROM t_locationinfo);
 inumber2pnfsid | isize | inumber2path 
----------------+-------+--------------
(0 rows)
```
There was no loss here, but this is understandable.   There is a difference in terms of how many iterations occur when processing a norm "POOL UP" event and one where a pool is manually or periodically scanned.  In this case, only one iteration (barring failure) is done, so there is no chance to remove additional copies.  

When there is a scan, or there are multiple pools scanning concurrently and these pools share files, the operation counts for those files will be greater than 1, and thus will create the necessary iterative conditions for the multiple removal error.

So, trying a scan:

2)
```
\s dmsdca15-7.1 pool disable -strict

TOTALS                            204194          204194              10    199.41 KB            101179               0     98.81 KB

\s dmsdca15-7.1 pool enable

pool scan dmsdca15-7.1

TOTALS                            206006          206006              10    201.18 KB            213641               0    208.63 KB

chimera=> SELECT inumber2pnfsid(inumber),isize,inumber2path(inumber) FROM t_inodes WHERE inumber IN (SELECT inumber FROM t_inodes WHERE itype=32768 AND isize>0 EXCEPT SELECT inumber FROM t_locationinfo);
 inumber2pnfsid | isize | inumber2path 
----------------+-------+--------------
...
(652 rows)
```

652 files ... a lot more than the original run because ... the delay is not 1 or 2 seconds, but 30.   So we have pretty good confirmation this is the probably the cause.

3)  Enable the verification after the pool down, to catch false removes:

```
\s dmsdca21-2.1 pool disable -strict

TOTALS                            312432          312432              12    305.11 KB            213641               0    208.63 KB

(failures are because cleaner hasdn't yet run the cleanup on the files I deleted from the last run).

chimera=> SELECT inumber2pnfsid(inumber),isize,inumber2path(inumber) FROM t_inodes WHERE inumber IN (SELECT inumber FROM t_inodes WHERE itype=32768 AND isize>0 EXCEPT SELECT inumber FROM t_locationinfo);
 inumber2pnfsid | isize | inumber2path 
----------------+-------+--------------
(0 rows)

[fndcatemp1] (Resilience@resilienceDomain) admin > mode -verifyLocations=ALL
Verify replica locations before removing a replica: ALL

\s dmsdca21-2.1 pool enable

pool scan dmsdca21-2.1

RECEIVED:

dCache Alarm
root@bogus6.fnal.gov
Today, 11:44 AM

25 Mar 2019 11:44:20 RESILIENCE_INCONSISTENT_LOCATIONS (fndcatemp1.fnal.gov)(Resilience)(resilienceDomain)() Resilience has detected an inconsistency between the namespace replica locations and the actual locations on disk; intervention by admin may be required.

TOTALS                            312470          312470              12    305.15 KB            320068               0    312.57 KB

chimera=> SELECT inumber2pnfsid(inumber),isize,inumber2path(inumber) FROM t_inodes WHERE inumber IN (SELECT inumber FROM t_inodes WHERE itype=32768 AND isize>0 EXCEPT SELECT inumber FROM t_locationinfo);
 inumber2pnfsid | isize | inumber2path 
----------------+-------+--------------
(0 rows)
```

SUCCESS!

**Comment by alrossi** [comment]
Tested the first patch, which is backportable (requires only changes to resilience and one change to alarms):

(1)  DOWN/UP, with forced scan of the restart:
```
\s  dmsdca15-4 pool disable -strict

pool scan dmsdca15-4$

0 missing

\s  dmsdca15-4 pool enable

pool scan dmsdca15-4$

25 Mar 2019 13:26:20 RESILIENCE_INCONSISTENT_LOCATIONS (fndcatemp1.fnal.gov)(Resilience)(resilienceDomain)() Resilience has detected an inconsistency between the namespace replica locations and the actual locations on disk; intervention by admin may be required.

0 missing
```
Alarm was logged, error reported, but no file loss.

(2)  Changed tags on the storage unit, forcing a rescan of all pools (since they all have this storage unit).  

```
\sp psu set storage unit -required=2 -onlyOneCopyPer=host,rack resilient-4.dcache-devel-test@enstore

25 Mar 2019 14:02:43 RESILIENCE_INCONSISTENT_LOCATIONS (fndcatemp1.fnal.gov)(Resilience)(resilienceDomain)() Resilience has detected an inconsistency between the namespace replica locations and the actual locations on disk; intervention by admin may be required.

chimera=> SELECT inumber2pnfsid(inumber),isize,inumber2path(inumber) FROM t_inodes WHERE inumber IN (SELECT inumber FROM t_inodes WHERE itype=32768 AND isize>0 EXCEPT SELECT inumber FROM t_locationinfo);
 inumber2pnfsid | isize | inumber2path 
----------------+-------+--------------
(0 rows)
```

Again, all pools scanned, many removes and recopies.  We can tell that the error is occurring frequently because of the continual logging of "Resilience has detected an inconsistency between the namespace replica locations and the actual locations on disk; intervention by admin may be required."
```
[root@fndcatemp1 ~]# cat /var/log/dcache/resilienceDomain.log | grep detected | wc -l
106221
```
This is actually not the intention (I wanted to rate-delimit the alarm; I've modified the patch).  But this actually helped in the testing.

**Comment by alrossi** [comment]
sanity check

chimera=> SELECT n.ipnfsid, count(*) from t_inodes n, t_locationinfo l where n.inumber = l.inumber and n.itype=32768 group by n.ipnfsid having count(*) < 2;
               ipnfsid                | count 
--------------------------------------+-------
 0000C4E1785D56D04CBB98181D8DA2CEE0A2 |     1
(1 row)


chimera=> SELECT n.ipnfsid, count(*) from t_inodes n, t_locationinfo l where n.inumber = l.inumber and n.itype=32768 group by n.ipnfsid having count(*) > 2;
 ipnfsid | count 
---------+-------

0000C4E1785D56D04CBB98181D8DA2CEE0A2 is a file in the volatile storage group which is not resilient

**Comment by alrossi** [comment]
The first patch:  https://rb.dcache.org/r/11628/

The second patch now needs to be tested.  That one also incorporates a new remove semantics, so it is crucial to make sure the we can tell it is doing the correct thing.  This will involve counting cached vs stick files on pools after a run is made.   I am not sure what the most efficient way to do this is.   I may want to reduce the installation to only a few files on a few pools to make this testing more manageable, before actually deploying the patch.

**Comment by alrossi** [comment]
Replaced above patch with simplified (less invasive backport):
https://rb.dcache.org/r/11632

Tested by

1.  setting 5 second delay
2.  removing tag constraints on storage unit
3.  bringing down 5 pools in succession, allowing copies to go on random pools
4.  bringing up the pools, removing excess copies.
5.  adding back in the hostname,rack tags to the unit, triggering mass redistribution of files

```
OPERATION                            completed   ops/sec       failed
    FILE                               6704945         0            0
    POOL_SCAN_DOWN                           0         0            0
    POOL_SCAN_ACTIVE                        48         0            0

TRANSFERS BY POOL                   from              to          failed         size           removed          failed         size
dmsdca15-1                          9815           11311               0     11.05 KB             20184               0     19.71 KB
dmsdca15-1.1                           0           12086               0     11.80 KB             36509               0     35.65 KB
dmsdca15-2                         12852           11409               0     11.14 KB             17961               0     17.54 KB
dmsdca15-2.1                       11907           12227               0     11.94 KB             28088               0     27.43 KB
dmsdca15-3                         19686           12483               0     12.19 KB             18115               0     17.69 KB
dmsdca15-3.1                        8716           13670               0     13.35 KB             26883               0     26.25 KB
dmsdca15-4                         17566           12667               0     12.37 KB              9135               0      8.92 KB
dmsdca15-4.1                        5779           13185               0     12.88 KB             31178               0     30.45 KB
dmsdca15-5                         27918           14174               0     13.84 KB              8834               0      8.63 KB
dmsdca15-5.1                        2608           14503               0     14.16 KB             31546               0     30.81 KB
dmsdca15-6                         31928           13983               0     13.66 KB              5940               0      5.80 KB
dmsdca15-6.1                       18396           13551               0     13.23 KB              6256               0      6.11 KB
dmsdca15-7                         35777           12990               0     12.69 KB              2908               0      2.84 KB
dmsdca15-7.1                       14969           12500               0     12.21 KB              9109               0      8.90 KB
dmsdca15-8                         34966           14314               0     13.98 KB                 0               0            0
dmsdca15-8.1                       17464           13295               0     12.98 KB             18153               0     17.73 KB
dmsdca18-1                          1680           20088               0     19.62 KB              6312               0      6.16 KB
dmsdca18-1.1                        8066           18661               0     18.22 KB                 0               0            0
dmsdca18-2                          8455           19047               0     18.60 KB              4433               0      4.33 KB
dmsdca18-2.1                        6634           16709               0     16.32 KB              3841               0      3.75 KB
dmsdca19-1                          5167           17610               0     17.20 KB              4118               0      4.02 KB
dmsdca19-1.1                        5418           19378               0     18.92 KB              4132               0      4.04 KB
dmsdca19-2                         10358           18137               0     17.71 KB               133               0          133
dmsdca19-2.1                          68           17121               0     16.72 KB              9637               0      9.41 KB
dmsdca20-1                            86           18111               0     17.69 KB             20109               0     19.64 KB
dmsdca20-1.1                       12555           18063               0     17.64 KB              7743               0      7.56 KB
dmsdca20-2                          2982           17580               0     17.17 KB             16364               0     15.98 KB
dmsdca20-2.1                       20575           18029               0     17.61 KB              1036               0      1.01 KB
dmsdca20-3                          5667           21969               0     21.45 KB             12337               0     12.05 KB
dmsdca20-3.1                       16334           18079               0     17.66 KB              3550               0      3.47 KB
dmsdca20-4                          8619           18516               0     18.08 KB              9645               0      9.42 KB
dmsdca20-4.1                        8746           19174               0     18.72 KB              9853               0      9.62 KB
dmsdca21-1                          4269           10915               0     10.66 KB             34519               0     33.71 KB
dmsdca21-1.1                       37017           12169               0     11.88 KB              4283               0      4.18 KB
dmsdca21-2                          9275           11618               0     11.35 KB             30177               0     29.47 KB
dmsdca21-2.1                       20223           11276               0     11.01 KB              8921               0      8.71 KB
dmsdca21-3                         14672           11413               0     11.15 KB             22096               0     21.58 KB
dmsdca21-3.1                       22904           11394               0     11.13 KB             16587               0     16.20 KB
dmsdca21-4                         19612            9258               0      9.04 KB             20135               0     19.66 KB
dmsdca21-4.1                       19157           10931               0     10.67 KB             20064               0     19.59 KB
dmsdca21-5                         24082           10743               0     10.49 KB             14565               0     14.22 KB
dmsdca21-5.1                       12971           11149               0     10.89 KB             24608               0     24.03 KB
dmsdca21-6                         27247           11323               0     11.06 KB             10237               0     10.00 KB
dmsdca21-6.1                        7276            9754               0      9.53 KB             28569               0     27.90 KB
dmsdca21-7                         34019           10490               0     10.24 KB              5221               0      5.10 KB
dmsdca21-7.1                        1860            9402               0      9.18 KB             25327               0     24.73 KB
dmsdca21-8                         38725           13852               0     13.53 KB               168               0          168
dmsdca21-8.1                           0           14759               0     14.41 KB             35369               0     34.54 KB

TOTALS                            685066          685066               0    669.01 KB            684888               0    668.84 KB

```

Checking afterwards, 0 losses, no singletons except for non-resilient file, no excess copies.  As above.

I will repeat some pool downs and ups with a longer delay (30 seconds).

But I feel the patch is ready to be tested on the DESY testbed.

**Comment by alrossi** [comment]
Reset delay to 30 seconds.
Took down, serially, five pools, allowed extra copies to be made.
Brought all pools back up.
Initiated system-wide pool scan.

```
TRANSFERS BY POOL                   from              to          failed         size           removed          failed         size
dmsdca15-1                          9102           13230               0     12.92 KB             11277               0     11.01 KB
dmsdca15-1.1                       11272           13483               0     13.17 KB             11903               0     11.62 KB
dmsdca15-2                          9096           12558               0     12.26 KB              7547               0      7.37 KB
dmsdca15-2.1                       13992           11822               0     11.54 KB              7720               0      7.54 KB
dmsdca15-3                         14016           13808               0     13.48 KB             11215               0     10.95 KB
dmsdca15-3.1                       12021           14336               0     14.00 KB             12146               0     11.86 KB
dmsdca15-4                         13763           12802               0     12.50 KB             10359               0     10.12 KB
dmsdca15-4.1                       16211           11086               0     10.83 KB              9372               0      9.15 KB
dmsdca15-5                         19363            8929               0      8.72 KB             39637               0     38.71 KB
dmsdca15-5.1                       15450           14480               0     14.14 KB             11430               0     11.16 KB
dmsdca15-6                         14097           14187               0     13.85 KB              5664               0      5.53 KB
dmsdca15-6.1                        9600           15747               0     15.38 KB              9834               0      9.60 KB
dmsdca15-7                         20016           14198               0     13.87 KB              7595               0      7.42 KB
dmsdca15-7.1                       13076           12655               0     12.36 KB              9282               0      9.06 KB
dmsdca15-8                         19865           13301               0     12.99 KB              7243               0      7.07 KB
dmsdca15-8.1                       17627           15158               0     14.80 KB             11512               0     11.24 KB
dmsdca18-1                         12458           10500               0     10.25 KB             60336               0     58.92 KB
dmsdca18-1.1                       19214           19780               0     19.32 KB              9055               0      8.84 KB
dmsdca18-2                          9651           18790               0     18.35 KB              5587               0      5.46 KB
dmsdca18-2.1                       13742           19853               0     19.39 KB              6617               0      6.46 KB
dmsdca19-1                         13574           18296               0     17.87 KB              6390               0      6.24 KB
dmsdca19-1.1                       14190           19627               0     19.17 KB              6772               0      6.61 KB
dmsdca19-2                         19477           20162               0     19.69 KB              9596               0      9.37 KB
dmsdca19-2.1                        7272            7740               0      7.56 KB             68838               0     67.22 KB
dmsdca20-1                         12410           17196               0     16.79 KB             15177               0     14.82 KB
dmsdca20-1.1                       13732           16673               0     16.28 KB             13979               0     13.65 KB
dmsdca20-2                         12412           19343               0     18.89 KB             13758               0     13.44 KB
dmsdca20-2.1                       14750           17991               0     17.57 KB              5938               0      5.80 KB
dmsdca20-3                         16563           20213               0     19.74 KB             13931               0     13.60 KB
dmsdca20-3.1                        4421            3323               0      3.25 KB             41906               0     40.92 KB
dmsdca20-4                         15874           19742               0     19.28 KB             13489               0     13.17 KB
dmsdca20-4.1                       17081           17988               0     17.57 KB             12521               0     12.23 KB
dmsdca21-1                         11731           10758               0     10.51 KB              9707               0      9.48 KB
dmsdca21-1.1                       16778           11457               0     11.19 KB              8780               0      8.57 KB
dmsdca21-2                         13795           14510               0     14.17 KB              8896               0      8.69 KB
dmsdca21-2.1                       11941           11607               0     11.33 KB              4865               0      4.75 KB
dmsdca21-3                         12739           13411               0     13.10 KB             11529               0     11.26 KB
dmsdca21-3.1                       14706           12892               0     12.59 KB             11818               0     11.54 KB
dmsdca21-4                         19028           12735               0     12.44 KB             10419               0     10.17 KB
dmsdca21-4.1                       18604           10583               0     10.33 KB              9201               0      8.99 KB
dmsdca21-5                         13278           14252               0     13.92 KB             11688               0     11.41 KB
dmsdca21-5.1                       12100           13325               0     13.01 KB             10792               0     10.54 KB
dmsdca21-6                             0               0               1            0             43887               0     42.86 KB
dmsdca21-6.1                       15346           14548               0     14.21 KB             10571               0     10.32 KB
dmsdca21-7                         20236           14555               0     14.21 KB              7684               0      7.50 KB
dmsdca21-7.1                       10850           12576               0     12.28 KB              8796               0      8.59 KB
dmsdca21-8                         22231           14161               0     13.83 KB              7858               0      7.67 KB
dmsdca21-8.1                       15671           14055               0     13.73 KB             10305               0     10.06 KB

TOTALS                            674422          674422               1    658.62 KB            674422               0    658.62 KB
```

WIth results, as expected:
```
chimera=> SELECT inumber2pnfsid(inumber),isize,inumber2path(inumber) FROM t_inodes WHERE inumber IN (SELECT inumber FROM t_inodes WHERE itype=32768 AND isize>0 EXCEPT SELECT inumber FROM t_locationinfo);
 inumber2pnfsid | isize | inumber2path 
----------------+-------+--------------
(0 rows)

chimera=> SELECT n.ipnfsid, count(*) from t_inodes n, t_locationinfo l where n.inumber = l.inumber and n.itype=32768 group by n.ipnfsid having count(*) < 2;
               ipnfsid                | count 
--------------------------------------+-------
 0000C4E1785D56D04CBB98181D8DA2CEE0A2 |     1
(1 row)

chimera=> SELECT n.ipnfsid, count(*) from t_inodes n, t_locationinfo l where n.inumber = l.inumber and n.itype=32768 group by n.ipnfsid having count(*) > 2;
 ipnfsid | count 
---------+-------
(0 rows)
```

Looks good to me.

**Comment by alrossi** [comment]
Committed to master
`8161f08b` - resilience: do simple existence check of replica on pool to avoid dark removes

with pull requests for 5.0, 4.2, 4.1 and 4.0

I am leaving this issue open until the stable commits.
