### ISSUE TITLE
chimera shell incompatible with enstore extractor

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#4751]
```
[root@fndcatemp1 ~]# chimera
Mar 28, 2019 9:50:58 AM com.hazelcast.config.XmlConfigLocator
INFO: Loading 'hazelcast.xml' from classpath.
WARN  - [131.225.240.89]:5701 [dcache-namespace] [3.11.1] No join method is enabled! Starting standalone.
Exception in thread "main" java.lang.ClassCastException: class org.dcache.chimera.namespace.ChimeraEnstoreStorageInfoExtractor
	at java.lang.Class.asSubclass(Class.java:3404)
	at org.dcache.chimera.cli.Shell.<init>(Shell.java:111)
	at org.dcache.chimera.cli.Shell.main(Shell.java:98)
```

It would seem that between

d9ec1e52f89a85eff860bb8016539d21cb286e9e 

and

db0a2b1490e57125b4b6c3285dab95aab36cc10b

```
Wed Nov 9 16:11:40 2016 +0100

        dcache-chimera: add get AccessLatency and ger RetentionPolicy command to CLI
        ...
```

the original constructor was replaced with:

```
-    public Shell(String url, String user, String password) throws Exception
+    public Shell(String url, String user, String password, String extractor, String accessLatency, String retentionPolicy) throws Exception
     {
+
         fs = FsFactory.createFileSystem(url, user, password);
         pwd = fs.path2inode(path);
+
+
+        Class<? extends ChimeraOsmStorageInfoExtractor> storageInfoExtractor =
+                Class.forName(extractor).asSubclass(ChimeraOsmStorageInfoExtractor.class);
+        Constructor<? extends ChimeraStorageInfoExtractable> constructor = storageInfoExtractor.getConstructor(AccessLatency.class, RetentionPolicy.class);
+
+        this.extractor = (ChimeraStorageInfoExtractable) constructor.newInstance(
+                AccessLatency.getAccessLatency(accessLatency),
+                RetentionPolicy.getRetentionPolicy(retentionPolicy));
     }
```

the enstore extractor subclasses ``ChimeraHsmStorageInfoExtractor``, not ``ChimeraOsmStorageInfoExtractor``

**Comment by alrossi** [comment]
https://rb.dcache.org/r/11640/

**Comment by paulmillar** [comment]
Patch committed and pull requests accepted.
