### ISSUE TITLE
pool sweeper data:  array out of bounds exception when restarting

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#4867]
After restart at Fermi following the application of the LRU patches (9830f2d and d2472e4edc) to the pools, the history and frontend services started to cause SpaceSweeper2 to barf up this exception:

```
17 May 2019 12:39:30 (v-stkendca1816-1) [Frontend-fndca3a PoolDataRequest] Uncaught exception in thread pool-26-thread-4
java.lang.ArrayIndexOutOfBoundsException: -1
        at org.dcache.util.histograms.CountingHistogram.configure(CountingHistogram.java:129) ~[dcache-common-4.2.32-FNAL.jar:4.2.32-FNAL]
        at org.dcache.pool.classic.SpaceSweeper2.getDataObject(SpaceSweeper2.java:322) ~[dcache-core-4.2.32-FNAL.jar:4.2.32-FNAL]
        at org.dcache.pool.classic.SpaceSweeper2.getDataObject(SpaceSweeper2.java:46) ~[dcache-core-4.2.32-FNAL.jar:4.2.32-FNAL]
        at org.dcache.pool.PoolInfoRequestHandler.lambda$messageArrived$2(PoolInfoRequestHandler.java:257) ~[dcache-core-4.2.32-FNAL.jar:4.2.32-FNAL]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
```

My suspicion is that under certain conditions the entry's last access timestamp could end up slightly larger than "now", in which case we get a negative value here:

```
List<Double> fileLifetime = new ArrayList<>();

        for (PnfsId id : list) {
            try {
                CacheEntry entry = _repository.getEntry(id);
                Long lvalue = now - entry.getLastAccessTime();  <<<<<<<<<<<<<<<<<<<<<<
                fileLifetime.add(lvalue.doubleValue());
            } catch (FileNotInCacheException e) {
                // Ignored
            } catch (CacheException e) {
                // Continue trying
            }
        }
```
Quick check run in IntelliJ:

```
   public static void main(String[] args) {
        try {
            List<Double> fileLifetime = new ArrayList<>();
            fileLifetime.add(-11.0);
            CountingHistogram histogram = SweeperData.createLastAccessHistogram();
            histogram.setData(fileLifetime);
            histogram.configure();
        } catch (ArrayIndexOutOfBoundsException e) {
            e.printStackTrace();
        }
    }
```
gives:
```
java.lang.ArrayIndexOutOfBoundsException: -1
	at org.dcache.util.histograms.CountingHistogram.configure(CountingHistogram.java:129)
	at org.dcache.pool.classic.SpaceSweeper2.main(SpaceSweeper2.java:333)
```

which is comparable to the trace above.

**Comment by alrossi** [comment]
What puzzles me is why it continues to happen on each refresh.  

Also, there are a bunch of ArrayIndexOutOfBoundsException null.

So maybe the values being added are null as well.

**Comment by alrossi** [comment]
TESTING.

1.   Created unit test using the sweeper ls -l output of one of the failing pools.

```
Well, now I'm really stumped.   Here's what I just did.  1.  sweeper ls -l on v-stkendca1815-3 to a local file
2.  awk '{print $5}' of that file to list of last accessed
3.  imported last accessed into commons/src/test/resources
4.  added junit test to CountingHistograms that uses that data, converting it like Sweeper code:

```private void givenFilelifetimeValuesFromSweeperLs() throws Exception {
        List<Double> fileLifetime = new ArrayList<>();
        InputStream stream = this.getClass()
                                 .getClassLoader()
                                 .getResourceAsStream(LAST_ACCESS);
        BufferedReader r = new BufferedReader(new InputStreamReader(stream));
        Long now = System.currentTimeMillis();
        while (true) {
            String timestamp = r.readLine();
            if (timestamp == null) {
                break;
            }
            Date d = DATE_FORMAT.parse(timestamp);
            Long lvalue = now - d.toInstant().toEpochMilli();
            fileLifetime.add(lvalue.doubleValue());
        }
        model.setData(fileLifetime);
    }```
5.  ran the test.

No errors.  Histogram prints out fine with values that look reasonable.
```

**Comment by alrossi** [comment]
TESTING.

Scanned all pools with ```show pinboard```, grepping for the ArrayIndex exception.  Collected names of pools, looped over them, downloading the result of sweeper ls -l.

Then ran ad hoc main:
```
public static void main(String[] args) {
        DateFormat format = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
        File[] files = new File("/Users/arossi/Desktop/filelifetime")
                        .listFiles((f) -> f.getName().endsWith(".txt"));
        List<Double> fileLifetime;
        long now;

        for (int i = 0; i < files.length; ++i) {
            fileLifetime  = new ArrayList<>();
            try (BufferedReader r = new BufferedReader(new FileReader(files[i]))) {
                now = System.currentTimeMillis();
                while (true) {
                    String line = r.readLine();
                    if (line == null) {
                        break;
                    }
                    line = line.trim();
                    Date d;
                    if (line.isEmpty()) {
                        d = new Date(now);
                    } else {
                        int lastSpace = line.lastIndexOf(" ");
                        String timestamp = line.substring(lastSpace + 1);
                        d = format.parse(timestamp);
                    }
                    Long lvalue = now - d.toInstant().toEpochMilli();
                    fileLifetime.add(lvalue.doubleValue());
                }
                CountingHistogram histogram = SweeperData.createLastAccessHistogram();
                histogram.setData(fileLifetime);
                histogram.configure();
                System.out.println(Formats.field(String.valueOf(i), 3, Formats.RIGHT) +
                                                   ": " + files[i].getName() + " succeeded.");
            } catch (Exception e) {
                System.err.println(Formats.field(String.valueOf(i), 3, Formats.RIGHT) +
                                                   ": " + files[i].getName() + " failed.");
                e.printStackTrace();
            }
        }
    }
```

No errors.

**Comment by alrossi** [comment]
TESTING.

Deployed master (with the atime fixes), plus small logging output inside the getDataObject() method in Sweeper.

Made all pools shared between volatile and resilient groups, so sweeper data universalized.

Started a number of processes to populate with 1-byte files.

Monitoring results.   I can do the RESTful (curl) call on histograms/files without errors.  I also see the File Lifetime graphs beginning to populate.

**Comment by alrossi** [comment]
The above is with master.  I will retry it with 4.2 after.

**Comment by alrossi** [comment]
I'm afraid, at this point, that the only way to get to the bottom of this is to redeploy a patched version of the sweeper and counting histogram with logging on at least one of those pools.

**Comment by alrossi** [comment]
Posted https://rb.dcache.org/r/11751/

This may or may not resolve this issue, but the patch in itself is necessary.
