### ISSUE TITLE
PinManager: "bulk ls" gives NullPointerException (5.1 snapshot)

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#4876]
Dear dCache devs,

I get this when doing `bulk ls` in the PinManager.

```
[dolphin12] (PinManager@utilityDomain) admin > bulk ls
Command 'bulk ls' triggered a bug (java.lang.NullPointerException); the service log file contains additional information. Please contact support@dcache.org.
```

Probably there are no bulk jobs, could that have something to do with it?

In the log:

```
24 May 2019 10:28:41 (PinManager) [admin] Command failed due to a bug, please contact support@dcache.org.
dmg.util.CommandPanicException: (1) Command failed: java.lang.NullPointerException
	at org.dcache.util.cli.AnnotatedCommandExecutor.execute(AnnotatedCommandExecutor.java:156)
	at dmg.cells.nucleus.CellAdapter.executeCommand(CellAdapter.java:239)
	at org.dcache.cells.UniversalSpringCell.executeCommand(UniversalSpringCell.java:195)
	at dmg.cells.nucleus.CellAdapter$1.doExecute(CellAdapter.java:105)
	at org.dcache.util.cli.CommandInterpreter.command(CommandInterpreter.java:129)
	at dmg.cells.nucleus.CellAdapter$1.command(CellAdapter.java:122)
	at dmg.cells.nucleus.CellAdapter.command(CellAdapter.java:224)
	at dmg.cells.nucleus.CellAdapter.executeLocalCommand(CellAdapter.java:916)
	at dmg.cells.nucleus.CellAdapter.messageArrived(CellAdapter.java:856)
	at dmg.cells.nucleus.CellNucleus$DeliverMessageTask.run(CellNucleus.java:1211)
	at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:251)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$4(CellNucleus.java:747)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.dcache.pinmanager.PinManagerCLI$BulkListCommand.call(PinManagerCLI.java:329)
	at org.dcache.pinmanager.PinManagerCLI$BulkListCommand.call(PinManagerCLI.java:318)
	at org.dcache.util.cli.AnnotatedCommandExecutor.execute(AnnotatedCommandExecutor.java:145)
	... 14 common frames omitted
```

Cheers,
Onno

**Comment by onnozweers** [comment]
Oh it's a duplicate of #3998

**Comment by paulmillar** [comment]
Thanks for reporting this, Onno.
The bug is trivial to fix; patch is currently under code review.

**Comment by onnozweers** [comment]
Thanks Paul!
