### ISSUE TITLE
webdav: Downloading file fail when a role is asserted

### ISSUE THREAD

**Issue by femiadeyemi** [dCache/dcache#4878]
When a known user assert a role and try to download a file, this result to an internal server error. This was first reported here: https://github.com/dCache/dcache-view/issues/159 and the same error can be reproduce by using curl.

The log file contains the following error trace:
```
[door:WebDAV-S-Olufemis-MacBook-Pro@dCacheDomain:AAWJ21hIIxg] Internal server error
java.lang.NullPointerException: null
	at org.dcache.webdav.DcacheResourceFactory.initializeTransfer(DcacheResourceFactory.java:1339)
	at org.dcache.webdav.DcacheResourceFactory.access$400(DcacheResourceFactory.java:140)
	at org.dcache.webdav.DcacheResourceFactory$HttpTransfer.<init>(DcacheResourceFactory.java:1470)
	at org.dcache.webdav.DcacheResourceFactory$ReadTransfer.<init>(DcacheResourceFactory.java:1544)
	at org.dcache.webdav.DcacheResourceFactory.beginRead(DcacheResourceFactory.java:1135)
	at org.dcache.webdav.DcacheResourceFactory.readFile(DcacheResourceFactory.java:837)
	at org.dcache.webdav.DcacheFileResource.sendContent(DcacheFileResource.java:118)
	at io.milton.http.entity.GetableResourceEntity.write(GetableResourceEntity.java:71)
	at io.milton.http.entity.DefaultEntityTransport.sendResponseEntity(DefaultEntityTransport.java:47)
	at io.milton.http.HttpManager.sendResponseEntity(HttpManager.java:115)
	at org.dcache.webdav.DcacheStandardFilter.process(DcacheStandardFilter.java:56)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at org.dcache.webdav.transfer.CopyFilter.process(CopyFilter.java:301)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at org.dcache.webdav.MiltonHandler.handle(MiltonHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.dcache.http.AuthenticationHandler.access$101(AuthenticationHandler.java:63)
	at org.dcache.http.AuthenticationHandler.lambda$handle$0(AuthenticationHandler.java:162)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at org.dcache.http.AuthenticationHandler.handle(AuthenticationHandler.java:160)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.dcache.webdav.LoggingHandler.handle(LoggingHandler.java:43)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by paulmillar** [comment]
Which version of dCache generated this stack-trace?

**Comment by femiadeyemi** [comment]
> Which version of dCache generated this stack-trace?
The master.
