### ISSUE TITLE
Stacktrace in Log

### ISSUE THREAD

**Issue by mksahakyan** [dCache/dcache#5359]
16 Mar 2020 15:47:15 (Frontend-release-6-1) [] Uncaught exception in thread pool-55-thread-56
java.lang.NullPointerException: Cannot merge statistics, metadata object was null.
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:900)
        at org.dcache.util.histograms.HistogramMetadata.mergeStatistics(HistogramMetadata.java:179)
        at org.dcache.util.collector.pools.PoolInfoCollectorUtils.mergeLastAccess(PoolInfoCollectorUtils.java:333)
        at org.dcache.restful.util.pool.PoolHistoriesHandler.getAggregateFileLifetime(PoolHistoriesHandler.java:193)
        at org.dcache.restful.util.pool.PoolHistoriesHandler.update(PoolHistoriesHandler.java:265)
        at org.dcache.util.collector.pools.PoolInfoAggregator.lambda$aggregateDataForPoolGroups$0(PoolInfoAggregator.java:100)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1675)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.dcache.util.collector.pools.PoolInfoAggregator.aggregateDataForPoolGroups(PoolInfoAggregator.java:95)
        at org.dcache.restful.util.pool.PoolDataRequestProcessor.postProcess(PoolDataRequestProcessor.java:105)
        at org.dcache.util.collector.RequestFutureProcessor.waitUntilFinished(RequestFutureProcessor.java:233)
        at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:251)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by alrossi** [comment]
Ah, the creepy-crawly histogram NPE.   Like whack-o-mole ...

**Comment by femiadeyemi** [comment]
It seem Prometheus (at least the frontend part) is broken. The following request:
```
curl -X GET "https://prometheus.desy.de:3880/api/v1/namespace/%2F?children=true&locality=false&qos=false" -H "accept: application/json"
```

returned the following response:
```
{
  "errors": [
    {
      "message": "HTTP 500 Internal Server Error",
      "status": "500"
    }
  ]
}
```

Is this stacktrace the cause?

**Comment by alrossi** [comment]
I wouldn't think so.  The stack trace is from the periodic collector for pool histograms.  Why would that affect the namespace API?  Can you do anything with the frontend?

**Comment by alrossi** [comment]
See #5360

**Comment by paulmillar** [comment]
@femiadeyemi No, the problem you described is (now) reported here #5360.  This bug should be unrelated  to the symptoms you describe.

**Comment by alrossi** [comment]
I'm fixing this one now as well ...

**Comment by alrossi** [comment]
https://rb.dcache.org/r/12264/
