### ISSUE TITLE
nfs door tries to kill mover twice

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#5411]
The NFS door kills the mover associated with the transfer twice: once then layout return is called and second time when file is closed. Though this in general not a problem, in addition to extra message errors, like:

```
21 Apr 2020 12:29:30 [dcache-photon14-08-2156] [NFS-dcache-se-photon04 PoolMoverKill] Killing mover 67108869: killed by door: returning layout
21 Apr 2020 12:29:30 [dcache-photon14-08-2156] [NFS-dcache-se-photon04 PoolMoverKill] java.util.NoSuchElementException: Job 67108869 not found
```

can be triggered.

**Comment by kofemann** [comment]
A possible effect on the pool:

```16 Mai 2020 00:50:52 (dcache-desy15-08) [door:nfs4-afs@dcache-door-desy01_nfs4wnDomain:AAWltZ68FFg nfs4-afs PoolAcceptFile 000052FFD1C3A9CF482DBBE5ED6687006A81] Transfer failed in post-processing. Please report this bug to support@dcache.org.
java.lang.IllegalStateException: Handle is closed
	at org.dcache.pool.repository.v5.WriteHandleImpl.close(WriteHandleImpl.java:346)
	at org.dcache.pool.classic.DefaultPostTransferService.lambda$execute$1(DefaultPostTransferService.java:118)
	at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:31)
	at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:149)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)


```
