### ISSUE TITLE
NullPointerException in PnfsManager doing PnfsListDirectory

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#5460]
Dear dCache devs,

In our PnfsManager log we see NullPointerExceptions like these: 

```
25 Jun 2020 11:41:59 (PnfsManager) [door:webdav2880-hake15@webdav2880-hake15Domain:AAWo5WdL/mA webdav2880-hake15 PnfsListDirectory] java.lang.NullPointerException
java.lang.NullPointerException: null
	at org.dcache.chimera.namespace.ChimeraHsmStorageInfoExtractor.getAccessLatency(ChimeraHsmStorageInfoExtractor.java:75)
	at org.dcache.chimera.namespace.ChimeraNameSpaceProvider.getFileAttributes(ChimeraNameSpaceProvider.java:909)
	at org.dcache.chimera.namespace.ChimeraNameSpaceProvider.list(ChimeraNameSpaceProvider.java:1202)
	at diskCacheV111.namespace.ForwardingNameSpaceProvider.list(ForwardingNameSpaceProvider.java:177)
	at diskCacheV111.namespace.MonitoringNameSpaceProvider.list(MonitoringNameSpaceProvider.java:308)
	at diskCacheV111.namespace.PnfsManagerV3.listDirectory(PnfsManagerV3.java:1550)
	at diskCacheV111.namespace.PnfsManagerV3.processMessageTransactionally_aroundBody4(PnfsManagerV3.java:1736)
	at diskCacheV111.namespace.PnfsManagerV3$AjcClosure5.run(PnfsManagerV3.java:1)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:66)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:72)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:70)
	at diskCacheV111.namespace.PnfsManagerV3.processMessageTransactionally(PnfsManagerV3.java:1709)
	at diskCacheV111.namespace.PnfsManagerV3.processPnfsMessage(PnfsManagerV3.java:1680)
	at diskCacheV111.namespace.PnfsManagerV3$ProcessThread.run(PnfsManagerV3.java:1596)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Related part in the webdav door log:

```
25 Jun 2020 11:41:59 (webdav2880-hake15) [door:webdav2880-hake15@webdav2880-hake15Domain:AAWo5WdL/mA] Listing of /pnfs/grid.sara.nl/data/projects.nl/eecolidar/01_Escience/ALS/Netherlands/ahn3_current/ahn3_current_TOP10NL_ud20200323_targets_veg incomplete: 
25 Jun 2020 11:42:46 (webdav2880-hake15) [door:webdav2880-hake15@webdav2880-hake15Domain:AAWo5V911EA] Internal server error: org.dcache.webdav.WebDavException: No redirect from mover on pool PoolName=hare13_ecolidardisk PoolAddress=hare13_ecolidardisk@hare13_ecolidardiskDomain after 3 min
```

We're running 6.0.16.

Any idea what could cause this? We also see queueing of directory listings; could that have something to do with it?

Kind regards,
Onno

**Comment by paulmillar** [comment]
Hi Onno,

Could you check whether files were being deleted from this directory while the listing was being generated?

Unless I'm missing something, this bug can only be triggered if the directory listing contains a file (i.e., a non-directory) item that does not have a parent directory.  Yet, in order to be part of the listing, it must have at least one parent (hard links have multiple parents).

Therefore, the most likely scenario I can think of is that the initial list of file names was generated and, while collecting the information about these files, one of the files was deleted.

Cheers,
Paul.
