### ISSUE TITLE
NFS mount issue with DiskLimitException on 6.2

### ISSUE THREAD

**Issue by ageorget** [dCache/dcache#5810]
Hi,

After upgrading from 5.2 to 6.2.15, I'm not able to mount NFS anymore.
I'm getting this error on every NFS door : 
```

25 Mar 2021 12:16:19 (nfsv41) [] Unhandled exception:
com.sleepycat.je.DiskLimitException: (JE 7.5.11) Disk usage is not within je.maxDisk or je.freeDisk limits and write operations are prohibited: maxDiskLimit=0 freeDiskLimit=5,368,709,120 adjustedMaxDiskLimit=0 maxDiskOverage=0 freeDiskShortage=4,148,953,088 diskFreeSpace=1,219,756,032 availableLogSize=-4,148,953,088 totalLogSize=1,647 activeLogSize=1,647 reservedLogSize=0 protectedLogSize=0 protectedLogSizeMap={}
        at com.sleepycat.je.Cursor.checkUpdatesAllowed(Cursor.java:5337)
        at com.sleepycat.je.Cursor.checkUpdatesAllowed(Cursor.java:5314)
        at com.sleepycat.je.Cursor.putInternal(Cursor.java:2410)
        at com.sleepycat.je.Cursor.putInternal(Cursor.java:830)
        at com.sleepycat.je.Database.put(Database.java:1603)
        at com.sleepycat.je.Database.put(Database.java:1656)
        at org.dcache.nfs.v4.BerkeleyDBClientStore.addClient(BerkeleyDBClientStore.java:165)
        at org.dcache.nfs.v4.NFSv4StateHandler.addClient(NFSv4StateHandler.java:144)
        at org.dcache.nfs.v4.NFSv4StateHandler.createClient(NFSv4StateHandler.java:266)
        at org.dcache.nfs.v4.OperationEXCHANGE_ID.process(OperationEXCHANGE_ID.java:209)
        at org.dcache.chimera.nfsv41.door.DoorOperationFactory$2.lambda$process$0(DoorOperationFactory.java:231)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
        at org.dcache.chimera.nfsv41.door.DoorOperationFactory$2.process(DoorOperationFactory.java:213)
        at org.dcache.nfs.v4.AbstractOperationExecutor.execute(AbstractOperationExecutor.java:58)
        at org.dcache.chimera.nfsv41.common.StatsDecoratedOperationExecutor.execute(StatsDecoratedOperationExecutor.java:57)
        at org.dcache.nfs.v4.NFSServerV41.NFSPROC4_COMPOUND_4(NFSServerV41.java:188)
        at org.dcache.nfs.v4.xdr.nfs4_prot_NFS4_PROGRAM_ServerStub.dispatchOncRpcCall(nfs4_prot_NFS4_PROGRAM_ServerStub.java:48)
        at org.dcache.oncrpc4j.rpc.RpcDispatcher$1.run(RpcDispatcher.java:110)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
```
sudo mount -vvv localhost:/ /pnfs
mount.nfs: timeout set for Thu Mar 25 13:27:33 2021
mount.nfs: trying text-based options 'vers=4.1,addr=127.0.0.1,clientaddr=127.0.0.1'
mount.nfs: mount(2): Input/output error
mount.nfs: mount system call failed
```

I don't find anything in the release notes except this commit adding the property je.freeDisk https://github.com/dcache/dcache/commit/559746c7869f8c6401911368b7f8b6fff575a4e2
Something changed in 6.2 concerning NFS mount?

Best,
Adrien

**Comment by mksahakyan** [comment]
Hi Adrien, 

could you please send the pool configuration file, where you should have something similar: 

pool.plugins.meta.db! je.freeDisk =0 
pool.plugins.meta.db!je.checkpointer.wakeupInterval=60 s 
.... 

thanks 
Marina 


From: "ageorget" ***@***.***> 
To: "dCache/dcache" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Sent: Thursday, 25 March, 2021 12:36:11 
Subject: [dCache/dcache] NFS mount issue with DiskLimitException on 6.2 (#5810) 





Hi, 

After upgrading from 5.2 to 6.2.15, I'm not able to mount NFS anymore. 
I'm getting this error on every NFS door : 
25 Mar 2021 12:16:19 (nfsv41) [] Unhandled exception:
com.sleepycat.je.DiskLimitException: (JE 7.5.11) Disk usage is not within je.maxDisk or je.freeDisk limits and write operations are prohibited: maxDiskLimit=0 freeDiskLimit=5,368,709,120 adjustedMaxDiskLimit=0 maxDiskOverage=0 freeDiskShortage=4,148,953,088 diskFreeSpace=1,219,756,032 availableLogSize=-4,148,953,088 totalLogSize=1,647 activeLogSize=1,647 reservedLogSize=0 protectedLogSize=0 protectedLogSizeMap={}
        at com.sleepycat.je.Cursor.checkUpdatesAllowed(Cursor.java:5337)
        at com.sleepycat.je.Cursor.checkUpdatesAllowed(Cursor.java:5314)
        at com.sleepycat.je.Cursor.putInternal(Cursor.java:2410)
        at com.sleepycat.je.Cursor.putInternal(Cursor.java:830)
        at com.sleepycat.je.Database.put(Database.java:1603)
        at com.sleepycat.je.Database.put(Database.java:1656)
        at org.dcache.nfs.v4.BerkeleyDBClientStore.addClient(BerkeleyDBClientStore.java:165)
        at org.dcache.nfs.v4.NFSv4StateHandler.addClient(NFSv4StateHandler.java:144)
        at org.dcache.nfs.v4.NFSv4StateHandler.createClient(NFSv4StateHandler.java:266)
        at org.dcache.nfs.v4.OperationEXCHANGE_ID.process(OperationEXCHANGE_ID.java:209)
        at org.dcache.chimera.nfsv41.door.DoorOperationFactory$2.lambda$process$0(DoorOperationFactory.java:231)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
        at org.dcache.chimera.nfsv41.door.DoorOperationFactory$2.process(DoorOperationFactory.java:213)
        at org.dcache.nfs.v4.AbstractOperationExecutor.execute(AbstractOperationExecutor.java:58)
        at org.dcache.chimera.nfsv41.common.StatsDecoratedOperationExecutor.execute(StatsDecoratedOperationExecutor.java:57)
        at org.dcache.nfs.v4.NFSServerV41.NFSPROC4_COMPOUND_4(NFSServerV41.java:188)
        at org.dcache.nfs.v4.xdr.nfs4_prot_NFS4_PROGRAM_ServerStub.dispatchOncRpcCall(nfs4_prot_NFS4_PROGRAM_ServerStub.java:48)
        at org.dcache.oncrpc4j.rpc.RpcDispatcher$1.run(RpcDispatcher.java:110)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834) 


I don't find anything in the release notes except this commit adding the property je.freeDisk [ https://github.com/dCache/dcache/commit/559746c7869f8c6401911368b7f8b6fff575a4e2 | 559746c ] 
Something changed in 6.2 concerning NFS mount? 

Best, 
Adrien

**Comment by ageorget** [comment]
Hi Marina,

`pool.plugins.meta.db!je.freeDisk = 0` is the default value set in `/usr/share/dcache/defaults/pool.properties`
I can't find the other one `pool.plugins.meta.db!je.checkpointer.wakeupInterval`

I just set `pool.plugins.meta=org.dcache.pool.repository.meta.db.BerkeleyDBMetaDataRepository` in my dcache.conf

Adrien

**Comment by mksahakyan** [comment]
Hi Adrien, 




your config files are fine, for now there is an issue with the default client Berkeley 

DB, it is required to have 5MB available space. We will fix this asap. 







But for now you can try to change the default clientDb location. 


nfs.clientdb.location = ${dcache.paths.nfs} 
dcache.paths.nfs =/var/lib/dcache/nfs 



cheers 

Marina

**Comment by ageorget** [comment]
Thanks Marina, it works by changing the default nfs path.
Btw it requires 5GB available space, not 5MB.

Adrien
