### ISSUE TITLE
exception in  org.dcache.chimera.FsSqlDriver#updateFsStat with hsqldb

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#5938]
Since commit a63e6030a0

```
31 May 2021 12:46:08 (PnfsManager) [] Thread Thread[pool-8-thread-1,5,PnfsManager-threads] died
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [UPDATE t_fstat SET iusedFiles = t.usedFiles, iusedSpace = t.usedSpace FROM (SELECT count(*) AS usedFiles, SUM(isize) AS usedSpace FROM t_inodes WHERE itype=32768) t]; nested exception is java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: T.USEDFILES
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:93)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:388)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:523)
	at org.dcache.chimera.FsSqlDriver.updateFsStat(FsSqlDriver.java:161)
	at org.dcache.chimera.JdbcFs.updateFsStat(JdbcFs.java:1335)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.dcache.commons.stats.MonitoringProxy.invoke(MonitoringProxy.java:54)
	at com.sun.proxy.$Proxy33.updateFsStat(Unknown Source)
	at org.dcache.chimera.namespace.ChimeraNameSpaceProvider.updateFsStat(ChimeraNameSpaceProvider.java:1613)
	at diskCacheV111.namespace.ForwardingNameSpaceProvider.updateFsStat(ForwardingNameSpaceProvider.java:235)
	at diskCacheV111.namespace.PnfsManagerV3.updateFsStat(PnfsManagerV3.java:2724)
	at diskCacheV111.namespace.PnfsManagerV3$1.run(PnfsManagerV3.java:427)
	at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:31)
	at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:149)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: T.USEDFILES
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.executeUpdate(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120)
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:511)
	at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:508)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:376)
	... 21 common frames omitted
Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: T.USEDFILES
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.ExpressionColumn.checkColumnsResolved(Unknown Source)
	at org.hsqldb.ParserDML.resolveUpdateExpressions(Unknown Source)
	at org.hsqldb.ParserDML.compileUpdateStatement(Unknown Source)
	at org.hsqldb.ParserCommand.compilePart(Unknown Source)
	at org.hsqldb.ParserCommand.compileStatements(Unknown Source)
	at org.hsqldb.Session.executeDirectStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 28 common frames omitted
```

**Comment by paulmillar** [comment]
Similar problem found when testing with system-test:

```
02 Jun 2021 10:01:46 (PnfsManager) [] Thread Thread[pool-8-thread-1,5,PnfsManager-threads] died
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [UPDATE t_fstat SET iusedFiles = t.usedFiles, iusedSpace = t.usedSpace FROM (SELECT count(*) AS usedFiles, SUM(isize) AS usedSpace FROM t_inodes WHERE itype=32768) t]; nested exception is java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: T.USEDFILES
        at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:93)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:388)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:523)
        at org.dcache.chimera.FsSqlDriver.updateFsStat(FsSqlDriver.java:161)
        at org.dcache.chimera.JdbcFs.updateFsStat(JdbcFs.java:1335)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.dcache.commons.stats.MonitoringProxy.invoke(MonitoringProxy.java:54)
        at com.sun.proxy.$Proxy33.updateFsStat(Unknown Source)
        at org.dcache.chimera.namespace.ChimeraNameSpaceProvider.updateFsStat(ChimeraNameSpaceProvider.java:1613)
        at diskCacheV111.namespace.ForwardingNameSpaceProvider.updateFsStat(ForwardingNameSpaceProvider.java:235)
        at diskCacheV111.namespace.PnfsManagerV3.updateFsStat(PnfsManagerV3.java:2724)
        at diskCacheV111.namespace.PnfsManagerV3$1.run(PnfsManagerV3.java:427)
        at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:31)
        at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:149)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: T.USEDFILES
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
        at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
        at org.hsqldb.jdbc.JDBCStatement.executeUpdate(Unknown Source)
        at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120)
        at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
        at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:511)
        at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:508)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:376)
        ... 21 common frames omitted
Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: T.USEDFILES
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.ExpressionColumn.checkColumnsResolved(Unknown Source)
        at org.hsqldb.ParserDML.resolveUpdateExpressions(Unknown Source)
        at org.hsqldb.ParserDML.compileUpdateStatement(Unknown Source)
        at org.hsqldb.ParserCommand.compilePart(Unknown Source)
        at org.hsqldb.ParserCommand.compileStatements(Unknown Source)
        at org.hsqldb.Session.executeDirectStatement(Unknown Source)
        at org.hsqldb.Session.execute(Unknown Source)
        ... 28 common frames omitted
```

**Comment by DmitryLitvintsev** [comment]
So. The issue is that HSQL does not support this SQL syntax.

**Comment by paulmillar** [comment]
Yup, looks like it.

**Comment by DmitryLitvintsev** [comment]
https://rb.dcache.org/r/13057/

**Comment by DmitryLitvintsev** [comment]
https://github.com/dCache/dcache/commit/f64a88005f9f5bb677e71002286c74fdadc4c0b2

**Comment by kofemann** [comment]
Works for me.
