### ISSUE TITLE
Telemetry collector refuses connections

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#5942]
Dear dCache devs,

It appears the telemetry collector refuses connections:

```
04 Jun 2021 12:14:58 (Telemetry) [] Sending data to https://stats.dcache.org/collector failed, caused by: 
java.net.ConnectException: Connection refused
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:561)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
        at org.dcache.telemetry.SendData.sendData(SendData.java:101)
        at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:31)
        at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:149)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection$ConnectEvent.handle(PlainHttpConnection.java:128)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:957)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:912)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:912)
```

Connecting from:

```
dolphin12.grid.surfsara.nl has address 145.100.33.46
dolphin12.grid.surfsara.nl has IPv6 address 2001:610:108:203a::1:46
```

If I go to https://stats.dcache.org/ with a browser, it says "unable to connect."

Is it broken?

Cheers,
Onno

**Comment by kofemann** [comment]
Hi Onno,

I am afraid that our network configuration changes have triggered this.

Thanks for reporting.

**Comment by paulmillar** [comment]
Hi Onno,

Is the problem still present?

I just tried and I can connect to that endpoint from my home ISP.

Cheers,
Paul.

**Comment by onnozweers** [comment]
Hi Paul,

I can connect to the collector now. With the browser, it says "ok". Also with curl from dolphin12:
```
[root@dolphin12 ~]# curl https://stats.dcache.org/collector
ok[root@dolphin12 ~]
```
At 13:14, the telemetry cell could connect to the collector but got a 502 error. Before that, it was only "connection refused". So I guess there is progress. I see no other connection attempt being logged, also after a restart of the domain.

**Comment by onnozweers** [comment]
I set logging level to debug, restarted, and then:

```
07 Jun 2021 16:49:47 (Telemetry) [] Information successfully sent to https://stats.dcache.org/collector
```

So it seems it works now! Is there any place we can see the results? 😀

**Comment by kofemann** [comment]
Sorry, I forgot to update the issue. Svenja fixed it.

-kofemann
/** caffeinated mutations of the core personality */

**Comment by kofemann** [comment]
@onnozweers The entries are visible only to us and I can see the updates coming from your site.

**Comment by ageorget** [comment]
Hi,
I just want to report that the telemetry collector is refusing connections for weeks now (since November 8th exactly): 

```
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]: 25 Jan 2023 15:48:22 (Telemetry) [] Sending data to https://stats.dcache.org/collector failed, caused by:
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]: java.net.ConnectException: Connection refused
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:561)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at org.dcache.telemetry.SendData.sendData(SendData.java:110)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:28)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:130)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at java.base/java.lang.Thread.run(Thread.java:829)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]: Caused by: java.net.ConnectException: Connection refused
```
Adrien

**Comment by paulmillar** [comment]
Hi @ageorget 

Thanks for reporting this.

However, could you open it as a separate issue, just so we don't conflate the issue that Onno reported with your issue.

Cheers,
Paul.
