### ISSUE TITLE
stacktrace  in webdav door log if p2p not allowed

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#6049]
On attempt to read file that is located on pool which can't be used for read and p2p is not permitted:

```
6 Sep 2021 12:29:22 (WebDAV-S-nairi) [door:WebDAV-S-nairi@dCacheDomain:AAXLUR9VmDA] Internal server error: org.dcache.webdav.WebDavException: Pool to pool not permitted
06 Sep 2021 12:29:22 (WebDAV-S-nairi) [] /tape/file.txt
java.lang.IllegalStateException: SendCallback@2ae22a8c[CLOSED][i=null,cb=org.eclipse.jetty.server.HttpChannel$SendCallback@789e79c0]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:218)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:550)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:915)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:987)
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:285)
	at org.eclipse.jetty.server.HttpOutput.complete(HttpOutput.java:515)
	at org.eclipse.jetty.server.Response.completeOutput(Response.java:926)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:538)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:540)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:395)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
dcache version 7.2-snapshot (84b45e6f11)

**Comment by paulmillar** [comment]
Just to mention that this stack-trace looks incomplete. Shouldn't there be something within dCache throwing this exception?

The error message is coming from Poolmanager (RequestContainerV5).

So, it looks like this is being transported back to WebDAV door as IAE, which is being re-thrown as a WebDAV exception.
