### ISSUE TITLE
Gridftp errors 

### ISSUE THREAD

**Issue by cfgamboa** [dCache/dcache#6064]
The following errors have been observed in the BNL dCache doors nodes.
Please let us now if this is right place to report this error stack.

```
[root@dcdoor08 ~]# cat /var/log/dcache/gridftp-dcdoor08Domain.log 
22 Sep 2021 03:21:18 (GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA) [door:GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA@gridftp-dcdoor08Domain] Bug detected, please report this to <support@dcache.org>
java.lang.IllegalStateException: Cannot send message with callback in state {} [TERMINATED]
	at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
	at dmg.cells.nucleus.CellNucleus.sendMessage(CellNucleus.java:532)
	at dmg.cells.nucleus.CellAdapter.sendMessage(CellAdapter.java:468)
	at org.dcache.ftp.door.AbstractFtpDoorV1$PerfMarkerTask.run(AbstractFtpDoorV1.java:4344)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
22 Sep 2021 03:21:48 (GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA) [door:GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA@gridftp-dcdoor08Domain] Bug detected, please report this to <support@dcache.org>
java.lang.IllegalStateException: Cannot send message with callback in state {} [TERMINATED]
	at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
	at dmg.cells.nucleus.CellNucleus.sendMessage(CellNucleus.java:532)
	at dmg.cells.nucleus.CellAdapter.sendMessage(CellAdapter.java:468)
	at org.dcache.ftp.door.AbstractFtpDoorV1$PerfMarkerTask.run(AbstractFtpDoorV1.java:4344)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
22 Sep 2021 03:22:18 (GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA) [door:GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA@gridftp-dcdoor08Domain] Bug detected, please report this to <support@dcache.org>
```

**Comment by paulmillar** [comment]
Thanks for reporting this problem.

Could you look in the log files for anything logged before these messages started, with the same transfer ID: `GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA` ?

**Comment by paulmillar** [comment]
There are two problems here:
1. something caused a transfer to abort in an unclean fashion (leaving the perf.marker thread active)
2. the cell somehow died without killing all its threads.

**Comment by cfgamboa** [comment]
Hi Paul,

```
[root@dcdoor08 dcache]# zgrep GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA *|wc -l
41962
```
```
AAXFBGiX_vA@gridftp-dcdoor08Domain] Bug detected, please report this to <support@dcache.org>
gridftp-dcdoor08Domain.log:28 Sep 2021 03:50:25 (GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA) [door:GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA@gridftp-dcdoor08Domain] Bug detected, please report this to <support@dcache.org>
gridftp-dcdoor08Domain.log:28 Sep 2021 03:50:55 (GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA) [door:GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA@gridftp-dcdoor08Domain] Bug detected, please report this to <support@dcache.org>
gridftp-dcdoor08Domain.log:28 Sep 2021 03:51:25 (GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA) [door:GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA@gridftp-dcdoor08Domain] Bug detected, please report this to <support@dcache.org>
gridftp-dcdoor08Domain.log:28 Sep 2021 03:51:55 (GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA) [door:GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA@gridftp-dcdoor08Domain] Bug detected, please report this to <support@dcache.org>
gridftp-dcdoor08Domain.log:28 Sep 2021 03:52:25 (GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA) [door:GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA@gridftp-dcdoor08Domain] Bug detected, please report this to <support@dcache.org>
gridftp-dcdoor08Domain.log:28 Sep 2021 03:52:55 (GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA) [door:GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA@gridftp-dcdoor08Domain] Bug detected, please report this to <support@dcache.org>
gridftp-dcdoor08Domain.log:28 Sep 2021 03:53:25 (GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA) [door:GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA@gridftp-dcdoor08Domain] Bug detected, please report this to <support@dcache.org>
gridftp-dcdoor08Domain.log:28 Sep 2021 03:53:55 (GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA) [door:GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA@gridftp-dcdoor08Domain] Bug detected, please report this to <support@dcache.org>
gridftp-dcdoor08Domain.log:28 Sep 2021 03:54:25 (GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA) [door:GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA@gridftp-dcdoor08Domain] Bug detected, please report this to <support@dcache.org>
gridftp-dcdoor08Domain.log:28 Sep 2021 03:54:55 (GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA) [door:GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA@gridftp-dcdoor08Domain] Bug detected, please report this to <support@dcache.org>
gridftp-dcdoor08Domain.log:28 Sep 2021 03:55:25 (GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA) [door:GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA@gridftp-dcdoor08Domain] Bug detected, please report this to <support@dcache.org>
```

**Comment by paulmillar** [comment]
Could you take another look at the first log entry?

The log entry likely takes up multiple lines and should contain a stack-trace.  This stack-trace is particularly useful information.

Cheers,
Paul.

**Comment by cfgamboa** [comment]
Hello,

```
29 Sep 2021 03:50:26 (GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA) [door:GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA@gridftp-dcdoor08Domain] Bug detected, please report this to <support@dcache.org>
java.lang.IllegalStateException: Cannot send message with callback in state {} [TERMINATED]
	at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
	at dmg.cells.nucleus.CellNucleus.sendMessage(CellNucleus.java:532)
	at dmg.cells.nucleus.CellAdapter.sendMessage(CellAdapter.java:468)
	at org.dcache.ftp.door.AbstractFtpDoorV1$PerfMarkerTask.run(AbstractFtpDoorV1.java:4344)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
29 Sep 2021 03:50:56 (GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA) [door:GFTP-dcdoor08-15ipv6subnet-AAXFBGiX_vA@gridftp-dcdoor08Domain] Bug detected, please report this to <support@dcache.org>
java.lang.IllegalStateException: Cannot send message with callback in state {} [TERMINATED]
```

**Comment by paulmillar** [comment]
OK, just to double-check: this is the first message in the log file with this session id (...`AAXFBGiX_vA`), right?

**Comment by cfgamboa** [comment]
Yes

**Comment by paulmillar** [comment]
Could you check the access log file for this door, looking for all entries with the session ID (...`AAXFBGiX_vA`) ?

If you still have these entries, please copy them into this ticket.

**Comment by cfgamboa** [comment]
No only the ID is logged in the griftp logs

**Comment by paulmillar** [comment]
OK, looking at this some more, what you have reported is inconsistent.

The original log-file entry (in the initial entry of this issue) is dated `22 Sep 2021 03:21:18`.  When I asked for the first log entry with this session ID, you posted an entry dated `29 Sep 2021 03:50:26`.  Perhaps those log files have rotated?

You also mentioned that there are no entries in the access log file regarding this login session.  The only reasonable explanation (that I can think of) is that the access log files have been rotated, and the information has been lost.  This is a real risk, as the access log files are large and aggressively rotated to keep their storage requirements reasonable.

Unfortunately, the information so far is rather limited and I cannot be sure what caused this problem.

Looking at the code, I can see a bug that _could_ have caused this problem.  However, without any further information, I cannot be sure.  I propose that I fix that problem and claim that this solves this issue.  If the problem comes back then we can open a fresh issue.

Does that sound like a reasonable way forward?

**Comment by paulmillar** [comment]
During testing I discovered I was wrong -- the failure mode I imagined does not result in the symptoms you described here.

Right now, I'm at a loss how to proceed without more information: either the original error (which should have been logged in the domain log file) or the access log file.
