### ISSUE TITLE
Unexpected failure during state change notification

### ISSUE THREAD

**Issue by cfgamboa** [dCache/dcache#6066]
More errors of these type are observed in the BNL dCache system.
Please let us know if this information needs to be reported in other system.
dcache-6.2.22-1.noarch

````
22 Sep 2021 03:44:04 (dcdoor08_1) [door:WebDAV2-dcdoor14-2@webdav2-dcdoor14_httpsDomain:AAXMkKHpmNg dc051_10 PoolDeliverFile 0000E81745F9FBA8486A8BFD18CDBDF7B20E] Unexpected failure during state change notification
java.lang.IllegalStateException: Attribute is not defined: STORAGECLASS
	at org.dcache.vehicles.FileAttributes.guard(FileAttributes.java:290)
	at org.dcache.vehicles.FileAttributes.getStorageClass(FileAttributes.java:603)
	at org.dcache.pool.migration.StorageClassFilter.test(StorageClassFilter.java:22)
	at org.dcache.pool.migration.StorageClassFilter.test(StorageClassFilter.java:10)
	at java.base/java.util.function.Predicate.lambda$and$0(Predicate.java:69)
	at java.base/java.util.function.Predicate.lambda$and$0(Predicate.java:69)
	at org.dcache.pool.migration.Job.accept(Job.java:640)
	at org.dcache.pool.migration.Job.stateChanged(Job.java:686)
	at org.dcache.pool.repository.v5.StateChangeListeners.lambda$stateChanged$0(StateChangeListeners.java:69)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by paulmillar** [comment]
Thanks for reporting this problem.

The problem appears to be with a file that a client wrote using the WebDAV door.

Does that correspond you what you know about this file?

Also, do you see this problem with clients writing with any other network protocols (e.g,. GridFTP)?

Cheers,
Paul.

**Comment by cfgamboa** [comment]
Hello @paulmillar for some reason I missed your questions on this old ticket. I am closing it now as I can not see this issue anymore we have upgraded 7.2 release
