### ISSUE TITLE
NPE on gridftp door after Client aborted transfer

### ISSUE THREAD

**Issue by ageorget** [dCache/dcache#6106]
Hi,

I saw many gridftp door stuck these last days with NPE errors in the pinboard log about file aborted by a client but the transfer remains in the door even after 4 days : 

```
08 Oct 2021 19:07:24 [gridftp-ccdcatli275-121625] [door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain] retrieve user=cmsgrid
08 Oct 2021 19:07:24 [gridftp-ccdcatli275-121625] [door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain] retrieve addr=/162.105.151.193:6570
08 Oct 2021 20:02:45 [gridftp-ccdcatli275-io-8] [door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain] java.io.IOException: Connection timed out
08 Oct 2021 20:02:45 [gridftp-ccdcatli275-121680] [door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain] Client aborted transfer, details follow:
    Control channel: remote 162.105.151.193:6570; local 193.48.99.109:2811
    Work-arounds: []
    Client info: scheme=gsiftp;appname="gfal2-util";appver="1.6.0 (gfal2 2.19.2)";
    Transaction: door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain:1633712844084000
    Transfer command: GET path=//pnfs/in2p3.fr/data/cms/disk/data/store/mc/RunIISummer20UL18NanoAODv9/WJetsToLNu_Pt-100To250_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/100000/3C3A4908-C984-8F4B-83DB-9EFA828BAF55.root;pasv;
    Transfer direction: DOWNLOAD
    Transfer started: 2021-10-08 19:07:24.084 (55 min ago)
    Mover started: 2021-10-08 19:46:41.439 (16 min ago)
    Data channel: PASSIVE; mode S; expecting connections from 162.105.151.193:20
    Pool: pool-cms-xferout-li272a (pool-cms-xferout-li272a@ccdcatli272-pool-cms-xferout-li272a-Domain)
    Mover ID: 50497740
    Protocol version: 2
    IP family: INET
    Delayed passive: PASV
    File size: 2647274334 B (2.47 GiB)
    File segment: 0-2647274334
    Passive adapter:
        Transfer mode: S
        Listening on:
            Client: /193.48.99.109:30794
            Pool: /134.158.208.88:33730
        Proxy status: not connected
08 Oct 2021 20:02:45 [gridftp-ccdcatli275-121680] [door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain] Transfer error: 451 Aborting transfer due to session termination
08 Oct 2021 20:02:46 [gridftp-ccdcatli275-io-8] [door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain] Uncaught exception in thread gridftp-ccdcatli275-io-8java.lang.NullPointerException: null
	at org.dcache.ftp.proxy.PassiveConnectionHandler.stopSelectionLoop(PassiveConnectionHandler.java:557)
	at org.dcache.ftp.proxy.PassiveConnectionHandler.close(PassiveConnectionHandler.java:601)
	at org.dcache.ftp.door.AbstractFtpDoorV1.shutdown(AbstractFtpDoorV1.java:1773)
	at diskCacheV111.doors.NettyLineBasedDoor.shutdown(NettyLineBasedDoor.java:271)
	at diskCacheV111.doors.NettyLineBasedDoor.channelInactive(NettyLineBasedDoor.java:313)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.logging.LoggingHandler.channelInactive(LoggingHandler.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at org.dcache.util.CDCThreadFactory.lambda$newThread$0(CDCThreadFactory.java:50)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

```
(gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain) ageorget > info
     User Host  : 162.105.151.193
          User  : cmsgrid
Control channel : remote 162.105.151.193:6570; local 193.48.99.109:2811
   Client info  : scheme=gsiftp;appname="gfal2-util";appver="1.6.0 (gfal2 2.19.2)";
    Local Host  : ccdcacli275.in2p3.fr/134.158.208.88
  Last Command  : GET path=//pnfs/in2p3.fr/data/cms/disk/data/store/mc/RunIISummer20UL18NanoAODv9/WJetsToLNu_Pt-100To250_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/100000/3C3A4908-C984-8F4B-83DB-9EFA828BAF55.root;pasv;
 Command Count  : 19
     I/O Queue  : gridftp
  Work-arounds  : []
gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain;p=GFtp-1;o=3033/0;
```

**Comment by ageorget** [comment]
Hi Paul,

This is what I found for this session in the FTP door's access log : 

```
level=INFO ts=2021-10-08T19:07:16.681+0200 event=org.dcache.ftp.hello session=door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain socket.remote=162.105.151.193:6570 socket.local=193.48.99.109:2811 reply="220 GSI FTP door ready"
level=INFO ts=2021-10-08T19:07:16.950+0200 event=org.dcache.ftp.response session=door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain command="AUTH GSSAPI" reply="334 ADAT must follow"
level=INFO ts=2021-10-08T19:07:17.246+0200 event=org.dcache.ftp.response session=door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain command="ADAT ..." reply="335 ADAT=..."
level=INFO ts=2021-10-08T19:07:17.789+0200 event=org.dcache.ftp.response session=door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain command="ADAT ..." reply="335 ADAT=..."
level=INFO ts=2021-10-08T19:07:18.052+0200 event=org.dcache.ftp.response session=door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain command="ADAT ..." reply="335 ADAT=..."
level=INFO ts=2021-10-08T19:07:18.314+0200 event=org.dcache.ftp.response session=door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain command="ADAT ..." reply="235 OK"
level=INFO ts=2021-10-08T19:07:18.599+0200 event=org.dcache.ftp.response session=door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain command="ENC{USER :globus-mapping:}" user.dn="/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=jixiao/CN=824776/CN=Jie Xiao" user.mapped=3033:119 reply="ENC{200 User :globus-mapping: logged in}"
level=INFO ts=2021-10-08T19:07:18.853+0200 event=org.dcache.ftp.response session=door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain command="ENC{PASS ...}" reply="ENC{200 PASS command successful}"
level=INFO ts=2021-10-08T19:07:19.108+0200 event=org.dcache.ftp.response session=door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain command="ENC{SITE HELP}" reply="ENC{214-The following site-specific commands are supported:\r\nSITE <SP> HELP - Information about SITE commands\r\nSITE <SP> BUFSIZE <SP> <size> - Set network buffer to <size>\r\nSITE <SP> CHKSUM <SP> <value> - Fail upload if ADLER32 checksum isn't <value>\r\nSITE <SP> CHGRP <SP> <group> <SP> <path> - Change group-owner of <path> to group <group>\r\nSITE <SP> CHMOD <SP> <perm> <SP> <path> - Change permission of <path> to octal value <perm>\r\nSITE <SP> CLIENTINFO <SP> <id> - Provide server with information about the client\r\nSITE <SP> SYMLINKFROM <SP> <path> - Register symlink location; SYMLINKTO must follow\r\nSITE <SP> SYMLINKTO <SP> <path> - Create symlink to <path>; SYMLINKFROM must be earlier command\r\nSITE <SP> TASKID <SP> <id> - Provide server with an identifier\r\nSITE <SP> USAGE <SP> [TOKEN <SP> <token> <SP> ] <path>\r\n214 SITE <SP> WHOAMI - Provides the username or uid of the user}"
level=INFO ts=2021-10-08T19:07:19.364+0200 event=org.dcache.ftp.response session=door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain command="ENC{FEAT}" reply="ENC{211-OK\r\n EOF\r\n PARALLEL\r\n MODE-E-PERF\r\n SIZE\r\n SBUF\r\n ERET\r\n ESTO\r\n GETPUT\r\n MDTM\r\n CKSUM ADLER32,MD5,MD4\r\n MODEX\r\n TVFS\r\n MFMT\r\n MFCT\r\n MFF Modify;Create;UNIX.mode;\r\n PASV AllowDelayed\r\n MLSC\r\n MLST Size*;Modify*;Create;Type*;Unique*;Perm*;UNIX.owner*;UNIX.group*;UNIX.uid*;UNIX.gid*;UNIX.mode*;UNIX.ctime;UNIX.atime;\r\n211 End}"
level=INFO ts=2021-10-08T19:07:19.618+0200 event=org.dcache.ftp.response session=door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain command="ENC{SITE CLIENTINFO scheme=gsiftp;appname=\"gfal2-util\";appver=\"1.6.0 (gfal2 2.19.2)\";}" reply="ENC{250 OK}"

level=INFO ts=2021-10-08T19:46:41.420+0200 event=org.dcache.ftp.response session=door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain command="ENC{GET path=//pnfs/in2p3.fr/data/cms/disk/data/store/mc/RunIISummer20UL18NanoAODv9/WJetsToLNu_Pt-100To250_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/100000/3C3A4908-C984-8F4B-83DB-9EFA828BAF55.root;pasv;}" reply="ENC{127 PORT (193,48,99,109,120,74)}"
level=INFO ts=2021-10-08T19:46:41.439+0200 event=org.dcache.ftp.response session=door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain command="ENC{GET path=//pnfs/in2p3.fr/data/cms/disk/data/store/mc/RunIISummer20UL18NanoAODv9/WJetsToLNu_Pt-100To250_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/100000/3C3A4908-C984-8F4B-83DB-9EFA828BAF55.root;pasv;}" reply="ENC{150 Opening BINARY data connection for /pnfs/in2p3.fr/data/cms/disk/data/store/mc/RunIISummer20UL18NanoAODv9/WJetsToLNu_Pt-100To250_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/100000/3C3A4908-C984-8F4B-83DB-9EFA828BAF55.root}"
level=INFO ts=2021-10-08T20:02:45.890+0200 event=org.dcache.ftp.response session=door:gridftp-ccdcatli275-AAXN2mlLGFg@gridftp-ccdcatli275Domain command="ENC{GET path=//pnfs/in2p3.fr/data/cms/disk/data/store/mc/RunIISummer20UL18NanoAODv9/WJetsToLNu_Pt-100To250_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/100000/3C3A4908-C984-8F4B-83DB-9EFA828BAF55.root;pasv;}" reply="ENC{451 Aborting transfer due to session termination}"
```

Cheers,
Adrien
