### ISSUE TITLE
Sweeper plug in doesn't exist...

### ISSUE THREAD

**Issue by DavidHarrimanSCV** [dCache/dcache#6116]
There appears to be an issue for me with the sweeper.  I'm seeing an error in the log regarding the class does not exist.  I'm using the trunk.  Is this a non-issue?  A configuration issue on my side?

Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]: DEBUG [pool1]              Creating shared instance of singleton bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor'
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]: DEBUG [pool1]              Could not find class file for introspecting configuration annotations: ${pool.plugins.sweeper}
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]: java.io.FileNotFoundException: class path resource [${pool/plugins/sweeper}.class] cannot be opened because it does not exist
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:56)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:50)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:123)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at org.springframework.context.annotation.ConfigurationClassUtils.checkConfigurationClassCandidate(ConfigurationClassUtils.java:112)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:282)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:242)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at org.dcache.cells.UniversalSpringCell.createContext(UniversalSpringCell.java:1027)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at org.dcache.cells.UniversalSpringCell.starting(UniversalSpringCell.java:229)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at dmg.cells.nucleus.CellAdapter.prepareStartup(CellAdapter.java:681)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at dmg.cells.nucleus.CellNucleus.doStart(CellNucleus.java:899)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$3(CellNucleus.java:735)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:229)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$2(CellNucleus.java:727)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]:         at java.base/java.lang.Thread.run(Thread.java:829)
Oct 16 20:32:54 dcache-node03.dsh.com dcache@dCacheDomain[15173]: DEBUG [pool1]              Creating shared instance of singleton bean 'org.springframework.context.support.PropertySourcesPlaceholderConfigurer#0'

**Comment by kofemann** [comment]
Hi @DavidHarrimanSCV ,

this is an unfortunate stack trace, that tells you that somthing went wrong during startup. Obviously we have to make it more user friendly. For now, please check the following possibilities: 

- directory `etc/grid-security/certificates` exist
- you have more that 5 GB free space on disk where pool is running
- the `setup` file in the pool directory don't contain invalid commands
- you don't have xroot plugins configured that are not in the class path
- the pool process is able to bind to all required port (dcache.net.lan, dcache.net.wan)
