### ISSUE TITLE
Unable to find address that faces dcqos002.usatlas.bnl.gov/192.12.15.15

### ISSUE THREAD

**Issue by cfgamboa** [dCache/dcache#6171]
Hello,

The following is the trace error for seen in dCache QOS setup

On this setup, the pools interacting with the tape system do not have external connectivity on internal connectivity is enabled. 
The pools interacting with the tape system are dcqos003_1/2/3 

The pools (dcqos003_3) appears to select the external interface of the webdavdoor ( dcqos002.usatlas.bnl.gov/192.12.15.15)
instead of the internal one.

```
21 Oct 2021 06:40:51 (dcqos003_3) [door:WebDAV2-dcqos002-2@webdav2-dcqos002_httpsDomain:AAXO2odKX8A WebDAV2-dcqos002-2 PoolDeliverFile 00007302BEA8121E491AAE14D1F9BEDA230B] Transfer failed: java.net.SocketException: Unable to find address that faces dcqos002.usatlas.bnl.gov/192.12.15.15
21 Oct 2021 06:40:52 (dcqos003_3) [door:WebDAV2-dcqos002-2@webdav2-dcqos002_httpsDomain:AAXO2odVkvA WebDAV2-dcqos002-2 PoolDeliverFile 000045A7C29058234E718280E849D1430B95] Transfer failed: java.net.SocketException: Unable to find address that faces dcqos002.usatlas.bnl.gov/192.12.15.15
21 Oct 2021 06:40:52 (dcqos003_3) [door:WebDAV-dcqos002-2@webdav-dcqos002_httpsDomain:AAXO2odVthg WebDAV-dcqos002-2 PoolDeliverFile 0000C5DF0AB3F8064E4BB107921CA0EB28B5] Transfer failed: java.net.SocketException: Unable to find address that faces dcqos002.usatlas.bnl.gov/192.12.15.15
21 Oct 2021 06:45:51 (dcqos003_3) [door:WebDAV2-dcqos002-2@webdav2-dcqos002_httpsDomain:AAXO2odKX8A WebDAV2-dcqos002-2 PoolDeliverFile 00007302BEA8121E491AAE14D1F9BEDA230B] Transfer failed: No connection from client after 300 seconds. Giving up.
21 Oct 2021 06:45:51 (dcqos003_3) [door:WebDAV2-dcqos002-2@webdav2-dcqos002_httpsDomain:AAXO2odKX8A WebDAV2-dcqos002-2 PoolDeliverFile 00007302BEA8121E491AAE14D1F9BEDA230B] Transfer failed in post-processing. Please report this bug to support@dcache.org.
java.lang.IllegalStateException: Handle is closed
	at org.dcache.pool.repository.v5.ReadHandleImpl.close(ReadHandleImpl.java:71)
	at org.dcache.pool.classic.DefaultPostTransferService.lambda$execute$1(DefaultPostTransferService.java:115)
	at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:31)
	at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:149)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
21 Oct 2021 06:45:52 (dcqos003_3) [door:WebDAV2-dcqos002-2@webdav2-dcqos002_httpsDomain:AAXO2odVkvA WebDAV2-dcqos002-2 PoolDeliverFile 000045A7C29058234E718280E849D1430B95] Transfer failed: No connection from client after 300 seconds. Giving up.
21 Oct 2021 06:45:52 (dcqos003_3) [door:WebDAV2-dcqos002-2@webdav2-dcqos002_httpsDomain:AAXO2odVkvA WebDAV2-dcqos002-2 PoolDeliverFile 000045A7C29058234E718280E849D1430B95] Transfer failed in post-processing. Please report this bug to support@dcache.org.
java.lang.IllegalStateException: Handle is closed
	at org.dcache.pool.repository.v5.ReadHandleImpl.close(ReadHandleImpl.java:71)
	at org.dcache.pool.classic.DefaultPostTransferService.lambda$execute$1(DefaultPostTransferService.java:115)
	at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:31)
	at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:149)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
21 Oct 2021 06:45:52 (dcqos003_3) [door:WebDAV-dcqos002-2@webdav-dcqos002_httpsDomain:AAXO2odVthg WebDAV-dcqos002-2 PoolDeliverFile 0000C5DF0AB3F8064E4BB107921CA0EB28B5] Transfer failed: No connection from client after 300 seconds. Giving up.
21 Oct 2021 06:45:52 (dcqos003_3) [door:WebDAV-dcqos002-2@webdav-dcqos002_httpsDomain:AAXO2odVthg WebDAV-dcqos002-2 PoolDeliverFile 0000C5DF0AB3F8064E4BB107921CA0EB28B5] Transfer failed in post-processing. Please report this bug to support@dcache.org.
java.lang.IllegalStateException: Handle is closed
	at org.dcache.pool.repository.v5.ReadHandleImpl.close(ReadHandleImpl.java:71)
	at org.dcache.pool.classic.DefaultPostTransferService.lambda$execute$1(DefaultPostTransferService.java:115)
	at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:31)
	at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:149)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

The billingdb shows entry as:

General problem: Unable to find address that faces dcqos002.usatlas.bnl.gov/192.12.15.15

Error code 666

**Comment by paulmillar** [comment]
I've included a patch that updates the `java.lang.IllegalStateException: Handle is closed` message to include more information.  This update should be available as part of the next dCache release cycle (7.2.4, 7.1.14, 7.0.23, 6.2.34).

Could you update your pool nodes to this version (or newer) of dCache and try to reproduce the problem?

The additional information should help pinpoint what is causing this problem.

**Comment by paulmillar** [comment]
Unfortunately, dCache v7.2.3 is not a recent enough version of dCache to provide the additional information.

Please upgrade your pool nodes to dCache v7.2.4 (or newer) as soon as is convenient.

This is so that, if the problem does come back, we will have sufficient information to fix it.

Cheers,
Paul.

**Comment by cfgamboa** [comment]
Hi

It seems that by enabling the `webdav.net.internal` to internal interface the issue is not longer observed.

It is not clear to me why the webdav door needs to be specified with the internal net value for traffic as I can see that the door is aware of different interfaces.

```
[dcqos001] (WebDAV-dcqos002-2@webdav-dcqos002_httpsDomain) admin > info
--- cache-login-strategy (Processes mapping requests) ---
gPlazma login cache: CacheStats{hitCount=144, missCount=114, loadSuccessCount=111, loadExceptionCount=0, totalLoadTime=782554163, evictionCount=95}
gPlazma map cache: CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
gPlazma reverse map cache: CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}

--- lb (Registers the door with a LoginBroker) ---
    LoginBroker      : LoginBrokerTopic@local
    Protocol Family  : https
    Protocol Version : 1.1
    Port             : 2881
    Addresses        : [fe80:0:0:0:9a03:9bff:fe04:736/fe80:0:0:0:9a03:9bff:fe04:736, dcqos002.usatlas.bnl.gov/10.42.38.49, dcqos002.usatlas.bnl.gov/2620:0:210:1:0:0:0:f, fe80:0:0:0:9a03:9bff:fe89:e1fe/fe80:0:0:0:9a03:9bff:fe89:e1fe, dcqos002.usatlas.bnl.gov/192.12.15.15]
    Tags             : [cdmi, dcache-view, glue, srm, storage-descriptor]
    Root             : /
    Read paths       : [/]
```

All the best,
Carlos

**Comment by paulmillar** [comment]
OK, good.

I think we can close this issue, right?

Cheers,
Paul.

**Comment by cfgamboa** [comment]
HI Paul,

Thank you, indeed please close this issue.

All the best,
Carlos

**Comment by cfgamboa** [comment]
Hello @paulmillar 

Unfortunately it appears that this issue came back.

I am running 7.2.15 on QOS instance.

At the webdav door
```
04 May 2022 20:14:36 (WebDAV-dcqos002-2) [door:WebDAV-dcqos002-2@webdav-dcqos002_httpsDomain:AAXeOKCLo1A] Internal server error: org.dcache.webdav.WebDavException: CacheException(rc=666;msg=General problem: Unable to find address that faces dcqos002.usatlas.bnl.gov/192.12.15.15)
```
The pool in on 10.42.38.0/24 only
```
04 May 2022 20:14:36 (dcqos003_6) [door:WebDAV-dcqos002-2@webdav-dcqos002_httpsDomain:AAXeOKCLo1A dcqos002_24 PoolDeliverFile 0000F6FAA2B8BA8C459E80B0A9E56E7BB243] Transfer failed: java.net.SocketException: Unable to find address that faces dcqos002.usatlas.bnl.gov/192.12.15.15
```

The Dav configuration has
```
webdav.net.internal=10.42.38.49
```

```
[root@dcqos002 ~]# getent hosts $(uname -n) | awk '{print $1}'
2620:0:210:1::f

```

So it seems that this BUG came back?


All the best,
Carlos

**Comment by cfgamboa** [comment]
@paulmillar this is not related to this issue ( webdav being the client) but other. So this ticket should remain closed.

**Comment by paulmillar** [comment]
Thanks for the clarification @cfgamboa.

In which issue should we discuss the problem you just posted?

Cheers,
Paul.

**Comment by cfgamboa** [comment]
The solution was proposed on www.dcache.org #10308, the DMZ pool needs to know the interface to communicate to other pools via:
 pp interface <IP of DMZ pool on internal network:>

Thank you Paul
