### ISSUE TITLE
GFTP doors unstable in dCache 7.2 

### ISSUE THREAD

**Issue by DmitryLitvintsev** [dCache/dcache#6195]
After upgrade to 7.2 we experience high rate of GFTP door failures due to:

```
java.lang.OutOfMemoryError: Java heap space
Dumping heap to /home/enstore/dcache-log/gridftp-stkendca55aDomain-oom.hprof ...
Unable to create /home/enstore/dcache-log/gridftp-stkendca55aDomain-oom.hprof: File exists
Terminating due to java.lang.OutOfMemoryError: Java heap space
2021-10-27 09:44:39 Process terminated unexpectedly
2021-10-27 09:44:39 Sleeping 10 seconds
```

(as you can see this was more than a second fail for that door)

The run up to the fail is always similar:

``` 
 Login failed for ...: Request to [>gPlazma@local] timed out
```

"..." stands for DN. One may speculate that message queue gets full for some reason not being able to contact gPlazma. 

Other protocol doors do not show any issues related to communication with gPlazma, so it seems that 
```
Login failed for ...: Request to [>gPlazma@local] timed out
```
is a red herring. That is, ithe problem is not with gPlazma but with the door. 

GFTP Doors usually colocated with pools and have 1 GB of heap allocated. They fail with OOM
Two dedicated doors on so called door node, have 10GB allocated. They don't dail with OOM, but just stop responding. 
With log file looking like:

```
Login failed for .... : Failed to deliver LoginMessage message <3334827556985914516:-5373597254133069821> to [>gPlazma@local]: c-dCacheDomain-AAXPL3Epvpg-AAXPL
3EqHFg@gridftp0-fndca4bDomain is busy (its estimated response time of 1726950 ms is longer than the message TTL of 30000 ms).
```

This issue severely affects our production system. 

I will try to produce some object histogram from the *hprof file.

**Comment by DmitryLitvintsev** [comment]
Unfortunately another heap dump happened after the above actions. May be there is more than one problem at play here

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/13246/

**Comment by paulmillar** [comment]
Analysing the heap dump shows the memory leak seems to be caused by having many objects of type `io.netty.handler.ssl.OpenSslEngine`.  The "leaked" objects are contained within a single ConcurrentHashMap, which is itself contained within netty code (`io.netty.handler.ssl.ReferenceCountedOpenSslContext`).

It looks like these `OpenSslEngine` objects are being created in `ServerGsiEngineDssContextFactory#create`.

Commit `ddd6c88ccd` modified this method from using the Java native code (`SSLContext#createSSLEngine`) to using the Netty code (`SslContext#newEngine`) -- note the change in capitalisation!

The Netty `SslContext#newEngine` [JavaDoc](https://netty.io/4.1/api/io/netty/handler/ssl/SslContext.html#newEngine-io.netty.buffer.ByteBufAllocator-java.lang.String-int-) states
> If SslProvider.OPENSSL_REFCNT is used then the object must be released

My suspicion (nothing more concrete) is that commit `ddd6c88ccd` introduced this memory leak by not releasing the reference.

**Comment by alrossi** [comment]
Sounds like a plausible explanation.   I shall have a look.

**Comment by alrossi** [comment]
The problem is that the TlsInterpreter does not use a pipeline, so the suggested solution (wrapping in a handler and inserting) does not seem immediately feasible.

We may need to roll back GFTP to the Java implementation.

**Comment by alrossi** [comment]
I.e., what we do in Https 

```
@Override
--
protected void addChannelHandlers(ChannelPipeline pipeline) | protected void addChannelHandlers(ChannelPipeline pipeline)
{ | {
SSLEngine engine = _sslContext.createSSLEngine(); | SSLEngine engine = _sslContext.newEngine(pipeline.channel().alloc());
engine.setUseClientMode(false); |  
engine.setWantClientAuth(false); | engine.setWantClientAuth(false);
pipeline.addLast("ssl", new SslHandler(engine)); | pipeline.addLast("ssl", new SslHandler(engine));
super.addChannelHandlers(pipeline); | super.addChannelHandlers(pipeline);
} | }
```

is not available.

**Comment by DmitryLitvintsev** [comment]
I support rollback. The least risky move to fix 7.2.

**Comment by alrossi** [comment]
We can just rollback the GridFTP and FTP interpreter parts.

**Comment by DmitryLitvintsev** [comment]
Other doors are unaffected?

**Comment by alrossi** [comment]
All the other instances use Netty pipelines.  I will double check this though

**Comment by alrossi** [comment]
Just for quick reference here, commit  ddd6c88ccd  corresponds to https://rb.dcache.org/r/13044

**Comment by alrossi** [comment]
Here's what I see:

(1) still uses Java SSLContext.class:

```
modules/srm-common/src/main/java/org/dcache/srm/client/FlexibleCredentialSSLConnectionSocketFactory.java

modules/common-security/src/main/java/org/dcache/ssl/CanlSslSocketCreator.java

(this latter is called by):

dmg.cells.services.LocationManager.java
```

(2) uses OpenSSL SslContext.class, but wraps in handler and inserts into pipeline (proper usage):

```
modules/dcache-xrootd/src/main/java/org/dcache/xrootd/plugins/tls/CDCCanlTLSHandlerFactory.java

modules/dcache/src/main/java/org/dcache/http/HttpsTransferService.java
```

(3) uses SslContext.class with engine but has not pipeline so release is never called (so native deallocation never takes place):

```
modules/dcache-ftp/src/main/java/org/dcache/ftp/door/TlsFtpInterpreterFactory.java

modules/common-security/src/main/java/org/dcache/dss/ServerGsiEngineDssContextFactory.java
```

**Comment by DmitryLitvintsev** [comment]
Overnight one of the doors hasn't failed yet but has become unresponsive. The following (new to me) stack seen:

```
30 Oct 2021 09:50:14 (GFTP-stkendca58a-AAXPkw9-hAg) [door:GFTP-stkendca58a-AAXPkw9-hAg@gridftp-stkendca58aDomain] Uncaught exception in thread GFTP-stkendca58a-io-25
io.netty.handler.codec.TooLongFrameException: frame length (84033) exceeds the allowed maximum (65536)
        at io.netty.handler.codec.LineBasedFrameDecoder.fail(LineBasedFrameDecoder.java:158)
        at io.netty.handler.codec.LineBasedFrameDecoder.fail(LineBasedFrameDecoder.java:154)
        at io.netty.handler.codec.LineBasedFrameDecoder.decode(LineBasedFrameDecoder.java:108)
        at io.netty.handler.codec.LineBasedFrameDecoder.decode(LineBasedFrameDecoder.java:84)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at org.dcache.util.CDCThreadFactory.lambda$newThread$0(CDCThreadFactory.java:50)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

[thread_dump.log](https://github.com/dCache/dcache/files/7446943/thread_dump.log)

As far as I can see: threads are blocked on : 

```
"GFTP-stkendca58a-io-31" #120 prio=5 os_prio=0 cpu=7887.44ms elapsed=38123.98s tid=0x00007f5e5c085800 nid=0x4bc6 runnable  [0x00007f5e706f2000]
   java.lang.Thread.State: RUNNABLE
        at dmg.cells.nucleus.CellNucleus.addToEventQueue(CellNucleus.java:612)
        at dmg.cells.nucleus.CellGlue.sendToAll(CellGlue.java:259)
        at dmg.cells.nucleus.CellGlue.doKill(CellGlue.java:450)
        - locked <0x0000000080b281e0> (a dmg.cells.nucleus.CellGlue)
        at dmg.cells.nucleus.CellGlue.lambda$kill$2(CellGlue.java:424)
        at dmg.cells.nucleus.CellGlue$$Lambda$342/0x000000084058ec40.apply(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(java.base@11.0.12/ConcurrentHashMap.java:1705)
        - locked <0x00000000ff2ffbd0> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
        at dmg.cells.nucleus.CellGlue.kill(CellGlue.java:424)
        - locked <0x0000000080b281e0> (a dmg.cells.nucleus.CellGlue)
        at dmg.cells.nucleus.CellGlue.kill(CellGlue.java:270)
        at dmg.cells.nucleus.CellNucleus.kill(CellNucleus.java:633)
        at dmg.cells.nucleus.CellAdapter.kill(CellAdapter.java:340)
        at diskCacheV111.doors.NettyLineBasedDoor.shutdown(NettyLineBasedDoor.java:268)
        at diskCacheV111.doors.NettyLineBasedDoor.userEventTriggered(NettyLineBasedDoor.java:361)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
        at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
        at io.netty.handler.logging.LoggingHandler.userEventTriggered(LoggingHandler.java:213)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
        at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
        at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:117)
        at io.netty.handler.codec.ByteToMessageDecoder.userEventTriggered(ByteToMessageDecoder.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
        at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.userEventTriggered(DefaultChannelPipeline.java:1428)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
        at io.netty.channel.DefaultChannelPipeline.fireUserEventTriggered(DefaultChannelPipeline.java:913)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:103)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:174)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at org.dcache.util.CDCThreadFactory.lambda$newThread$0(CDCThreadFactory.java:50)
        at org.dcache.util.CDCThreadFactory$$Lambda$321/0x000000084050c040.run(Unknown Source)
        at java.lang.Thread.run(java.base@11.0.12/Thread.java:829)
```

**Comment by alrossi** [comment]
I think this is symptomatic of the SSL regression.  I am posting a patch we I have been testing on the testbed which reverts the SSL context to Java for FTP doors.

**Comment by alrossi** [comment]
Please have a look at https://rb.dcache.org/r/13247/

**Comment by alrossi** [comment]
The 200K transfer test is about 3/4 done against master.  The only thing I notice that is different in JDK Mission Control is that the pace of GC is a bit more furious.  But I don't see any obvious evidence of leaks.   

So the test I devised is probably insufficient to replicate the problem.

One of the issues is perhaps that the door only has 10 concurrent interpreters/transfers.   Some of the more active doors on Public seem to have almost an order of magnitude more, e.g. 

```
Alberts-MacBook-Pro:dcache arossi$ echo "\s System@gridftp-stkendca56aDomain ps" | ssh -p 24223 enstore@fndca3b.fnal.gov 2> /dev/null | grep GFTP | wc -l
      72
```
So maybe I just need to stress the system more

**Comment by alrossi** [comment]
Maybe e-mode needs to be on.  It has been a while since I used gridftp.  Can this be done with globus-url-copy?

**Comment by alrossi** [comment]
Maybe one of these?
```
   -dcsafe | -data-channel-safe
       set data channel protection mode to SAFE
  -dcpriv | -data-channel-private
       set data channel protection mode to PRIVATE
   -fast
       Recommended when using GridFTP servers. Use MODE E for all data
       transfers, including reusing data channels between list and transfer
       operations.
```

**Comment by alrossi** [comment]
retrying with -dcsafe.

**Comment by alrossi** [comment]
I think this is a question of just leaving the door running long enough.   On master I am now seeing the heap allocation slowly creep up.  This may or may not be triggered by -dcsafe, but as soon as we get an OOM I will retry with the patch and keep it running longer.

**Comment by alrossi** [comment]
The original script was not getting me results, so I have changed strategies.   I will keep at this for a while longer to see if I can get master gftp to crash.

**Comment by paulmillar** [comment]
@DmitryLitvintsev I'm think the problem you described [here](https://github.com/dCache/dcache/issues/6195#issuecomment-955284459) is unrelated to the issue being described in this issue.

This is, I believe it is NOT related to the SslEngine problem.

Please open a fresh issue, including the information you provided.

**Comment by DmitryLitvintsev** [comment]
Restarted the system with patch https://rb.dcache.org/r/13247/

**Comment by DmitryLitvintsev** [comment]
With the patch still having OOM Exception:

```
curl -k -L  http://fndcaitb4.fnal.gov:2880/pnfs/fnal.gov/usr/test/litvinse/scratch/gridftp-stkendca71aDomain-oom.hprof -o gridftp-stkendca71aDomain-oom.hprof
```

**Comment by DmitryLitvintsev** [comment]
[gridftp-stkendca71aDomain.log.gz](https://github.com/dCache/dcache/files/7457130/gridftp-stkendca71aDomain.log.gz)

**Comment by DmitryLitvintsev** [comment]
No OOM errors seen in the last two days. Closing the issue.
