### ISSUE TITLE
Mysterious direct memory xroot byte buffer leak on pool

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#6209]
Observed for the first time the following at FNAL running 7.2 (7.2.1-FNAL(7.2.0-11-g028dabb)):

```
02 Nov 2021 14:00:08 (p-nova-stkendca1912-6) [] LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:385)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:139)
	org.dcache.xrootd.pool.ChunkedFileDescriptorReadvResponse.read(ChunkedFileDescriptorReadvResponse.java:48)
	org.dcache.xrootd.stream.AbstractChunkedReadvResponse.read(AbstractChunkedReadvResponse.java:120)
	org.dcache.xrootd.stream.AbstractChunkedReadvResponse.nextChunk(AbstractChunkedReadvResponse.java:64)
	org.dcache.xrootd.stream.AbstractChunkedReadvResponse.nextChunk(AbstractChunkedReadvResponse.java:33)
	org.dcache.xrootd.stream.ChunkedResponseWriteHandler.doFlush(ChunkedResponseWriteHandler.java:172)
	org.dcache.xrootd.stream.ChunkedResponseWriteHandler.flush(ChunkedResponseWriteHandler.java:96)
	io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
	org.dcache.xrootd.core.XrootdRequestHandler.respond(XrootdRequestHandler.java:268)
	org.dcache.xrootd.core.XrootdRequestHandler.requestReceived(XrootdRequestHandler.java:239)
	org.dcache.xrootd.core.XrootdRequestHandler.channelRead(XrootdRequestHandler.java:99)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	org.dcache.util.ChannelCdcSessionHandlerWrapper.channelRead(ChannelCdcSessionHandlerWrapper.java:173)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	org.dcache.util.CDCThreadFactory.lambda$newThread$0(CDCThreadFactory.java:50)
	java.base/java.lang.Thread.run(Thread.java:829)
```

This was immediately followed by: 

```
02 Nov 2021 14:00:08 (p-nova-stkendca1912-6) [] Restarting due to fatal JVM error: java.lang.OutOfMemoryError: Direct buffer memory
02 Nov 2021 14:00:08 (p-nova-stkendca1912-6) [] Restarting due to fatal JVM error: java.lang.OutOfMemoryError: Direct buffer memory
02 Nov 2021 14:00:08 (p-nova-stkendca1912-6) [] Restarting due to fatal JVM error: java.lang.OutOfMemoryError: Direct buffer memory
02 Nov 2021 14:00:08 (p-nova-stkendca1912-6) [] Restarting due to fatal JVM error: java.lang.OutOfMemoryError: Direct buffer memory
02 Nov 2021 14:00:09 (p-nova-stkendca1912-6) [] Restarting due to fatal JVM error: java.lang.OutOfMemoryError: Direct buffer memory
02 Nov 2021 14:00:09 (p-nova-stkendca1912-6) [] Restarting due to fatal JVM error: java.lang.OutOfMemoryError: Direct buffer memory
02 Nov 2021 14:00:10 (p-nova-stkendca1912-6) [] Restarting due to fatal JVM error: java.lang.OutOfMemoryError: Direct buffer memory
02 Nov 2021 14:00:10 (p-nova-stkendca1912-6) [] Restarting due to fatal JVM error: java.lang.OutOfMemoryError: Direct buffer memory
02 Nov 2021 14:00:11 (p-nova-stkendca1912-6) [] Restarting due to fatal JVM error: java.lang.OutOfMemoryError: Direct buffer memory
02 Nov 2021 14:00:11 (p-nova-stkendca1912-6) [] Restarting due to fatal JVM error: java.lang.OutOfMemoryError: Direct buffer memory
02 Nov 2021 14:00:11 (p-nova-stkendca1912-6) [] Restarting due to fatal JVM error: java.lang.OutOfMemoryError: Direct buffer memory
02 Nov 2021 14:00:11 (p-nova-stkendca1912-6) [] Restarting due to fatal JVM error: java.lang.OutOfMemoryError: Direct buffer memory
```

Then another leaked buffer exception trace, and finally, the pool goes into the familiar repository error mode with:

```
java.lang.InterruptedException THREAD_INTERRUPTED: InterruptedException may cause incorrect internal state, unable to continue. Environment is invalid and must be closed.
	at com.sleepycat.je.ThreadInterruptedException.wrapSelf(ThreadInterruptedException.java:105)
	at com.sleepycat.je.dbi.EnvironmentImpl.checkIfInvalid(EnvironmentImpl.java:1750)
	at com.sleepycat.je.dbi.EnvironmentImpl.checkOpen(EnvironmentImpl.java:1759)
	at com.sleepycat.je.Environment.checkOpen(Environment.java:2491)
	at com.sleepycat.je.Database.checkEnv(Database.java:2392)
	at com.sleepycat.je.Database.openCursor(Database.java:928)
	at com.sleepycat.collections.CurrentTransaction.openCursor(CurrentTransaction.java:425)
	at com.sleepycat.collections.MyRangeCursor.openCursor(MyRangeCursor.java:60)
	at com.sleepycat.collections.MyRangeCursor.<init>(MyRangeCursor.java:36)
	at com.sleepycat.collections.DataCursor.init(DataCursor.java:178)
	at com.sleepycat.collections.DataCursor.<init>(DataCursor.java:66)
	at com.sleepycat.collections.StoredContainer.getValue(StoredContainer.java:308)
	at com.sleepycat.collections.StoredMap.get(StoredMap.java:246)
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:329)
	at org.dcache.pool.repository.meta.db.BerkeleyDBMetaDataRepository.setLastModifiedTime(BerkeleyDBMetaDataRepository.java:227)
	at org.dcache.pool.repository.meta.db.CacheRepositoryEntryImpl.setLastAccessTime(CacheRepositoryEntryImpl.java:204)
	at org.dcache.pool.repository.ForwardingReplicaRecord.setLastAccessTime(ForwardingReplicaRecord.java:89)
	at org.dcache.pool.repository.ForwardingReplicaRecord.setLastAccessTime(ForwardingReplicaRecord.java:89)
	at org.dcache.pool.repository.ReplicaStoreCache$Monitor.setLastAccessTime(ReplicaStoreCache.java:258)
	at org.dcache.pool.repository.v5.ReplicaRepository.openEntry(ReplicaRepository.java:755)
	at org.dcache.pool.classic.PoolV4.createMover(PoolV4.java:762)
	at org.dcache.pool.classic.PoolV4.lambda$queueIoRequest$7(PoolV4.java:789)
	at org.dcache.pool.classic.MoverRequestScheduler.createRequest(MoverRequestScheduler.java:246)
	at org.dcache.pool.classic.MoverRequestScheduler.lambda$getOrCreateMover$0(MoverRequestScheduler.java:215)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	at org.dcache.pool.classic.MoverRequestScheduler.getOrCreateMover(MoverRequestScheduler.java:212)
	at org.dcache.pool.classic.IoQueueManager.getOrCreateMover(IoQueueManager.java:162)
	at org.dcache.pool.classic.PoolV4.queueIoRequest(PoolV4.java:789)
	at org.dcache.pool.classic.PoolV4.ioFile(PoolV4.java:796)
	at org.dcache.pool.classic.PoolV4.messageArrived(PoolV4.java:1014)
	at jdk.internal.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.dcache.cells.CellMessageDispatcher$LongReceiver.deliver(CellMessageDispatcher.java:304)
	at org.dcache.cells.CellMessageDispatcher.call(CellMessageDispatcher.java:201)
	at org.dcache.cells.AbstractCell.messageArrived(AbstractCell.java:326)
	at dmg.cells.nucleus.CellAdapter.messageArrived(CellAdapter.java:890)
	at dmg.cells.nucleus.CellNucleus$DeliverMessageTask.run(CellNucleus.java:1316)
	at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:251)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$2(CellNucleus.java:764)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

(reported repeatedly)

I have never seen this xroot error previously.  I checked our code (dcache and xrootd4j) for all instances of buffer.alloc() but none of them have been recently (e.g., after about 2016) changed.

The only allocation that has been "added" is ... the SSLHandler.  But that is placed in the pipeline and the buffer should be released when the pipeline is closed (automatically).  That is the suggested programming model, in fact.

**Comment by alrossi** [comment]
The leak detector means what it says.

https://netty.io/wiki/reference-counted-objects.html#troubleshooting-buffer-leaks

**Comment by DmitryLitvintsev** [comment]
reading the above info tells me that we need to set:

```
'-Dio.netty.leakDetectionLevel=advanced'
```

in our running application and :

```
-Dio.netty.leakDetection.level=paranoid
```
in unit tests

**Comment by alrossi** [comment]
It seemed to me that the output we are seeing is already 'advanced' ...

But it wouldn't hurt.

**Comment by alrossi** [comment]
i.e., "simple" gives this message:

```
LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetectionLevel=advanced' or call ResourceLeakDetector.setLevel()
```

but when it is at a higher level you get the access records (as we do)

??

or does this: 

```
Recent access records: 

```
(absence of number) imply only the first, whereas with advanced you get an enumerated list?

```
Relaunch your application with the JVM option mentioned above and you will see the recent locations of your application where the leaked buffer was accessed. The following output shows a leak from our unit test (XmlFrameDecoderTest.testDecodeWithXml()):

Running io.netty.handler.codec.xml.XmlFrameDecoderTest
15:03:36.886 [main] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected.
Recent access records: 1
```

**Comment by DmitryLitvintsev** [comment]
Not seeing that option in `dcache.properties`:

```
(not-for-services)dcache.java.options=\
    -server \
    -Xmx${dcache.java.memory.heap} \
    -XX:MaxDirectMemorySize=${dcache.java.memory.direct} \
    -Dsun.net.inetaddr.ttl=${dcache.net.inetaddr.lifetime} \
    -Dorg.globus.tcp.port.range=${dcache.net.wan.port.min},${dcache.net.wan.port.max} \
    -Dorg.dcache.dcap.port=${pool.mover.dcap.port} \
    -Dorg.dcache.ftp.log-aborted-transfers=${pool.mover.ftp.enable.log-aborted-transfers} \
    -Dorg.dcache.net.tcp.portrange=${dcache.net.lan.port.min}:${dcache.net.lan.port.max} \
    -Djava.security.krb5.realm=${dcache.authn.kerberos.realm} \
    -Djava.security.krb5.kdc=${dcache.authn.kerberos.key-distribution-center-list} \
    -Djavax.security.auth.useSubjectCredsOnly=false \
    -Djava.security.auth.login.config=${dcache.authn.jaas.config} \
    -Dcontent.types.user.table=${dcache.paths.content-types} \
    -Dzookeeper.sasl.client=false \
    -Dcurator-dont-log-connection-problems=true \
    -XX:+HeapDumpOnOutOfMemoryError \
    -XX:HeapDumpPath=${dcache.java.oom.file} \
    -XX:+ExitOnOutOfMemoryError \
    -XX:+StartAttachListener \
    -XX:+UseCompressedOops \
    -javaagent:${dcache.paths.classes}/aspectjweaver-1.9.2.jar \
    ${dcache.java.options.common} \
    ${dcache.java.options.extra}
```

```
(not-for-services)dcache.java.options.common=\
    -Djava.awt.headless=true \
    -DwantLog4jSetup=n
```

**Comment by alrossi** [comment]
Yeah I already checked that.
