### ISSUE TITLE
Webdav NPE on pool

### ISSUE THREAD

**Issue by ageorget** [dCache/dcache#6253]
Hi,

During some heavy webdav loadtest from LSST on our ESCAPE dCache instance (6.2.29), I found hundreds of NPE messages in the pool logs like this : 

```
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: 15 Nov 2021 13:19:27 (pool-escape-litest11a) [door:webdav-ccdcalitest10@webdav-ccdcalitest10Domain:AAXQ0tDMiEA RemoteTransferManager] Command failed due to a bug, please contact support@dcache.
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: dmg.util.CommandPanicException: (1) Command failed: java.lang.NullPointerException
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at org.dcache.util.cli.AnnotatedCommandExecutor.execute(AnnotatedCommandExecutor.java:156)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at dmg.cells.nucleus.CellAdapter.executeCommand(CellAdapter.java:238)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at org.dcache.cells.UniversalSpringCell.executeCommand(UniversalSpringCell.java:195)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at dmg.cells.nucleus.CellAdapter$1.doExecute(CellAdapter.java:104)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at org.dcache.util.cli.CommandInterpreter.command(CommandInterpreter.java:129)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at dmg.cells.nucleus.CellAdapter$1.command(CellAdapter.java:121)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at dmg.cells.nucleus.CellAdapter.command(CellAdapter.java:223)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at dmg.cells.nucleus.CellAdapter.executeLocalCommand(CellAdapter.java:924)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at dmg.cells.nucleus.CellAdapter.messageArrived(CellAdapter.java:855)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at dmg.cells.nucleus.CellNucleus$DeliverMessageTask.run(CellNucleus.java:1223)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:251)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$4(CellNucleus.java:755)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at java.base/java.lang.Thread.run(Thread.java:834)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: Caused by: java.lang.NullPointerException: null
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at java.base/java.util.Objects.requireNonNull(Objects.java:221)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at org.dcache.pool.movers.RemoteHttpDataTransferProtocol.remoteAddress(RemoteHttpDataTransferProtocol.java:412)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at org.dcache.pool.movers.RemoteHttpDataTransferProtocol.remoteConnections(RemoteHttpDataTransferProtocol.java:876)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at org.dcache.pool.movers.MoverProtocolMover.remoteConnections(MoverProtocolMover.java:81)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at org.dcache.pool.classic.MoverRequestScheduler$PrioritizedRequest.toJobInfo(MoverRequestScheduler.java:754)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at org.dcache.pool.classic.MoverRequestScheduler.getJobInfo(MoverRequestScheduler.java:326)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at org.dcache.pool.classic.IoQueueManager$MoverLsCommand.call(IoQueueManager.java:430)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at org.dcache.pool.classic.IoQueueManager$MoverLsCommand.call(IoQueueManager.java:403)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: at org.dcache.util.cli.AnnotatedCommandExecutor.execute(AnnotatedCommandExecutor.java:145)
Nov 15 13:19:27 ccdcalitest11 dcache@ccdcalitest11-pool-escape-litest11a-Domain[104744]: ... 14 common frames omitted
```

On the webdav door side I just found this information : 
`Nov 15 13:19:27 ccdcalitest10 dcache@webdav-ccdcalitest10Domain[99243]: 15 Nov 2021 13:19:27 (webdav-ccdcalitest10) [door:webdav-ccdcalitest10@webdav-ccdcalitest10Domain:AAXQ0tDMiEA] Failed to fetch information for progress marker: failed to query pool pool-escape-litest11a: (1) Command failed: java.lang.NullPointerException`

```
level=INFO ts=2021-11-15T13:19:25.085+0100 event=org.dcache.webdav.request request.method=PROPFIND request.url=https://ccdcalitest10.in2p3.fr:2880/pnfs/in2p3.fr/data/escape/cc_in2p3_dcache/lsst_source/auto_uploaded_ALWUoPB28kL6ZCliMW1uGJhC1Portarx response.code=207 response.reason=Multi-status socket.remote=[2001:1458:301:cd::100:c4]:40256 user-agent="fts_url_copy/3.11.1 gfal2/2.20.1 neon/0.0.29" user.dn="CN=1112682106,CN=553049744,CN=Robot: ESCAPE WP2 CERN 01,CN=531497,CN=ewp2c01,OU=Users,OU=Organic Units,DC=cern,DC=ch" user.mapped=3915:239,239[6KvjjoG8:xIlSDX9A]
level=INFO ts=2021-11-15T13:19:27.663+0100 event=org.dcache.webdav.request request.method=COPY request.url=https://ccdcalitest10.in2p3.fr:2880/pnfs/in2p3.fr/data/escape/cc_in2p3_dcache/lsst_dest/LSST_DAC21/01191242/lsst_a_1191242_R42_S10_u.fits response.code=202 socket.remote=[2001:1458:301:cd::100:19c]:41708 user-agent="fts_url_copy/3.11.1 gfal2/2.20.1 neon/0.0.29" user.dn="CN=1112682106,CN=553049744,CN=Robot: ESCAPE WP2 CERN 01,CN=531497,CN=ewp2c01,OU=Users,OU=Organic Units,DC=cern,DC=ch" user.mapped=3915:239,239[ccUO6s14:eVfJDjJ2] tpc.credential=none tpc.require-checksum=false tpc.source=https://eoseulake.cern.ch:443/eos/eulake/tests/rucio_test/eulake_1/LSST_DAC21/84/62/LSST_DAC21__01191242__lsst_a_1191242_R42_S10_u.fits
level=INFO ts=2021-11-15T13:19:27.708+0100 event=org.dcache.webdav.request request.method=HEAD request.url=https://ccdcalitest10.in2p3.fr:2880/pnfs/in2p3.fr/data/escape/cc_in2p3_dcache/lsst_dest/LSST_DAC21/01191242/lsst_a_1191242_R42_S10_u.fits response.code=200 response.reason=OK socket.remote=[2001:1458:301:cd::100:19c]:41708 user-agent="fts_url_copy/3.11.1 gfal2/2.20.1 neon/0.0.29" user.dn="CN=1112682106,CN=553049744,CN=Robot: ESCAPE WP2 CERN 01,CN=531497,CN=ewp2c01,OU=Users,OU=Organic Units,DC=cern,DC=ch" user.mapped=3915:239,239[ccUO6s14:eVfJDjJ2]
level=INFO ts=2021-11-15T13:19:27.734+0100 event=org.dcache.webdav.request request.method=PROPFIND request.url=https://ccdcalitest10.in2p3.fr:2880/pnfs/in2p3.fr/data/escape/cc_in2p3_dcache/lsst_dest/LSST_DAC21/01191242/lsst_a_1191242_R42_S10_u.fits response.code=207 response.reason=Multi-status socket.remote=[2001:1458:301:cd::100:19c]:41708 user-agent="fts_url_copy/3.11.1 gfal2/2.20.1 neon/0.0.29" user.dn="CN=1112682106,CN=553049744,CN=Robot: ESCAPE WP2 CERN 01,CN=531497,CN=ewp2c01,OU=Users,OU=Organic Units,DC=cern,DC=ch" user.mapped=3915:239,239[ccUO6s14:eVfJDjJ2]

```

They're using Escape FTS server and their activity is mainly PUT transfers from CERN EOS to IN2P3 when these errors occurred.

Cheers,
Adrien

**Comment by paulmillar** [comment]
This problem was fixed in [dCache v6.2.30](https://www.dcache.org/old/downloads/1.9/release-notes-6.2.shtml#release6.2.30).

Please upgrade the pool nodes to that version or newer (ideally, the latest 6.2 release) and the problem should go away.

Cheers,
Paul.

**Comment by ageorget** [comment]
Oh perfect. I'm upgrading the nodes to 6.2.34.
I'll let you know if these errors disappear.

Cheers,
Adrien

**Comment by ageorget** [comment]
No more errors in the last 24h after upgrading to 6.2.34, thanks Paul for the tips.
I'm closing this issue.
Cheers
