### ISSUE TITLE
7.2: NFS door fails after start and drops off of port 1111

### ISSUE THREAD

**Issue by DmitryLitvintsev** [dCache/dcache#6270]
Noticed that I cannot connect to NFS cell (of its domain) via admin interface. Noticed these in log file:

```
17 Nov 2021 14:23:55 (NFS-enstore01) [] Unhandled exception:
org.dcache.chimera.ChimeraFsException: Failed to deliver PnfsRenameMessage message <-7551833850579303502:-7193724067600889468> to [>PnfsManager@local]: Route for >PnfsManager@local< not found at >
nfsDomain<
        at org.dcache.chimera.DCacheAwareJdbcFs.rename(DCacheAwareJdbcFs.java:378)
        at org.dcache.chimera.nfsv41.door.ChimeraVfs.move(ChimeraVfs.java:219)
        at org.dcache.nfs.vfs.VfsCache.move(VfsCache.java:129)
        at org.dcache.nfs.vfs.ForwardingFileSystem.move(ForwardingFileSystem.java:86)
        at org.dcache.chimera.nfsv41.door.MonitoringVfs.move(MonitoringVfs.java:364)
        at org.dcache.nfs.vfs.PseudoFs.move(PseudoFs.java:267)
        at org.dcache.nfs.v4.OperationRENAME.process(OperationRENAME.java:83)
        at org.dcache.chimera.nfsv41.door.DoorOperationFactory$OpRename.process(DoorOperationFactory.java:310)
        at org.dcache.chimera.nfsv41.door.DoorOperationFactory$2.lambda$process$0(DoorOperationFactory.java:231)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
        at org.dcache.chimera.nfsv41.door.DoorOperationFactory$2.process(DoorOperationFactory.java:213)
        at org.dcache.nfs.v4.AbstractOperationExecutor.execute(AbstractOperationExecutor.java:58)
        at org.dcache.chimera.nfsv41.common.StatsDecoratedOperationExecutor.execute(StatsDecoratedOperationExecutor.java:57)
        at org.dcache.nfs.v4.NFSServerV41.NFSPROC4_COMPOUND_4(NFSServerV41.java:188)
        at org.dcache.nfs.v4.xdr.nfs4_prot_NFS4_PROGRAM_ServerStub.dispatchOncRpcCall(nfs4_prot_NFS4_PROGRAM_ServerStub.java:48)
        at org.dcache.oncrpc4j.rpc.RpcDispatcher$1.run(RpcDispatcher.java:110)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: diskCacheV111.util.TimeoutCacheException: Failed to deliver PnfsRenameMessage message <-7551833850579303502:-7193724067600889468> to [>PnfsManager@local]: Route for >PnfsManager@local< not found at >nfsDomain<
        at diskCacheV111.util.PnfsHandler.request(PnfsHandler.java:262)
        at diskCacheV111.util.PnfsHandler.renameEntry(PnfsHandler.java:366)
        at org.dcache.chimera.DCacheAwareJdbcFs.rename(DCacheAwareJdbcFs.java:371)
        ... 19 common frames omitted
Caused by: dmg.cells.nucleus.NoRouteToCellException: Failed to deliver PnfsRenameMessage message <-7551833850579303502:-7193724067600889468> to [>PnfsManager@local]: Route for >PnfsManager@local< not found at >nfsDomain<
        at dmg.cells.nucleus.CellGlue.sendException(CellGlue.java:642)
        at dmg.cells.nucleus.CellGlue.sendMessage(CellGlue.java:568)
        at dmg.cells.nucleus.CellGlue.sendMessage(CellGlue.java:484)
        at dmg.cells.nucleus.CellNucleus.sendMessage(CellNucleus.java:568)
        at dmg.cells.nucleus.CellAdapter.sendMessage(CellAdapter.java:468)
        at org.dcache.cells.CellStub.send(CellStub.java:418)
        at org.dcache.cells.CellStub.send(CellStub.java:390)
        at org.dcache.cells.CellStub.send(CellStub.java:378)
        at diskCacheV111.util.PnfsHandler.requestAsync(PnfsHandler.java:289)
        at diskCacheV111.util.PnfsHandler.requestAsync(PnfsHandler.java:272)
        at diskCacheV111.util.PnfsHandler.request(PnfsHandler.java:257)
        ... 21 common frames omitted
17 Nov 2021 14:23:55 (NFS-enstore01) [] Unhandled exception:
```
This started to happen after restart to pick up new kernel

**Comment by DmitryLitvintsev** [comment]
Obviously PnfsManager is there. It is running on the same host. So I am lost really.

**Comment by DmitryLitvintsev** [comment]
```
[root@fndca2b world_readable]# mv CD-LTO8G2.q CD-LTO8G2.q.1
mv: cannot move ‘CD-LTO8G2.q’ to ‘CD-LTO8G2.q.1’: Remote I/O error
```

**Comment by DmitryLitvintsev** [comment]
This seem to affect v4.1 mount. on v2 all looks OK:

```
[root@stkendca1910 world_readable]# mv tpc_test4.1634690001855077071.root tpc_test4.1634690001855077071.root.moved
[root@stkendca1910 world_readable]# echo $?
0
[root@stkendca1910 world_readable]# ls -al tpc_test4.1634690001855077071.root.moved
-rw-rw-rw- 1 8637 3200 429747477 Oct 19 19:33 tpc_test4.1634690001855077071.root.moved
[root@stkendca1910 world_readable]# 
```

**Comment by DmitryLitvintsev** [comment]
OK, Here is what I found out. 

I am running with:

```
dcache.systemd.strict=false
```

But after upgrade on Oct 20 I also did:

```
systemctl enabe dcache.target
```
Thinking that this will cause the service to come up on start up after reboot. Today we rebooted multiple servers and apparently they started by `systemctl`

But when running:

```
dcache status
```
I would see services as stopped. Without thinking much  I ran :

```
dcache start
```

The error reported on this issue is the consequence of that. 

SO.... How to make service start up on reboot if I want : 

```
dcache.systemd.strict=false
```
mainly *only* because I want log in the same log files where they were before

**Comment by paulmillar** [comment]
Hi @DmitryLitvintsev , your [last comment](https://github.com/dCache/dcache/issues/6270#issuecomment-972115274) appears not to be directly related to the NFS connection problem.

Perhaps it would be better recorded in a separate issue?

**Comment by paulmillar** [comment]
Some follow-up questions:

**First**, you said:
> Obviously PnfsManager is there. It is running on the same host. So I am lost really.

Just to double-check what you said.  Is the `PnfsManager` service running within `nfsDomain` domain, or is this service running in a different domain on the same machine?

**Second**, how many core domains do you run in your cluster, and on which machines do they run?

**Third**, please check whether the `nfsDomain` has established TCP connections to all core domains in the cluster; for example, by discovering the java process PID and filtering by pid (e.g., `netstat -tp|grep <pid>`). The PID may be discovered via sysctl (e.g., `systemctl status dcache@nfsDomain | grep "Main PID"`) or via the `dcache status nfsDomain` command.

**Comment by DmitryLitvintsev** [comment]
PnfsManager runs on the same hosts, different domain

One core domain - dCacheDomain 

What happened is this - NFS cell connected to dCacheDomain on port 1111, but once it run into this exception it disconnected and could not be connected to from admin.  By all means it looked crashed. Strangely the PNFS mount still "looked" OK, one can do "ls" say. But not cp. My theory is that `systemd` and `dcache` were competitively restarting the NFS domain,

**Comment by paulmillar** [comment]
OK, thanks for the info.

First, it doesn't matter that the domain hosting PnfsManager and the nfsDomain are running on the same host, all messages from satellite domains are routed through a core domain.  Since you have only one core domain (dCacheDomain) then any message from nfsDomain is sent to dCacheDomain, which will forward it to PnfsManager.

Second, in terms of causal relationship: I believe you have this the wrong way around.

It looks to me like the exception you described (in your first message) is a symptom of the tunnel between nfsDomain and dCacheDomain dying, not the cause of it -- at least, I don't see any evidence to suggest it is the cause.

In the absence of any specific evidence, perhaps the two most likely causes are that there was some network issue killed the TCP connection, or because nfsDomain believes dCacheDomain is no longer a core domain.

The network glitch theory seems unlikely, as the tunnel should simply re-establish itself once the network was fixed.

The nfsDomain believing dCacheDomain isn't a core domain would mean that dCacheDomain would have to leave ZK as a core domain and either fail to add itself back or nfsDomain failed to react correctly when dCacheDomain came back as a core domain.

**Comment by DmitryLitvintsev** [comment]
Paul, 

I think I have explained as to what happened: systemd was starting dCache and also dcache was started using "dcache start" command. Again - one the node that runs PnfsManager, NFS and cleaner has started "twice" or "multiple times" as the exception quoted here lead to NFS domain restart. 

When I opened the ticket that was not yet realized.

Dmitry
