### ISSUE TITLE
Regression in resilience from 5.2 to 7.2:  required=null now problematic on resilient pool groups

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#6312]
Here is the typical stack trace observed:

```
24 Nov 2021 03:21:34 (Resilience) [] Uncaught exception in thread pool-8-thread-1813
java.lang.RuntimeException: Trying to verify required replicas for a storage unit which is not resilient; this is a bug.
        at org.dcache.resilience.data.StorageUnitConstraints.getRequired(StorageUnitConstraints.java:119)
        at org.dcache.resilience.data.FileUpdate.validateForAction(FileUpdate.java:333)
        at org.dcache.resilience.handlers.FileOperationHandler.handleScannedLocation(FileOperationHandler.java:335)
        at org.dcache.resilience.db.LocalNamespaceAccess.handleQuery(LocalNamespaceAccess.java:302)
        at org.dcache.resilience.db.LocalNamespaceAccess.handlePnfsidsForPool(LocalNamespaceAccess.java:218)
        at org.dcache.resilience.handlers.PoolOperationHandler.handlePoolScan(PoolOperationHandler.java:95)
        at org.dcache.resilience.util.PoolScanTask.call(PoolScanTask.java:92)
        at org.dcache.resilience.util.ErrorAwareTask.lambda$createFireAndForgetTask$1(ErrorAwareTask.java:93)
        at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:31)
        at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:149)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:251)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
24 Nov 2021 03:21:34 (Resilience) [] Uncaught exception in thread pool-8-thread-1815
```

**Comment by alrossi** [comment]
Related to https://rt.dcache.org/Ticket/Display.html?id=10242
10242: Implenting Resiience on a previously not resilient pool group in connection with tape and pins

**Comment by alrossi** [comment]
Duplicate of problem solved by https://rb.dcache.org/r/13276/

Closing.
