### ISSUE TITLE
frontend failed to start without /etc/grid-security/certificates and didn't tell us

### ISSUE THREAD

**Issue by XMol** [dCache/dcache#6327]
Hi dCache.org,

when I mentioned our issue with frontend that failed to start on a newly deployed node, Lea pointed me to one other ticket on a related subject: #5605.

The behaviour in itself if fine, though it would be much more helpful if frontend would tell us which directory is missing, instead of just...
> Parameter 'directory' is not a directory

... which is what @svemeyer had [mentioned already](https://github.com/dCache/dcache/issues/5605#issuecomment-961218774). I didn't find a new issue on this matter, as Paul had suggested, so here you go. 🙂 

Ciao,  
Xavier.

PS: this is the complete stack trace, in case you want to know:
```
01 Dec 2021 12:58:52 (System) [] Bug detected in dCache; please report this to <support@dcache.org> with the following information.
java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
        at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:545)
        at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:521)
        at eu.emi.security.authn.x509.helpers.pkipath.PlainStoreUtils.establishWildcardLocations(PlainStoreUtils.java:92)
        at eu.emi.security.authn.x509.helpers.pkipath.PlainStoreUtils.establishWildcardsLocations(PlainStoreUtils.java:112)
        at eu.emi.security.authn.x509.helpers.trust.DirectoryTrustAnchorStore.update(DirectoryTrustAnchorStore.java:194)
        at eu.emi.security.authn.x509.helpers.trust.OpensslTrustAnchorStoreImpl.<init>(OpensslTrustAnchorStoreImpl.java:62)
        at eu.emi.security.authn.x509.impl.OpensslCertChainValidator.<init>(OpensslCertChainValidator.java:113)
        at org.dcache.ssl.CanlContextFactory$Builder.build(CanlContextFactory.java:210)
        at org.dcache.util.jetty.CanlContextFactory$1.getTrustManagers(CanlContextFactory.java:248)
        at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:382)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:256)
        at org.dcache.util.jetty.CanlContextFactory$1.doStart(CanlContextFactory.java:213)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.dcache.util.jetty.CanlContextFactory.createDelegate(CanlContextFactory.java:252)
        at org.dcache.util.Callables$MemoizingCallableFromFiles.call(Callables.java:135)
        at org.dcache.util.Callables$ExpiringMemoizingCallable.call(Callables.java:94)
        at org.dcache.util.jetty.CanlContextFactory.doStart(CanlContextFactory.java:175)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.dcache.util.jetty.ConnectorFactoryBean.createContextFactory(ConnectorFactoryBean.java:296)
        at org.dcache.util.jetty.ConnectorFactoryBean.getObject(ConnectorFactoryBean.java:337)
        at org.dcache.util.jetty.ConnectorFactoryBean.getObject(ConnectorFactoryBean.java:44)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1817)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1266)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedList(BeanDefinitionValueResolver.java:427)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:173)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1699)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1444)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.dcache.cells.UniversalSpringCell.createContext(UniversalSpringCell.java:1032)
        at org.dcache.cells.UniversalSpringCell.starting(UniversalSpringCell.java:231)
        at dmg.cells.nucleus.CellAdapter.prepareStartup(CellAdapter.java:681)
        at dmg.cells.nucleus.CellNucleus.doStart(CellNucleus.java:889)
        at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$5(CellNucleus.java:726)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:229)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$4(CellNucleus.java:718)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by alrossi** [comment]
HI Xavier

This patch https://rb.dcache.org/r/13253/

fixed this issue.   The fix is included in

7.2.5
7.1.15
7.0.24
6.2.35

Closing issue.

Thanks!

Al

**Comment by XMol** [comment]
Thank you Al! 

Yes, I forgot to mention that we're only running on 6.2.34, so one version before your fix.

👍

**Comment by lemora** [comment]
Sorry for pointing you in the wrong direction!
