### ISSUE TITLE
statistic module: Can't prepare Html directory message

### ISSUE THREAD

**Issue by cfgamboa** [dCache/dcache#6351]
Following error is reported below appears in the /var/log/dcache/statisticsDomain.log 

dCache version:
 dcache-7.2.5-1.noarch
OS version:
[root@dcqos001 defaults]# cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 7.9 (Maipo)

The configuration for this cell in the layout file is ( excluding the other cells)

```
[statisticsDomain]
[statisticsDomain/statistics]

```

```
07 Dec 2021 10:17:24 (System) [] Can't prepare Html directory : /var/lib/dcache/statistics/2021/12/07
java.nio.file.FileAlreadyExistsException: /var/lib/dcache/statistics/2021/12/07/total.drw
        at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:573)
        at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258)
        at java.base/java.nio.file.Files.copy(Files.java:1295)
        at diskCacheV111.services.PoolStatisticsV0.prepareDailyHtmlFiles(PoolStatisticsV0.java:994)
        at diskCacheV111.services.PoolStatisticsV0$HourlyRunner.run(PoolStatisticsV0.java:404)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

I am able to see stat files updated:
```
[root@dcqos001 defaults]# ls -l /var/lib/dcache/statistics/2021/12/07
total 132
-rw-r--r-- 1 root root 1017 Dec  7 00:23 2021-12-07-00.raw
-rw-r--r-- 1 root root 1017 Dec  7 01:23 2021-12-07-01.raw
-rw-r--r-- 1 root root 1017 Dec  7 02:23 2021-12-07-02.raw
-rw-r--r-- 1 root root 1017 Dec  7 03:23 2021-12-07-03.raw
-rw-r--r-- 1 root root 1017 Dec  7 04:23 2021-12-07-04.raw
-rw-r--r-- 1 root root 1017 Dec  7 05:23 2021-12-07-05.raw
-rw-r--r-- 1 root root 1074 Dec  7 06:23 2021-12-07-06.raw
-rw-r--r-- 1 root root 1186 Dec  7 07:23 2021-12-07-07.raw
-rw-r--r-- 1 root root 1186 Dec  7 08:23 2021-12-07-08.raw
-rw-r--r-- 1 root root 1351 Dec  7 09:23 2021-12-07-09.raw
-rw-r--r-- 1 root root 1205 Dec  7 10:07 2021-12-07-day.drw
-rw-r--r-- 1 root root 1080 Dec  7 10:07 2021-12-07-day.raw
-rw-r--r-- 1 root root 1763 Dec  7 00:23 class-diskdata:DISKDATA@osm.html
-rw-r--r-- 1 root root 2474 Dec  7 00:23 classes.html
-rw-r--r-- 1 root root 1763 Dec  7 00:23 class-tapedata:TAPEDATA@osm.html
-rw-r--r-- 1 root root  555 Dec  7 00:23 index.html
-rw-r--r-- 1 root root 2408 Dec  7 00:23 pool-dcqos001_10.html
-rw-r--r-- 1 root root 1781 Dec  7 00:23 pool-dcqos001_11.html
-rw-r--r-- 1 root root 1771 Dec  7 00:23 pool-dcqos001_12.html
-rw-r--r-- 1 root root 1781 Dec  7 00:23 pool-dcqos001_13.html
-rw-r--r-- 1 root root 1769 Dec  7 00:23 pool-dcqos001_1.html
-rw-r--r-- 1 root root 1777 Dec  7 00:23 pool-dcqos001_3.html
-rw-r--r-- 1 root root 1769 Dec  7 00:23 pool-dcqos001_4.html
-rw-r--r-- 1 root root 2414 Dec  7 00:23 pool-dcqos001_5.html
-rw-r--r-- 1 root root 1769 Dec  7 00:23 pool-dcqos001_6.html
-rw-r--r-- 1 root root 1779 Dec  7 00:23 pool-dcqos001_7.html
-rw-r--r-- 1 root root 1779 Dec  7 00:23 pool-dcqos001_8.html
-rw-r--r-- 1 root root 1771 Dec  7 00:23 pool-dcqos001_9.html
-rw-r--r-- 1 root root 8871 Dec  7 00:23 pools.html
-rw-r--r-- 1 root root 1137 Dec  7 00:23 total.drw
-rw-r--r-- 1 root root   75 Dec  7 00:23 total.raw
```

Could you please advise.

All the best,
Carlos

**Comment by kofemann** [comment]
Hi Carlos, 

looks like a bug on our side.

**Comment by cfgamboa** [comment]
Hi
I have updated the QOS instance to 7.2.7 still the trace is precent see below:


```
16 Dec 2021 08:17:24 (System) [] Can't prepare Html directory : /var/lib/dcache/statistics/2021/12/16
java.nio.file.FileAlreadyExistsException: /var/lib/dcache/statistics/2021/12/16/total.drw
	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:573)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258)
	at java.base/java.nio.file.Files.copy(Files.java:1295)
	at diskCacheV111.services.PoolStatisticsV0.prepareDailyHtmlFiles(PoolStatisticsV0.java:994)
	at diskCacheV111.services.PoolStatisticsV0$HourlyRunner.run(PoolStatisticsV0.java:404)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
16 Dec 2021 09:17:24 (System) [] Can't prepare Html directory : /var/lib/dcache/statistics/2021/12/16
java.nio.file.FileAlreadyExistsException: /var/lib/dcache/statistics/2021/12/16/total.drw
	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:573)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258)
	at java.base/java.nio.file.Files.copy(Files.java:1295)
	at diskCacheV111.services.PoolStatisticsV0.prepareDailyHtmlFiles(PoolStatisticsV0.java:994)
	at diskCacheV111.services.PoolStatisticsV0$HourlyRunner.run(PoolStatisticsV0.java:404)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
16 Dec 2021 10:17:24 (System) [] Can't prepare Html directory : /var/lib/dcache/statistics/2021/12/16
java.nio.file.FileAlreadyExistsException: /var/lib/dcache/statistics/2021/12/16/total.drw
	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:573)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258)
	at java.base/java.nio.file.Files.copy(Files.java:1295)
	at diskCacheV111.services.PoolStatisticsV0.prepareDailyHtmlFiles(PoolStatisticsV0.java:994)
	at diskCacheV111.services.PoolStatisticsV0$HourlyRunner.run(PoolStatisticsV0.java:404)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
16 Dec 2021 10:20:16 (c-dCacheDomain-AAXTRPVdD_g-AAXTRPVkCSA) [] Failed to add route: No such cell: c-dCacheDomain-AAXTRPVdD_g-AAXTRPVkCSA@statisticsDomain
16 Dec 2021 10:25:08 (System) [] Failed to create file /var/lib/dcache/statistics/2021/12/16/2021-12-16-10.raw: File exists or directory not writable : /var/lib/dcache/statistics/2021/12/16/2021-12-16-10.raw
20 Dec 2021 15:41:26 (c-dCacheDomain-AAXTmeloWGA-AAXTmel9CUA) [] Failed to add route: No such cell: c-dCacheDomain-AAXTmeloWGA-AAXTmel9CUA@statisticsDomain
20 Dec 2021 15:41:29 (c-dCacheDomain-AAXTmeloWGA-AAXTmel9CUA) [dCacheDomain,7.2.7,CORE] Error while reading from tunnel: java.net.SocketException: Socket closed
20 Dec 2021 15:46:19 (System) [] Failed to create file /var/lib/dcache/statistics/2021/12/20/2021-12-20-15.raw: File exists or directory not writable : /var/lib/dcache/statistics/2021/12/20/2021-12-20-15.raw
```
