### ISSUE TITLE
Chimera failed to construct terminal (old jline)

### ISSUE THREAD

**Issue by vokac** [dCache/dcache#6411]
It seems to me that dCache is using too old jline 2.14.3 that display exception while starting chimera on CentOS8 with default `TERM=xterm-256color` environment variable:
```sh
[root@dpmhead.farm.particle.cz ~]# chimera 
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
	at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
	at jline.UnixTerminal.<init>(UnixTerminal.java:65)
	at jline.UnixTerminal.<init>(UnixTerminal.java:50)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
	at jline.TerminalFactory.create(TerminalFactory.java:102)
	at jline.TerminalFactory.get(TerminalFactory.java:186)
	at jline.TerminalFactory.get(TerminalFactory.java:192)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:243)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:235)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:223)
	at org.dcache.util.cli.ShellApplication$1.<init>(ShellApplication.java:40)
	at org.dcache.util.cli.ShellApplication.<init>(ShellApplication.java:40)
	at org.dcache.chimera.cli.Shell.<init>(Shell.java:100)
	at org.dcache.chimera.cli.Shell.main(Shell.java:93)

Type 'help' for help on commands.
Type 'exit' or Ctrl+D to exit.
chimera:/#
```
When I change terminal than exception disappears, e.g.
```sh
[root@dpmhead.farm.particle.cz ~]# TERM=vt100 chimera 
Type 'help' for help on commands.
Type 'exit' or Ctrl+D to exit.
chimera:/# 
```
There seems to be related bugreport https://github.com/jline/jline2/issues/281 and this issue was already fixed.

**Comment by kofemann** [comment]
Hi @vokac ,

thanks for reporting. The dependency is updated and will be a part of the next major dCache release.
