### ISSUE TITLE
pool: bug report for 7.2

### ISSUE THREAD

**Issue by DmitryLitvintsev** [dCache/dcache#6456]
reporting bug:

```
04 Feb 2022 19:06:41 (v-stkendca1806-1) [door:NFS-enstore01@nfsDomain:AAXXOukD/Qg NFS-enstore01 PoolDeliverFile 00008FBFF2A3F3B542BCA50AD15FEEF94
E90] Transfer failed due to a disk error: CacheException(rc=204;msg=File could not be opened; please check the file system: Failed to read the fi
le, because file is Broken.)
04 Feb 2022 19:06:41 (v-stkendca1806-1) [door:NFS-enstore01@nfsDomain:AAXXOukD/Qg NFS-enstore01 PoolDeliverFile 00008FBFF2A3F3B542BCA50AD15FEEF94
E90] Pool: v-stkendca1806-1, fault occurred in transfer: File could not be opened; please check the file system: Failed to read the file, because
 file is Broken.. Pool disabled: , cause: CacheException(rc=204;msg=File could not be opened; please check the file system: Failed to read the fi
le, because file is Broken.)
04 Feb 2022 19:06:41 (v-stkendca1806-1) [door:NFS-enstore01@nfsDomain:AAXXOukD/Qg NFS-enstore01 PoolDeliverFile 00008FBFF2A3F3B542BCA50AD15FEEF94
E90] Transfer failed due to a bug
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:221)
        at org.dcache.util.TryCatchTemplate.setCancellable(TryCatchTemplate.java:158)
        at org.dcache.util.TryCatchTemplate.execute(TryCatchTemplate.java:170)
        at org.dcache.util.TryCatchTemplate.<init>(TryCatchTemplate.java:80)
        at org.dcache.pool.movers.AbstractMover$2.<init>(AbstractMover.java:239)
        at org.dcache.pool.movers.AbstractMover.execute(AbstractMover.java:239)
        at org.dcache.pool.classic.MoverRequestScheduler$PrioritizedRequest.transfer(MoverRequestScheduler.java:792)
        at org.dcache.pool.classic.MoverRequestScheduler.sendToExecution(MoverRequestScheduler.java:527)
        at org.dcache.pool.classic.MoverRequestScheduler.getOrCreateMover(MoverRequestScheduler.java:227)
        at org.dcache.pool.classic.IoQueueManager.getOrCreateMover(IoQueueManager.java:162)
        at org.dcache.pool.classic.PoolV4.queueIoRequest(PoolV4.java:789)
        at org.dcache.pool.classic.PoolV4.ioFile(PoolV4.java:796)
        at org.dcache.pool.classic.PoolV4.messageArrived(PoolV4.java:1014)
        at jdk.internal.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.dcache.cells.CellMessageDispatcher$LongReceiver.deliver(CellMessageDispatcher.java:304)
        at org.dcache.cells.CellMessageDispatcher.call(CellMessageDispatcher.java:201)
        at org.dcache.cells.AbstractCell.messageArrived(AbstractCell.java:326)
        at dmg.cells.nucleus.CellAdapter.messageArrived(CellAdapter.java:890)
        at dmg.cells.nucleus.CellNucleus$DeliverMessageTask.run(CellNucleus.java:1316)
        at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:251)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$2(CellNucleus.java:764)
        at java.base/java.lang.Thread.run(Thread.java:829)
04 Feb 2022 19:06:41 (v-stkendca1806-1) [door:NFS-enstore01@nfsDomain:AAXXOukD/Qg NFS-enstore01 PoolDeliverFile 00008FBFF2A3F3B542BCA50AD15FEEF94E90] Transfer failed in post-processing. Please report this bug to support@dcache.org.
java.lang.IllegalStateException: Handle is closed
        at org.dcache.pool.repository.v5.ReadHandleImpl.close(ReadHandleImpl.java:71)
        at org.dcache.pool.classic.DefaultPostTransferService.lambda$execute$1(DefaultPostTransferService.java:115)
        at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:31)
        at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:149)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/13420/

**Comment by paulmillar** [comment]
Incidentally, does the `java.lang.IllegalStateException: Handle is closed` exception have a `Caused by` part?

If you're running dCache v7.2.4 (or newer) then there should be some additional information that is not captured in the original report.
