### ISSUE TITLE
bad SQL grammar for hsqldb in cleaner

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#6496]
with current master (fb67d1e86e)

```
17 Feb 2022 10:22:48 (cleaner) [] Bug detected
java.util.concurrent.CompletionException: org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [DELETE FROM t_locationinfo_trash WHERE ilocation=? AND ipnfsid=? AND itype=1]; nested exception is java.sql.SQLException: statement is not in batch mode
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [DELETE FROM t_locationinfo_trash WHERE ilocation=? AND ipnfsid=? AND itype=1]; nested exception is java.sql.SQLException: statement is not in batch mode
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:647)
	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:936)
	at org.dcache.chimera.namespace.DiskCleaner.removeFiles(DiskCleaner.java:219)
	at org.dcache.chimera.namespace.DiskCleaner.sendRemoveToPoolCleaner(DiskCleaner.java:259)
	at org.dcache.chimera.namespace.DiskCleaner.cleanPoolComplete(DiskCleaner.java:345)
	at org.dcache.chimera.namespace.DiskCleaner.runDelete(DiskCleaner.java:192)
	at org.dcache.chimera.namespace.DiskCleaner.lambda$runDelete$0(DiskCleaner.java:171)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	... 6 common frames omitted
Caused by: java.sql.SQLException: statement is not in batch mode
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlExceptionSQL(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeBatch(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$batchUpdate$2(JdbcTemplate.java:950)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	... 14 common frames omitted
Caused by: org.hsqldb.HsqlException: statement is not in batch mode
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	... 20 common frames omitted
```

**Comment by lemora** [comment]
Hi.

Do you happen to have have trace logging for the time and cleaner instance? I have a suspicion what might have happened, but it needs investigating.
Does this happen often or occasionally? Did you do any stress testing at the time?
