### ISSUE TITLE
NPE during dcache startup 

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#6777]
system test , commit 317f9a6832
```
12 Sep 2022 10:24:21 (qos-engine) [] Thread Thread[pool-326-thread-1,5,qos-engine-threads] died
java.lang.NullPointerException: Cannot invoke "org.dcache.poolmanager.PoolMonitor.getPoolSelectionUnit()" because "this.poolMonitor" is null
	at org.dcache.qos.services.engine.provider.ALRPStorageUnitQoSProvider.poolSelectionUnit(ALRPStorageUnitQoSProvider.java:302)
	at org.dcache.qos.services.engine.provider.ALRPStorageUnitQoSProvider.fetchRequirements(ALRPStorageUnitQoSProvider.java:162)
	at org.dcache.qos.local.clients.LocalQoSRequirementsClient.fileQoSRequirementsRequested(LocalQoSRequirementsClient.java:79)
	at org.dcache.qos.services.engine.handler.FileQoSStatusHandler.fileQoSStatusChanged(FileQoSStatusHandler.java:242)
	at org.dcache.qos.services.engine.handler.FileQoSStatusHandler.lambda$handleAddCacheLocation$0(FileQoSStatusHandler.java:120)
	at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:247)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by alrossi** [comment]
I was unable to reproduce this behavior on either my laptop or my SL7 test node, but it evidently is a race condition.  I'll investigate further.

**Comment by alrossi** [comment]
Is this really during startup (i.e., ```packages/system-test/target/bin/ctlcluster start```) ?  Or are you writing files?
