### ISSUE TITLE
Issue with new CA policies containing DN with comma?

### ISSUE THREAD

**Issue by sfayer** [dCache/dcache#6778]
Hi,

I've noticed that we've started seeing an error in our gPlazma log recently (dCache version 7.2.16):
```
12 Sep 2022 16:32:12 (gPlazma) [SRM-gfe02 Login AUTH x509] policy-lcg.info:102 Problem with 'subjectdn' line: value does not end with '"'
12 Sep 2022 16:32:12 (gPlazma) [SRM-gfe02 Login AUTH x509] policy-lcg.info: bad info file: missing 'subjectdn'
12 Sep 2022 16:32:12 (gPlazma) [SRM-gfe02 Login AUTH x509] policy-igtf-classic.info:84 Problem with 'subjectdn' line: value does not end with '"'
12 Sep 2022 16:32:12 (gPlazma) [SRM-gfe02 Login AUTH x509] policy-igtf-classic.info: bad info file: missing 'subjectdn'
12 Sep 2022 16:32:12 (gPlazma) [SRM-gfe02 Login AUTH x509] policy-egi-core.info:101 Problem with 'subjectdn' line: value does not end with '"'
12 Sep 2022 16:32:12 (gPlazma) [SRM-gfe02 Login AUTH x509] policy-egi-core.info: bad info file: missing 'subjectdn'
12 Sep 2022 16:32:12 (gPlazma) [SRM-gfe02 Login AUTH x509] Bug in plugin:
java.lang.IllegalArgumentException: Chunk [] is not a valid entry
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:210)
        at com.google.common.base.Splitter$MapSplitter.split(Splitter.java:493)
        at org.dcache.gplazma.util.IGTFInfo$Builder.setRequires(IGTFInfo.java:365)
        at org.dcache.gplazma.util.IGTFInfoFile.read(IGTFInfoFile.java:188)
        at org.dcache.gplazma.util.IGTFInfoFile.get(IGTFInfoFile.java:83)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1693)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.dcache.gplazma.util.IGTFInfoDirectory.updateDirectory(IGTFInfoDirectory.java:141)
        at org.dcache.gplazma.util.IGTFInfoDirectory.verifyUptoDate(IGTFInfoDirectory.java:121)
        at org.dcache.gplazma.util.IGTFInfoDirectory.getPrincipals(IGTFInfoDirectory.java:96)
        at org.dcache.gplazma.plugins.X509Plugin.identifyPrincipalsFromIssuer(X509Plugin.java:359)
        at org.dcache.gplazma.plugins.X509Plugin.identifyPrincipalsFromEEC(X509Plugin.java:180)
        at org.dcache.gplazma.plugins.X509Plugin.authenticate(X509Plugin.java:167)
        at org.dcache.gplazma.plugins.GPlazmaAuthenticationPlugin.authenticate(GPlazmaAuthenticationPlugin.java:48)
        at org.dcache.gplazma.strategies.DefaultAuthenticationStrategy.lambda$authenticate$0(DefaultAuthenticationStrategy.java:60)
        at org.dcache.gplazma.strategies.PAMStyleStrategy.callPlugins(PAMStyleStrategy.java:91)
        at org.dcache.gplazma.strategies.DefaultAuthenticationStrategy.authenticate(DefaultAuthenticationStrategy.java:50)
        at org.dcache.gplazma.GPlazma$Setup.doAuthPhase(GPlazma.java:530)
        at org.dcache.gplazma.GPlazma.login(GPlazma.java:250)
        at org.dcache.gplazma.GPlazma.login(GPlazma.java:210)
        at org.dcache.auth.Gplazma2LoginStrategy.login(Gplazma2LoginStrategy.java:193)
        at org.dcache.services.login.MessageHandler.messageArrived(MessageHandler.java:58)
        at jdk.internal.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.dcache.cells.CellMessageDispatcher$LongReceiver.deliver(CellMessageDispatcher.java:286)
        at org.dcache.cells.CellMessageDispatcher.call(CellMessageDispatcher.java:188)
        at org.dcache.cells.AbstractCell.messageArrived(AbstractCell.java:302)
        at dmg.cells.nucleus.CellAdapter.messageArrived(CellAdapter.java:848)
        at dmg.cells.nucleus.CellNucleus$DeliverMessageTask.run(CellNucleus.java:1274)
        at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:247)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$2(CellNucleus.java:727)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
It's not clear if this is actually causing issues beyond the messages in the log: We've not had any complaints but I do see some login failures where I can't see any reason why they shouldn't succeed.

The CA files (as of IGTF release 1.117) now contain some DNs that have an embedded comma, from `/etc/grid-security/certificates/policy-lcg.info`:
```
subjectdn = \
...
  "/DC=DZ/DC=ARN/O=DZ e-Science GRID/CN=DZ e-Science CA", \
  "/C=US/O=DigiCert, Inc./CN=DigiCert Assured ID Grid Client RSA2048 SHA256 2022 CA1", \
  "/C=US/O=DigiCert, Inc./CN=DigiCert Assured ID Grid TLS RSA2048 SHA256 2022 CA1", \
  "/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Root CA", \
...
```
Could this be causing a problem for dCache? (I realise I'm not running the latest patch release, but I didn't see any reference to this being fixed recently in the release notes).

(For reference) ARGUS had problems with the new CA DNs although I don't think it has much else in common: https://ggus.eu/index.php?mode=ticket_info&ticket_id=158702

Regards,
Simon

**Comment by kofemann** [comment]
Hi Simon.
I run some local tests and can read policy-lcg.info file without issues. There might be some other file causing the problem. Can you please tar and send the whole `/etc/grid-security/certificates/` directory.

**Comment by kofemann** [comment]
looks like the `bad` file is `policy-igtf-slcs.info`

**Comment by kofemann** [comment]
https://rb.dcache.org/r/13675/
