### ISSUE TITLE
8.2 NPE on Spacemanager startup if spacemanager.authz.link-group-file-name is not set

### ISSUE THREAD

**Issue by ageorget** [dCache/dcache#6817]
Hi,

I'm testing dCache upgrade from 8.1 to 8.2 version and I faced an issue with Spacemanager during startup : 

```
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]: 07 Oct 2022 10:25:58 (SpaceManager3) [] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'linkgroup-loader' defined in class path resource [diskCacheV111/services/space/spacemanager.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]: PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'authorizationFileName' threw exception; nested exception is java.lang.NullPointerException
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]: 07 Oct 2022 10:25:58 (System) [] Bug detected in dCache; please report this to <support@dcache.org> with the following information.
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]: org.springframework.beans.PropertyBatchUpdateException: Failed properties: Property 'authorizationFileName' threw exception; nested exception is java.lang.NullPointerException
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:135)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:79)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1735)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1447)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at org.dcache.cells.UniversalSpringCell.createContext(UniversalSpringCell.java:1067)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at org.dcache.cells.UniversalSpringCell.starting(UniversalSpringCell.java:235)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at dmg.cells.nucleus.CellAdapter.prepareStartup(CellAdapter.java:689)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at dmg.cells.nucleus.CellNucleus.doStart(CellNucleus.java:899)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$3(CellNucleus.java:735)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:247)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$2(CellNucleus.java:727)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]:         at java.base/java.lang.Thread.run(Thread.java:829)
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]: 07 Oct 2022 10:25:58 (System) [] Failure at startup: (666) URL [file:/usr/share/dcache/services/spacemanager.batch]: line 27: (1) Command failed: org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
Oct 07 10:25:58 ccdcamcli22 dcache@SpaceManagerDomain3[4064941]: PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'authorizationFileName' threw exception; nested exception is java.lang.NullPointerException
```

It looks related to the commit https://github.com/dcache/dcache/commit/0acb2433ea9096df4eb8593e4c8c79bac3b36e1b
Even if space-reservation is disabled with `dcache.enable.space-reservation=false` and `spacemanager.enable.unreserved-uploads-to-linkgroups=false`, the spacemanager is now asking for a filename.
The problem disappeared after setting `spacemanager.authz.link-group-file-name=/tmp/toto`

Adrien

**Comment by kofemann** [comment]
Thanks @ageorget for the info and early testing!
