### ISSUE TITLE
NFS issue after upgrading to 8.2

### ISSUE THREAD

**Issue by elenamplanas** [dCache/dcache#6855]
We've upgraded our test environment to 8.2, and we've faced a problem when trying to mount if the NFS cell is in the same server with the namespace Domain.
There are no problems when the NFS door is in other server.

In our environment we've different NFS doors for different purposes.
- a NFS 3 and 4.1 door sharing server with the pnfsmanager, which is used to export /pnfs path internally (on pools for Enstore use, head-nodes, etc)
- few NFS 4.1 doors in "door" servers with other door services (to be used by final users)

Our configuration where we found the problem is this:

```
## dCache Layout for dcns04-test.pic.es

############################################
# Domain: namespace-dcns04-testDomain
[namespace-${host.name}Domain]
dcache.broker.scheme=core
dcache.java.memory.heap=3072m
pnfsmanager.default-access-latency=ONLINE
pnfsmanager.default-retention-policy=REPLICA
pnfsmanager.enable.folding=true
pnfsmanager.plugins.storage-info-extractor=org.dcache.chimera.namespace.ChimeraEnstoreStorageInfoExtractor
# Cell: cleaner
[namespace-${host.name}Domain/cleaner]
cleaner.enable.hsm=false
# Cell: pnfsmanager
[namespace-${host.name}Domain/pnfsmanager]
pnfsmanager.enable.acl=true
## End namespace-dcns04-testDomain
############################################

############################################
# Domain: nfsv3-dcns04-testDomain
[nfsv3-${host.name}Domain]
dcache.java.memory.heap=512m
# Cell: nfs
[nfsv3-${host.name}Domain/nfs]
nfs.domain=pic.es
nfs.idmap.legacy=true
nfs.loginbroker.family=nfsv3
nfs.loginbroker.tags=srm
nfs.mover.queue=nfs4
nfs.version=3,4.1
## End nfsv3-dcns04-testDomain
############################################
```
And the error what appears when trying to mount (locally or from a remote server) is:
```
04 Nov 2022 12:05:38 (NFS-dcns04-test) [] Uncaught exception in thread OncRpcSvc (3)
com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: 'void org.dcache.nfs.vfs.Stat.setIno(int)'
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2053)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
	at org.dcache.nfs.vfs.VfsCache.statFromCacheOrLoad(VfsCache.java:247)
	at org.dcache.nfs.vfs.VfsCache.getattr(VfsCache.java:177)
	at org.dcache.nfs.vfs.ForwardingFileSystem.getattr(ForwardingFileSystem.java:137)
	at org.dcache.nfs.v3.MountServer.MOUNTPROC3_MNT_3(MountServer.java:106)
	at org.dcache.nfs.v3.xdr.mount_protServerStub.dispatchOncRpcCall(mount_protServerStub.java:56)
	at org.dcache.oncrpc4j.rpc.RpcDispatcher$1.lambda$run$0(RpcDispatcher.java:100)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
	at org.dcache.oncrpc4j.rpc.RpcDispatcher$1.run(RpcDispatcher.java:99)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoSuchMethodError: 'void org.dcache.nfs.vfs.Stat.setIno(int)'
	at org.dcache.chimera.nfsv41.door.ChimeraVfs.fromChimeraStat(ChimeraVfs.java:432)
	at org.dcache.chimera.nfsv41.door.ChimeraVfs.getattr(ChimeraVfs.java:332)
	at org.dcache.nfs.vfs.VfsCache.lambda$statFromCacheOrLoad$0(VfsCache.java:247)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	... 14 common frames omitted
```
We've seen that the nfs4.jar has been upgraded from nfs4j-core-0.22.2.jar (on dCache 7.2) to nfs4j-core-0.23.0.jar.

We also tried exportin only nfsv4.1 but the same problem was faced when trying to mount, locally or on a remote server.
To do a last test, we changed the jar file, using the previous version, and the error doesn't appear.
```
[root@dcns04-test ~]# ll /usr/share/dcache/classes/nfs4j*
-rw-r--r-- 1 root root 941491 Nov  7 15:28 /usr/share/dcache/classe s/nfs4j-core-0.22.2.jar
lrwxrwxrwx 1 root root     21 Nov  7 15:29 /usr/share/dcache/classes/nfs4j-core-0.23.0.jar -> nfs4j-core-0.22.2.jar
-rw-r--r-- 1 root root 945550 Oct 21 16:05 /usr/share/dcache/classes/nfs4j-core-0.23.0.jar_original
```

We don't know if there is a misconfiguration on our side, or if there is a bug.
The new nfs4j version is working correctly on all others NFS doors.

Thanks

**Comment by kofemann** [comment]
Hi @elenamplanas ,

Looks like you had a custom jar file on your system.
You can check the content of the rpm file as:

```
$ rpm -qlp ~/Downloads/dcache-8.2.3-1.noarch.rpm | grep nfs                                                                         (git)-[master] 
/usr/share/dcache/classes/dcache-nfs-8.2.3.jar
/usr/share/dcache/classes/nfs4j-core-0.23.0.jar
/usr/share/dcache/defaults/nfs.properties
/usr/share/dcache/defaults/pnfsmanager.properties
/usr/share/dcache/httpd/static/images/pnfslogo1.gif
/usr/share/dcache/httpd/static/images/pnfslogotrans.gif
/usr/share/dcache/lib/preparePnfs.sh
/usr/share/dcache/pnfs
/usr/share/dcache/pnfs/psql_drop_companion.sql
/usr/share/dcache/pnfs/psql_install_companion.sql
/usr/share/dcache/services/nfs.batch
/usr/share/dcache/services/pnfsmanager.batch
/var/lib/dcache/nfs

```

**Comment by elenamplanas** [comment]
Hi @kofemann ,

yes, I put the previous version of nfs4j. 
Using the file /usr/share/dcache/classes/nfs4j-core-0.23.0.jar, the one provided in the rpm, we faced the problem to mount, but when we put the nfs4j-core-0.22.0.jar in place, the "problem" was solved and we could mount the /pnfs path without errors.

**Comment by elenamplanas** [comment]
I've upgraded another environment using rpm of version 8.2.4 and we've not faced the problem.
I'm going to upgrade the environment where we faced the problem to the same version and if it's still failing then there should be a problem on our configuration.
Thanks.
