### ISSUE TITLE
dCache upgrade to 8.2.4 staging pool errors

### ISSUE THREAD

**Issue by cfgamboa** [dCache/dcache#6868]
Dear all,

A dCache integration instance is upgraded from 7.2 to 8.2.4. After that the restores via ENDIT to HPSS are not working. The writes worked but there are fail attemps
For example the restore of a file `00000CAE5AAE1EE84656AC16E080361336D9`
````
[dcqos001] (dcqos005_4@dcqos005fourDomain) admin > rh ls
80397291-6dd1-4a2d-89dc-226bb19bc5bc ACTIVE Wed Nov 16 19:14:32 EST 2022 Wed Nov 16 19:14:32 EST 2022 00007FC1F3631E4D45D2A6EA8CA24F52AA54 tapedata:TAPEDATA
0d276499-ea26-435d-9244-c90954a08151 ACTIVE Thu Nov 17 10:41:29 EST 2022 Thu Nov 17 10:41:29 EST 2022 00000CAE5AAE1EE84656AC16E080361336D9 tapedata:TAPEDATA
```

The are error stack observed is 
```
17 Nov 2022 10:41:30 [dcqos005_4-0] [door:WebDAV2-dcqos002-2@webdav2-dcqos002_httpsDomain:AAXtrGxBPXA PoolManager PoolFetchFile 00000CAE5AAE1EE84656AC16E080361336D9] Uncaught exception in thread dcqos005_4-0java.lang.NoSuchMethodError: 'com.google.common.util.concurrent.ListenableFuture com.google.common.util.concurrent.Futures.transformAsync(com.google.common.util.concurrent.ListenableFuture, com.google.common.util.concurrent.AsyncFunction)'
	at org.ndgf.endit.AbstractEnditNearlineStorage.stage(AbstractEnditNearlineStorage.java:137)
	at org.ndgf.endit.ListeningNearlineStorage.stage(ListeningNearlineStorage.java:65)
	at org.dcache.pool.nearline.NearlineStorageHandler$StageRequestContainer.submit(NearlineStorageHandler.java:929)
	at org.dcache.pool.nearline.NearlineStorageHandler$AbstractRequestContainer.addAll(NearlineStorageHandler.java:770)
	at org.dcache.pool.nearline.NearlineStorageHandler.stage(NearlineStorageHandler.java:406)
	at org.dcache.pool.classic.PoolV4.messageArrived(PoolV4.java:1021)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.dcache.cells.CellMessageDispatcher$ShortReceiver.deliver(CellMessageDispatcher.java:272)
	at org.dcache.cells.CellMessageDispatcher.call(CellMessageDispatcher.java:188)
	at org.dcache.cells.AbstractCell.messageArrived(AbstractCell.java:302)
	at dmg.cells.nucleus.CellAdapter.messageArrived(CellAdapter.java:856)
	at dmg.cells.nucleus.CellNucleus$DeliverMessageTask.run(CellNucleus.java:1274)
	at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:247)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$2(CellNucleus.java:727)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

Could you please advise?

All the best,
Carlos

**Comment by cfgamboa** [comment]
Hello,
Note that if I downgrade the pool node to 7.2.16 the restore resumes 

All the best,
Carlos

**Comment by mksahakyan** [comment]
Hi Carlos, there is an issue with ENDIT, this has been fixed by @krishna-veni,  you will need to upgrade to a newer  version.

**Comment by cfgamboa** [comment]
Hello @mksahakyan 
What the release contains the fix?

All the best,
Carlos

**Comment by cfgamboa** [comment]
@krishna-veni thank you, it seems that is working now.
