### ISSUE TITLE
RemoteTransferManager-5990java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by cfgamboa** [dCache/dcache#6886]
Hello 

I came across to this error and I am reporting it accordingly

dCache 7.2.16-2

[root@dcdoor13 dcache]# zgrep AAXuHjPk+bg webdav2-dcdoor13_httpsDomain.log-20221123.gz 
23 Nov 2022 02:26:10 (WebDAV2-dcdoor13-2) [door:WebDAV2-dcdoor13-2@webdav2-dcdoor13_httpsDomain:AAXuHjPk+bg] Failed to fetch information for progress marker: 

```
23 nov. 2022 02:26:10 [RemoteTransferManager-5990] [door:WebDAV2-dcdoor13-2@webdav2-dcdoor13_httpsDomain:AAXuHjPk+bg WebDAV2-dcdoor13-2 TransferStatusQuery] Uncaught exception in thread RemoteTransferManager-5990java.lang.NullPointerException: null
	at diskCacheV111.services.TransferManagerHandler.dnGetmoverId(TransferManagerHandler.java)
	at diskCacheV111.services.TransferManagerHandler.appendInfo(TransferManagerHandler.java:844)
	at diskCacheV111.services.TransferManager.messageArrived(TransferManager.java:247)
	at jdk.internal.reflect.GeneratedMethodAccessor304.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.dcache.cells.CellMessageDispatcher$LongReceiver.deliver(CellMessageDispatcher.java:286)
	at org.dcache.cells.CellMessageDispatcher.call(CellMessageDispatcher.java:188)
	at org.dcache.cells.AbstractCell.messageArrived(AbstractCell.java:302)
	at dmg.cells.nucleus.CellAdapter.messageArrived(CellAdapter.java:848)
	at dmg.cells.nucleus.CellNucleus$DeliverMessageTask.run(CellNucleus.java:1274)
	at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:247)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$2(CellNucleus.java:727)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
All the best,
Carlos

**Comment by paulmillar** [comment]
Thanks for reporting this.

A couple of questions:

How often have you seen this error (with `dnGetmoverId`) ?

Did this report coincide with the domain hosting the transfermanagers service being restart?

**Comment by cfgamboa** [comment]
Hello 

Not often,  this is first observation of it. 
The transfermanager was not restarted at observation time

All the best,
Carlos

**Comment by kofemann** [comment]
Closing ticket in favor of RT https://rt.dcache.org/Ticket/Display.html?id=10455
