### ISSUE TITLE
xrootd proxy mode Uncaught exception in thread xrootd-net-17

### ISSUE THREAD

**Issue by cfgamboa** [dCache/dcache#6912]
Hello Al 

Another issue here. While the fix seemed to address the issue described on the ticket #6875, I have now observed that if that a file hosted in a pool at the same host where the door runs the transfer does not work for read.

This works:
```
[cgamboa@lxplus733 ~]$ xrdcp -f root://dcqos002.usatlas.bnl.gov:1094/pnfs/usatlas.bnl.gov/diskdata/gamboa/test_carlos_diskonly.8.2.4 test.1
[4.738MB/4.738MB][100%][==================================================][808.6kB/s]  
```
The pool hosting the file is, (dcqos005.usatlas.bnl.gov) is internal on IPV6/IPV4:

```
[dcqos001] (dcqos005_9@dcqos005nineDomain) admin > \sn cacheinfoof /pnfs/usatlas.bnl.gov/diskdata/gamboa/test_carlos_diskonly.8.2.4
 dcqos005_9
```

**On this case the pool hosting the file is located on the door server. The door server has external/internal connectivity  on IPV6/IPV4.**
```
[dcqos001] (dcqos005_9@dcqos005nineDomain) admin > \sn cacheinfoof /pnfs/usatlas.bnl.gov/diskdata/new_test_hsi_20
 dcqos001_8
```

xrootd log
```
Dec  6 14:30:14 dcqos001 dcache@xrootd-dcqos001Domain: 06 Dec 2022 14:30:14 (Xrootd-dcqos001-proxy) [] proxy 7cb23dcb-c6ca-467b-8130-00719a220449, channel inactive event received on [id: 0x6392b5a5, L:/10.42.38.45:55642 ! R:/10.42.38.45:33313].
Dec  6 14:30:19 dcqos001 dcache@xrootd-dcqos001Domain: 06 Dec 2022 14:30:19 (Xrootd-dcqos001-proxy) [] proxy 7cb23dcb-c6ca-467b-8130-00719a220449, channel inactive event received on [id: 0x9fdc2d0d, L:::/0:0:0:0:0:0:0:0:32399].
```

Pool log shows  
```
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: 06 Dec 2022 14:30:14 (dcqos001_8) [] Uncaught exception in thread xrootd-net-17
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: java.lang.NoClassDefFoundError: org/dcache/xrootd/pool/ChunkedFileDescriptorReadResponse
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at org.dcache.xrootd.pool.XrootdPoolRequestHandler.doOnRead(XrootdPoolRequestHandler.java:618)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at org.dcache.xrootd.core.XrootdRequestHandler.getResponse(XrootdRequestHandler.java:200)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at org.dcache.xrootd.core.XrootdRequestHandler.requestReceived(XrootdRequestHandler.java:166)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at org.dcache.xrootd.core.XrootdRequestHandler.channelRead(XrootdRequestHandler.java:115)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at org.dcache.util.ChannelCdcSessionHandlerWrapper.channelRead(ChannelCdcSessionHandlerWrapper.java:158)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at org.dcache.util.CDCThreadFactory.lambda$newThread$0(CDCThreadFactory.java:42)
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: at java.base/java.lang.Thread.run(Thread.java:829)
```

Thank you,
Carlos

**Comment by alrossi** [comment]
I'll have another look at this tomorrow, Carlos, but at first blush this doesn't look like it might seem.

If the pool error is the only error you are seeing, 

```
Dec  6 14:30:14 dcqos001 dcache@dcqos001eightDomain: java.lang.NoClassDefFoundError: org/dcache/xrootd/pool/ChunkedFileDescriptorReadResponse
```

Seems to indicate that you have conflicting .jars.  I don't know how that might have happened.  

The door and the pool share the same libraries, right?

```
ls -l  /usr/share/dcache/classes/*xroot*.jar
```

shows what?

My analysis may be wrong here.   But if it is not, then I will probably need more logging information from the door.

Thanks ... Al

**Comment by cfgamboa** [comment]
Hi Al,

I am overwriting the dcache-xrootd-8.2.4.jar with your latest code updates. 
```
[root@dcqos001 ~]# ls -l  /usr/share/dcache/classes/*xroot*.jar
-rw-r--r-- 1 root root 176095 Dec  4 15:40 /usr/share/dcache/classes/dcache-xrootd-8.2.4.jar
-rw-r--r-- 1 root root 269037 Nov  9 09:33 /usr/share/dcache/classes/xrootd4j-4.5.2.jar
-rw-r--r-- 1 root root  30944 Nov  9 09:33 /usr/share/dcache/classes/xrootd4j-authz-plugin-alice-1.2.0.jar
-rw-r--r-- 1 root root  92163 Nov  9 09:33 /usr/share/dcache/classes/xrootd4j-gsi-4.5.2.jar
-rw-r--r-- 1 root root   6787 Nov  9 09:33 /usr/share/dcache/classes/xrootd4j-scitokens-4.5.2.jar
-rw-r--r-- 1 root root   8175 Nov  9 09:33 /usr/share/dcache/classes/xrootd4j-unix-4.5.2.jar
-rw-r--r-- 1 root root  15507 Nov  9 09:33 /usr/share/dcache/classes/xrootd4j-ztn-4.5.2.jar
```
All the best,
Carlos

**Comment by alrossi** [comment]
When you overwrote the .jars, did you restart the pool as well as the door?

**Comment by cfgamboa** [comment]
Well Al, you nailed it:
After restarting the pool containing the file 

```
[root@dcqos001 ~]# systemctl restart dcache@dcqos001eightDomain.service
```

This worked
```
[cgamboa@lxplus733 ~]$ xrdcp -f root://dcqos002.usatlas.bnl.gov:1096/pnfs/usatlas.bnl.gov/diskdata/new_test_hsi_20 test.1
[63.37kB/63.37kB][100%][==================================================][21.12kB/s]  
```
And 
```
[cgamboa@lxplus733 ~]$ xrdcp -f root://dcqos001.usatlas.bnl.gov:1096/pnfs/usatlas.bnl.gov/diskdata/new_test_hsi_20 test.1
[63.37kB/63.37kB][100%][==================================================][31.68kB/s]  
```
Thank you,
Carlos

**Comment by alrossi** [comment]
Too easy.  I'm skeptical (::smile::).

But glad it worked!

Cheers, Al

(can we close this?)

**Comment by cfgamboa** [comment]
yes, please. until next time... ;)
