### ISSUE TITLE
NPE in QoS module

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#6934]
```
02 Jan 2023 12:23:06 (qos-verifier) [] Error during fire and forget:
diskCacheV111.util.CacheException: Bug detected: java.lang.NullPointerException
	at org.dcache.qos.util.ErrorAwareTask.lambda$toFireAndForgetTask$1(ErrorAwareTask.java:87)
	at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:28)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException: null
	at org.dcache.qos.services.verifier.data.PoolInfoMap.isPoolDraining(PoolInfoMap.java:600)
	at org.dcache.qos.services.verifier.handlers.FileStatusVerifier.verify(FileStatusVerifier.java:138)
	at org.dcache.qos.services.verifier.handlers.VerifyOperationHandler.handleVerification(VerifyOperationHandler.java:359)
	at org.dcache.qos.services.verifier.util.VerificationTask.run(VerificationTask.java:89)
	at org.dcache.qos.util.ErrorAwareTask.lambda$toFireAndForgetTask$1(ErrorAwareTask.java:84)
	... 7 common frames omitted
```

**Comment by alrossi** [comment]
```
org.dcache.qos.services.verifier.data.PoolInfoMap.isPoolDraining(PoolInfoMap.java:600)
```

is

```
           if (info == null || info.getMode() == null) {
                return false;
            }
```

???

**Comment by kofemann** [comment]
Ah, my branch behind the master, thus I miss the commit d39815e55a69d9f64e7d9561ce06c291cb12e623
