### ISSUE TITLE
Telemetry collector refuses connections

### ISSUE THREAD

**Issue by ageorget** [dCache/dcache#6973]
Hi,
I just want to report that the dCache telemetry collector is refusing connections for weeks now (since November 8th exactly):
```

Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]: 25 Jan 2023 15:48:22 (Telemetry) [] Sending data to https://stats.dcache.org/collector failed, caused by:
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]: java.net.ConnectException: Connection refused
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:561)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at org.dcache.telemetry.SendData.sendData(SendData.java:110)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:28)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:130)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]:         at java.base/java.lang.Thread.run(Thread.java:829)
Jan 25 15:48:22 ccdcamcli20 dcache@infoDomain[2798639]: Caused by: java.net.ConnectException: Connection refused
```

Adrien

**Comment by paulmillar** [comment]
Thanks for reporting this Adrien.

Just to add a comment. Separately from the underlying network problem,  dCache should only log a stack-trace if there is a (dCache-internal) bug.  Therefore, I think dCache shouldn't be logging a stack-trace in this case.

**Comment by ageorget** [comment]
I agree that a warning message is better than a stack-trace for this kind of problem.
BTW, looks like the Telemetry collector is working now :)

**Comment by kofemann** [comment]
The service is fixed and the code is update to avoid stack-traces.
