### ISSUE TITLE
IndexOutOfBounds error on pools with histogram (history)

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#6979]
```
27 Jan. 2023 14:21:10 [pool-7-thread-1981] [] Uncaught exception in
thread pool-7-thread-1981java.lang.IndexOutOfBoundsException: Index 576
out of bounds for length 576
     at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
     at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
     at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
     at java.base/java.util.Objects.checkIndex(Objects.java:372)
     at java.base/java.util.ArrayList.set(ArrayList.java:473)
     at org.dcache.util.histograms.TimeseriesHistogram.update(TimeseriesHistogram.java:241)
     at org.dcache.util.histograms.TimeseriesHistogram.replace(TimeseriesHistogram.java:150)
     at org.dcache.util.collector.pools.PoolInfoCollectorUtils.updateQueueSeries(PoolInfoCollectorUtils.java:554)
     at org.dcache.util.collector.pools.PoolInfoCollectorUtils.updateQstatTimeSeries(PoolInfoCollectorUtils.java:583)
     at org.dcache.util.collector.pools.PoolInfoCollectorUtils.updateQstatTimeSeries(PoolInfoCollectorUtils.java:515)
     at org.dcache.util.collector.pools.PoolHistoriesAggregator.update(PoolHistoriesAggregator.java:102)
     at org.dcache.util.collector.pools.PoolInfoAggregator.lambda$aggregateDataForPoolGroups$0(PoolInfoAggregator.java:99)
     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
     at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
     at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1693)
     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
     at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
     at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
     at org.dcache.util.collector.pools.PoolInfoAggregator.aggregateDataForPoolGroups(PoolInfoAggregator.java:94)
     at org.dcache.services.history.pools.PoolHistoriesRequestProcessor.postProcess(PoolHistoriesRequestProcessor.java:184)
     at org.dcache.util.collector.RequestFutureProcessor.waitUntilFinished(RequestFutureProcessor.java:230)
     at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:247)
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
     at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by alrossi** [comment]
See https://rb.dcache.org/r/13869/
