### ISSUE TITLE
bulk:  NPE in existence check when submitting target

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#6997]
There is a neglected join somewhere (this is 9.0) which is causing the uid value of the request to be null

```
03 Feb 2023 08:07:43 (bulk) [] Uncaught exception in thread pool-11-thread-1
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3965)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950)
        at org.dcache.services.bulk.store.jdbc.request.JdbcBulkRequestStore.getRequest(JdbcBulkRequestStore.java:311)
        at org.dcache.services.bulk.handler.BulkRequestHandler.requestExists(BulkRequestHandler.java:296)
        at org.dcache.services.bulk.handler.BulkRequestHandler.isRequestActive(BulkRequestHandler.java:278)
        at org.dcache.services.bulk.handler.BulkRequestHandler.storeJobTarget(BulkRequestHandler.java:327)
        at org.dcache.services.bulk.handler.BulkRequestHandler.submitRequestJob(BulkRequestHandler.java:214)
        at org.dcache.services.bulk.manager.ConcurrentRequestManager.activateRequest(ConcurrentRequestManager.java:475)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.dcache.services.bulk.manager.ConcurrentRequestManager$ConcurrentRequestProcessor.processNextRequests(ConcurrentRequestManager.java:233)
        at org.dcache.services.bulk.manager.ConcurrentRequestManager$ConcurrentRequestProcessor.doRun(ConcurrentRequestManager.java:204)
        at org.dcache.services.bulk.manager.ConcurrentRequestManager$ConcurrentRequestProcessor.run(ConcurrentRequestManager.java:133)
        at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:130)
        at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:247)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by alrossi** [comment]
Note:  this basically stops target processing so it is urgent, but it only affects the most recent changes to master, not the released versions.
