### ISSUE TITLE
NPE with Webdav door on DELETE

### ISSUE THREAD

**Issue by ageorget** [dCache/dcache#7035]
Hello dCache team,

For few weeks, we observed some NPE stacktraces in the Webdav door logs during some DELETE operations on SAM tests directories : 

```
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: 28 Feb 2023 14:14:22 (webdav-ccdcatli310) [door:webdav-ccdcatli310@webdav-ccdcatli310Domain:AAX1wliYe9A] Internal server error
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: java.lang.NullPointerException: null
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at java.base/java.util.ArrayList.addAll(ArrayList.java:702)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at io.milton.http.DeleteHelperImpl.isLockedOut(DeleteHelperImpl.java:65)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at io.milton.http.http11.DeleteHandler.processExistingResource(DeleteHandler.java:92)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:131)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at io.milton.http.http11.DeleteHandler.processResource(DeleteHandler.java:83)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.dcache.webdav.DcacheResourceHandlerHelper.process(DcacheResourceHandlerHelper.java:42)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at io.milton.http.http11.DeleteHandler.process(DeleteHandler.java:72)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.dcache.webdav.DcacheStandardFilter.process(DcacheStandardFilter.java:50)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at io.milton.http.FilterChain.process(FilterChain.java:46)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.dcache.webdav.transfer.CopyFilter.process(CopyFilter.java:276)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at io.milton.http.FilterChain.process(FilterChain.java:46)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at io.milton.http.HttpManager.process(HttpManager.java:158)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.dcache.webdav.MiltonHandler.handle(MiltonHandler.java:77)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.dcache.http.AuthenticationHandler.access$001(AuthenticationHandler.java:55)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.dcache.http.AuthenticationHandler.lambda$handle$0(AuthenticationHandler.java:156)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at java.base/java.security.AccessController.doPrivileged(Native Method)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.dcache.http.AuthenticationHandler.handle(AuthenticationHandler.java:153)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.dcache.http.AbstractLoggingHandler.handle(AbstractLoggingHandler.java:110)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:322)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.server.Server.handle(Server.java:516)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
Feb 28 14:14:22 ccdcatli310 dcache@webdav-ccdcatli310Domain[24260]: at java.base/java.lang.Thread.run(Thread.java:829)
```

The DELETE request : 
`
level=ERROR ts=2023-02-28T14:14:22.481+0100 event=org.dcache.webdav.request request.method=DELETE request.url=https://ccdavcms.in2p3.fr:2880/disk/data/store/unmerged/SAM.se_webdav_etf01_ccdavcms_cert/ response.code=500 socket.remote=188.184.81.101:8212 user-agent="org.cms.SE-WebDAV/v2.00.01 gfal2/2.21.2 neon/0.0.29" user.dn="CN=1970364652,CN=1397016715,CN=140829103,CN=900206079,CN=Andrea Sciaba,CN=430796,CN=sciaba,OU=Users,OU=Organic Units,DC=cern,DC=ch" user.mapped=3033:119 duration=120078`

The directory exists and is empty so I don't understand what's raising this NPE error.
dCache 8.2.7

Adrien

**Comment by kofemann** [comment]
The problem comes from inconsistency in milton library.

https://github.com/miltonio/milton2/issues/184

However, I don't expect that they will fix it. Thus we need to fix it on our side.
