### ISSUE TITLE
8.2.18 

### ISSUE THREAD

**Issue by cfgamboa** [dCache/dcache#7104]
This error is observed in dCache 8.2.18, the error is observed on the Bulk cell.
```
bulk:
    30 Mar 2023 13:45:43 [bulk-0] [] Cell message monitoring set to false
    30 Mar 2023 13:45:43 [bulk-0] [] Cell classification set to null
    30 Mar 2023 13:45:51 [bulk-0] [] HikariPool-1 - Starting...
    30 Mar 2023 13:45:52 [bulk-0] [] HikariPool-1 - Start completed.
    30 Mar 2023 13:46:07 [bulk-0] [] Initializing the activity factory.
    30 Mar 2023 13:46:08 [bulk-0] [] pinging PnfsManager ...
    30 Mar 2023 13:46:08 [bulk-0] [] PnfsManager unavailable, waiting 5 seconds.
    30 Mar 2023 13:46:13 [bulk-0] [] PnfsManager unavailable, waiting 5 seconds.
    30 Mar 2023 13:46:18 [bulk-0] [] PnfsManager unavailable, waiting 5 seconds.
    30 Mar 2023 13:46:23 [bulk-0] [] PnfsManager unavailable, waiting 5 seconds.
    30 Mar 2023 13:46:28 [bulk-0] [] PnfsManager unavailable, waiting 5 seconds.
    30 Mar 2023 13:46:33 [bulk-0] [] PnfsManager unavailable, waiting 5 seconds.
    30 Mar 2023 13:46:38 [bulk-0] [] PnfsManager unavailable, waiting 5 seconds.
    30 Mar 2023 13:46:43 [bulk-0] [] PnfsManager unavailable, waiting 5 seconds.
    30 Mar 2023 13:46:49 [pool-6-thread-1] [] Loading requests into the request store/queue; incomplete requests will be reset to QUEUED.
    30 Mar 2023 13:46:49 [pool-6-thread-1] [] Initializing the job manager.
    30 Mar 2023 13:46:49 [pool-6-thread-1] [] Signalling the job manager.
    30 Mar 2023 13:46:49 [pool-6-thread-1] [] Service startup completed.
    30 Mar 2023 13:46:49 [pool-7-thread-9] [] addInfo 7cb9ebbf-c103-4842-b88a-e17d4db5ffb2, path /pnfs/usatlas.bnl.gov/qostape/valid3/TAG/e1574_s1969_r5790/valid3.156512.Herwigpp_UEEE3_CTEQ6L1_Gtt_G850_T2500_L1.recon.TAG.e1574_s1969_r5790_tid01574526_00/TAG.01574526._000171.pool.root.4, error No such file or directory /pnfs/usatlas.bnl.gov/qostape/valid3/TAG/e1574_s1969_r5790/valid3.156512.Herwigpp_UEEE3_CTEQ6L1_Gtt_G850_T2500_L1.recon.TAG.e1574_s1969_r5790_tid01574526_00/TAG.01574526._000171.pool.root.4.
    30 Mar 2023 13:46:49 [pool-7-thread-8] [] Uncaught exception in thread pool-7-thread-8org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; ERROR: value too long for type character varying(256); nested exception is org.postgresql.util.PSQLException: ERROR: value too long for type character varying(256)
    	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104)
    	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
    	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
    	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
    	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)
    	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
    	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:893)
    	at org.dcache.services.bulk.store.jdbc.JdbcBulkDaoUtils.insert(JdbcBulkDaoUtils.java:267)
    	at org.dcache.services.bulk.store.jdbc.JdbcBulkDaoUtils.upsert(JdbcBulkDaoUtils.java:259)
    	at org.dcache.services.bulk.store.jdbc.rtarget.JdbcRequestTargetDao.insertOrUpdate(JdbcRequestTargetDao.java:174)
    	at org.dcache.services.bulk.store.jdbc.rtarget.JdbcBulkTargetStore.storeOrUpdate(JdbcBulkTargetStore.java:208)
    	at org.dcache.services.bulk.job.PrestoreRequestContainerJob.store(PrestoreRequestContainerJob.java:335)
    	at org.dcache.services.bulk.job.PrestoreRequestContainerJob.storeAll(PrestoreRequestContainerJob.java:376)
    	at org.dcache.services.bulk.job.PrestoreRequestContainerJob.preprocessTargets(PrestoreRequestContainerJob.java:150)
    	at org.dcache.services.bulk.job.AbstractRequestContainerJob.run(AbstractRequestContainerJob.java:283)
    	at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:28)
    	at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:130)
    	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
    	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
    	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
    	at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:247)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    	at java.base/java.lang.Thread.run(Thread.java:829)
    Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(256)
    	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
    	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
    	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
    	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
    	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
    	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
    	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:134)
    	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
    	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
    	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$1(JdbcTemplate.java:894)
    	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
    	... 19 common frames omitted
    
    30 Mar 2023 13:46:49 [pool-7-thread-7] [] Uncaught exception in thread pool-7-thread-7org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; ERROR: value too long for type character varying(256); nested exception is org.postgresql.util.PSQLException: ERROR: value too long for type character varying(256)
    	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104)
    	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
    	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
    	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
    	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)
    	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
    	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:893)
    	at org.dcache.services.bulk.store.jdbc.JdbcBulkDaoUtils.insert(JdbcBulkDaoUtils.java:267)
    	at org.dcache.services.bulk.store.jdbc.JdbcBulkDaoUtils.upsert(JdbcBulkDaoUtils.java:259)
    	at org.dcache.services.bulk.store.jdbc.rtarget.JdbcRequestTargetDao.insertOrUpdate(JdbcRequestTargetDao.java:174)
    	at org.dcache.services.bulk.store.jdbc.rtarget.JdbcBulkTargetStore.storeOrUpdate(JdbcBulkTargetStore.java:208)
    	at org.dcache.services.bulk.job.PrestoreRequestContainerJob.store(PrestoreRequestContainerJob.java:335)
    	at org.dcache.services.bulk.job.PrestoreRequestContainerJob.storeAll(PrestoreRequestContainerJob.java:376)
    	at org.dcache.services.bulk.job.PrestoreRequestContainerJob.preprocessTargets(PrestoreRequestContainerJob.java:150)
    	at org.dcache.services.bulk.job.AbstractRequestContainerJob.run(AbstractRequestContainerJob.java:283)
    	at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:28)
    	at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:130)
    	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
    	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
    	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
    	at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:247)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    	at java.base/java.lang.Thread.run(Thread.java:829)
    Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(256)
    	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
    	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
    	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
    	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
    	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
    	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
    	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:134)
    	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
    	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
    	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$1(JdbcTemplate.java:894)
    	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
    	... 19 common frames omitted
        ```

**Comment by maatthias** [comment]
Some more information.  The exception below points to table `request_target` field `path` 
```
Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO request_target (pid, rid, pnfsid, path, type, activity, state, created_at, last_updated) VALUES (0, '1e525fa6-e771-41b9-97b1-08a4b43f5fae', '?', '/pnfs/usatlas.bnl.gov/qostape/mc16_13TeV/DAOD_JETM1/e6997_e5984_s3126_r10201_r10210_p3916/mc16_13TeV.364677.Sherpa_CT10_CT14nnlo_CSShower_2to2jets_JZ1W.deriv.DAOD_JETM1.e6997_e5984_s3126_r10201_r10210_p3916_tid18600291_00/DAOD_JETM1.18600291._000025.pool.root.1_1663863932', '?', 'STAGE', 'CREATED', '2023-03-30 14:31:13.17427-04', '2023-03-30 14:31:13.17427-04') was aborted: ERROR: value too long for type character varying(256)  Call getNextException to see other errors in the batch.
```

**Comment by cfgamboa** [comment]
```
                                      Table "public.request_target"
    Column     |            Type             | Collation | Nullable |                  Default                   
---------------+-----------------------------+-----------+----------+--------------------------------------------
 id            | bigint                      |           | not null | nextval('request_target_id_seq'::regclass)
 pid           | bigint                      |           | not null | 
 rid           | character varying(64)       |           | not null | 
 pnfsid        | character varying(36)       |           | not null | 
 path          | character varying(256)      |           | not null | 
 type          | character varying(16)       |           | not null | 
 activity      | character varying(32)       |           | not null | 
 state         | character varying(16)       |           | not null | 
 created_at    | timestamp without time zone |           | not null | 
 started_at    | timestamp without time zone |           |          | 
 last_updated  | timestamp without time zone |           | not null | 
 error_type    | character varying(64)       |           |          | 
 error_message | text                        |           |          | 
Indexes:
    "i_target_pkey" PRIMARY KEY, btree (rid, path)
    "request_target_id_key" UNIQUE CONSTRAINT, btree (id)
    "idx_target_activity" btree (activity)
    "idx_target_created" btree (created_at)
    "idx_target_id_rid" btree (id, rid)
    "idx_target_last_updated" btree (last_updated)
    "idx_target_pid" btree (pid)
    "idx_target_pnfsid" btree (pnfsid)
    "idx_target_state" btree (state)
    "idx_target_type" btree (type)
Foreign-key constraints:
    "request_target_rid_fkey" FOREIGN KEY (rid) REFERENCES bulk_request(id) ON UPDATE CASCADE ON DELETE CASCADE
```

**Comment by cfgamboa** [comment]
Thank you @alrossi

**Comment by alrossi** [comment]
For efficiency of storage, we are truncating the head of the path.   This is a placeholder in any case, as we recover the full path if necessary from the pnfsid.

As I said, there should not be an error associated with the over-length path.

**Comment by alrossi** [comment]
No, unfortunately,  this:   

https://rb.dcache.org/r/13803/

was not backported (on purpose) to 8.2, because it depends on some other disruptive changes to the database that took place between 8.2 and 9.0

The only thing I can suggest at this point is to modify the table directly:

```
ALTER TABLE request_target ALTER path TYPE varchar(512);
```

or whatever size you think is appropriate.   8.2 still relies on the full path being there.  9.0 does not any longer.

Al

**Comment by maatthias** [comment]
I increased the length to 512 for now.

**Comment by vingar** [comment]
@alrossi Do you mean that the recommended version for the Tape REST API is 9.* ?

**Comment by alrossi** [comment]
9.0 should definitely be in place when WLCG begins its campaign ... Fall of 2023 or Spring 2024?  I forget precisely when.  

If it is possible to move there before then, please do.   Be advised that the upgrade will trigger changes to the database which may take a bit to complete, depending on the size of the request_target table.  My benchmark is about an hour for every 20 million rows in that table.

**Comment by cfgamboa** [comment]
9.0 golden release I guess?

**Comment by alrossi** [comment]
P.S @vingar it's actually the Bulk service that has the greatest changes in 9.0, but the Frontend service has a few things smaller but important things that changed as well.  The API itself has not yet changed, though it looks like we are in for some more discussion soon.

9.0 is an intermediate release.  I believe the Golden release will be 9.2 ... right @kofemann ?

**Comment by alrossi** [comment]
So can we close this issue?

**Comment by kofemann** [comment]
Yes, 9.2 is expected to be the next golden release
