### ISSUE TITLE
Index 0 out of bounds for length 0 on NFS Domain

### ISSUE THREAD

**Issue by geonmo** [dCache/dcache#7105]
Hello, everyone.

We are constantly seeing errors while copying files in bulk to the dCache v8.2.17's NFS directory.
(An error occurs because it doesn't reach 10,000 copies.)

If an error occurs, the `linux cp` command shows `Remote I/O error` message. 

At the same time, the nofile of the NFSDomain has increased dramatically. 

If we don't restart the daemon quickly, we can see that the maximum number of open files is reached.

Attached is the log below. 

According to the log, the ArrayList.get function in the link below seems to be a problem.

https://github.com/dCache/dcache/blob/8.2.18/modules/dcache-nfs/src/main/java/org/dcache/chimera/nfsv41/door/proxy/NfsProxyIo.java#L252

Regards,

-- Geonmo

```bash
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: 31 Mar 2023 15:09:06 (NFS-belle-se2-head) [belle-se-disk01.private.lo/192.168.124.151:928 00000800000000000382BA0130] DSWRITE:
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at org.dcache.chimera.nfsv41.door.proxy.NfsProxyIoFactory.getOrCreateProxy(NfsProxyIoFactory.java:80)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at org.dcache.chimera.nfsv41.door.proxy.ProxyIoWRITE.process(ProxyIoWRITE.java:96)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at org.dcache.chimera.nfsv41.door.DoorOperationFactory$2.lambda$process$0(DoorOperationFactory.java:235)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at java.base/java.security.AccessController.doPrivileged(Native Method)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at org.dcache.chimera.nfsv41.door.DoorOperationFactory$2.process(DoorOperationFactory.java:212)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at org.dcache.nfs.v4.AbstractOperationExecutor.execute(AbstractOperationExecutor.java:58)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at org.dcache.chimera.nfsv41.common.StatsDecoratedOperationExecutor.execute(StatsDecoratedOperationExecutor.java:56)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at org.dcache.nfs.v4.NFSServerV41.NFSPROC4_COMPOUND_4(NFSServerV41.java:188)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at org.dcache.nfs.v4.xdr.nfs4_prot_NFS4_PROGRAM_ServerStub.dispatchOncRpcCall(nfs4_prot_NFS4_PROGRAM_ServerStub.java:48)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at org.dcache.oncrpc4j.rpc.RpcDispatcher$1.lambda$run$0(RpcDispatcher.java:100)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at java.base/java.security.AccessController.doPrivileged(Native Method)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at org.dcache.oncrpc4j.rpc.RpcDispatcher$1.run(RpcDispatcher.java:99)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at java.base/java.lang.Thread.run(Thread.java:829)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at java.base/java.util.Objects.checkIndex(Objects.java:372)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at java.base/java.util.ArrayList.get(ArrayList.java:459)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at org.dcache.chimera.nfsv41.door.proxy.NfsProxyIo.processSequence(NfsProxyIo.java:252)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at org.dcache.chimera.nfsv41.door.proxy.NfsProxyIo.sendCompound(NfsProxyIo.java:204)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at org.dcache.chimera.nfsv41.door.proxy.NfsProxyIo.exchange_id(NfsProxyIo.java:217)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at org.dcache.chimera.nfsv41.door.proxy.NfsProxyIo.<init>(NfsProxyIo.java:113)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at org.dcache.chimera.nfsv41.door.proxy.NfsProxyIoFactory.createIoAdapter(NfsProxyIoFactory.java:164)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at org.dcache.chimera.nfsv41.door.proxy.NfsProxyIoFactory.lambda$getOrCreateProxy$1(NfsProxyIoFactory.java:90)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
Mar 31 15:09:06 belle-se2-head dcache@dCacheDomain: ... 19 common frames omitted
```

**Comment by kofemann** [comment]
Hi @geonmo Thanks for the reporting.  Can you specify the client kernel version and the output of `lsmod` command?

**Comment by geonmo** [comment]
@kofemann Here is a NFS Client's kernel and lsmod output.
```bash
[geonmo@belle-se-disk01 ~]$ uname -r
2.6.32-504.30.3.el6.x86_64
[geonmo@belle-se-disk01 ~]$ lsmod

xfs                  1125216  5
exportfs                4236  1 xfs
ext3                  240580  1
jbd                    80950  1 ext3
dm_round_robin          2525  50
scsi_dh_emc             7652  20
dm_multipath           17884  41 dm_round_robin
microcode             112653  0
iTCO_wdt                7115  0
iTCO_vendor_support     3056  1 iTCO_wdt
dcdbas                  8963  0
power_meter             9009  0
acpi_ipmi               3745  1 power_meter
ipmi_si                44751  1 acpi_ipmi
ipmi_msghandler        38701  2 acpi_ipmi,ipmi_si
sb_edac                17082  0
edac_core              46645  3 sb_edac
lpc_ich                12995  0
mfd_core                1895  1 lpc_ich
shpchp                 29130  0
sg                     29318  0
ses                     6411  0
enclosure               8438  1 ses
ext4                  378491  8
jbd2                   93427  1 ext4
mbcache                 8193  2 ext3,ext4
sd_mod                 36998  83
crc_t10dif              1305  1 sd_mod
qla2xxx               469742  160
scsi_transport_fc      55075  1 qla2xxx
scsi_tgt               12077  1 scsi_transport_fc
megaraid_sas           96205  2
bnx2x                 698238  0
libcrc32c               1246  1 bnx2x
wmi                     6287  0
dm_mirror              14384  0
dm_region_hash         12085  1 dm_mirror
dm_log                  9930  2 dm_mirror,dm_region_hash
dm_mod                 95622  167 dm_multipath,dm_mirror,dm_log
crc32c_intel           14866  1
be2iscsi              105183  0
bnx2i                  47648  0
cnic                   55627  1 bnx2i
uio                    10430  1 cnic
ipv6                  334804  143 cnic
cxgb4i                 28361  0
cxgb4                 102865  1 cxgb4i
cxgb3i                 24491  0
libcxgbi               52106  2 cxgb4i,cxgb3i
cxgb3                 150534  1 cxgb3i
mdio                    4769  2 bnx2x,cxgb3
libiscsi_tcp           15964  3 cxgb4i,cxgb3i,libcxgbi
qla4xxx               275535  0
iscsi_boot_sysfs        9458  2 be2iscsi,qla4xxx
libiscsi               48300  7 be2iscsi,bnx2i,cxgb4i,cxgb3i,libcxgbi,libiscsi_tcp,qla4xxx
scsi_transport_iscsi    99144  5 be2iscsi,bnx2i,libcxgbi,qla4xxx,libiscsi
```

**Comment by kofemann** [comment]
Looks like the output of `lsmod` is before mounting the nfs door. Though `IndexOutOfBoundsException` is definitely an error on our end, you should prefer to use at least centos7 .

**Comment by kofemann** [comment]
Hi @geonmo. I have looked at the code and, indeed, it's broken. However, this we already have discovered in the past and in dcache 9.0 part is already re-written. Unfortunately, the changes can't be backported into 8.2 releases.

In general, for a better NFS experience please use a more modern Linux version. As mentioned above, at least centos7.
Moreover, please enable flexfile layout by specifying it in the `exports` file, for example:

```
/exports/data 10.1.1.1(rw,lt=flex_files)
```

**Comment by geonmo** [comment]
The information you provided was very helpful. 
I will close this issue, but it would be nice to mark it somewhere so other users don't ask about it again.  
Thank you for your help.
