### ISSUE TITLE
Webdav PUT failed with "No free port within range"

### ISSUE THREAD

**Issue by ageorget** [dCache/dcache#7148]
Hello,

I observed few strange errors during LSST jobs campaign, some HTTP PUT transfers are failing with the error  "No free port within range".
The servers are running only one pool and `pool.mover.http.port` is set to one dedicated port. 

```
pool.mover.http.port.min = 30000
pool.mover.http.port.max = 30000
```
dCache 8.2.18

It randomly happens on every pools not one in particular.
In the pool logs : 
```

May 05 01:07:54 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]: 05 May 2023 01:07:54 (pool-lsst-li449a) [door:WebDAV-ccdcacli404@webdav-ccdcacli404Domain:AAX65j4Tu8A WebDAV-ccdcacli404 PoolDeliverFile 0000866C83CCA8A9408986CA572B9D60952D] Transfer failed: java.net.BindException: No free port within range
May 05 01:12:54 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]: 05 May 2023 01:12:54 (pool-lsst-li449a) [door:WebDAV-ccdcacli404@webdav-ccdcacli404Domain:AAX65j4Tu8A WebDAV-ccdcacli404 PoolDeliverFile 0000866C83CCA8A9408986CA572B9D60952D] Transfer failed: No connection from client after 300 seconds. Giving up.
May 05 01:12:54 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]: 05 May 2023 01:12:54 (pool-lsst-li449a) [door:WebDAV-ccdcacli404@webdav-ccdcacli404Domain:AAX65j4Tu8A WebDAV-ccdcacli404 PoolDeliverFile 0000866C83CCA8A9408986CA572B9D60952D] Transfer failed in post-processing. Please report this bug to support@dcache.org.
May 05 01:12:54 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]: java.lang.IllegalStateException: Handle is closed
May 05 01:12:54 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]:         at org.dcache.pool.repository.v5.ReadHandleImpl.close(ReadHandleImpl.java:69)
May 05 01:12:54 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]:         at org.dcache.pool.classic.DefaultPostTransferService.lambda$execute$1(DefaultPostTransferService.java:115)
May 05 01:12:54 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]:         at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:28)
May 05 01:12:54 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]:         at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:130)
May 05 01:12:54 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
May 05 01:12:54 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
May 05 01:12:54 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]:         at java.base/java.lang.Thread.run(Thread.java:829)
May 05 01:12:54 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]: Caused by: java.lang.Exception: Previous, successful close.
May 05 01:12:54 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]:         at org.dcache.pool.repository.v5.ReadHandleImpl.close(ReadHandleImpl.java:73)
May 05 01:12:54 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]:         ... 6 common frames omitted
May 05 06:46:50 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]: 05 May 2023 06:46:50 (pool-lsst-li449a) [door:WebDAV-ccdcacli405@webdav-ccdcacli405Domain:AAX66vomOvA WebDAV-ccdcacli405 PoolAcceptFile 0000544A3FEF2C3048468EB93E8357128915] Transfer failed: java.net.BindException: No free port within range
May 05 06:51:50 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]: 05 May 2023 06:51:50 (pool-lsst-li449a) [door:WebDAV-ccdcacli405@webdav-ccdcacli405Domain:AAX66vomOvA WebDAV-ccdcacli405 PoolAcceptFile 0000544A3FEF2C3048468EB93E8357128915] Transfer failed: No connection from client after 300 seconds. Giving up.
May 05 06:51:50 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]: 05 May 2023 06:51:50 (pool-lsst-li449a) [door:WebDAV-ccdcacli405@webdav-ccdcacli405Domain:AAX66vomOvA WebDAV-ccdcacli405 PoolAcceptFile 0000544A3FEF2C3048468EB93E8357128915] Transfer failed in post-processing. Please report this bug to support@dcache.org.
May 05 06:51:50 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]: java.lang.IllegalStateException: Handle is closed
May 05 06:51:50 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]:         at org.dcache.pool.repository.v5.WriteHandleImpl.close(WriteHandleImpl.java:371)
May 05 06:51:50 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]:         at org.dcache.pool.classic.DefaultPostTransferService.lambda$execute$1(DefaultPostTransferService.java:115)
May 05 06:51:50 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]:         at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:28)
May 05 06:51:50 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]:         at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:130)
May 05 06:51:50 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
May 05 06:51:50 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
May 05 06:51:50 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]:         at java.base/java.lang.Thread.run(Thread.java:829)
May 05 06:51:50 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]: Caused by: java.lang.Exception: Previous, successful close.
May 05 06:51:50 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]:         at org.dcache.pool.repository.v5.WriteHandleImpl.close(WriteHandleImpl.java:382)
May 05 06:51:50 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]:         ... 6 common frames omitted
May 05 06:51:50 ccdcacli449 dcache@ccdcacli449-pool-lsst-li449a-Domain[1723]: 05 May 2023 06:51:50 (pool-lsst-li449a) [door:WebDAV-ccdcacli405@webdav-ccdcacli405Domain:AAX66vomOvA WebDAV-ccdcacli405 PoolAcceptFile 0000544A3FEF2C3048468EB93E8357128915] Failed to read file size: java.nio.file.NoSuchFileException: /data/pool-lsst-li449a/pool/data/0000544A3FEF2C3048468EB93E8357128915
```

This is not a lot of errors, 50 over a million of requests but I'm curious to understand what can lead to that.

Best,
Adrien

**Comment by ageorget** [comment]
I heard years ago from Tigran or Paul that GridFTP was the main reason for port range. HTTP is more likely to use a single port in order to reuse connection from clients. That's working well, but sometimes, some transfers are failing with this "No free port within range" error. 

The webdav door is listening on the default 2880 port : 
`tcp6       0      0 :::2880                 :::*                    LISTEN      952418/java`

On the network configuration side : 

dcache.net.wan.port.min=30001
dcache.net.wan.port.max=31000
pool.mover.http.port.min = 30000
pool.mover.http.port.max = 30000

I also forgot to mention that servers are configured in dualstack IPv4/IPv6.

**Comment by ageorget** [comment]
Hi,
When we first configured Webdav to use the port range 30000-31000, I didn't see any error like that.
As I said, this problem is not harmful at all. It only happens 1 time every 100k requests and the client retry is correctly handle.
This is very hard to debug because it happens randomly on pools and not very often.
If you know any specific way or command to get the information you want, it will be helpful.
