### ISSUE TITLE
Failing to build system-test module

### ISSUE THREAD

**Issue by hrhee** [dCache/dcache#7160]
Hello dCache developers,

I am trying to build the `system-test` module (following [BUILDING.md](https://github.com/dCache/dcache/blob/master/BUILDING.md#the-system-test-module))

The status of my checkout is [`commit 050f680f10`](https://github.com/dCache/dcache/commit/050f680f10).

I am using mvn (Apache Maven 3.8.5) and java - openjdk 11.0.19.

With enabled unit-tests the `gplazma plugin Nsswitch` tests are failing:

```
$ mvn clean package -am -pl packages/system-test

...
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.dcache.gplazma.plugins.NsswitchTest
[ERROR] Tests run: 27, Failures: 0, Errors: 27, Skipped: 0, Time elapsed: 1.112 s <<< FAILURE! - in org.dcache.gplazma.plugins.NsswitchTest
[ERROR] org.dcache.gplazma.plugins.NsswitchTest.shouldIdentityMapNameToUid  Time elapsed: 0.642 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @67b64c45

...

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for dCache parent 9.1.0-SNAPSHOT:
[INFO]
[INFO] Logback config for building and testing ............ SUCCESS [  0.918 s]
[INFO] dCache parent ...................................... SUCCESS [  6.094 s]
[INFO] Logback config for console output .................. SUCCESS [  0.566 s]
[INFO] dCache common ...................................... SUCCESS [ 25.374 s]
[INFO] CLI framework ...................................... SUCCESS [  3.570 s]
[INFO] dCache common authentication ....................... SUCCESS [  5.320 s]
[INFO] cells .............................................. SUCCESS [  9.586 s]
[INFO] gPlazma 2 .......................................... SUCCESS [ 11.502 s]
[INFO] gPlazma 2 Argus plugin ............................. SUCCESS [  2.821 s]
[INFO] gPlazma 2 Fermi plugin ............................. SUCCESS [  3.000 s]
[INFO] gPlazma 2 grid plugins ............................. SUCCESS [  7.712 s]
[INFO] gPlazma 2 Kerberos plugin .......................... SUCCESS [  0.983 s]
[INFO] gPlazma 2 JAAS plugin .............................. SUCCESS [  2.535 s]
[INFO] gPlazma 2 Network Information Service plugin ....... SUCCESS [  1.101 s]
[INFO] gPlazma 2 Name Service Switch plugin ............... FAILURE [  3.807 s]
[INFO] gPlazma 2 principal ban file plugin ................ SKIPPED

...
```

When skipping unit-tests I get a build error for `SRM Common`:

```
$mvn clean package -DskipTests -am -pl packages/system-test
[INFO] -----------------------< org.dcache:srm-common >------------------------
[INFO] Building SRM Common 9.1.0-SNAPSHOT                               [32/54]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.2.0:clean (default-clean) @ srm-common ---
[INFO] Deleting /home/rheef/Source/dcache/modules/srm-common/target
[INFO]
[INFO] --- maven-enforcer-plugin:3.2.1:enforce (enforce-maven) @ srm-common ---
[INFO]
[INFO] --- git-commit-id-maven-plugin:5.0.0:revision (default) @ srm-common ---
[INFO]
[INFO] --- axistools-maven-plugin:1.4:wsdl2java (gridsite) @ srm-common ---
[INFO] about to add compile source root
[INFO] Processing wsdl: /home/rheef/Source/dcache/modules/srm-common/src/main/wsdl/gridsite1.wsdl
May 15, 2023 11:43:09 AM org.apache.axis.utils.JavaUtils isAttachmentSupported
WARNING: Unable to find required classes (javax.activation.DataHandler and javax.mail.internet.MimeMultipart). Attachment support is disabled.
[INFO] Processing wsdl: /home/rheef/Source/dcache/modules/srm-common/src/main/wsdl/gridsite2.wsdl
[INFO]
[INFO] --- axistools-maven-plugin:1.4:wsdl2java (srm) @ srm-common ---
[INFO] about to add compile source root
[INFO] Processing wsdl: /home/rheef/Source/dcache/modules/srm-common/src/main/wsdl/srm2.2.wsdl
[INFO]
[INFO] --- maven-patch-plugin:1.2:apply (default) @ srm-common ---
[INFO] Applying patch: 01-fix-exception-message.diff
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for dCache parent 9.1.0-SNAPSHOT:
[INFO]
[INFO] Logback config for building and testing ............ SUCCESS [  0.753 s]
[INFO] dCache parent ...................................... SUCCESS [  5.074 s]
[INFO] Logback config for console output .................. SUCCESS [  0.543 s]
[INFO] dCache common ...................................... SUCCESS [  8.072 s]
[INFO] CLI framework ...................................... SUCCESS [  3.187 s]
[INFO] dCache common authentication ....................... SUCCESS [  3.229 s]
[INFO] cells .............................................. SUCCESS [  5.810 s]
[INFO] gPlazma 2 .......................................... SUCCESS [  3.898 s]
[INFO] gPlazma 2 Argus plugin ............................. SUCCESS [  2.226 s]
[INFO] gPlazma 2 Fermi plugin ............................. SUCCESS [  2.292 s]
[INFO] gPlazma 2 grid plugins ............................. SUCCESS [  3.493 s]
[INFO] gPlazma 2 Kerberos plugin .......................... SUCCESS [  0.995 s]
[INFO] gPlazma 2 JAAS plugin .............................. SUCCESS [  2.095 s]
[INFO] gPlazma 2 Network Information Service plugin ....... SUCCESS [  1.161 s]
[INFO] gPlazma 2 Name Service Switch plugin ............... SUCCESS [  2.385 s]
[INFO] gPlazma 2 principal ban file plugin ................ SUCCESS [  2.320 s]
[INFO] gPlazma 2 VOMS plugin .............................. SUCCESS [  1.150 s]
[INFO] gPlazma 2 KPWD plugin .............................. SUCCESS [  2.400 s]
[INFO] gPlazma 2 LDAP plugin .............................. SUCCESS [  2.553 s]
[INFO] gPlazma 2 htpasswd plugin .......................... SUCCESS [  2.329 s]
[INFO] gPlazma 2 Openid Connect plugin .................... SUCCESS [  5.632 s]
[INFO] gPlazma 2 Omni-session plugin ...................... SUCCESS [  2.855 s]
[INFO] gPlazma 2 Multi Mapping Plugin ..................... SUCCESS [  2.826 s]
[INFO] gPlazma 2 roles plugin ............................. SUCCESS [  2.466 s]
[INFO] gPlazma 2 SciToken plugin .......................... SUCCESS [  3.417 s]
[INFO] NFS 4.1 ACL Vehicles ............................... SUCCESS [  1.183 s]
[INFO] dCache Vehicles .................................... SUCCESS [  4.082 s]
[INFO] dCache Nearline Storage SPI ........................ SUCCESS [  1.223 s]
[INFO] NFS 4.1 ACL ........................................ SUCCESS [  2.312 s]
[INFO] Chimera ............................................ SUCCESS [  4.133 s]
[INFO] FTP client ......................................... SUCCESS [  3.463 s]
[INFO] SRM Common ......................................... FAILURE [  0.584 s]
[INFO] dCache Core ........................................ SKIPPED

...

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

...

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-patch-plugin:1.2:apply (default) on project srm-common: Failed to apply patch: 01-fix-exception-message.diff. See debug output for more information.: Error while executing process. Cannot run program "patch" (in directory "/home/rheef/Source/dcache/modules/srm-common/target/generated-sources/axistools/wsdl2java"): error=2, No such file or directory -> [Help 1]
```

**Comment by kofemann** [comment]
Hi @hrhee ,

You need to install `patch` utility to build the dcache.

**Comment by hrhee** [comment]
> Hi @hrhee ,
> 
> You need to install `patch` utility to build the dcache.

Thanks a lot, @kofemann ! After installing the `patch` utility the build for `system-test` module succeeded when skipping the unit-tests
(`mvn clean package -DskipTests -am -pl packages/system-test`).

However, with unit-tests enabled I run into the same failures as before with the `gplazma Nsswitch plugin`:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.dcache.gplazma.plugins.NsswitchTest
[ERROR] Tests run: 27, Failures: 0, Errors: 27, Skipped: 0, Time elapsed: 1.074 s <<< FAILURE! - in org.dcache.gplazma.plugins.NsswitchTest
[ERROR] org.dcache.gplazma.plugins.NsswitchTest.shouldIdentityMapNameToUid  Time elapsed: 0.622 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @67b64c45
 ...

[ERROR] Tests run: 15, Failures: 0, Errors: 15, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for dCache parent 9.1.0-SNAPSHOT:
[INFO]
[INFO] Logback config for building and testing ............ SUCCESS [  0.848 s]
[INFO] dCache parent ...................................... SUCCESS [  5.550 s]
[INFO] Logback config for console output .................. SUCCESS [  0.593 s]
[INFO] dCache common ...................................... SUCCESS [ 25.331 s]
[INFO] CLI framework ...................................... SUCCESS [  3.809 s]
[INFO] dCache common authentication ....................... SUCCESS [  5.134 s]
[INFO] cells .............................................. SUCCESS [  9.703 s]
[INFO] gPlazma 2 .......................................... SUCCESS [ 11.468 s]
[INFO] gPlazma 2 Argus plugin ............................. SUCCESS [  2.774 s]
[INFO] gPlazma 2 Fermi plugin ............................. SUCCESS [  2.891 s]
[INFO] gPlazma 2 grid plugins ............................. SUCCESS [  7.697 s]
[INFO] gPlazma 2 Kerberos plugin .......................... SUCCESS [  0.989 s]
[INFO] gPlazma 2 JAAS plugin .............................. SUCCESS [  2.564 s]
[INFO] gPlazma 2 Network Information Service plugin ....... SUCCESS [  1.074 s]
[INFO] gPlazma 2 Name Service Switch plugin ............... FAILURE [  3.752 s]
[INFO] gPlazma 2 principal ban file plugin ................ SKIPPED
...
[INFO] BUILD FAILURE
...
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M9:test (default-test) on project gplazma2-nsswitch:
[ERROR]
...
```

As I would like to write my own `gplazma plugin`, I'd be interested to make it succeed.

**Comment by hrhee** [comment]
The  content of the corresponding dump file is

```
$ cat 2023-05-15T13-19-39_066-jvmRun1.dump

# Created at 2023-05-15T13:21:07.343
org.apache.maven.surefire.api.testset.TestSetFailedException: Test mechanism :: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @67b64c45
        at org.apache.maven.surefire.common.junit4.JUnit4RunListener.rethrowAnyTestMechanismFailures(JUnit4RunListener.java:226)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:175)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @67b64c45
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at org.powermock.reflect.internal.WhiteboxImpl.doGetAllMethods(WhiteboxImpl.java:1507)
        at org.powermock.reflect.internal.WhiteboxImpl.getAllMethods(WhiteboxImpl.java:1481)
        at org.powermock.reflect.internal.WhiteboxImpl.findMethodOrThrowException(WhiteboxImpl.java:861)
        at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:821)
        at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:804)
        at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:466)
        at org.powermock.modules.junit4.common.internal.impl.PowerMockJUnit4RunListener.testFinished(PowerMockJUnit4RunListener.java:55)
        at org.junit.runner.notification.SynchronizedRunListener.testFinished(SynchronizedRunListener.java:87)
        at org.junit.runner.notification.RunNotifier$9.notifyListener(RunNotifier.java:225)
        at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
        at org.junit.runner.notification.RunNotifier.fireTestFinished(RunNotifier.java:222)
        at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:53)
        at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
        at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
        at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
        at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
        at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
        at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
        at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:117)
        at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
        at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
        ... 4 more
```

**Comment by hrhee** [comment]
Thank you so much, @lemora !

This solved my problem :)
