### ISSUE TITLE
Issue access the dCache namespace via Frontend in 9.1.1

### ISSUE THREAD

**Issue by christianvoss** [dCache/dcache#7250]
Hi all,

I've updated our pre-production cluster to 9.1.1 yesterday. We've seen problems accessing the namespace through the REST-API (see stack-trace below). The client receives a 500 code.

We were able to access `bulk` and all other transfers looked good as well.

We do not observe it in 9.1.0, but also in 9.0.9. I've not yet tested 8.2.26. I'll try to do so and will update the Issue

Thanks a lot,
Christian

```
20 Jul 2023 12:38:29 [jetty-59] [] Uncaught exception in thread jetty-59java.lang.IllegalArgumentException: null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:131)
        at diskCacheV111.vehicles.PnfsMessage.setPnfsPath(PnfsMessage.java:38)
        at org.dcache.vehicles.PnfsResolveSymlinksMessage.<init>(PnfsResolveSymlinksMessage.java:24)
        at org.dcache.http.PathMapper.asDcachePath(PathMapper.java:98)
        at org.dcache.restful.resources.namespace.FileResources.getFileAttributes(FileResources.java:182)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.dcache.http.AuthenticationHandler.access$001(AuthenticationHandler.java:55)
        at org.dcache.http.AuthenticationHandler.lambda$handle$0(AuthenticationHandler.java:156)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
        at org.dcache.http.AuthenticationHandler.handle(AuthenticationHandler.java:153)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.dcache.http.AbstractLoggingHandler.handle(AbstractLoggingHandler.java:110)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:322)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by svemeyer** [comment]
This might be related to PR #7227 (released in dCache 9.1.1) and #7226 (released in dCache 9.0.9) @alrossi 
The changes were not backported to 8.2

**Comment by alrossi** [comment]
Definitely related.  I'm on it ...

**Comment by alrossi** [comment]
@christianvoss could you give me the REST command with parameters that provokes this?  I am scratching my head trying to see how path can be null when going through the two REST commands which enforce to be non-null ...  Thanks

**Comment by alrossi** [comment]
Just to be clear:

`9.2.0-SNAPSHOT(421e1dc)`

### Example

**PATH without symlink**

```
curl -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/namespace/volatile/data_1b?children=false&locality=false&qos=false&optional=false" -H "accept: application/json"
```

RESP 200

```
{
  "fileMimeType": "application/octet-stream",
  "labels": [],
  "size": 1,
  "creationTime": 1688642774327,
  "fileType": "REGULAR",
  "pnfsId": "00008292994D904A47C6A26C6F4E419D3A28",
  "nlink": 1,
  "mode": 420,
  "mtime": 1688642775488
}
```
and

**PATH with symlink**

```
curl -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/namespace/any/my_scratch/data_1b?children=false&locality=false&qos=false&optional=false" -H "accept: application/json"
```

RESP 200

```
{
  "fileMimeType": "application/octet-stream",
  "labels": [],
  "size": 1,
  "creationTime": 1688642774327,
  "fileType": "REGULAR",
  "pnfsId": "00008292994D904A47C6A26C6F4E419D3A28",
  "nlink": 1,
  "mode": 420,
  "mtime": 1688642775488
}

**Comment by alrossi** [comment]
I don't see how to give the REST call a null path ...

**Comment by alrossi** [comment]
### BUT!

now I see one instance of 

```
21 Jul 2023 08:35:39 [jetty-157] [] Uncaught exception in thread jetty-157java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at diskCacheV111.vehicles.PnfsMessage.setPnfsPath(PnfsMessage.java:38)
	at org.dcache.vehicles.PnfsResolveSymlinksMessage.<init>(PnfsResolveSymlinksMessage.java:24)
	at org.dcache.http.PathMapper.asDcachePath(PathMapper.java:98)
	at org.dcache.restful.resources.namespace.FileResources.getFileAttributes(FileResources.java:182)

...
```

HUH?

**Comment by alrossi** [comment]
OK, got it now.

```
checkArgument(pnfsPath == null || pnfsPath.charAt(0) == '/');
```

That path is not null.  If you give it a relative path or an empty path, it fails the second condition.

**Comment by alrossi** [comment]
see

https://rb.dcache.org/r/14026/
