### ISSUE TITLE
admin shell:   stop reporting command syntax errors as bugs/stack traces

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache#7271]
Example

```
request submit -activity=UPDATE_QOS -arguments=qosPolicy:TEST,qosState=1 /pnfs/fs/usr/fermilab/users/arossi/any/199/data-2023073105321690799520563158873
Command 'request submit -activity=UPDATE_QOS -arguments=qosPolicy:TEST,qosState=1 /pnfs/fs/usr/fermilab/users/arossi/any/199/data-2023073105321690799520563158873' triggered a bug (java.lang.IllegalArgumentException: Chunk [qosState=1] is not a valid entry); the service log file contains additional information. Please contact support@dcache.org.
```

on pinboard:

```
02 Aug 2023 14:02:11 [bulk-0] [xBY:GU admin] Command failed due to a bug, please contact support@dcache.org.dmg.util.CommandPanicException: (1) Command failed: java.lang.IllegalArgumentException: Chunk [qosState=1] is not a valid entry
	at org.dcache.util.cli.AnnotatedCommandExecutor.execute(AnnotatedCommandExecutor.java:145)
	at dmg.cells.nucleus.CellAdapter.executeCommand(CellAdapter.java:217)
	at org.dcache.cells.UniversalSpringCell.executeCommand(UniversalSpringCell.java:190)
	at dmg.cells.nucleus.CellAdapter$1.doExecute(CellAdapter.java:90)
	at org.dcache.util.cli.CommandInterpreter.command(CommandInterpreter.java:174)
	at dmg.cells.nucleus.CellAdapter$1.command(CellAdapter.java:106)
	at dmg.cells.nucleus.CellAdapter.command(CellAdapter.java:195)
	at dmg.cells.nucleus.CellAdapter.executeLocalCommand(CellAdapter.java:881)
	at dmg.cells.nucleus.CellAdapter.messageArrived(CellAdapter.java:820)
	at dmg.cells.nucleus.CellNucleus$DeliverMessageTask.run(CellNucleus.java:1273)
	at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:247)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$2(CellNucleus.java:725)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Chunk [qosState=1] is not a valid entry
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218)
	at com.google.common.base.Splitter$MapSplitter.split(Splitter.java:525)
	at org.dcache.services.bulk.BulkServiceCommands$RequestSubmit.call(BulkServiceCommands.java:981)
	at org.dcache.services.bulk.BulkServiceCommands$RequestSubmit.call(BulkServiceCommands.java:924)
	at org.dcache.util.cli.AnnotatedCommandExecutor.execute(AnnotatedCommandExecutor.java:134)
	... 14 common frames omitted

```

The problem is merely the `=` instead of `:` in the arguments.   I don't believe this is only a problem with the bulk interface ... it seems more generalized.   I've been meaning to fix this for a while

**Comment by alrossi** [comment]
(This is what you get by abusing IllegalArgumentException (of which I am also guilty).   I know it would mean changing the signature of a whole slew of methods, but these kind of errors should not be unchecked/runtime exceptions ...)

**Comment by alrossi** [comment]
See. https://rb.dcache.org/r/14103/

**Comment by kofemann** [comment]
As we often use `IllegalArgumentException` to indicate programming bugs always convert them into CommandException is not 100% correct. Thus, admin shell should throw some kind of `IllegalCommandArgumentException`.

Let's reopen the issue as a reminder for a better solution.

**Comment by alrossi** [comment]
Actually, that was the purpose of https://github.com/dCache/dcache/issues/7361

One of these two issues should be close.

**Comment by kofemann** [comment]
ah, my bad

**Comment by alrossi** [comment]
NP.
