### ISSUE TITLE
tape API/bulk: seem to choke on any interval other than "PND"

### ISSUE THREAD

**Issue by DmitryLitvintsev** [dCache/dcache#7414]
running this command:
```
curl -f -k -L -H "Authorization: Bearer ${TOKEN}" -X  POST https://fndcadoor.fnal.gov:3880/api/v1/tape/stage -H "Content-Type: application/json" -d '{"files": [ {"diskLifetime":"P1W","path":"/mu2e/tape/phy-sim/dig/mu2e/CosmicCORSIKADigiTriggered/MDC2020n_10h/art/af/7b/dig.mu2e.CosmicCORSIKADigiTriggered.MDC2020n_10h.001205_00000005.art"}]}'
```
results in:
```
30 Oct 2023 17:41:44 [pool-8-thread-98] [] Uncaught exception in thread pool-8-thread-98java.time.format.DateTimeParseException: Text cannot be parsed to a Duration
	at java.base/java.time.Duration.parse(Duration.java:417)
	at org.dcache.services.bulk.activity.plugin.pin.StageActivity.getLifetimeInMillis(StageActivity.java:159)
	at org.dcache.services.bulk.activity.plugin.pin.StageActivity.perform(StageActivity.java:126)
	at org.dcache.services.bulk.job.PrestoreRequestContainerJob.perform(PrestoreRequestContainerJob.java:292)
	at org.dcache.services.bulk.job.PrestoreRequestContainerJob.processFileTargets(PrestoreRequestContainerJob.java:164)
	at org.dcache.services.bulk.job.AbstractRequestContainerJob.run(AbstractRequestContainerJob.java:285)
	at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:28)
	at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:130)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:247)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
on server, but the request is formed and it there doing nothing (no pinning happens):
```
[fndca3b] (bulk@bulkDomain) enstore > request info a0aa52f0-f15c-482a-ab92-febf613c526d
a0aa52f0-f15c-482a-ab92-febf613c526d:
status:           STARTED
arrived at:       2023-10-30 17:41:44.214
started at:       2023-10-30 17:41:44.245
last modified at: 2023-10-30 17:41:44.245
target prefix:    
targets:
CREATED                   |                   STARTED |                 COMPLETED |        STATE | TARGET
2023-10-30 17:41:44.29    |                         ? |                         ? |        READY | /mu2e/tape/phy-sim/dig/mu2e/CosmicCORSIKADigiTriggered/MDC2020n_10h/art/af/7b/dig.mu2e.CosmicCORSIKADigiTriggered.MDC2020n_10h.001205_00000005.art
next offset: -1

[fndca3b] (bulk@bulkDomain) enstore > request ls a0aa52f0-f15c-482a-ab92-febf613c526d
SEQNO        | ARRIVED             |            MODIFIED |        OWNER |     STATUS | ID
1181         | 2023/10/30-17:41:44 | 2023/10/30-17:41:44 |   44592:9914 |    STARTED | a0aa52f0-f15c-482a-ab92-febf613c526d
[fndca3b] (bulk@bulkDomain) enstore > 
```

**Comment by alrossi** [comment]
Seems like the second issue is more important than the first, which can be for the moment handled with a notice that the Java support is lacking for certain constructs.  ('W' is not allowed)
