### ISSUE TITLE
Traceback with oauth-authorization-server

### ISSUE THREAD

**Issue by vingar** [dCache/dcache#7488]
Hello 

We are observing the following traceback with dCache 8.2.40:
```
03 Jan 2024 08:09:46 (Frontend-dcfrontend01) [] /.well-known/oauth-authorization-server
javax.servlet.ServletException: WellKnownHandler
	at org.dcache.services.httpd.handlers.WellKnownHandler.handle(WellKnownHandler.java:112)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:190)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:322)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.dcache.services.httpd.exceptions.OnErrorException: No such endpoint
	at org.dcache.services.httpd.handlers.WellKnownHandler.handle(WellKnownHandler.java:94)
	... 30 common frames omitted
```

**Comment by vingar** [comment]
With this recommended gplazma configuration from ATLAS:

```
[${host.name}Domain/gplazma]
gplazma.oidc.provider!atlas = https://atlas-auth.web.cern.ch/ -profile=wlcg -prefix=/pnfs/usatlas.bnl.gov/ -authz-id="uid:XXXX gid:XXXX username:XXXXX"
gplazma.oidc.audience-targets = https://wlcg.cern.ch/jwt/v1/any  https://dcgftp.usatlas.bnl.gov https://dcgftp.usatlas.bnl.gov:2881 roots://dcgftp.usatlas.bnl.gov:1094 roots://dcgftp.usatlas.bnl.gov:1096 dcgftp.usatlas.bnl.gov  https://dcdoor-tape.usatlas.bnl.gov dcdoor-tape.usatlas.bnl.gov
```

**Comment by kofemann** [comment]
Hi @vingar,

I think the issue is already fixed by commit https://github.com/dCache/dcache/commit/05d9c4cf29447b72a122f43770e830d6a07a9c99 and released in 9.2.6.

**Comment by vingar** [comment]
Hi @kofemann,
We'll inform you after the upgrade to version 9.2.* on the 22nd of January
