### ISSUE TITLE
org.eclipse.jetty.http.BadMessageException: 500: Response header too large (v9.2.8)

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#7496]
Dear dCache devs,

We have users complaining that they get a 500 error while doing listings with Rclone over WebDAV. In the log of the WebDAV door I can see this:

```
16 Jan 2024 16:40:31 (webdav2880-walrus14) [door:webdav2880-walrus14@webdav2880-walrus14Domain:AAYPEfMKIWA] Internal server error
java.lang.RuntimeException: org.eclipse.jetty.http.BadMessageException: 500: Response header too large
	at io.milton.http.webdav.DefaultWebDavResponseHandler.respondPropFind(DefaultWebDavResponseHandler.java:212)
	at io.milton.http.AbstractWrappingResponseHandler.respondPropFind(AbstractWrappingResponseHandler.java:200)
	at org.dcache.webdav.AcceptAwareResponseHandler.respondPropFind(AcceptAwareResponseHandler.java:104)
	at io.milton.http.AbstractWrappingResponseHandler.respondPropFind(AbstractWrappingResponseHandler.java:200)
	at org.dcache.webdav.WorkaroundsResponseHandler.respondPropFind(WorkaroundsResponseHandler.java:138)
	at io.milton.http.AbstractWrappingResponseHandler.respondPropFind(AbstractWrappingResponseHandler.java:200)
	at io.milton.http.AbstractWrappingResponseHandler.respondPropFind(AbstractWrappingResponseHandler.java:200)
	at io.milton.http.webdav.PropFindHandler.processExistingResource(PropFindHandler.java:156)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
	at io.milton.http.webdav.PropFindHandler.processResource(PropFindHandler.java:112)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
	at org.dcache.webdav.DcacheResourceHandlerHelper.process(DcacheResourceHandlerHelper.java:42)
	at io.milton.http.webdav.PropFindHandler.process(PropFindHandler.java:106)
	at org.dcache.webdav.DcacheStandardFilter.process(DcacheStandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at org.dcache.webdav.transfer.CopyFilter.process(CopyFilter.java:276)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at org.dcache.webdav.MiltonHandler.handle(MiltonHandler.java:77)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.dcache.http.AuthenticationHandler.access$001(AuthenticationHandler.java:55)
	at org.dcache.http.AuthenticationHandler.lambda$handle$0(AuthenticationHandler.java:157)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
	at org.dcache.http.AuthenticationHandler.handle(AuthenticationHandler.java:154)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.dcache.http.AbstractLoggingHandler.handle(AbstractLoggingHandler.java:110)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:322)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.eclipse.jetty.http.BadMessageException: 500: Response header too large
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:773)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:248)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:229)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:555)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:1009)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:1086)
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:285)
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:269)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:896)
	at java.base/java.io.OutputStream.write(OutputStream.java:122)
	at io.milton.http.webdav.DefaultWebDavResponseHandler.respondPropFind(DefaultWebDavResponseHandler.java:210)
	... 52 common frames omitted
```

This appears to have started after our upgrade from 8.2.32 to 9.2.8.

One user reports this:

```
rclone --config dcache_ext.conf ls dcache_ext:tape/pacbio/
2024/01/16 14:22:15 ERROR : : error listing: couldn't list files: 500 Server Error
2024/01/16 14:22:15 Failed to ls with 2 errors: last error was: couldn't list files: 500 Server Error 
```

Macaroon properties:
```
location Optional.empty

identifier 3h7Xjf7/
cid iid:gKiyGb+o
cid id:53575;53253;holstegelab-mhulsman
cid before:2024-04-02T07:46:24.156494Z
cid home:/pnfs/grid.sara.nl/data/holstegelab
cid root:/pnfs/grid.sara.nl/data/holstegelab
cid activity:DOWNLOAD,UPLOAD,DELETE,MANAGE,LIST,READ_METADATA,UPDATE_METADATA
cid ip:<large list of subnets that includes the user's IP> 
```

The directory:

```
[root@db4 ~]# ls -l /pnfs/grid.sara.nl/data/holstegelab/tape/pacbio/ | wc -l
325
```

Any idea what could be wrong?

Cheers,
Onno

**Comment by DmitryLitvintsev** [comment]
Yeah. We have run into it at CMS T1 site :(. No idea at the moment.

**Comment by paulmillar** [comment]
The problem is triggered within the underlying HTTP library: Jetty.  Jetty limits HTTP response headers to 8 KiB by default.  It seems that dCache (and/or Milton) is attempting to send a response header that is larger than this 8 KiB limit.

The 8 KiB is somewhat arbitrary (it's a trade-off).  Jetty is configurable, to allow larger headers; however, this configuration option isn't exposed by dCache, so (I believe) we can't easily adjust dCache's configuration to bump up the limit.  In any case, simply increasing the maximum response header size is probably the wrong approach: there's no reason why dCache should be replying with such a large response header.

Jetty waits until the HTTP entity is being written before sending the HTTP response headers.  Therefore the problem only becomes apparent once Milton starts sending the PROPFIND HTTP entity, and (because of this) the stacktrace doesn't tell us which header is too large.

Enabling DEBUG level output on the `org.eclipse.jetty.server.HttpConnection` and `org.eclipse.jetty.http.HttpGenerator` loggers should provide entries like:

    generate: HEADER_OVERFLOW for {} ({},{},{})@{}

and just before that, an entry like:

    IGNORED EXCEPTION: BufferOverflowException [...]

These lines (or the surrounding lines)  _might_ provide some information on what is going wrong, but it's a bit of a long shot.

Some other potentially useful information:

  1. is the problem repeatable: does exactly the same request always yield this problem?
  2. does the problem go away if the request is made without using a macaroon?
  3. does the problem go away if the macaroon is smaller (e.g., fewer IP addresses)?

One other piece of information: could you provide the access log file entry for the problematic error?

Cheers,
Paul.

**Comment by DmitryLitvintsev** [comment]
Hi Paul:

I noticed this with GSI:


depth 0 OK:
```
$ curl --capath /etc/grid-security/certificates --cert /tmp/x509up_u`id -u` --cacert /tmp/x509up_u`id -u` -X PROPFIND -H "Depth:0"  https://cmsdcatapeitb01.fnal.gov:2880/WAX/11/store/mc/
<?xml version="1.0" encoding="utf-8" ?>
<d:multistatus xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:d="DAV:"><d:response><d:href>/WAX/11/store/mc/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype><d:getetag>"000700000000000000FD5DC0_-272564264"</d:getetag><d:displayname>mc</d:displayname><d:getcontenttype>text/html; charset=utf-8</d:getcontenttype><d:getlastmodified>Sun, 13 Aug 2023 16:35:49 GMT</d:getlastmodified><d:creationdate>2014-05-13T19:49:05Z</d:creationdate></d:prop><d:status>HTTP/1.1 200 O
```

depth 1 fail (stack race in the log):

```
$ curl -f --capath /etc/grid-security/certificates --cert /tmp/x509up_u`id -u` --cacert /tmp/x509up_u`id -u` -X PROPFIND -H "Depth:1"  https://cmsdcatapeitb01.fnal.gov:2880/WAX/11/store/mc/
curl: (22) The requested URL returned error: 500 Server Error
```
But this works:

```
 gfal-ls https://cmsdcatapeitb01.fnal.gov:2880/WAX/11/store/mc/
2006
2007
2008
2019GEMUpg14
....
```
Directory not that large:
```
$ gfal-ls https://cmsdcatapeitb01.fnal.gov:2880/WAX/11/store/mc/ | wc -l 
351
```

So, I can assume you can reproduce the issue by running:

```
curl -X PROPFIND -H "Depth:1" ...
```

**Comment by DmitryLitvintsev** [comment]
Hmmm..... I am afraid this may have something to do with your metalink patch .... 
With :

```
 (WebDAV@webdavDomain) admin > log set stdout org.eclipse.jetty.server.HttpConnection DEBUG 
 (WebDAV@webdavDomain) admin > log set stdout org.eclipse.jetty.http.HttpGenerator DEBUG 
```
I see:

```
16 Jan 2024 15:42:31 (WebDAV-cmsdcatapeitb01) [door:WebDAV-cmsdcatapeitb01@webdavDomain:AAYPFwGXmig] Date: Tue, 16 Jan 2024 21:42:31 GMT
Server: dCache/9.2.9-SNAPSHOT
Strict-Transport-Security: max-age=31536000
Content-Type: application/xml; charset=utf-8
Link: <https://cmsdcatapeitb01.fnal.gov:2880/WAX/11/store/mc/?type=metalink>; rel=describedby; type="application/metalink4+xml"
Link: <https://cmsdcatapeitb01.fnal.gov:2880/WAX/11/store/mc/?type=metalink>; rel=describedby; type="application/metalink4+xml"
Link: <https://cmsdcatapeitb01.fnal.gov:2880/WAX/11/store/mc/?type=metalink>; rel=describedby; type="application/metalink4+xml"
Link: <https://cmsdcatapeitb01.fnal.gov:2880/WAX/11/store/mc/?type=metalink>; rel=describedby; type="application/metalink4+xml"
Link: <https://cmsdcatapeitb01.fnal.gov:2880/WAX/11/store/mc/?type=metalink>; rel=describedby; type="application/metalink4+xml"
Link: <https://cmsdcatapeitb01.fnal.gov:2880/WAX/11/store/mc/?type=metalink>; rel=describedby; type="application/metalink4+xml"
.....
Link: <https://cmsdcatapeitb01.fnal.gov:2880/WAX/11/store/mc/?type=metalink>; rel=describedby; type="application/metalink4+xml"
Link: <https://cmsdcatapeitb01.fnal.gov:2880/WAX/11/store/mc/?type=metalink>; rel=describedby; type="application/metalink4+xml"
DAV: 1, 2


16 Jan 2024 15:42:31 (WebDAV-cmsdcatapeitb01) [door:WebDAV-cmsdcatapeitb01@webdavDomain:AAYPFwGXmig] generate: HEADER_OVERFLOW for SendCallback@849f0f6[PROCESSING][i=HTTP/1.1{s=207,h=357,cl=-1},cb=org.ecl
ipse.jetty.server.HttpChannel$SendCallback@6dc6cb34] ([p=0,l=8192,c=8192,r=8192],[p=0,l=32768,c=216259,r=32768],false)@START
16 Jan 2024 15:42:31 (WebDAV-cmsdcatapeitb01) [door:WebDAV-cmsdcatapeitb01@webdavDomain:AAYPFwGXmig] generate: NEED_HEADER for SendCallback@849f0f6[PROCESSING][i=HTTP/1.1{s=500,h=1,cl=0},cb=org.eclipse.je
tty.server.HttpChannel$SendCallback$1@6cb25916] (null,null,true)@START
16 Jan 2024 15:42:31 (WebDAV-cmsdcatapeitb01) [door:WebDAV-cmsdcatapeitb01@webdavDomain:AAYPFwGXmig] generateHeaders HTTP/1.1{s=500,h=1,cl=0} last=true content=null
16 Jan 2024 15:42:31 (WebDAV-cmsdcatapeitb01) [door:WebDAV-cmsdcatapeitb01@webdavDomain:AAYPFwGXmig] Connection: close


16 Jan 2024 15:42:31 (WebDAV-cmsdcatapeitb01) [door:WebDAV-cmsdcatapeitb01@webdavDomain:AAYPFwGXmig] EOF_CONTENT
16 Jan 2024 15:42:31 (WebDAV-cmsdcatapeitb01) [door:WebDAV-cmsdcatapeitb01@webdavDomain:AAYPFwGXmig] generate: FLUSH for SendCallback@849f0f6[PROCESSING][i=HTTP/1.1{s=500,h=1,cl=0},cb=org.eclipse.jetty.se
rver.HttpChannel$SendCallback$1@6cb25916] ([p=0,l=81,c=8192,r=81],null,true)@COMPLETING
16 Jan 2024 15:42:31 (WebDAV-cmsdcatapeitb01) [door:WebDAV-cmsdcatapeitb01@webdavDomain:AAYPFwGXmig] generate: SHUTDOWN_OUT for SendCallback@849f0f6[PROCESSING][i=HTTP/1.1{s=500,h=1,cl=0},cb=org.eclipse.j
etty.server.HttpChannel$SendCallback$1@6cb25916] ([p=81,l=81,c=8192,r=0],null,true)@END
16 Jan 2024 15:42:31 (WebDAV-cmsdcatapeitb01) [door:WebDAV-cmsdcatapeitb01@webdavDomain:AAYPFwGXmig] generate: DONE for SendCallback@849f0f6[PROCESSING][i=HTTP/1.1{s=500,h=1,cl=0},cb=org.eclipse.jetty.ser
ver.HttpChannel$SendCallback$1@6cb25916] ([p=81,l=81,c=8192,r=0],null,true)@END
16 Jan 2024 15:42:31 (WebDAV-cmsdcatapeitb01) [door:WebDAV-cmsdcatapeitb01@webdavDomain:AAYPFwGXmig] abort HttpConnection@1ec7b52::DecryptedEndPoint@fac5dd1{l=/2620:6a:0:8420:0:0:0:ec:2880,r=/2620:6a:0:87
:219:b9ff:fe03:7377:42830,OSHUT,fill=-,flush=-,to=5509/60000} {}
16 Jan 2024 15:42:31 (WebDAV-cmsdcatapeitb01) [door:WebDAV-cmsdcatapeitb01@webdavDomain:AAYPFwGXmig] Internal server error
java.lang.RuntimeException: org.eclipse.jetty.http.BadMessageException: 500: Response header too large
        at io.milton.http.webdav.DefaultWebDavResponseHandler.respondPropFind(DefaultWebDavResponseHandler.java:212)
...
```

**Comment by paulmillar** [comment]
Yes, indeed.  That's my conclusion, too.

There's a bug that these `link` headers are being generated for PROPFIND requests.  They should only be there for GET and HEAD requests.

The header is also appearing multiple times: that's also bad (and probably causing the problem).

**Comment by DmitryLitvintsev** [comment]
Yup, went one patch before "metalink support patch" (1f79ce55cee5cfdb7bb0addac5947927552b8bee):


```
git checkout 707000c026c6355c9bb0aae69dba7fd656825e24
```

built, deployed, works:
```
$ curl -f --capath /etc/grid-security/certificates --cert /tmp/x509up_u`id -u` --cacert /tmp/x509up_u`id -u` -X PROPFIND -H "Depth:1"  https://cmsdcatapeitb01.fnal.gov:2880/WAX/11/store/mc
<?xml version="1.0" encoding="utf-8" ?>
<d:multistatus xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:d="DAV:"><d:response><d:href>/WAX/11/store/mc/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype><d:getetag>"000700000000000000FD5DC0_-272564264"</d:getetag><d:displayname>mc</d:displayname><d:getcontenttype>text/html; charset=utf-8</d:getcontenttype><d:getlastmodified>Sun, 13 Aug 2023 16:35:49 GMT</d:getlastmodified><d:creationdate>2014-05-13T19:49:05Z</d:creationdate></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontentlength/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/WAX/11/store/mc/2006/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype><d:getetag>"000700000000000000FD5E08_-1818286241"</d:getetag><d:displayname>2006</d:displayname><d:getcontenttype>text/html; charset=utf-8</d:getcontenttype><d:getlastmodified>Mon, 18 Dec 2006 03:33:38 GMT</d:getlastmodified><d:creationdate>2006-11-09T19:16:22Z</d:creationdate></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontentlength/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/WAX/11/store/mc/2007/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype><d:getetag>"000700000000000001518500_-1499475818"</d:getetag><d:displayname>2007</d:displayname><d:getcontenttype>text/html; charset=utf-8</d:getcontenttype><d:getlastmodified>Tue, 04 Dec 2007 19:26:40 GMT</d:getlastmodified><d:creationdate>2007-01-04T20:14:18Z</d:creationdate></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontentlength/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/WAX/11/store/mc/2008/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype><d:getetag>"00070000000000000E78F048_1856089250"</d:getetag><d:displayname>2008</d:displayname><d:getcontenttype>text/html; charset=utf-8</d:getcontenttype><d:getlastmodified>Mon, 09 Jun 2008 18:41:07 GMT</d:getlastmodified><d:creationdate>2008-01-07T12:40:11Z</d:creationdate></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontentlength/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/WAX/11/store/mc/201
...
```

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/14201/

**Comment by onnozweers** [comment]
Any idea when we can expect this fix in an RPM? Our users desperately want this fix. If it takes long, that's OK, but then I may build my own RPM with the patch. So, it would be nice to have some insight on the planning.

**Comment by lemora** [comment]
Hi Onno, we will release the newest 9.2 bugfix release that includes this patch next week.

**Comment by onnozweers** [comment]
Hi @lemora, thanks!

**Comment by onnozweers** [comment]
Users confirm the problem is now solved.
Thanks for the rapid action!

Cheers, Onno

**Comment by DmitryLitvintsev** [comment]
Well... TBH the action could have been "rapider". But thanks! :). Don't hesitate to open issue or rt ticket. I personally have issues with user forum e-mails (my personal technical problem, which I have no time to investigate).
