### ISSUE TITLE
Webdav door : org.eclipse.jetty.io.EofException: null

### ISSUE THREAD

**Issue by cfgamboa** [dCache/dcache#7549]
Hello,

Please note that Webdav doors are showing this error. The dCache version is 9.2.6

```
14 Apr 2024 21:43:36 (WebDAV2-dcdoor31-externalipv6) [] 
org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:280)
	at org.eclipse.jetty.io.ssl.SslConnection.networkFlush(SslConnection.java:489)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:1112)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:831)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:248)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:229)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:555)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:1014)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:1086)
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:285)
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:269)
	at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:751)
	at org.eclipse.jetty.server.HttpWriter.flush(HttpWriter.java:59)
	at org.eclipse.jetty.server.ResponseWriter.flush(ResponseWriter.java:146)
	at org.dcache.webdav.transfer.RemoteTransferHandler$RemoteTransfer.sendMarker(RemoteTransferHandler.java:1334)
	at org.dcache.webdav.transfer.RemoteTransferHandler$RemoteTransfer.generateMarker(RemoteTransferHandler.java:1238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Connection refused
	at java.base/sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:182)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:130)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:493)
	at java.base/java.nio.channels.SocketChannel.write(SocketChannel.java:507)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:274)
```

All the best,
Carlos

**Comment by kofemann** [comment]
It looks like the door complains that the client has disconnected while the door is trying to send a transfer maker. Unpleasant, but harmless. To you see it too often?

**Comment by cfgamboa** [comment]
Yes often enough to create this ticket :)
