### ISSUE TITLE
Tunnels to core domains broken when zookeeper receives an empty update

### ISSUE THREAD

**Issue by kofemann** [dCache/dcache#7696]
When Zookeeper updates core domain infos, dCache will first kill the existing cell tunnels and then later try to read and parse the new value. If the new value is an empty string (for whatever reason), parsing will fail, but a new connection will not be established. The corresponding error in the log:

```
18 Nov 2024 08:45:00 (c-dcache-head-xxx03_messageDomain-AAYmVA1LtnA-AAYmVA16phA) [dcache-head-xxx03_messageDomain,9.2.21,CORE] Error while reading from tunnel: java.net.SocketExceptio>
18 Nov 2024 08:45:43 (c-dcache-head-xxx03_messageDomain-AAYnKxn40fA) [] Uncaught exception in thread TunnelConnector-dcache-head-xxx03_messageDomain
java.lang.NullPointerException: null
        at java.base/java.net.Socket.<init>(Socket.java:448)
        at java.base/java.net.Socket.<init>(Socket.java:264)
        at java.base/javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:277)
        at dmg.cells.network.LocationManagerConnector.connect(LocationManagerConnector.java:64)
        at dmg.cells.network.LocationManagerConnector.run(LocationManagerConnector.java:94)
        at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$2(CellNucleus.java:725)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by calestyo** [comment]
Could that be #5326?

**Comment by kofemann** [comment]
Might be. This is one of the those issues which you can trigger only by proactively breaking the system. In this particular case I was writing an empty string into ZK node.

**Comment by calestyo** [comment]
Ah no, then not. Because "my" issue happens just normally when restarting (typically many) dcache services.

**Comment by kofemann** [comment]
Give it a try. The fix is just released.

**Comment by calestyo** [comment]
Sure, but only with the next downtime :-)
